### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by Zhaohaojie4598** [open-mmlab/mmocr#1002]
Question one:
When I run this command: python mmocr/utils/ocr.py demo/demo_text_det.jpg --output demo/det_out.jpg --det TextSnake --recog None --export demo/    ,I only get json document. There is no det_out.jpg. Why?
Question two:
I have used icdar2015 to train my dbnet, and I use this command" python mmocr\utils\ocr.py  demo\demo_kie.jpeg --det dbnet --recog sar --print-result --imshow , I get the error ,ValueError: ('dbnet', 'is not a supported text detection algorthm'). Why?

**Comment by xinke-wang** [comment]
Hi,
1. I ran this command, and the code works well on my side. Please double-check the output path `demo/det_out.jpg` or try another dir.
2. It should be whether `DB_r18` or `DB_r50` and `SAR`. You may check the supported model list here:
https://github.com/open-mmlab/mmocr/blob/9cfa29f8629fa6684d466a22089c0d5e850fca98/mmocr/utils/ocr.py#L190-L203

**Comment by Zhaohaojie4598** [comment]
OK ，thank u



---Original---
From: "Xinyu ***@***.***&gt;
Date: Fri, May 6, 2022 22:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmocr] two questions (Issue #1002)




 
Hi,
  
I ran this command, and the code works well on my side. Please double-check the output path demo/det_out.jpg or try another dir. 

It should be whether DB_r18 or DB_r50 and SAR. You may check the supported model list here:
 https://github.com/open-mmlab/mmocr/blob/9cfa29f8629fa6684d466a22089c0d5e850fca98/mmocr/utils/ocr.py#L190-L203
