### ISSUE TITLE
How Can i transform labelme annotation to icdar2015 for detect model?

### ISSUE THREAD

**Issue by dsp6414** [open-mmlab/mmocr#1003]
lots of model are trained by icdar2015 in this repository, but my custom dataset are labeled by labelme, is there any script to transform labelme to icdar2015?

**Comment by Mountchicken** [comment]
Hi @dsp6414 
We have recently supported this feature, check this out #972

**Comment by gaotongxiao** [comment]
And here's the guide: https://mmocr.readthedocs.io/en/latest/tools.html#convert-annotations-from-labelme
