### ISSUE TITLE
Question about supported languages in MMOCR

### ISSUE THREAD

**Issue by Di-Ma-S21** [open-mmlab/mmocr#1008]
Hi,

We are trying to use MMOCR (Detection+Recognition) to read texts in our local images. Could we know how many languages can be recognised in the latest version of MMOCR?

Many thanks!

**Comment by xinke-wang** [comment]
Hi,

Currently, most of the released detection and recognition models in MMOCR were trained on English datasets. For detection, some models were pre-trained on the multi-lingual dataset (models with `_ICDAR2017`), others were pre-trained on English-only data (models with `_ICDAR2015`, `_CTW`, etc.). For recognition, we provide an [Chinese SAR model](https://github.com/open-mmlab/mmocr/blob/main/configs/textrecog/sar/README.md#chinese-dataset) for reading Chinese texts, others are trained on English-only datasets.

If you have your own annotated datasets, all of the released algorithms can be used for training.

In addition, more pre-trained models will be released in next few months, please stay tuned.

**Comment by Di-Ma-S21** [comment]
@xinke-wang Hi Xinke, 
Thanks for your reply! That's very helpful! I just noticed that in the Demo: https://mmocr.readthedocs.io/en/latest/demo.html, it mentioned that the Tesseract is integrated as a text detector and/or recognizer in the task pipeline. I believe that Tesseract should be a multi-lingual OCR model. 

1. Could I know if Tesseract is already included in MMOCR packages after installing it? 
2. I am not sure if the demo in Example 3 (Detection+Recoginition) also uses Tesseract?

Thanks!

**Comment by gaotongxiao** [comment]
> Could I know if Tesseract is already included in MMOCR packages after installing it?

It's just an optional requirement. You'll still have to install Tesseract and tesserocr following the [guide](https://github.com/sirfz/tesserocr)

> I am not sure if the demo in Example 3 (Detection+Recoginition) also uses Tesseract?

Sure, Tesseract can be used as a detector and/or recognizer anywhere.

**Comment by Di-Ma-S21** [comment]
@gaotongxiao Many thanks for your help!
