### ISSUE TITLE
train not enough

### ISSUE THREAD

**Issue by Zhaohaojie4598** [open-mmlab/mmocr#1009]
I have finished to train DBNET on icdar2015, but I think it is not enough, so I want to try to continue to train DBNET by totaltext. What should I do?

**Comment by Mountchicken** [comment]
Hi @Zhaohaojie4598 
- If you want to use ICDAR15 as pre-training to initialize the parameters and retrain DBNet on totaltext, then you can specify parameter [`load_from`](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/default_runtime.py#L10)
- If you want to continue training, i.e. keep the optimizer parameters, etc, then you can specify parameter [`resume from`](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/default_runtime.py#L11)

**Comment by Zhaohaojie4598** [comment]
sorry, I don't know how to use my model. before this ,I  use this command :python tools/train.py configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py --work-dir dbnet , and then how to use this model to train totaltext.

**Comment by Zhaohaojie4598** [comment]
And more question, how to mobilize my model on scene text detection.

**Comment by Mountchicken** [comment]
> sorry, I don't know how to use my model. before this ,I use this command :python tools/train.py configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py --work-dir dbnet , and then how to use this model to train totaltext.

- Find the path to the checkpoint. It should be located at `dbnet/` and let's assume that it's name is `epoch_1200.pth`
- Set `load_from` as `dbnet/epoch_1200.pth`.
https://github.com/open-mmlab/mmocr/blob/13986f497de938cae957e9863851e7f49ccdbe6d/configs/_base_/default_runtime.py#L8-L13

**Comment by Mountchicken** [comment]
> And more question, how to mobilize my model on scene text detection.

- If you want to deploy your model, please refer to the [doc](https://mmocr.readthedocs.io/en/latest/deployment.html#deployment)

**Comment by Zhaohaojie4598** [comment]
> > sorry, I don't know how to use my model. before this ,I use this command :python tools/train.py configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py --work-dir dbnet , and then how to use this model to train totaltext.
> 
> * Find the path to the checkpoint. It should be located at  and let's assume that it's name is `dbnet/``epoch_1200.pth`
> * Set  as .`load_from``dbnet/epoch_1200.pth`
>   https://github.com/open-mmlab/mmocr/blob/13986f497de938cae957e9863851e7f49ccdbe6d/configs/_base_/default_runtime.py#L8-L13

how about the parameter，and I don't find the code for totaltext 

> > sorry, I don't know how to use my model. before this ,I use this command :python tools/train.py configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py --work-dir dbnet , and then how to use this model to train totaltext.
> 
> * Find the path to the checkpoint. It should be located at  and let's assume that it's name is `dbnet/``epoch_1200.pth`
> * Set  as .`load_from``dbnet/epoch_1200.pth`
>   https://github.com/open-mmlab/mmocr/blob/13986f497de938cae957e9863851e7f49ccdbe6d/configs/_base_/default_runtime.py#L8-L13

**Comment by Zhaohaojie4598** [comment]
I have finished to train DBNET on icdar2015, but I think it is not enough. OK, I find there is det_dataset for icdar2017, so I choose to use icdar2017 to improve my model. But in the textdet/dbnt, there is no code for icdar2017.

**Comment by Zhaohaojie4598** [comment]
this is my parameter ：configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py --work-dir dbnet --resume-from dbnet/epoch_1200.pth  
and when I run ，it quickly finished， why？
here is the feedback：
UserWarning: config is now expected to have a `runner` section, please set `runner` in your config.
  'please set `runner` in your config.', UserWarning)
Done (t=0.08s)
creating index...
index created!
2022-05-24 12:07:04,068 - mmocr - INFO - load checkpoint from local path: dbnet/epoch_1200.pth
2022-05-24 12:07:05,710 - mmocr - INFO - resumed epoch 1200, iter 150000
2022-05-24 12:07:05,710 - mmocr - INFO - Start running, host: Administrator@computer, work_dir: E:\myjob\mmocr\dbnet
2022-05-24 12:07:05,710 - mmocr - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) PolyLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(NORMAL      ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) PolyLrUpdaterHook                  
(NORMAL      ) EvalHook                           
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_iter:
(VERY_HIGH   ) PolyLrUpdaterHook                  
(NORMAL      ) EvalHook                           
(LOW         ) IterTimerHook                      
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(NORMAL      ) EvalHook                           
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(NORMAL      ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_epoch:
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
2022-05-24 12:07:05,710 - mmocr - INFO - workflow: [('train', 1)], max: 1200 epochs
2022-05-24 12:07:05,710 - mmocr - INFO - Checkpoints will be saved to E:\myjob\mmocr\dbnet by HardDiskBackend.

**Comment by Mountchicken** [comment]
Use `load-from` instead of `resume-from`

**Comment by gaotongxiao** [comment]
I'm closing this issue as there's no update for a while.
