### ISSUE TITLE
Redundant Assertion found in textsnake_targets.py

### ISSUE THREAD

**Issue by Bovey0809** [open-mmlab/mmocr#101]
https://github.com/open-mmlab/mmocr/blob/6c1c34fb918be659dc6c61c6fd021f41b555a76f/mmocr/datasets/pipelines/textdet_targets/textsnake_targets.py#L237
https://github.com/open-mmlab/mmocr/blob/6c1c34fb918be659dc6c61c6fd021f41b555a76f/mmocr/datasets/pipelines/textdet_targets/textsnake_targets.py#L238

I think it should be
```python
assert sideline1.ndim == sideline2.ndim == 2
assert sideline1.shape[1] == sideline2.shape[1] == 2
```

**Comment by HolyCrap96** [comment]
Thanks a lot for reporting these mistakes!
