### ISSUE TITLE
TypeError: UniformConcatDataset: OCRDataset: function takes exactly 5 arguments (1 given)

### ISSUE THREAD

**Issue by yue-ops** [open-mmlab/mmocr#1010]
i decide to train a textreco model on a chinese dataset. I create my chinese dataset follow the ocr_toy_datasets. i change the path of datasets in sar_r31_parallel_decoder_chinese.py and create my own dict_file. but when i started to train the model,it report the error.
![image](https://user-images.githubusercontent.com/66400188/167588565-65acc37e-906b-46d9-8bf2-fbc14e7b3851.png)
![image](https://user-images.githubusercontent.com/66400188/167588607-b115a612-3f01-4cc8-87e0-2a5efe0fa257.png)
![image](https://user-images.githubusercontent.com/66400188/167588638-d91bb459-31a9-4f79-ad85-96198936d8ae.png)
![image](https://user-images.githubusercontent.com/66400188/167588680-d5797947-a6fa-45df-87d1-2470140c4e9b.png)
is there something wrong with the chinese dataset?

**Comment by Mountchicken** [comment]
Hi @yue-ops 
Please share your config files so that we can find the problem.

**Comment by yue-ops** [comment]
my configs file is this:

_base_ = [
    '../../_base_/default_runtime.py',
    '../../_base_/schedules/schedule_adam_step_5e.py'
]

dict_file = 'E:/code/mmocr/dict_license_plate.txt'
label_convertor = dict(
    type='AttnConvertor', dict_file=dict_file, with_unknown=True)

model = dict(
    type='SARNet',
    backbone=dict(type='ResNet31OCR'),
    encoder=dict(
        type='SAREncoder',
        enc_bi_rnn=False,
        enc_do_rnn=0.1,
        enc_gru=False,
    ),
    decoder=dict(
        type='ParallelSARDecoder',
        enc_bi_rnn=False,
        dec_bi_rnn=False,
        dec_do_rnn=0,
        dec_gru=False,
        pred_dropout=0.1,
        d_k=512,
        pred_concat=True),
    loss=dict(type='SARLoss'),
    label_convertor=label_convertor,
    max_seq_len=30)

img_norm_cfg = dict(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='ResizeOCR',
        height=48,
        min_width=48,
        max_width=256,
        keep_aspect_ratio=True,
        width_downsample_ratio=0.25),
    dict(type='ToTensorOCR'),
    dict(type='NormalizeOCR', **img_norm_cfg),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'filename', 'ori_shape', 'resize_shape', 'text', 'valid_ratio'
        ]),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiRotateAugOCR',
        rotate_degrees=[0, 90, 270],
        transforms=[
            dict(
                type='ResizeOCR',
                height=48,
                min_width=48,
                max_width=256,
                keep_aspect_ratio=True,
                width_downsample_ratio=0.25),
            dict(type='ToTensorOCR'),
            dict(type='NormalizeOCR', **img_norm_cfg),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=[
                    'filename', 'ori_shape', 'resize_shape', 'valid_ratio'
                ]),
        ])
]

dataset_type = 'OCRDataset'
train_prefix = 'H:/license_plate/text_reco/diy_plate/training_image_gt'
train_ann_file = 'H:/license_plate/text_reco/diy_plate/train_gt.txt'

train = dict(
    type=dataset_type,
    img_prefix=train_prefix,
    ann_file=train_ann_file,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=False)

test_prefix = 'H:/license_plate/text_reco/diy_plate/test'
test_ann_file = 'H:/license_plate/text_reco/diy_plate/test_gt.txt'

test = dict(
    type=dataset_type,
    img_prefix=test_prefix,
    ann_file=test_ann_file,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=False)

data = dict(
    samples_per_gpu=1,
    workers_per_gpu=0,
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1),
    train=dict(
        type='UniformConcatDataset', datasets=[train],
        pipeline=train_pipeline),
    val=dict(
        type='UniformConcatDataset', datasets=[test], pipeline=test_pipeline),
    test=dict(
        type='UniformConcatDataset', datasets=[test], pipeline=test_pipeline))

evaluation = dict(interval=1, metric='acc')

**Comment by Mountchicken** [comment]
Can you share part of your annotation file? It seems to be the problem.

**Comment by yue-ops** [comment]
some information of my datasets:

![image](https://user-images.githubusercontent.com/66400188/167602752-b1810659-03b8-4613-b166-34bceef4e401.png)
![image](https://user-images.githubusercontent.com/66400188/167602814-b92e58ff-731d-4ff1-a040-ff467ff2a739.png)
![image](https://user-images.githubusercontent.com/66400188/167602856-c31f6d5b-0e2c-49e6-a9a9-9ebf1cba310d.png)

**Comment by yue-ops** [comment]
though a dalao 's help this problem has been sloved ! the problem is that the  label.txt is not encoded rightly ,then i form the label.txt using "utf-8" the code is running correctly !
