### ISSUE TITLE
how to ocr with local training model?

### ISSUE THREAD

**Issue by tangjinou** [open-mmlab/mmocr#1011]
I have trained  DBNet model with icdar2019 

when i add  this in ocr.py, 
            'DB_r18_CN': {
                'config':
                'dbnet/dbnet_r18_fpnc_18e_icdar2019.py',
                'ckpt':
                'dbnet/icdar2019'
                'epoch_18.pth'
            }

and use this script "python mmocr/utils/ocr.py demo/浙AXD613.JPG --det DB_r18_CN --recog SAR_CN --output demo/浙AXD613"

something wrong like this happen:
"load checkpoint from http path: https://download.openmmlab.com/mmocr/textdet/dbnet/icdar2019epoch_18.pth
Downloading: "https://download.openmmlab.com/mmocr/textdet/dbnet/icdar2019epoch_18.pth" to /root/.cache/torch/hub/checkpoints/icdar2019epoch_18.pth
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
urllib.error.HTTPError: HTTP Error 404: Not Found"


How to slove this problem?  3KS

**Comment by xinke-wang** [comment]
Hi, please use the `--det-ckpt` param to specify your own model root.
https://github.com/open-mmlab/mmocr/blob/08eecb92565613b3c6f2016cbb0b5984d1c6ce6f/mmocr/utils/ocr.py#L57-L62

**Comment by tangjinou** [comment]
3ks， It is ok
