### ISSUE TITLE
Train Text Detection on Custom Dataset

### ISSUE THREAD

**Issue by bely66** [open-mmlab/mmocr#1014]
I have a custom Text Detection Dataset with only bounding boxes in yolo or normal object Detection format.
I’ve noticed all detection models require segmentation to run.

### **So what’s required to fine-tune mmocr models on my dataset?**

if by some label generation script, where can I find it?
If I need to relabel my data again, what’s the Labelling Criteria and on what platform?

thanks

**Comment by Mountchicken** [comment]
Hi @bely66 
- Sorry for the late reply. You need to convert your dataset format to a format supported by MMOCR. A conversion script is recommended, and you can find some data converter examples [here](https://github.com/open-mmlab/mmocr/tree/main/tools/data/textdet)
- It's ok to have only bounding boxes format as we can convert it into segmentation with some simple code like:
```python
x1, y1, x2, y2 = bbox
w = x2 - x1
h = y2 - y1
segmentation = [x1, y1, x1 + w, y1, x1 + w, y1 + h, x1, y1 + h]
```
- Here is a similar converter I can find to your situation: [vintext](https://github.com/open-mmlab/mmocr/blob/main/tools/data/textdet/vintext_converter.py#L92)

**Comment by bely66** [comment]
Thanks a lot it’s training.
Is there a preferred number of pictures to train with given that it’s not an English characters language.

**Comment by Mountchicken** [comment]
Text detector training usually doesn't require too many images, about two thousand is sufficient.

**Comment by bely66** [comment]
Does this hold for non-english datasets?

**Comment by Mountchicken** [comment]
I have not done any experiment with non-English datasets, but intuitively, the text itself is an accumulation of strokes, and the detector only needs to know that these strokes are text, rather than requiring a large number of samples to learn fineness features like a text recognizer. So whether the language is English or not, the detector only needs a moderate number of samples(like 1500 in ICDAR2015) to be trained, I guess.

**Comment by bely66** [comment]
Okay thanks, I'll cloes this issue now

**Comment by hmiche** [comment]
@bely66 hello can you send me the Notebook that you used to train the model i can't see how i can do it . and thank's
