### ISSUE TITLE
Configuration for training on a toy dataset.

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmocr#1015]
The [MMOCR tutorial](https://colab.research.google.com/github/open-mmlab/mmocr/blob/main/demo/MMOCR_Tutorial.ipynb#scrollTo=nYon41X7RTOT) offer great starting point on how perform training on a toy data set with the MMOCR recognizer. The tutorial use the data set under the folder `ocr_toy_dataset` which is accessible via this [link](https://github.com/open-mmlab/mmocr/tree/main/tests/data/ocr_toy_dataset).

To test my understanding further, I would like to perform training using the `toy_dataset`  which have the annotation under the `.json` format.

As per the tutorial, I first import the `configuration` file as below

```
from mmcv import Config
cfg = Config.fromfile('/mmocr/configs/textrecog/sar/sar_r31_parallel_decoder_toy_dataset.py') # Note the addition of /mmocr preceding text
```
followed by `cfg` changes to make it work with Google Colab`

```
from mmdet.apis import set_random_seed
cfg.work_dir = 'mmocr/demo/tutorial_exps'
cfg.optimizer.lr = 0.001 / 8
cfg.lr_config.warmup = None
cfg.log_config.interval = 40
cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.gpu_ids = range(1)
```

However, I am stuck at how to change the configuration so that proper `dir` path is pointed to the `list` of annotation which reside under the folder `/mmocr/tests/data/toy_dataset/labelme` , as well as proper path is pointed to the images under the path `/mmocr/tests/data/toy_dataset/imgs/test`

With reference to the [OP](https://github.com/open-mmlab/mmocr/issues/512), I have the impression this can be done as below

```
cfg.prefix = '/mmocr/tests/data/toy_dataset'
cfg.train1.img_prefix = '/mmocr/tests/data/toy_dataset/imgs/test'
```

But, I have the impression this setting is incorrect.

May I know how to properly point the `annotation` and `images` directory path in the `cfg` ?

For the benefit of future user, I also attach the Google Colab that have been altered to work with the `toy_dataset`  and annotation under `.json` format. The notebook is accessible via the link : https://colab.research.google.com/drive/1SmeeGaFg6h3I_w2_E2vxzMPvG8U0Q6LQ#scrollTo=r5jBBV4Qznp8

**Comment by Mountchicken** [comment]
Hi @balandongiv 
- [sar_r31_parallel_decoder_toy_dataset.py](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/toy_data.py#L7) contains two trainning set, which are `train1` and `train2`. You can see that both datasets point to the same img file (`tests/data/ocr_toy_dataset/imgs`), but use a different annotation format (`label.txt for train1 and label.lmdb for train2`). We usually use this cfg to test whether the newly developed features are working properly and we have to test on both annotation formats. But in your case, you only need to use one annotation format when training.
- From your description, it looks like your dataset is placed under `/mmocr/tests/data/toy_dataset/labelme`, so let's assume that your data set is composed like this:
  ```text
  #/mmocr/tests/data/toy_dataset/labelme
  ———labelme
       |__ imgs
       |__ train_label.txt
       |__ test_label.txt
  ```
- Then you can modify the cfg as follows:
  ```python
  cfg.root = '/mmocr/tests/data/toy_dataset/labelme'
  cfg.img_prefix = f'{root}/imgs'
  cfg.train_anno_file1 = f'{root}/train_label.txt'
  cfg.test_anno_file1 = f'{root}/test_label.txt'
  cfg.train2 = None
  ```

**Comment by balandongiv** [comment]
Thanks for the prompt reply, this help shed some light. FYI, I am currently using the dataset provided under the `mmocr` repo which accessible via this [link](https://github.com/open-mmlab/mmocr/tree/main/tests/data/toy_dataset).

From the [repo](https://github.com/open-mmlab/mmocr/tree/main/tests/data/toy_dataset), the images and annotations are structured as below.

```
#/mmocr/tests/data/toy_dataset/labelme
———labelme
     |__ img_1.json
     |__ img_10.json
     |__ img_2.json
```

and 

```
#/mmocr/tests/data/toy_dataset/imgs/test
———test
       |__ img_1.jpg
       |__ img_10.jpg
       |__ img_2.jpg
```

Based on your explanation, I have the impression the  `cfg` should be modified as below

cfg.root = '/mmocr/tests/data/toy_dataset/labelme'
cfg.img_prefix = f'{root}/imgs/test'

But, now the annotation reside under `/mmocr/tests/data/toy_dataset/labelme` are all in `.JSON`.  Given that you recommended the following


```
cfg.train_anno_file1 = f'{root}/train_label.txt'
cfg.test_anno_file1 = f'{root}/test_label.txt'
cfg.train2 = None
```

Is it correct that I first need to convert the [labels generated by labelme to the MMOCR data format](https://mmocr.readthedocs.io/en/latest/tools.html#convert-annotations-from-labelme) and point the `labelme_converter.py` `out_dir` to the following directory ( although the `out_dir `can be pointed to any `dir`)

```
#/mmocr/tests/data/toy_dataset/labelme
———labelme
     |__ train_label.txt
     |__ test_label.txt

```
Thanks again for the fast response. I have comb the net to find relevant source, but fail to find one. Should exist, appreciate if you can point to the relevant source

**Comment by Mountchicken** [comment]
You are right @balandongiv. We need to firstly convert annotation in labelme format to MMOCR's annotation format using `labelme_converter.py`. You can follow these steps
- Converter labelme format to MMOCR format
  ```bash
  python tools/data/common/labelme_converter.py tests/data/toy_dataset/labelme tests/data/toy_dataset/imgs tests/data/toy_dataset --tasks recog --format txt
  ```
This will generate a file train_label.txt at `tests/data/toy_dataset/train_label.txt`. Note that this won't give you a `test_label.txt` as there is no test set, so you can just assign `test_anno_file1` to `train_label.txt`
- Modify the cfg as follow:
  ```python
  cfg.root = '/mmocr/tests/data/toy_dataset/'
  cfg.img_prefix = f'{root}/imgs'
  cfg.train_anno_file1 = f'{root}/train_label.txt'
  cfg.test_anno_file1 = f'{root}/train_label.txt'
  cfg.train2 = None
  ```

**Comment by Mountchicken** [comment]
@balandongiv BTW, `tests/data/toy_dataset` is meant for detection task. If you want to train a recognition model like SAR, you should just use `tests/data/ocr_toy_dataset`.
```
cfg.root = '/mmocr/tests/data/ocr_toy_dataset/'
cfg.img_prefix = f'{root}/imgs'
cfg.train_anno_file1 = f'{root}/label.txt'
cfg.test_anno_file1 = f'{root}/label.txt'
cfg.train2 = None
```

**Comment by balandongiv** [comment]
Thanks for crystal clear clarification @Mountchicken .

> @balandongiv BTW, `tests/data/toy_dataset` is meant for detection task. If you want to train a recognition model like SAR, you should just use `tests/data/ocr_toy_dataset`.
> 
> ```
> cfg.root = '/mmocr/tests/data/ocr_toy_dataset/'
> cfg.img_prefix = f'{root}/imgs'
> cfg.train_anno_file1 = f'{root}/label.txt'
> cfg.test_anno_file1 = f'{root}/label.txt'
> cfg.train2 = None
> ```

Instead of directly use the `mmocr`  friendly format, I intend to understand the steps if one are to start with other raw format. Hence the motivation working with data set under `toy_dataset`. Also along the way, I intend to documented this learning process and shared it with future reader. The Notebook is available at this [link](https://colab.research.google.com/drive/1SmeeGaFg6h3I_w2_E2vxzMPvG8U0Q6LQ#scrollTo=sVFIsa-FhUM-).




> You are right @balandongiv. We need to firstly convert annotation in labelme format to MMOCR's annotation format using `labelme_converter.py`. You can follow these steps
> 
>     * Converter labelme format to MMOCR format
>       ```shell
>       python tools/data/common/labelme_converter.py tests/data/toy_dataset/labelme tests/data/toy_dataset/imgs tests/data/toy_dataset --tasks recog --format txt
>       ```
> 
> 

Since this example/tutorial intend to work in Google Colab, to my knowledge, it is impossible to run the line

`python tools/data/common/labelme_converter.py tests/data/toy_dataset/labelme tests/data/toy_dataset/imgs tests/data/toy_dataset --tasks recog --format txt`

Instead, I paste the whole content under the `labelme_converter.py` under the cell as shown in this [link](https://colab.research.google.com/drive/1SmeeGaFg6h3I_w2_E2vxzMPvG8U0Q6LQ#scrollTo=Ns2uWQCIgyyj&line=3&uniqifier=1)

and call the `parse_labelme_json` [as follow](https://colab.research.google.com/drive/1SmeeGaFg6h3I_w2_E2vxzMPvG8U0Q6LQ#scrollTo=gn9ZjoSieQNw&line=5&uniqifier=1)


```
json_file='/mmocr/tests/data/toy_dataset/labelme'
img_dir='/mmocr/tests/data/toy_dataset/imgs'
out_dir='/mmocr/tests/data/toy_dataset'
tasks='recog'
ignore_marker='###'
recog_format='txt'


parse_labelme_json(json_file,
                   img_dir,
                   out_dir,
                   tasks,
                   ignore_marker=ignore_marker,
                   recog_format=recog_format)
```

However the compiler return `TypeError`

`Unsupported format: /mmocr/tests/data/toy_dataset/labelme`

Similar error also was thrown if I tested this approach in my local Ubuntu machine.

Nevertheless, this issue is beyond the scope of the OP. But, really appreciate if @Mountchicken  can give some hint.

**Comment by Mountchicken** [comment]
- Here is a trick to run command in Colab: Add a `!` before the python command.
```bash
!python tools/data/common/labelme_converter.py tests/data/toy_dataset/labelme tests/data/toy_dataset/imgs tests/data/toy_dataset --tasks recog --format txt
```
- It's a great idea to record your learning process in Colab and share it with others, and we may collaborate to add this tutorial to MMOCR's tutorial. But for now, I just can't open your Colab notebook, which says I don't have permission.
- This problem looks like the parameters are being passed to the wrong variables and you can check it.

**Comment by balandongiv** [comment]
Hi @Mountchicken .

-  ahaaa, I forget about the magic command `!`.
- You should be able to access the notebook via this [link ](https://github.com/balandongiv/mmocr_tutorial/blob/main/custom%20mmocr.ipynb) or the full path https://github.com/balandongiv/mmocr_tutorial/blob/main/custom%20mmocr.ipynb

> * This problem looks like the parameters are being passed to the wrong variables and you can check it.

- The problem is resolve with the `!`.


Following your previous suggestion,


> @balandongiv BTW, `tests/data/toy_dataset` is meant for detection task. If you want to train a recognition model like SAR, you should just use `tests/data/ocr_toy_dataset`.
> 
> ```
> cfg.root = '/mmocr/tests/data/ocr_toy_dataset/'
> cfg.img_prefix = f'{root}/imgs'
> cfg.train_anno_file1 = f'{root}/label.txt'
> cfg.test_anno_file1 = f'{root}/label.txt'
> cfg.train2 = None
> ```

I believe the `code` should be

```
cfg.root = '/mmocr/tests/data/ocr_toy_dataset/'
cfg.img_prefix = f'{cfg.root}/imgs'
cfg.train_anno_file1 = f'{cfg.root}/label.txt'
cfg.test_anno_file1 = f'{cfg.root}/label.txt'
```
Please note the `cfg.root` instead of `root` within the curly bracket.

**Comment by Mountchicken** [comment]
Thank you for pointing that out!

**Comment by balandongiv** [comment]
Thanks for the support here also @Mountchicken

**Comment by cvarun94** [comment]
> Hi @balandongiv
> 
> * [sar_r31_parallel_decoder_toy_dataset.py](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/toy_data.py#L7) contains two trainning set, which are `train1` and `train2`. You can see that both datasets point to the same img file (`tests/data/ocr_toy_dataset/imgs`), but use a different annotation format (`label.txt for train1 and label.lmdb for train2`). We usually use this cfg to test whether the newly developed features are working properly and we have to test on both annotation formats. But in your case, you only need to use one annotation format when training.
> * From your description, it looks like your dataset is placed under `/mmocr/tests/data/toy_dataset/labelme`, so let's assume that your dataset is composed like this:
>   ```
>   #/mmocr/tests/data/toy_dataset/labelme
>   ———labelme
>        |__ imgs
>        |__ train_label.txt
>        |__ test_label.txt
>   ```
> * Then you can modify the cfg as follows:
>   ```python
>   cfg.root = '/mmocr/tests/data/toy_dataset/labelme'
>   cfg.img_prefix = f'{root}/imgs'
>   cfg.train_anno_file1 = f'{root}/train_label.txt'
>   cfg.test_anno_file1 = f'{root}/test_label.txt'
>   cfg.train2 = None
>   ```

Hi, I import the SAR config file and did the changes as you suggested as shown below:

> cfg.root = r"D:\AI_Core\mml\custom_dates"
> cfg.img_prefix = os.path.join(cfg.root, 'imgs')
> cfg.train_anno_file1 = os.path.join(cfg.root, 'label.txt')
> cfg.test_anno_file1 = os.path.join(cfg.root, 'label.txt')
> cfg.train2=None
> cfg.work_dir='demo/tutorial_exps/custom_dates'

but when I do cfg.data.train the above made changed don't show, i.e my custom data is not shown in it and the img_prefix and ann_file contain the ocr_toy_dataset paths..

Kindly tell me the proper way to edit the config file to train custom data.

Thanks

**Comment by balandongiv** [comment]
Hi @cvarun94 , maybe you can consider this [unofficial tutorial](https://github.com/balandongiv/mmocr_tutorial/blob/main/custom%20mmocr.ipynb). I yet iron the notebook, but I believe  it might help you getting started with setting the `cfg`.
