### ISSUE TITLE
DBNet Batching Issue

### ISSUE THREAD

**Issue by bely66** [open-mmlab/mmocr#1016]
I'm planning on using DBnet and I have some assumptions:
1. DBnet is the fastest model on the system, and one of the most accurate ones
2. DBnet doesn't support batching in inference
3. DBnet is the fastest to train among the other models

So I wanted to know if there's any variation from DBnet like DBnetpp that support bacthing.
and if not what's the other top alternatives.
regards.

**Comment by xinke-wang** [comment]
Hi, Currently, only PANet and TextSnake support batch mode in inference in MMOCR (check [here](https://github.com/open-mmlab/mmocr/tree/main/demo)). And, there are no other variations from DBNet and DBnetpp at present.

**Comment by bely66** [comment]
Okay thanks I'll close this issue now
