### ISSUE TITLE
Text Recognition in Production

### ISSUE THREAD

**Issue by bely66** [open-mmlab/mmocr#1019]
I wanna deploy one of the recognition models here on MMOCR.
I'm facing some questions that wasn't answered in the papers like model speed. 

For the recognition models, in terms of speed how do they rank?
From an intuitive pov **CRNN** seems the fastest model in them, but the lowest in accuracy.
So what's the next model in terms of speed, and would it be suitable in production setup running with K80 or high-end CPU along with a Detection model.

Regards

**Comment by Mountchicken** [comment]
Hi @bely66 
- It depends on your deployment scenario. CRNN is not as accurate as the Attention-based method for scene text, but it' is the best algorithm for deployment. CTC decoder is fast and more accurate on documents, long-text, and Chinese text.
- If you are looking for both speed and accuracy, then I suggest you replace CRNN's backbone with [ResNet45](https://github.com/open-mmlab/mmocr/blob/main/tests/test_models/test_ocr_backbone.py#L78), so that both requirements can be balanced.

**Comment by bely66** [comment]
I can see that the backbone of CRNN on mmocr is VGG, how can I change the configuration to ResNet45 without messing up the output.

**Comment by bely66** [comment]
Hi @Mountchicken 
I can see that the backbone of CRNN on mmocr is VGG, how can I change the configuration to ResNet45 without messing up the output.

**Comment by Mountchicken** [comment]
Modify [backbone](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_models/crnn.py#L7) in CRNN's config as:
```python
backbone=ResNet(
        in_channels=3,
        stem_channels=[64, 128],
        block_cfgs=dict(type='BasicBlock', use_conv1x1='True'),
        arch_layers=[3, 4, 6, 6, 3],
        arch_channels=[32, 64, 128, 256, 512],
        strides=[(2, 2), (2, 2), (2, 1), (2, 1), (2, 1)])
```

**Comment by bely66** [comment]
Thanks @Mountchicken 
I'm getting this error now
`: : Given groups=1, weight of size [64, 3, 3, 3], expected input[1024, 1, 32, 100] to have 3 channels, but got 1 channels insteadGiven groups=1, weight of size [64, 3, 3, 3], expected input[1024, 1, 32, 100] to have 3 channels, but got 1 channels instead
`

**Comment by bely66** [comment]
Thanks @Mountchicken
I'm getting this error now
`: : Given groups=1, weight of size [64, 3, 3, 3], expected input[1024, 1, 32, 100] to have 3 channels, but got 1 channels insteadGiven groups=1, weight of size [64, 3, 3, 3], expected input[1024, 1, 32, 100] to have 3 channels, but got 1 channels instead`

I'm thinking about two things:
1. Either changing the ResNet in_channels to 1
2. Or changing the CRNN pipeline, by removing `color_mode='gray_scale'`

**Comment by gaotongxiao** [comment]
Right, but you might need to do a bit of calculation to make sure the resnet output matches the dimension of `VeryDeepVGG`, which was CRNN's default backbone
https://github.com/open-mmlab/mmocr/blob/51f2d9a4c3c2ab5ae8a52fca7822660126724b21/mmocr/models/textrecog/backbones/very_deep_vgg.py#L69-L76

**Comment by bely66** [comment]
Okay here's my thought process:
1. The output channels of ResNet is already 512, so no modifications for these steps
2. For the height 32 equals 2^5, which means 5 strides (which already the case in the current configuration)
3. For the width 4 + 1,  this means two strides and I'm not sure about the +1, but that's the second stride

I resolved the error by removing the "gray_scale" parameter. 
and I resized the input image to 32 x 128

I'll close this issue now 
Thanks

**Comment by SolveProb** [comment]
> Okay here's my thought process:
> 
> 1. The output channels of ResNet is already 512, so no modifications for these steps
> 2. For the height 32 equals 2^5, which means 5 strides (which already the case in the current configuration)
> 3. For the width 4 + 1,  this means two strides and I'm not sure about the +1, but that's the second stride
> 
> I resolved the error by removing the "gray_scale" parameter. and I resized the input image to 32 x 128
> 
> I'll close this issue now Thanks

If model.backbone in train_cfg for ocr recognize  is type of "mmocr.model.MiniVGG",  then the input shape of tensor is : NCHW, and output tensor shape  is: N, 512, H/32, W/4 + 1

ref: https://mmocr.readthedocs.io/en/latest/_modules/mmocr/models/textrecog/backbones/mini_vgg.html
