### ISSUE TITLE
batch_mode prediction extending to other text detector

### ISSUE THREAD

**Issue by EYcab** [open-mmlab/mmocr#1020]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Since batch_mode is only supported on PANet and textsnake, I wonder what makes it difficult to extend this feature to other detectors, such as dbnet.

**Comment by Mountchicken** [comment]
Hi @EYcab 
We are now refactoring the whole text detection process and it will be supported soon.

**Comment by EYcab** [comment]
Thank you for your timely reply,@Mountchicken.
Could we know the schedule when this feature is updated?

**Comment by Mountchicken** [comment]
By next month. We are having a complete refactor on MMOCR.

**Comment by EYcab** [comment]
Awesome, thanks a lot.
