### ISSUE TITLE
精度表格里阈值是多少

### ISSUE THREAD

**Issue by tpoisonooo** [open-mmlab/mmocr#1025]
你好，我用 metric=`hmean-iou` 测试  panet - icdar2015，结果有好几个阈值：

Evaluating hmean-iou...
thr 0.30, recall: 0.752, precision: 0.841, hmean: 0.794
thr 0.40, recall: 0.752, precision: 0.841, hmean: 0.794
thr 0.50, recall: 0.752, precision: 0.841, hmean: 0.794
thr 0.60, recall: 0.752, precision: 0.841, hmean: 0.794
thr 0.70, recall: 0.752, precision: 0.841, hmean: 0.794
thr 0.80, recall: 0.752, precision: 0.841, hmean: 0.794
thr 0.90, recall: 0.731, precision: 0.864, hmean: 0.792

**我跑的模型是 int8 的**，想问原始 mmocr fp32 文档里，panet - icdar2015 用的 thr 是多少？

https://github.com/open-mmlab/mmocr/tree/main/configs/textdet/panet

**Comment by gaotongxiao** [comment]
Although the log has not recorded all results from different thresholds, I reran the test script and got the following results:
```bash
Evaluating hmean-iou...
thr 0.30, recall: 0.761, precision: 0.832, hmean: 0.795
thr 0.40, recall: 0.761, precision: 0.832, hmean: 0.795
thr 0.50, recall: 0.761, precision: 0.832, hmean: 0.795
thr 0.60, recall: 0.761, precision: 0.832, hmean: 0.795
thr 0.70, recall: 0.761, precision: 0.832, hmean: 0.795
thr 0.80, recall: 0.761, precision: 0.832, hmean: 0.795
thr 0.90, recall: 0.740, precision: 0.860, hmean: 0.796
```
So thr=0.9 yields the best result 0.796.
