### ISSUE TITLE
FILTERING THE RECOGINATION

### ISSUE THREAD

**Issue by abedall** [open-mmlab/mmocr#1027]
HI, I want to recognition some of the boxes that have been detected, 'not every box', in other words I need to recognition the largest boxes only and ignore the others..is that possible to apply here ..and thanks for the amazing work you have done.

eg 
am working on medical dataset and i want to recognition only the name of the medicine (which is the largest box ) like the photo below
![bill (2)](https://user-images.githubusercontent.com/56658518/169507219-c3aaca0a-4500-4200-97e3-556db2358bc8.jpg)

**Comment by abedall** [comment]
![bill (2)](https://user-images.githubusercontent.com/56658518/169511644-3a086e31-cc43-4c3b-8671-fd0bf47c7a54.png)

**Comment by Mountchicken** [comment]
Hi @abedall 
- If you are using `ocr.py` to do inference,  then one way is to write a function that filters the detected boxes based on the size and apply it here.
- E.g.
```python
from shapely.geometry import Polygon as plg
def find_largest_box(bboxes):
      max_area = 0.
      max_idx = 0
      for idx, bbox in enumerate(boxes):
           area = plg(bboxes).area
           if area > max_area:
                max_area =area
                max_idx = idx
      return(bboxes[idx])
...
det_result = self.single_inference(det_model, self.args.arrays, 
                                    self.args.batch_mode, 
                                    self.args.det_batch_size) 
bboxes_list = [res['boundary_result'] for res in det_result] 
max_box = find_largest_box(bboxes_list)
```
https://github.com/open-mmlab/mmocr/blob/13986f497de938cae957e9863851e7f49ccdbe6d/mmocr/utils/ocr.py#L675-L678

**Comment by abedall** [comment]
thanks so much for the fast reply @Mountchicken  Mountchicken 
so to do this I have to replace every ( bboxes_list ) in the code with the ( max_box ) that I found ?is that right?
and I have to retrain the model as well or not?
and thanks soo much for your help

**Comment by Mountchicken** [comment]
@abedall 
You don't need to retrain the model and you only need to replace `bbox_list` at [line 678](https://github.com/open-mmlab/mmocr/blob/13986f497de938cae957e9863851e7f49ccdbe6d/mmocr/utils/ocr.py#L678) in [ocr.py](https://github.com/open-mmlab/mmocr/blob/13986f497de938cae957e9863851e7f49ccdbe6d/mmocr/utils/ocr.py#L678).

**Comment by Mountchicken** [comment]
![image](https://user-images.githubusercontent.com/65173622/169629796-0d2af94e-4188-4229-bd96-876eff0835c8.png)
![00abbc9d-2bb7-47b1-9589-4acc544295b7](https://user-images.githubusercontent.com/65173622/169629805-18fb6a0f-fca2-4626-b66f-0ac2b8c67c1a.png)
