### ISSUE TITLE
how long did you train dbnet on icdar dataset, and how about gpu config?

### ISSUE THREAD

**Issue by liuheng92** [open-mmlab/mmocr#1028]
I am encounting the low gpu utils. So I am cuorious about your config and spending time.

**Comment by gaotongxiao** [comment]
Our recent experiments were performed on one single A100 and both released configurations converged within 24 hrs.

**Comment by zrazerx** [comment]
I tried to train with my poor 1050Ti 4G, but it shows that CUDA out of memory.....  so what gpu are you using for training dbnet on icdar dataset? I wonder if there is something wrong with my config

**Comment by liuheng92** [comment]
> Our recent experiments were performed on one single A100 and both released configurations converged within 24 hrs.

thx

**Comment by liuheng92** [comment]
> I tried to train with my poor 1050Ti 4G, but it shows that CUDA out of memory..... so what gpu are you using for training dbnet on icdar dataset? I wonder if there is something wrong with my config
you may get more memory

**Comment by gaotongxiao** [comment]
FYI, DBNet takes up no more than 8G memory.
