### ISSUE TITLE
How should I set imgs.lmdb path

### ISSUE THREAD

**Issue by AtsukiOsanai** [open-mmlab/mmocr#1033]
Thank you for giving the great repo.
I saw the document about [creating lmdb dataset](https://github.com/open-mmlab/mmocr/blob/main/docs/en/tools.md#convert-text-recognition-dataset-to-lmdb-format), however I don't know how to set their path.
For ocr_toy_dataset, I can find the config for label.lmdb [here](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/toy_data.py#L24), yet how about [imgs.lmdb](https://github.com/open-mmlab/mmocr/tree/main/tests/data/ocr_toy_dataset/imgs.lmdb)?
I hope you give an example for a lmdb image dataset.

**Comment by Mountchicken** [comment]
Hello there @AtsukiOsanai 
- You can refer to [PR982](https://github.com/open-mmlab/mmocr/pull/982) for details.

**Comment by AtsukiOsanai** [comment]
@Mountchicken 
Thank you for your quick response.
Ah, I had misread the lines of lmdb_root.
Setting`lmdb_root = f'{train_root}/imgs.lmdb'` worked for me.
