### ISSUE TITLE
Multi-Language Recognition Support

### ISSUE THREAD

**Issue by bely66** [open-mmlab/mmocr#1035]
My detection model picks up both english and non-english words.
and I want to recognize/transcript both languages.
What's the best course of action?
I know that training a model to predict both languages is very good for speed, But I don't know how it'd affect the performance.

Another Solution would be to have two separate recognition models, and a language detection network so that every crop from the detection stage is passed to the right model.
But I don't know how efficient is that.

So again based on that to rephrase my question better, what's the most convenient approach for a Production environment for this case?

Regards,

**Comment by Mountchicken** [comment]
Hello there @bely66 
- It is recommended that you train only one model. For example, all Chinese OCR engines can also recognize English as well. After all, English holds a small number of categories that only have 26 letters so it can be used as a subset of another language altogether. Don't worry about the accuracy. I'm not quite sure what's the non-English language you are trying to recognize, but for some languages, their word is composed of both English characters and other characters, in which case only one unified recognition model can be used.
- As for your second solution, you can train two separate recognition models and you don't need to train a language detection network. You can just simply pick the model output with the highest confidence score.

**Comment by bely66** [comment]
Hi @Mountchicken, 
Okay that seems convenient for me.
Last question before I close this issue, the other language is a non-latin language so it's analogous to chinese
Based on that what're the recommended amount of data to train this network with.

**Comment by bely66** [comment]
Okay thank you
I'll close for now and reopen it if any inconvenience happens
