### ISSUE TITLE
How to trian chinese characters recongnization?

### ISSUE THREAD

**Issue by wanlipeng** [open-mmlab/mmocr#104]
how to motify dataset and add new characters to train?

**Comment by cuhk-hbsun** [comment]
Thanks for your question. You can give your custom dict file in config.
For example, if you your `sar` model with `configs/textrecog/sar/sar_r31_parallel_decoder_academic.py`
modify
```python
label_convertor = dict(
    type='AttnConvertor', dict_type='DICT90', with_unknown=True)
```
to
```python
label_convertor = dict(
    type='AttnConvertor', dict_file=<custom_dict_file>, with_unknown=True)
```

And the `custom_dict_file` is a txt file, while one char in each line, like:
```
中
文
模
型
```

**Comment by cuhk-hbsun** [comment]
Please refor to https://mmocr.readthedocs.io/en/latest/api.html#textrecog-convertors for the usage of label_convertor.

**Comment by wanlipeng** [comment]
多谢您的回复,另外请教下您,如果想要自定义自己的dataset,更好在那便修改呢?

**Comment by wanlipeng** [comment]
多谢您的回复,另外请教下您,如果想要自定义自己的dataset,更方便在哪里修改呢?

**Comment by cuhk-hbsun** [comment]
是自定义格式的annotation_file吗还是要写新的dataset? 可以举个例子说明一下需求, 目前的dataset支持的灵活性还是比较大的
如果是要写新的dataset, 可以仿照mmocr/datasets/ocr_dataset.py
