### ISSUE TITLE
DB多卡训练报错

### ISSUE THREAD

**Issue by ga546** [open-mmlab/mmocr#1040]
![image](https://user-images.githubusercontent.com/82253048/170306143-7059e1e1-0be0-4165-aaf6-f27fb31e549f.png)
多卡训练报错
这是运行指令
./tools/dist_train.sh configs/textdet/dbnet/db_net_r18_fpnc_boat_number_det.py boat_number_det_model/train2 2
请问这是什么原因？

**Comment by xinke-wang** [comment]
The command runs well on my side. Can you check if you have modified the code or running the code under correct path?
There should not has `--` in this param.
https://github.com/open-mmlab/mmocr/blob/f89ab858f4f13869d4d3e5a6eca31e4b4f8ae2d7/tools/train.py#L27

**Comment by ga546** [comment]
Actually,I changed  codes in train.py as you said.
Now it works well. Thanks a lot! @xinke-wang
