### ISSUE TITLE
MASTER model master_academic.py not found

### ISSUE THREAD

**Issue by scry-yewenzhou** [open-mmlab/mmocr#1043]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Per the latest version, if you run readtext() by passing in recog="MASTER", it would give you an error about master_academic.py not found.

**Bug fix**
go to the directory configs/textrecog/master and rename master_r31_12e_ST_MJ_SA.py to master_academic.py

**Comment by Mountchicken** [comment]
Hi @scry-yewenzhou 
Thanks for pointing it out. We will fix it soon.
