### ISSUE TITLE
Punctuation in Detection --> Recognition Pipeline

### ISSUE THREAD

**Issue by bely66** [open-mmlab/mmocr#1046]
My question is related on how to pass punctuation to Recognition, which is based on how i annotate and train the detection.
I have two options:
1. Passing punctuation alone, **for EX** "he said:" in detection --> [he, said, :]
2. Passing punctuation with the word befor it.  **for EX** "he said:" in detection --> [he, said:]

My question is which one makes sense for recognition.

**Comment by Mountchicken** [comment]
Hi @bely66 
The second one looks more reasonable. The `;` symbol alone is too small and may not be detected.

**Comment by bely66** [comment]
Okay that makes sense
