### ISSUE TITLE
如何根据配置文件里的配置去查看文本检测和文本识别的数据预处理和后处理？

### ISSUE THREAD

**Issue by Tomhouxin** [open-mmlab/mmocr#1049]
![image](https://user-images.githubusercontent.com/23637856/171162672-c5c6017d-157e-4663-9cef-2d80633e679f.png)
想要看看Dbnet 和Crnn在python里的数据预处理的实现，目前看给出的c++示例里面的预处理貌似不全，比如还有Pading的操作没有，因此想看看python在哪实现的预处理，然后转为c++

**Comment by Mountchicken** [comment]
Hi @Tomhouxin 
- For DBNet, pipelines can be find at
 [mmocr/datasets/pipelines/ocr_transforms.py](https://github.com/open-mmlab/mmocr/blob/main/mmocr/datasets/pipelines/ocr_transforms.py)
[mmocr/datasets/pipelines/dbnet_transforms.py](https://github.com/open-mmlab/mmocr/blob/main/mmocr/datasets/pipelines/dbnet_transforms.py)
- For CRNN, pipelines can be find at
 [mmocr/datasets/pipelines/ocr_transforms.py](https://github.com/open-mmlab/mmocr/blob/main/mmocr/datasets/pipelines/ocr_transforms.py)
- What's more, MMOCR also inherits some transforms from MMDet, which can be found here
 [mmdet/datasets/pipelines/transforms.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py)
- E.g. `Padding` operation can be found here
https://github.com/open-mmlab/mmdetection/blob/240d7a31c745578aa8c4df54c3074ce78b690c34/mmdet/datasets/pipelines/transforms.py#L577-L588

**Comment by Tomhouxin** [comment]
ok! Thanks
