### ISSUE TITLE
Build in Early Stopping within MMOCR framework

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmocr#1051]
IIUC, early stopping is a process to avoid overfitting on the training dataset. While there are several article available on how to achieve this with  `Pytorch` (see [1](https://pythonguides.com/pytorch-early-stopping/), [2](https://pytorch-lightning.readthedocs.io/en/stable/common/early_stopping.html)), but  I wonder whether `MMOCR` has any special function to call this kind of feature. Quick search on the [mmcor readme](https://mmocr.readthedocs.io/en/stable/search.html?q=early+stopping&check_keywords=yes&area=default) show nothing about this feature.

**Comment by xinke-wang** [comment]
MMOCR does not include such a feature at present. But you can save the best checkpoint while validation. If you are interested in adding such a feature to MMOCR, welcome to raise a PR.

**Comment by balandongiv** [comment]
Thanks for the update @xinke-wang , really appreciate it
