### ISSUE TITLE
Why does the ocr_mask_rcnn_r50_fpn_ohem_poly have 80 classes in the bbox and mask heads?

### ISSUE THREAD

**Issue by GPhilo** [open-mmlab/mmocr#1052]
Hello,

as per the question in the title, I am confused as why is the model defined with [80 classes](https://github.com/open-mmlab/mmocr/blob/376fe05e6ce7008df37150c2c54cf45c0bd1ddc8/configs/_base_/det_models/ocr_mask_rcnn_r50_fpn_ohem_poly.py#L48) in the bbox and mask heads.

As 80 is exactly the number of classes of the COCO dataset, could this be a refuse? Shouldn't we have only one class (i.e., "text")?

**Comment by Mountchicken** [comment]
Hi @GPhilo 
Mask RCNN is adapted from `MMDet`, so the number of predicted categories remains unchanged.

**Comment by Mountchicken** [comment]
@gaotongxiao Can you please tell the reason?

**Comment by GPhilo** [comment]
For more context, as a test I changed the num_classes value to 1 and trained a network, which works just fine.

**Comment by gaotongxiao** [comment]
Chatted with the author of this config and he believed that was just a mistake. `num_classes=1` should work slightly better in OCR.
