### ISSUE TITLE
about high GPU memory usage

### ISSUE THREAD

**Issue by tairen99** [open-mmlab/mmocr#1055]
Hi mmocr,

Thank you for sharing your wonderful work on OCR.
   
I am trying to test the recognition model: [ABINet](https://github.com/open-mmlab/mmocr/blob/main/configs/textrecog/abinet/README.md), and it generates correct recognition.

The only issue is it has very high GPU memory usage (13.3 GB), which may be an issue if I want to run multiple instances of recognition models. Please see attached image for detail:
![image](https://user-images.githubusercontent.com/32938376/171969947-6741c39f-ba1c-4ee6-94b3-689d03c3dd7f.png)

I want to know whether you have a good way to control/reduce the GPU memory usage of your ABINet model?

If it was converted to Torchserve, will it save some GPU memory?

Thank you in advance.

**Comment by Mountchicken** [comment]
Hi @tairen99 
`ABINet` is a big Model. To save GPU memory during inference, you can try to reduce the batch size.
