### ISSUE TITLE
How to automatically split train and test dataset

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmocr#1057]
I just wonder whether there is helper function that can automatically split the images+annotation akin to the [sklearn.model_selection](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.model_selection).train_test_split[¶](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html#sklearn-model-selection-train-test-split) when train a custom dataset

Currently, the naive ways I can think of is,
1) Manually separate the images+annotation into separate `train` and `validation` folder.
2) Create `mmocr-compatible` annotation format for the  images+annotation in each of the  `train` and `validation` folder.

However, this manual approach may not the best since I cannot control the  randomness  and the sample proportion for the train and test dataset.

Should there is no `helper` exist, may I know the recommend approach of doing this?

**Comment by Mountchicken** [comment]
Hi @balandongiv 
For datasets without validation sets, MMOCR's convertor scripts provide the option to split the dataset, e.g. [ArT](https://github.com/open-mmlab/mmocr/blob/main/tools/data/textrecog/art_converter.py#L17) [BID](https://github.com/open-mmlab/mmocr/blob/main/tools/data/textrecog/bid_converter.py#L230)

If you want to split a custom dataset, you can refer to those convertors as you also need to convert them into MMOCR's annotation format.

**Comment by balandongiv** [comment]
Thanks for the insight @Mountchicken , I will try to play around with the script
