### ISSUE TITLE
How to train in text detection by custom dataset?

### ISSUE THREAD

**Issue by cpc0401** [open-mmlab/mmocr#1058]
Could anyone share the complete steps for text detection training or provide the examples?
Bcuz there is no tutorial for text detection training in **mmocr_tutorial.ipynb**, it is hard for understand and do training.
I saw @cuhk-hbsun said in #229  that you could prepare the dataset like `tests/data/toy_dataset` for text detection. 
But after I'd prepared the dataset like that and try to use `/mmocr/configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2015.py` for training, copied the file example `/mmocr/configs/_base_/det_datasets/icdar2015.py` to edit the data_root and dataset_type, and command `!python3 tools/train.py configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2015_forPCB.py --work-dir test_5epoch`, it doesn't work and pop up the error `TypeError: string indices must be integers`.
Could anyone fix this issue and provide the example for text detection training?
Thank you very much!

**Comment by Mountchicken** [comment]
Hi @cpc0401 
Please share us with the full error log and your config file.

**Comment by cpc0401** [comment]
after the command: `!python3 tools/train.py configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2015_forPCB.py --work-dir test_5epoch`
the full error log:

> /mmocr/mmocr/utils/setup_env.py:33: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
>   f'Setting OMP_NUM_THREADS environment variable for each process '
> /mmocr/mmocr/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
>   f'Setting MKL_NUM_THREADS environment variable for each process '
> 2022-06-07 09:29:09,565 - mmocr - INFO - Environment info:
> ------------------------------------------------------------
> sys.platform: linux
> Python: 3.7.13 (default, Apr 24 2022, 01:04:09) [GCC 7.5.0]
> CUDA available: True
> GPU 0: Tesla T4
> CUDA_HOME: /usr/local/cuda
> NVCC: Cuda compilation tools, release 11.1, V11.1.105
> GCC: x86_64-linux-gnu-gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
> PyTorch: 1.11.0+cu113
> PyTorch compiling details: PyTorch built with:
>   - GCC 7.3
>   - C++ Version: 201402
>   - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - LAPACK is enabled (usually provided by MKL)
>   - NNPACK is enabled
>   - CPU capability usage: AVX2
>   - CUDA Runtime 11.3
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
>   - CuDNN 8.2
>   - Magma 2.5.2
>   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 
> 
> TorchVision: 0.12.0+cu113
> OpenCV: 4.1.2
> MMCV: 1.5.2
> MMCV Compiler: GCC 7.3
> MMCV CUDA Compiler: 11.1
> MMOCR: 0.6.0+376fe05
> ------------------------------------------------------------
> 
> 2022-06-07 09:29:09,907 - mmocr - INFO - Distributed training: False
> 2022-06-07 09:29:10,241 - mmocr - INFO - Config:
> log_config = dict(interval=5, hooks=[dict(type='TextLoggerHook')])
> dist_params = dict(backend='nccl')
> log_level = 'INFO'
> load_from = None
> resume_from = None
> workflow = [('train', 1)]
> opencv_num_threads = 0
> mp_start_method = 'fork'
> optimizer = dict(type='Adam', lr=0.0001)
> optimizer_config = dict(grad_clip=None)
> lr_config = dict(policy='step', step=[200, 400])
> runner = dict(type='EpochBasedRunner', max_epochs=600)
> checkpoint_config = dict(interval=100)
> model_poly = dict(
>     type='PSENet',
>     backbone=dict(
>         type='mmdet.ResNet',
>         depth=50,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=-1,
>         norm_cfg=dict(type='SyncBN', requires_grad=True),
>         init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'),
>         norm_eval=True,
>         style='caffe'),
>     neck=dict(
>         type='FPNF',
>         in_channels=[256, 512, 1024, 2048],
>         out_channels=256,
>         fusion_type='concat'),
>     bbox_head=dict(
>         type='PSEHead',
>         in_channels=[256],
>         out_channels=7,
>         loss=dict(type='PSELoss'),
>         postprocessor=dict(type='PSEPostprocessor', text_repr_type='poly')),
>     train_cfg=None,
>     test_cfg=None)
> model_quad = dict(
>     type='PSENet',
>     backbone=dict(
>         type='mmdet.ResNet',
>         depth=50,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=-1,
>         norm_cfg=dict(type='SyncBN', requires_grad=True),
>         init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'),
>         norm_eval=True,
>         style='caffe'),
>     neck=dict(
>         type='FPNF',
>         in_channels=[256, 512, 1024, 2048],
>         out_channels=256,
>         fusion_type='concat'),
>     bbox_head=dict(
>         type='PSEHead',
>         in_channels=[256],
>         out_channels=7,
>         loss=dict(type='PSELoss'),
>         postprocessor=dict(type='PSEPostprocessor', text_repr_type='quad')),
>     train_cfg=None,
>     test_cfg=None)
> dataset_type = 'CustomDataset'
> data_root = 'tests/data/pcb_dataset'
> train = dict(
>     type='CustomDataset',
>     ann_file='tests/data/pcb_dataset/instances_training.json',
>     img_prefix='tests/data/pcb_dataset/imgs',
>     pipeline=None)
> test = dict(
>     type='CustomDataset',
>     ann_file='tests/data/pcb_dataset/instances_test.json',
>     img_prefix='tests/data/pcb_dataset/imgs',
>     pipeline=None)
> train_list = [
>     dict(
>         type='CustomDataset',
>         ann_file='tests/data/pcb_dataset/instances_training.json',
>         img_prefix='tests/data/pcb_dataset/imgs',
>         pipeline=None)
> ]
> test_list = [
>     dict(
>         type='CustomDataset',
>         ann_file='tests/data/pcb_dataset/instances_test.json',
>         img_prefix='tests/data/pcb_dataset/imgs',
>         pipeline=None)
> ]
> img_norm_cfg = dict(
>     mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
> train_pipeline = [
>     dict(type='LoadImageFromFile', color_type='color_ignore_orientation'),
>     dict(
>         type='LoadTextAnnotations',
>         with_bbox=True,
>         with_mask=True,
>         poly2mask=False),
>     dict(type='ColorJitter', brightness=0.12549019607843137, saturation=0.5),
>     dict(
>         type='Normalize',
>         mean=[123.675, 116.28, 103.53],
>         std=[58.395, 57.12, 57.375],
>         to_rgb=True),
>     dict(
>         type='ScaleAspectJitter',
>         img_scale=[(3000, 736)],
>         ratio_range=(0.5, 3),
>         aspect_ratio_range=(1, 1),
>         multiscale_mode='value',
>         long_size_bound=1280,
>         short_size_bound=640,
>         resize_type='long_short_bound',
>         keep_ratio=False),
>     dict(type='PSENetTargets'),
>     dict(type='RandomFlip', flip_ratio=0.5, direction='horizontal'),
>     dict(type='RandomRotateTextDet'),
>     dict(
>         type='RandomCropInstances',
>         target_size=(640, 640),
>         instance_key='gt_kernels'),
>     dict(type='Pad', size_divisor=32),
>     dict(
>         type='CustomFormatBundle',
>         keys=['gt_kernels', 'gt_mask'],
>         visualize=dict(flag=False, boundary_key='gt_kernels')),
>     dict(type='Collect', keys=['img', 'gt_kernels', 'gt_mask'])
> ]
> img_scale_test_ctw1500 = (1280, 1280)
> test_pipeline_ctw1500 = [
>     dict(type='LoadImageFromFile', color_type='color_ignore_orientation'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(1280, 1280),
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(
>                 type='Normalize',
>                 mean=[123.675, 116.28, 103.53],
>                 std=[58.395, 57.12, 57.375],
>                 to_rgb=True),
>             dict(type='Pad', size_divisor=32),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img'])
>         ])
> ]
> img_scale_test_icdar2015 = (2240, 2240)
> test_pipeline_icdar2015 = [
>     dict(type='LoadImageFromFile', color_type='color_ignore_orientation'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(2240, 2240),
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(
>                 type='Normalize',
>                 mean=[123.675, 116.28, 103.53],
>                 std=[58.395, 57.12, 57.375],
>                 to_rgb=True),
>             dict(type='Pad', size_divisor=32),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img'])
>         ])
> ]
> model = dict(
>     type='PSENet',
>     backbone=dict(
>         type='mmdet.ResNet',
>         depth=50,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=-1,
>         norm_cfg=dict(type='SyncBN', requires_grad=True),
>         init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'),
>         norm_eval=True,
>         style='caffe'),
>     neck=dict(
>         type='FPNF',
>         in_channels=[256, 512, 1024, 2048],
>         out_channels=256,
>         fusion_type='concat'),
>     bbox_head=dict(
>         type='PSEHead',
>         in_channels=[256],
>         out_channels=7,
>         loss=dict(type='PSELoss'),
>         postprocessor=dict(type='PSEPostprocessor', text_repr_type='quad')),
>     train_cfg=None,
>     test_cfg=None)
> data = dict(
>     samples_per_gpu=8,
>     workers_per_gpu=2,
>     val_dataloader=dict(samples_per_gpu=1),
>     test_dataloader=dict(samples_per_gpu=1),
>     train=dict(
>         type='UniformConcatDataset',
>         datasets=[
>             dict(
>                 type='CustomDataset',
>                 ann_file='tests/data/pcb_dataset/instances_training.json',
>                 img_prefix='tests/data/pcb_dataset/imgs',
>                 pipeline=None)
>         ],
>         pipeline=[
>             dict(
>                 type='LoadImageFromFile',
>                 color_type='color_ignore_orientation'),
>             dict(
>                 type='LoadTextAnnotations',
>                 with_bbox=True,
>                 with_mask=True,
>                 poly2mask=False),
>             dict(
>                 type='ColorJitter',
>                 brightness=0.12549019607843137,
>                 saturation=0.5),
>             dict(
>                 type='Normalize',
>                 mean=[123.675, 116.28, 103.53],
>                 std=[58.395, 57.12, 57.375],
>                 to_rgb=True),
>             dict(
>                 type='ScaleAspectJitter',
>                 img_scale=[(3000, 736)],
>                 ratio_range=(0.5, 3),
>                 aspect_ratio_range=(1, 1),
>                 multiscale_mode='value',
>                 long_size_bound=1280,
>                 short_size_bound=640,
>                 resize_type='long_short_bound',
>                 keep_ratio=False),
>             dict(type='PSENetTargets'),
>             dict(type='RandomFlip', flip_ratio=0.5, direction='horizontal'),
>             dict(type='RandomRotateTextDet'),
>             dict(
>                 type='RandomCropInstances',
>                 target_size=(640, 640),
>                 instance_key='gt_kernels'),
>             dict(type='Pad', size_divisor=32),
>             dict(
>                 type='CustomFormatBundle',
>                 keys=['gt_kernels', 'gt_mask'],
>                 visualize=dict(flag=False, boundary_key='gt_kernels')),
>             dict(type='Collect', keys=['img', 'gt_kernels', 'gt_mask'])
>         ]),
>     val=dict(
>         type='UniformConcatDataset',
>         datasets=[
>             dict(
>                 type='CustomDataset',
>                 ann_file='tests/data/pcb_dataset/instances_test.json',
>                 img_prefix='tests/data/pcb_dataset/imgs',
>                 pipeline=None)
>         ],
>         pipeline=[
>             dict(
>                 type='LoadImageFromFile',
>                 color_type='color_ignore_orientation'),
>             dict(
>                 type='MultiScaleFlipAug',
>                 img_scale=(2240, 2240),
>                 flip=False,
>                 transforms=[
>                     dict(type='Resize', keep_ratio=True),
>                     dict(
>                         type='Normalize',
>                         mean=[123.675, 116.28, 103.53],
>                         std=[58.395, 57.12, 57.375],
>                         to_rgb=True),
>                     dict(type='Pad', size_divisor=32),
>                     dict(type='ImageToTensor', keys=['img']),
>                     dict(type='Collect', keys=['img'])
>                 ])
>         ]),
>     test=dict(
>         type='UniformConcatDataset',
>         datasets=[
>             dict(
>                 type='CustomDataset',
>                 ann_file='tests/data/pcb_dataset/instances_test.json',
>                 img_prefix='tests/data/pcb_dataset/imgs',
>                 pipeline=None)
>         ],
>         pipeline=[
>             dict(
>                 type='LoadImageFromFile',
>                 color_type='color_ignore_orientation'),
>             dict(
>                 type='MultiScaleFlipAug',
>                 img_scale=(2240, 2240),
>                 flip=False,
>                 transforms=[
>                     dict(type='Resize', keep_ratio=True),
>                     dict(
>                         type='Normalize',
>                         mean=[123.675, 116.28, 103.53],
>                         std=[58.395, 57.12, 57.375],
>                         to_rgb=True),
>                     dict(type='Pad', size_divisor=32),
>                     dict(type='ImageToTensor', keys=['img']),
>                     dict(type='Collect', keys=['img'])
>                 ])
>         ]))
> evaluation = dict(interval=10, metric='hmean-iou')
> work_dir = 'test_5epoch'
> gpu_ids = [0]
> 
> 2022-06-07 09:29:10,242 - mmocr - INFO - Set random seed to 248809471, deterministic: False
> 2022-06-07 09:29:10,525 - mmocr - INFO - initialize ResNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'torchvision://resnet50'}
> 2022-06-07 09:29:10,526 - mmcv - INFO - load model from: torchvision://resnet50
> 2022-06-07 09:29:10,526 - mmcv - INFO - load checkpoint from torchvision path: torchvision://resnet50
> 2022-06-07 09:29:10,634 - mmcv - WARNING - The model and loaded state dict do not match exactly
> 
> unexpected key in source state_dict: fc.weight, fc.bias
> 
> 2022-06-07 09:29:10,660 - mmocr - INFO - initialize FPNF with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform'}
> /usr/local/lib/python3.7/dist-packages/mmdet/datasets/custom.py:180: UserWarning: CustomDataset does not support filtering empty gt images.
>   'CustomDataset does not support filtering empty gt images.')
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 66, in build_from_cfg
>     return obj_cls(**args)
>   File "/usr/local/lib/python3.7/dist-packages/mmdet/datasets/custom.py", line 121, in __init__
>     valid_inds = self._filter_imgs()
>   File "/usr/local/lib/python3.7/dist-packages/mmdet/datasets/custom.py", line 183, in _filter_imgs
>     if min(img_info['width'], img_info['height']) >= min_size:
> TypeError: string indices must be integers
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 66, in build_from_cfg
>     return obj_cls(**args)
>   File "/mmocr/mmocr/datasets/uniform_concat_dataset.py", line 67, in __init__
>     datasets = [build_dataset(c, kwargs) for c in new_datasets]
>   File "/mmocr/mmocr/datasets/uniform_concat_dataset.py", line 67, in <listcomp>
>     datasets = [build_dataset(c, kwargs) for c in new_datasets]
>   File "/usr/local/lib/python3.7/dist-packages/mmdet/datasets/builder.py", line 82, in build_dataset
>     dataset = build_from_cfg(cfg, DATASETS, default_args)
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
>     raise type(e)(f'{obj_cls.__name__}: {e}')
> TypeError: CustomDataset: string indices must be integers
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tools/train.py", line 230, in <module>
>     main()
>   File "tools/train.py", line 192, in main
>     datasets = [build_dataset(cfg.data.train)]
>   File "/usr/local/lib/python3.7/dist-packages/mmdet/datasets/builder.py", line 82, in build_dataset
>     dataset = build_from_cfg(cfg, DATASETS, default_args)
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
>     raise type(e)(f'{obj_cls.__name__}: {e}')
> TypeError: UniformConcatDataset: CustomDataset: string indices must be integers

my config file: 

> dataset_type = 'CustomDataset'
> data_root = 'tests/data/pcb_dataset'
> 
> train = dict(
>     type=dataset_type,
>     ann_file=f'{data_root}/instances_training.json',
>     img_prefix=f'{data_root}/imgs',
>     pipeline=None)
> 
> test = dict(
>     type=dataset_type,
>     ann_file=f'{data_root}/instances_test.json',
>     img_prefix=f'{data_root}/imgs',
>     pipeline=None)
> 
> train_list = [train]
> 
> test_list = [test]

**Comment by xinke-wang** [comment]
`dataset_type` should be either `IcdarDataset` or `TextDetDataset`, which depends on your annotation format. For `IcdarDataset`, it accepts coco-like json format annotations (see `tests/data/toy_dataset/instances_test.json`); for the `TextDetDataset`, it accepts jsonline format annotations (see `tests/data/toy_dataset/instances_training.txt`).

**Comment by cpc0401** [comment]
> I saw you specify the `dataset_type` as `CustomDataset`, however, `dataset_type` should be either `IcdarDataset` or `TextDetDataset`, which depends on your annotation format. For `IcdarDataset`, it accepts coco-like json format annotations (see `tests/data/toy_dataset/instances_test.json`); for the `TextDetDataset`, it accepts jsonline format annotations (see `tests/data/toy_dataset/instances_training.txt`).

Ok, I'll try it later, thanks for your response.

**Comment by cpc0401** [comment]
> I saw you specify the `dataset_type` as `CustomDataset`, however, `dataset_type` should be either `IcdarDataset` or `TextDetDataset`, which depends on your annotation format. For `IcdarDataset`, it accepts coco-like json format annotations (see `tests/data/toy_dataset/instances_test.json`); for the `TextDetDataset`, it accepts jsonline format annotations (see `tests/data/toy_dataset/instances_training.txt`).

thanks! I solved it.

**Comment by MailSuesarn** [comment]
@cpc0401 I came here because I needed to train text detection with my dataset as well. I'm a beginner. Can you please explain the steps for text detection training to me in detail? Or at least could you please provide the relevant code? Thank you in advance.
