### ISSUE TITLE
kie模型转torchserve之后如何http调用

### ISSUE THREAD

**Issue by jackiezzq** [open-mmlab/mmocr#1063]
![image](https://user-images.githubusercontent.com/18511799/172785796-e802c4c5-e079-455a-b04b-3837526de31c.png)
kie模型输入应该不止是图片，这个body怎么构造

**Comment by gaotongxiao** [comment]
In KIE, there are four terms required for inference: `relations`, `texts`, `gt_bboxes` and `img`, where the first three arguments are generated in https://github.com/open-mmlab/mmocr/blob/f2b9ba93be459c384e293789852dcc67fe1def32/mmocr/datasets/kie_dataset.py#L76.

But the generation of these keys relies on `annotations` first. Apart from fetching them from the dataset, you may also refer to the implementation in ocr.py for online `annotation` generation in case you will be using KIE in a production environment.
https://github.com/open-mmlab/mmocr/blob/9d7818b564b2b410c69c50c98488a40a3f3635fd/mmocr/utils/ocr.py#L756-L766
