### ISSUE TITLE
custom height/width in SATRN

### ISSUE THREAD

**Issue by yazansayed** [open-mmlab/mmocr#1066]
testing with SATRN config file (academic and small)
if I change the height and width in `ResizeOCR` of the train pipeline I get an error like:
```
/mmocr/mmocr/models/textrecog/layers/satrn_layers.py
 --> out = x + h_pos_encoding + w_pos_encoding
The size of tensor a (125) must match the size of tensor b (100) at non-singleton dimension 3

```

**Comment by Mountchicken** [comment]
Hi @yazansayed 
`SATRN` uses a 2D adaptive position embedding in its encoder.
https://github.com/open-mmlab/mmocr/blob/7c5c784a94e6fe9faa91565b2ea33e4e5a9f2c4d/mmocr/models/textrecog/layers/satrn_layers.py#L103-L111
- The size of the 2D embedding is hard coded to (100, 100) which means the feature map from the backbone should have a smaller size than (100,100).
- According to the error message, the input feature's width is 125 which exceeds 100. 
- You can set a larger default [width](https://github.com/open-mmlab/mmocr/blob/main/mmocr/models/textrecog/layers/satrn_layers.py#L111), like 150 or 200, depending on your image size.

**Comment by yazansayed** [comment]
thanks
