### ISSUE TITLE
Pretrained files for DBnet++

### ISSUE THREAD

**Issue by TMYsecret** [open-mmlab/mmocr#1068]
Hi, dear mmocr team! Would u mind providing the res50dcnv2_synthtext.pth pretrained parameters file?

This pretrained model on synthtext is needed in DBnet++ config files on ICDAR2015.

Location: configs/textdet/dbnetpp/dbnetpp_r50dcnv2_fpnc_1200e_icdar2015.py line:15  load_from = 'checkpoints/textdet/dbnetpp/res50dcnv2_synthtext.pth'

Look forward to ur reply, Thank u very much~

**Comment by gaotongxiao** [comment]
We always have the weights and logs in the docs: https://mmocr.readthedocs.io/en/latest/textdet_models.html#dbnetpp

Download it at [here](https://download.openmmlab.com/mmocr/textdet/dbnet/dbnetpp_r50dcnv2_fpnc_100k_iter_synthtext-20220502-db297554.pth)

**Comment by TMYsecret** [comment]
Thank u for ur reply!
