### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by happy20200** [open-mmlab/mmocr#1069]
FileNotFoundError: checkpoints/textdet/dbnetpp/res50dcnv2_synthtext.pth can not be found.
how can i found this model?

**Comment by gaotongxiao** [comment]
Sorry for being a bit misleading. The path in config can be replaced by

https://download.openmmlab.com/mmocr/textdet/dbnet/dbnetpp_r50dcnv2_fpnc_100k_iter_synthtext-20220502-db297554.pth

If it works, you're welcome to raise a PR to help us fix it :)

**Comment by happy20200** [comment]
It doesn't matter，thanks
