### ISSUE TITLE
How to train KIE Model with custom dataset?

### ISSUE THREAD

**Issue by AnoZee** [open-mmlab/mmocr#107]
I see that there are currently 26 classes in `wildreceipt/class_list.txt`.
I am looking to train the model with only 4 classes and the dataset is prepared in the same structure as in `wildreceipt/`.

How do I now train the model with this custom dataset. In the documentation I only found instructions to train Detection & Recognition models.

**Comment by cuhk-hbsun** [comment]
Same as detection and recognition. 
For example, if you have custom dataset called `data/custom_dataset`, 
1. modify `data_root = 'data/wildreceipt'` in `configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py` to `data_root = 'data/custom_dataset'`
2. train with command: (GPU_NUM=1 is ok)
```bash
./tools/dist_train.sh configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py ./work_dirs/kie 1
```
