### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [256, 256, 1, 1], expected input[16, 24, 160, 160] to have 256 channels, but got 24 channels instead

### ISSUE THREAD

**Issue by happy20200** [open-mmlab/mmocr#1072]
![1655216490(1)](https://user-images.githubusercontent.com/59427046/173600868-64044a23-5340-41b9-983e-1a9416310a3e.png)
replace the backbone of dbnet++ to MobileNetV2, but got this error, what should i do, how to change the backbone of a model

**Comment by xinke-wang** [comment]
Hi, replacing the backbone may lead to different parameters (e.g. channel numbers, feature map size), thus you may need to modify the `neck` and/or other configs.

Take [dbnet_r18_fpnc.py](https://github.com/open-mmlab/mmocr/blob/main/configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py) and [dbnet_r50dcnv2_fpnc.py](https://github.com/open-mmlab/mmocr/blob/main/configs/textdet/dbnet/dbnet_r50dcnv2_fpnc_1200e_icdar2015.py) as an example.
