### ISSUE TITLE
自定义数据集问题

### ISSUE THREAD

**Issue by zhaoguoqing12** [open-mmlab/mmocr#1075]
我想使用DBNet训练，在自定义标签中segmentation字段是否可以>4个坐标？ 
并且我想请问iscrowd和category_id字段各代表什么含义？

**Comment by zhaoguoqing12** [comment]
> * 分割坐标长度可以大于4。
> * `category_id`通常为1，表示对象的标签，在MMOCR中，将对象的标签表示为文本。
> * `iscrowd`表示是否忽略此文本。  `iscrowd = 1`表示忽略此文本。

@Harold-lkk 好的 感谢

**Comment by zhaoguoqing12** [comment]
我怎样在训练中可视化我的标签结果？

**Comment by Mountchicken** [comment]
Hi @zhaoguoqing12 
We haven't implemented such a feature yet. But we are working on this and it will be available soon.
