### ISSUE TITLE
TorchServe read images in batch mode

### ISSUE THREAD

**Issue by Hegelim** [open-mmlab/mmocr#1076]
I read this: https://mmocr.readthedocs.io/en/latest/model_serving.html which talks about how to use TorchServe to serve mmocr models. However, it seems to me the pattern of the command such as
```
curl http://127.0.0.1:8080/predictions/dbnet -T demo/demo_text_det.jpg
```
can only allow reading images one at a time, right? What if I want to read images in batch? I then did some research such as: https://github.com/pytorch/serve/issues/1235, and looks to me that we might need to write a custom handler to handle multiple requests at the same time. Because mmocr has its own model conversion tool: https://github.com/open-mmlab/mmocr/blob/main/tools/deployment/mmocr2torchserve.py, it seems it's hard to specify which custom handler to use when packaging the model as talked about in the torch doc: https://github.com/pytorch/serve/tree/master/model-archiver

So my questions are:
1. What is the right way to read images in batch? 
2. Should we write custom handlers? If so, how? 
3. How to package checkpoint and custom handlers file together into mar?

**Comment by gaotongxiao** [comment]
Forwarding it to @AllentDan

**Comment by RunningLeon** [comment]
@Hegelim Hi, you could refer to https://pytorch.org/serve/batch_inference_with_ts.html# for batch inference with ts.
