### ISSUE TITLE
preprocessing for images in MMocr

### ISSUE THREAD

**Issue by mohammad69h94** [open-mmlab/mmocr#1077]
Does require any preprocessing for images before using MMocr? 
for best practise, what is your advice?

**Comment by Mountchicken** [comment]
Hi @mohammad69h94 
- preprocessing is not necessary, because we provide various preprocessing pipelines that you can use according to your actual needs

**Comment by gaotongxiao** [comment]
@balandongiv For now, you may refer to [MMDetection's tutorial](https://mmdetection.readthedocs.io/en/latest/tutorials/data_pipeline.html) for a general understanding of the data pipeline. We also know MMOCR needs a customized tutorial as well as detailed docstrings for all transforms, and recently we have been working very hard to supplement them, which will be available very soon.

**Comment by mohammad69h94** [comment]
> Hi @mohammad69h94
> 
> * preprocessing is not necessary, because we provide various preprocessing pipelines that you can use according to your actual needs

I mean preprocessing images before inference. for example, theresholding, resizing, filtering and so on.

**Comment by Mountchicken** [comment]
@mohammad69h94 
Oh, I see. During inference, we only resize images to a certain size that is acceptable by the network, and this is being done by MMOCR's pipeline and you don't need to do it yourself. Here are some examples:

- Resize config during inference for recognition models:
[CRNN](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_pipelines/crnn_pipeline.py#L21)

- Resize config during inference for detection models:
[DBNet](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/det_pipelines/dbnet_pipeline.py#L36)
