### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 0

### ISSUE THREAD

**Issue by dididadaren** [open-mmlab/mmocr#1080]
when i try to train icdar2015?(l have config  as follows).

**Comment by dididadaren** [comment]
configs

**Comment by dididadaren** [comment]
.

**Comment by xinke-wang** [comment]
Have you modified any part of the code? You may download and try the IC15 annotations provided by mmocr [here](https://mmocr.readthedocs.io/en/latest/datasets/det.html).

**Comment by dididadaren** [comment]
i have solved this just  by  commending   out  this  code line
