### ISSUE TITLE
how to get rectangle results when we do inference with fcenet model?

### ISSUE THREAD

**Issue by Gavinic** [open-mmlab/mmocr#1082]
now the output is polygon as blew：
![image](https://user-images.githubusercontent.com/20828244/174148145-175128a9-7eba-4805-904d-c9cec74a2c74.png)
 and the result in json file is:
 
![image](https://user-images.githubusercontent.com/20828244/174148303-d4cc4196-0134-4e0d-83bd-fa3e30cc9d0a.png)

my code is as blew:
`from mmocr.utils.ocr import MMOCR
ocr = MMOCR(det='FCE_IC15', recog=None, det_ckpt='epoch_10.pth')

# 推理
results = ocr.readtext('demo/demo_kie.jpeg', output='res/demo_kie_res.jpeg', export='res',
print_result=True, merge=True, imshow=False)
`
Thank you

**Comment by Mountchicken** [comment]
Hi @Gavinic 
FCENet is hardcoded to only produce polygon output. You can modify code here to produce quad output.
https://github.com/open-mmlab/mmocr/blob/d068370b85e2eb84d83351a85dcfb531edc121a2/mmocr/models/textdet/postprocess/fce_postprocessor.py#L108-L109

```python
      new_boundaries.append(points.reshape(-1).tolist() + [score]) 
return new_boundaries
```
