### ISSUE TITLE
How can i load two models for test A1+B2 model?

### ISSUE THREAD

**Issue by simplify23** [open-mmlab/mmocr#1084]
I wrote an identification model, divided into modules A+B. I trained model 1: A1+B1 and model 2: A2+B2 respectively. I want to load different modules of the two models separately during the test, and the test model is A1+B2. How do you implement an assessment that loads both models at the same time? How can i load two models by --eval-options.

**Comment by gaotongxiao** [comment]
Sorry for the late reply. It's certainly attainable, as long as you make full use of `init_cfg`.

Say you have a simple model:
```python
model = dict(
    backbone=dict(type='A'),
    bbox_head=dict(type='B')
)
```

Then you want to load & test the combination of module A in `ckpt1.pth` and module B in `ckpt2.tph`. Just modify the config as the following:
```python
model = dict(
    backbone=dict(type='A', init_cfg=dict(
            type='Pretrained',
            checkpoint='ckpt1.pth',
            prefix='backbone.',
        )),
    bbox_head=dict(type='B', init_cfg=dict(
            type='Pretrained',
            checkpoint='ckpt2.pth',
            prefix='bbox_head.',
        ))
)
```

And you're good to go!

**Comment by simplify23** [comment]
Thanks~
