### ISSUE TITLE
mmocr_handler no batch mode by default

### ISSUE THREAD

**Issue by Hegelim** [open-mmlab/mmocr#1086]
### Issue
I am trying to use TorchServe to serve the model from MMOCR. FYI https://mmocr.readthedocs.io/en/latest/model_serving.html
However, by default, the custom handler does not support inference in batch mode: https://github.com/open-mmlab/mmocr/blob/main/tools/deployment/mmocr_handler.py
If I use this custom handler, package it using `mmocr2torchserve.py`, then by default, the model served wouldn't be able to do inference in batch mode. 

### Possible Solution
A deeper dive revealed that the inference function would call `model_inference` function from https://github.com/open-mmlab/mmocr/blob/d068370b85e2eb84d83351a85dcfb531edc121a2/mmocr/apis/inference.py#L59 which turns batch_mode off by default. 
A possible solution is to change https://github.com/open-mmlab/mmocr/blob/main/tools/deployment/mmocr_handler.py#L46 to `results = model_inference(self.model, data, batch_mode=True)`, then everything works fine. 

### Question
The fix above would allow the model to do inference in batch. However, do I also need to modify the postprocess function and preprocess function in order to better support batching?

**Comment by gaotongxiao** [comment]
Thank you very much for sharing your solution! For your question, it depends on the types of the models that you want to deploy. Some of the models do not support batch inference, while others do not really need any change and work like a charm. Read the table here for more info: https://mmocr.readthedocs.io/en/latest/demo.html#models

**Comment by Hegelim** [comment]
I see, that makes sense. Would you consider adding some kind of "switch" so that it allows users to turn on batch mode for some models and turns off batch mode for some other models?

**Comment by gaotongxiao** [comment]
Sounds good, I'm adding it to our backlog.
