### ISSUE TITLE
Separate performance result for multiple validation datasets

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmocr#1087]
Assume the model is `train` using dataset `A` and validated against dataset  `B` and dataset `C`. 

I previous read somewhere either in the documentation or issue being raise in Github (Both of which I am unable to trace back now :pensive: :pensive:) that the build-in script output the average performance metric of the dataset  `B`  and   `C`.

But instead, I would like have separate performance metric for each of the validation dataset. May I know which `.py`  function that I can modify to achieve the desire requirement?

**Comment by gaotongxiao** [comment]
It's always available in MMOCR. In text recognition tasks, we usually evaluate the model against 6 datasets ([config](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/academic_test.py)), and the separate performance will be reported indexing by their prefixes.
```text
{"mode": "val", "epoch": 6, "iter": 2, "lr": 1e-05, "0_word_acc": 0.3627, "0_word_acc_ignore_case": 0.842, "0_word_acc_ignore_case_symbol": 0.9467, "0_char_recall": 0.9851, "0_char_precision": 0.9829, "0_1-N.E.D": 0.9812, "1_word_acc": 0.2071, "1_word_acc_ignore_case": 0.8393, "1_word_acc_ignore_case_symbol": 0.8733, "1_char_recall": 0.9571, "1_char_precision": 0.9657, "1_1-N.E.D": 0.9482, "2_word_acc": 0.8345, "2_word_acc_ignore_case": 0.931, "2_word_acc_ignore_case_symbol": 0.9429, "2_char_recall": 0.9818, "2_char_precision": 0.9818, "2_1-N.E.D": 0.9697, "3_word_acc": 0.4974, "3_word_acc_ignore_case": 0.6967, "3_word_acc_ignore_case_symbol": 0.7352, "3_char_recall": 0.8794, "3_char_precision": 0.8889, "3_1-N.E.D": 0.8631, "4_word_acc": 0.262, "4_word_acc_ignore_case": 0.7721, "4_word_acc_ignore_case_symbol": 0.7891, "4_char_recall": 0.9028, "4_char_precision": 0.9226, "4_1-N.E.D": 0.897, "5_word_acc": 0.6597, "5_word_acc_ignore_case": 0.8333, "5_word_acc_ignore_case_symbol": 0.8507, "5_char_recall": 0.9386, "5_char_precision": 0.9409, "5_1-N.E.D": 0.9327}
```

**Comment by balandongiv** [comment]
Thanks for the insight @gaotongxiao

**Comment by balandongiv** [comment]
Hi @gaotongxiao ,

May I know where to locate the following information



> ```
> {"mode": "val", "epoch": 6, "iter": 2, "lr": 1e-05, "0_word_acc": 0.3627, "0_word_acc_ignore_case": 0.842, "0_word_acc_ignore_case_symbol": 0.9467, "0_char_recall": 0.9851, "0_char_precision": 0.9829, "0_1-N.E.D": 0.9812, "1_word_acc": 0.2071, "1_word_acc_ignore_case": 0.8393, "1_word_acc_ignore_case_symbol": 0.8733, "1_char_recall": 0.9571, "1_char_precision": 0.9657, "1_1-N.E.D": 0.9482, "2_word_acc": 0.8345, "2_word_acc_ignore_case": 0.931, "2_word_acc_ignore_case_symbol": 0.9429, "2_char_recall": 0.9818, "2_char_precision": 0.9818, "2_1-N.E.D": 0.9697, "3_word_acc": 0.4974, "3_word_acc_ignore_case": 0.6967, "3_word_acc_ignore_case_symbol": 0.7352, "3_char_recall": 0.8794, "3_char_precision": 0.8889, "3_1-N.E.D": 0.8631, "4_word_acc": 0.262, "4_word_acc_ignore_case": 0.7721, "4_word_acc_ignore_case_symbol": 0.7891, "4_char_recall": 0.9028, "4_char_precision": 0.9226, "4_1-N.E.D": 0.897, "5_word_acc": 0.6597, "5_word_acc_ignore_case": 0.8333, "5_word_acc_ignore_case_symbol": 0.8507, "5_char_recall": 0.9386, "5_char_precision": 0.9409, "5_1-N.E.D": 0.9327}
> ```

Currently I have the following `working directory`

```
# /epoch
|_epoch
__None.log.json
```
 and the `None.log.json` contain only the following info


```
{"mode": "train", "epoch": 1, "iter": 5, "lr": 1.0, "memory": 1747, "data_time": 0.54623, "loss_ctc": 7.27019, "loss": 7.27019, "time": 0.6077}
{"mode": "train", "epoch": 1, "iter": 10, "lr": 1.0, "memory": 1747, "data_time": 0.00758, "loss_ctc": 3.76519, "loss": 3.76519, "time": 0.05148}
{"mode": "train", "epoch": 1, "iter": 15, "lr": 1.0, "memory": 1747, "data_time": 0.0075, "loss_ctc": 3.35921, "loss": 3.35921, "time": 0.05105}
{"mode": "train", "epoch": 1, "iter": 20, "lr": 1.0, "memory": 1747, "data_time": 0.00729, "loss_ctc": 3.30817, "loss": 3.30817, "time": 0.0509}
```


For context, the training set ( Syn90k) and testing set (IIIT5K, SVT), evaluation (interval=1, metric='acc')
