### ISSUE TITLE
Preparation of MJSynth mmocr-annotation compatible for text recognition

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmocr#1088]
The [documentation](https://mmocr.readthedocs.io/en/latest/datasets/recog.html#mjsynth-syn90k) suggested to apply the `txt2lmdb.py` for the preparation of `label.lmdb` for text recognition.

However there is no `txt2lmdb.py`  available under the specified [folder ](https://github.com/open-mmlab/mmocr/tree/main/tools/data/utils).

IIUC, this should be [lmdb_converter.py](https://github.com/open-mmlab/mmocr/blob/main/tools/data/utils/lmdb_converter.py) instead of `txt2lmdb.py` .

**Comment by xinke-wang** [comment]
Hi, `txt2lmdb.py` was deprecated in PR #979, the document has not been updated yet, would you like to raise a PR to fix this?

**Comment by balandongiv** [comment]
Thanks for the link @xinke-wang .

To double check about the setting.

Assume the following folder and file setting

#/Syn90k
———Syn90k
     |__ mnt/ramdisk/max/90kDICT32px
     |__ label.txt
     |__ shuffle_labels.txt


Then, the lines to produced the `label.lmdb`


```
    from tools.data.utils.lmdb_converter import recog2lmdb
   root='/Syn90k'
    img_root = os.path.join(root,'mnt','ramdisk','max','90kDICT32px') # Input imglist path 
    label_path =os.path.join(root, 'label.txt') # Path to label file
    output = root  # Output lmdb path
    label_only = True  # Only converter label to lmdb
    recog2lmdb(img_root, label_path, output,label_only=label_only )
```


However, upon completion, the following two files were produced instead

`data.mdb` and `lock.mdb`

May I know what setting should be changed to have the ``label.lmdb` as an output?

I will raise a PR based on the discussion here.

**Comment by xinke-wang** [comment]
`.lmdb` format annotation contains two files including `data.mdb` and `lock.mdb`, so it is expected to generate a directory named `label.lmdb` which contains the above files.

**Comment by balandongiv** [comment]
Thanks for the insight @xinke-wang , 

Unfortunately, with reference to aforementioned folder/file structure and syntax, only two files were produced `data.mdb` and `lock.mdb`. 

Specifically


#/Syn90k
———Syn90k
     |__ mnt/ramdisk/max/90kDICT32px
     |__ label.txt
     |__ shuffle_labels.txt
     |__ data.mdb
     |__ lock.mdb

Should I rename the `output` as

`output = os.path.join(root,'label.lmdb')`

**Comment by gaotongxiao** [comment]
Thanks for bringing this up! It really was a mistake and we'll be polishing the documentation very soon.
