### ISSUE TITLE
What is the exact meaning of the text score

### ISSUE THREAD

**Issue by liuquande** [open-mmlab/mmocr#1092]
Hi, 

I am using the ABINet to predict the digits in some figures, and noticed that each result is usually attached with a score value (c.f. figure below). 
![image](https://user-images.githubusercontent.com/29408526/174703334-2b645410-2f9e-46b3-98f8-2adb4ad27616.png)

May I know the exact meaning of the score value, if it indicates the confidence of model prediction, what is the range of score value?
Many thanks.

Best.

**Comment by Mountchicken** [comment]
Hi @liuquande 

The score should be in range (0, 1), but the code is incorrect.  Modify the code as below will give you the correct value.

https://github.com/open-mmlab/mmocr/blob/4f36bcd1aa5678eae7a44ef2407697e1d14ac176/mmocr/models/textrecog/convertors/attn.py#L125-L127

```python
seq = outputs[idx, :, :]
seq = seq.softmax(dim=-1)
max_value, max_idx = torch.max(seq, -1)
str_index, str_score = [], []
```

**Comment by liuquande** [comment]
Oh I see, thanks for the reply.
