### ISSUE TITLE
Getting ValueError when using MJ_train.py setup

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmocr#1093]
Using MJ_train.py as the base for text recognition training set result in the following error

`ValueError: UniformConcatDataset: OCRDataset: AnnFileLoader: We only support using LineJsonParser to parse lmdb file. Please use LineJsonParser in the dataset config`

Change the parser
https://github.com/open-mmlab/mmocr/blob/4f36bcd1aa5678eae7a44ef2407697e1d14ac176/configs/_base_/recog_datasets/MJ_train.py#L17

from

```
parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' '))
```

to
```
parser = dict(
type = 'LineJsonParser',
 keys = ['filename', 'text'])
```

should resolve the issue.

By default, the script load the `lmdb` as shown from the assignment

```
train_root = 'data/mixture/Syn90k'
train_img_prefix = f'{train_root}/mnt/ramdisk/max/90kDICT32px'
train_ann_file = f'{train_root}/label.lmdb'
```

**Comment by Mountchicken** [comment]
Hi @balandongiv 
Thanks to point it out. You can raise a PR to help us fix it.
