### ISSUE TITLE
Get score for all possible outcomes (full distribution)

### ISSUE THREAD

**Issue by davidmasek** [open-mmlab/mmocr#1097]
Hello, after predicting with MMOCR recognizers I get the predicted text and scores for each letter. I would like to also get scores for other than the top prediction (so I can for example choose the second best letter if I'm sure that the top prediction is invalid).

Is this possible? I'm mostly using NRTR model if relevant.

Thank you.

**Comment by Mountchicken** [comment]
Hi @davidmasek 
- For NRTR, this is the place where the score and the best letter are calculated. You can make some modifications based on your situation. 
https://github.com/open-mmlab/mmocr/blob/d669ce2e8286937e1ed16ec9feae6401ce5893f5/mmocr/models/textrecog/convertors/attn.py#L124-L141

**Comment by davidmasek** [comment]
I registered my own AttnConvertor based on the one provided and it works as expected. Thank you.
