### ISSUE TITLE
Why not just use readtext for TorchServe inference

### ISSUE THREAD

**Issue by Hegelim** [open-mmlab/mmocr#1099]
I am using TorchServe to serve ABINet model, and by diving deep into the source code:
https://github.com/open-mmlab/mmocr/blob/main/tools/deployment/mmocr_handler.py#L46
I noticed that instead of using `mmocr.readtext()` as in https://mmocr.readthedocs.io/en/stable/demo.html, we called the `model_inference` function instead. 

My questions are:
1. Is there a specific reason why we don't use the more convenient `mmocr.readtext()`?
2. When using `model_inference()`, is detection+recognition both involved or only detection/recognition?

**Comment by gaotongxiao** [comment]
1. There is no specific reason stopping us from doing so, and it does sound like a great idea. The current `MMOCRHanlder` is just a general one across all OpenMMLab projects. We have not put much effort into customizing it yet, as we did not receive any requests for it.
2. `model_inference` is a fundamental API that only involves one model at a time.
