### ISSUE TITLE
Question about SynthText dataset

### ISSUE THREAD

**Issue by skyerhxx** [open-mmlab/mmocr#110]
When I was running robust_scanner in textrecog, I found the dataset preparation process in MMOCR document did not work.
Follow the instruction, I cannot get the good SynthText dataset which matches the shuffle_labels.txt
![image](https://user-images.githubusercontent.com/31229906/115650066-1f745080-a35b-11eb-832c-fdcb26f3492e.png)

Specially, downloading the dataset from SynthText website can only get images like net_63_64.jpg, but in the shuffle_labels.txt, it needs net_63_64_12.jpg(I think you split the original image into patches)
![image](https://user-images.githubusercontent.com/31229906/115650521-f1dbd700-a35b-11eb-99a8-64f8131189e8.png)

So how should I get the SynthText dataset which is splited into patches? Or could you please provide the patch dataset?
Thanks a lot

**Comment by innerlee** [comment]
The png is produced by this funtion https://github.com/open-mmlab/mmocr/blob/main/mmocr/utils/img_util.py#L6, which will drop orientation info of jpg.

We will provide documentation & script to process that.

If in hurry, you may rename the pngs in the annotation file back to jpg.

**Comment by skyerhxx** [comment]
Thank you.
Besides, the icdar2011 dataset cannot be downloaded from its website now. Could you please share a baiduwangpan link?

**Comment by innerlee** [comment]
Sorry we cannot share dataset images. You may contact the organizers, or seek help from friends. I will mark this thread as community help.

**Comment by cuhk-hbsun** [comment]
@skyerhxx 
The reason for the inconsistency between the file name in dir and shuffle_label.txt is that, 
1. in `image dir` download from the official website, the image is the `whole image`, which contains multiple texts, for text detection;
2. in `shuffle_label.txt`, the image is the `cropped image` from the whole image, for text recognition only;
3. We will `provide a script file` that cropping the box image from the whole image as soon as possible.

**Comment by williamking5** [comment]
@cuhk-hbsun Looking forward to the scripts

**Comment by williamking5** [comment]
@skyerhxx I have found another script that can crop words from CLOVA-AI benchmark.

[](https://github.com/clovaai/deep-text-recognition-benchmark/issues/6)

**Comment by cuhk-hbsun** [comment]
@williamking5 Thanks. And would you like to be a contributor to involve the script to MMOCR repo (like `tools/data/textrecog/synthtext_converter.py`) and update the `docs/datasets.md`?

**Comment by williamking5** [comment]
@cuhk-hbsun Yes my pleasure.

I have another question about the ICDAR 2011 dataset. The number of training samples on the original website is 3583. But on the rrc website, the number is 3564. And on the mmocr documentation the number is 3567. I'd like to know which version of dataset you use and how did you process the dataset?

RRC:

![RRC](https://user-images.githubusercontent.com/16954932/117561470-c4b45600-b0c9-11eb-8915-c677041b60e0.png)

Official:

![Official](https://user-images.githubusercontent.com/16954932/117561485-d564cc00-b0c9-11eb-9340-e2addb3c0894.png)

Yours:

![image](https://user-images.githubusercontent.com/16954932/117561515-05ac6a80-b0ca-11eb-8bde-42111b4a2f92.png)

Looking forward to your reply :)

**Comment by williamking5** [comment]
And I noticed that the official website of ICDAR2011 is not available for registering which you provide in the documentation:

http://www.cvc.uab.es/icdar2011competition/?com=downloads

Also, the train_label.txt in your documentation is actually ICDAR 2015 labels, please double check the mistakes.

**Comment by williamking5** [comment]
Well, after I download the dataset on RRC, I know why the number is 3567, ignore the question please :)
