### ISSUE TITLE
appoint special gpus when using dist_train

### ISSUE THREAD

**Issue by justcodew** [open-mmlab/mmocr#1100]
when using dist_train,it  will defaultly  use from gpu 0. if i want to use the special gpus,such as gpu 2,3 when i have 4 gpus?
the origin command 
./tools/dist_train.sh configs/textrecog/sar/sar_r31_parallel_decoder_own_dataset.py sar 2
will using gpus 0,1
where should i change?

**Comment by xinke-wang** [comment]
You can use `CUDA_VISIBLE_DEVICES` to specify the GUPs you would like to use. For example, `export CUDA_VISIBLE_DEVICES=2,3` before you run the training progress.

**Comment by justcodew** [comment]
it works. thank you
