### ISSUE TITLE
shapely.errors.TopologicalError when training art data 

### ISSUE THREAD

**Issue by justcodew** [open-mmlab/mmocr#1104]
i come arcoss some error when training art data .
1. i  get the art data according [https://github.com/open-mmlab/mmocr/blob/main/docs/en/datasets/det.md]( https://github.com/open-mmlab/mmocr/blob/main/docs/en/datasets/det.md)
2.  then  i set the dataset same as configs/_base_/det_datasets/icdar2015.py
3.  set det config as   configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py ,just change the dataset.
4. run command : `./tools/dist_train.sh configs/textdet/dbnet/dbnet_r18_fpnc_1200e_art2019.py output/dbnet_r18_art 2`
and then
![image](https://user-images.githubusercontent.com/107862224/174994106-bebc67bd-4c40-4019-a160-932903b526c4.png)

![image](https://user-images.githubusercontent.com/107862224/174993443-193bd985-745b-4294-98b1-5df2fb180133.png)

**Comment by xinke-wang** [comment]
Hi, it seems there are invalid polygons contained in this dataset, which triggers an error in the dbnet pipeline `imgaug` where the IoU cannot be calculated. We'll fix this issue in the later version.

For now, if you want to get a quick fix, one way is directly ignore these invalid polygons like putting a try-except unit to line83 and returning the original results without augmentation.
https://github.com/open-mmlab/mmocr/blob/d669ce2e8286937e1ed16ec9feae6401ce5893f5/mmocr/datasets/pipelines/dbnet_transforms.py#L83

Another way is to fix the invalid polygon by calling `poly_make_valid`
https://github.com/open-mmlab/mmocr/blob/75d32504e002f7da3c38c04babd80182be836339/mmocr/core/evaluation/utils.py#L139

**Comment by justcodew** [comment]
thx. i find  there are  some text inside text cases  in the art dataset.  which detect method would work better in such scene?
![1](https://user-images.githubusercontent.com/107862224/175235338-ca33952a-7389-4450-879f-b6d95a784535.png)
![2](https://user-images.githubusercontent.com/107862224/175235435-9222fceb-19a9-48a9-a662-9e183951d20d.png)
![4](https://user-images.githubusercontent.com/107862224/175235454-2acb5120-2e8f-4f89-8f9a-97e8f0cbb9b5.png)

**Comment by justcodew** [comment]
there is a another  error in evalue code  when training art data

![image](https://user-images.githubusercontent.com/107862224/176079593-8cf4ec84-04f9-4e82-a622-8af3f23f9da5.png)

**Comment by xinke-wang** [comment]
The ICDAR evaluation metric only accepts polygons with `len(polygon) >=8 and len(polygon) % 2 == 0`, other polygons cannot pass the assertion. You may need to filter out these invalid polygons.
