### ISSUE TITLE
[Errno 21] Is a directory: 'data/mixture/Syn90k/label.lmdb'

### ISSUE THREAD

**Issue by MingyuLau** [open-mmlab/mmocr#1105]
When I tried to train MASTER on GPUs, it raised the error as below, however, I had orgnaized  my  data right and the directory "label.lmdb" surely had two files named "data.mdb" and "lock.mdb"

![RCS){OT{P@`2LUI@_Z4~SQ7](https://user-images.githubusercontent.com/88388495/175296225-5dc2e6e6-4c90-42ae-8807-44f2d7bc91fd.png)

![%ZWF28 )OY@@`@2R%T4$)TJ](https://user-images.githubusercontent.com/88388495/175296250-50f91238-a068-4e21-abc6-39fd77e9bf34.png)

**Comment by Mountchicken** [comment]
Hi @MingyuLau 

It seems to be the problem of dataset config. Try replacing the code as below.
https://github.com/open-mmlab/mmocr/blob/1f888c9e97d2fa7a3849e4b803bcc079c548bc83/configs/_base_/recog_datasets/ST_SA_MJ_train.py#L9-L23
>>> replace to
```python
train1 = dict(
    type='OCRDataset',
    img_prefix=train_img_prefix1,
    ann_file=train_ann_file1,
    loader=dict(
        type='AnnFileLoader',
        repeat=1,
        file_format='lmdb',
        parser=dict(
            type='LineJsonParser',
            keys=['filename', 'text']),
    pipeline=None,
    test_mode=False)
```

**Comment by MingyuLau** [comment]
Thank you for dealing the problem for me immediately, and it is effective that the previos error is fixed,but this time a new "pipeline" error is raised.
![J3_U0TLWAZ{ QV 05%VY0%G](https://user-images.githubusercontent.com/88388495/175299765-111f95e8-5592-4459-bfa3-09b8b70c4e0b.png)

**Comment by Mountchicken** [comment]
Maybe we need to fix more, try

https://github.com/open-mmlab/mmocr/blob/1f888c9e97d2fa7a3849e4b803bcc079c548bc83/configs/_base_/recog_datasets/ST_SA_MJ_train.py#L39-L41

>>> replace to
```python
train3['loader']['file_format'] = 'txt'
tran3['loader']['parser'] = dict(
                              type='LineStrParser',
                              keys=['filename', 'text'],
                              keys_idx=[0, 1],
                              separator=' ')
train_list = [train1, train2, train3]
```

**Comment by MingyuLau** [comment]
@Mountchicken    Sorry for bothering, I found a typo in your code yesterday, there is a missing ")" for the "loader=dict(......)", after I fix the typo, the console raise the same error "is a directory" as before

**Comment by Mountchicken** [comment]
@MingyuLau 
Can you show me you dataset configs? This problem is due to the incorrect use of `LineStrParse`r when loading a dataset in `lmdb` format, which in fact `LineJsonParser` should be used.

**Comment by MingyuLau** [comment]
@Mountchicken 
```python
# Text Recognition Training set, including:
# Synthetic Datasets: SynthText, Syn90k

train_root = 'data/mixture'

train_img_prefix1 = f'{train_root}/Syn90k/mnt/ramdisk/max/90kDICT32px'
train_ann_file1 = f'{train_root}/Syn90k/label.lmdb'

train1 = dict(
    type='OCRDataset',
    img_prefix=train_img_prefix1,
    ann_file=train_ann_file1,
    loader=dict(
        type='AnnFileLoader',
        repeat=1,
        file_format='lmdb',
        parser=dict(
            type='LineJsonParser',
            keys=['filename', 'text'])),
    pipeline=None,
    test_mode=False)

train_img_prefix2 = f'{train_root}/SynthText/' + \
    'synthtext/SynthText_patch_horizontal'
train_ann_file2 = f'{train_root}/SynthText/label.lmdb'

train_img_prefix3 = f'{train_root}/SynthText_Add'
train_ann_file3 = f'{train_root}/SynthText_Add/label.txt'

train2 = {key: value for key, value in train1.items()}
train2['img_prefix'] = train_img_prefix2
train2['ann_file'] = train_ann_file2

train3 = {key: value for key, value in train1.items()}
train3['img_prefix'] = train_img_prefix3
train3['ann_file'] = train_ann_file3
train3['loader']['file_format'] = 'txt'

train_list = [train1, train2, train3]

```

**Comment by Mountchicken** [comment]
@MingyuLau 
Sorry for the misunderstanding. We have merged a new PR to fix this problem. The correct config should be

```python
train_root = 'data/mixture'

train_img_prefix1 = f'{train_root}/Syn90k/mnt/ramdisk/max/90kDICT32px'
train_ann_file1 = f'{train_root}/Syn90k/label.lmdb'

train1 = dict(
    type='OCRDataset',
    img_prefix=train_img_prefix1,
    ann_file=train_ann_file1,
    loader=dict(
        type='AnnFileLoader',
        repeat=1,
        file_format='lmdb',
        parser=dict(type='LineJsonParser', keys=['filename', 'text'])),
    pipeline=None,
    test_mode=False)

train_img_prefix2 = f'{train_root}/SynthText/' + \
    'synthtext/SynthText_patch_horizontal'
train_ann_file2 = f'{train_root}/SynthText/label.lmdb'

train_img_prefix3 = f'{train_root}/SynthText_Add'
train_ann_file3 = f'{train_root}/SynthText_Add/label.txt'

train2 = {key: value for key, value in train1.items()}
train2['img_prefix'] = train_img_prefix2
train2['ann_file'] = train_ann_file2

train3 = {key: value for key, value in train1.items()}
train3['img_prefix'] = train_img_prefix3
train3['ann_file'] = train_ann_file3
train3['loader']['file_format'] = 'txt'
train3['loader']['parser'] = dict(
    type='LineStrParser',
    keys=['filename', 'text'],
    keys_idx=[0, 1],
    separator=' ')

train_list = [train1, train2, train3]
```

**Comment by Mountchicken** [comment]
SA is in `txt` format and need to use `LineStrParser`. Parser is always confusing and we are working on this, and later on we will provide a more specific document.

**Comment by MingyuLau** [comment]
@Mountchicken 
But it still give me the same error, did I do something wrong when I convert the "label.txt" to "label.lmdb" ？I choose "the label-only" option using "lmdb_converter.py"
![OB5PXUESGU_~HOLMY8UVVU1](https://user-images.githubusercontent.com/88388495/175500148-a72466e9-7232-4a94-97f8-de7296273a45.png)

**Comment by MingyuLau** [comment]
And this is my structure of dataset, orgnised as the official document
![_6Q({ENLX45{B0 91BNJ3W](https://user-images.githubusercontent.com/88388495/175501671-d0f11857-54f1-4089-aab1-41b12928797f.png)

**Comment by Mountchicken** [comment]
@MingyuLau 
It's not the problem of `lmdb_converter.py`. The problem still lies in the use of `LineStrParser` for lmdb annotations, but the modified config has solved this problem. My guess is that there is a problem with your version of MMOCR or there is something missing during the installation process. Please try to install the newest version of MMOCR. Use `pip install -v -e .` after you clone it.

**Comment by MingyuLau** [comment]
@Mountchicken 
I found it strange that I had fix my dataset config  file, but it seems that it didn't work because the output in console shows that the config is still "str" not "json"
![9%}8Q~ _ C1}E7OIT87OWXK](https://user-images.githubusercontent.com/88388495/175523447-664a05e1-3320-482d-a3da-27101a16f3b8.png)

**Comment by Mountchicken** [comment]
Try `pip install -v -e .`

**Comment by MingyuLau** [comment]
It makes no difference

**Comment by MingyuLau** [comment]
@Mountchicken 
why I change the config file but the output shows that nothing had been changed?

**Comment by MingyuLau** [comment]
Yes，I am training with [master_r31_12e_ST_MJ_SA.py](https://github.com/open-mmlab/mmocr/blob/main/configs/textrecog/master/master_r31_12e_ST_MJ_SA.py) ?Andtihis is my training file:
'''python
_base_ = [
    '../../_base_/default_runtime.py', '../../_base_/recog_models/master.py',
    '../../_base_/schedules/schedule_adam_step_12e.py',
    '../../_base_/recog_pipelines/master_pipeline.py',
    '../../_base_/recog_datasets/ST_SA_MJ_train.py',
    '../../_base_/recog_datasets/academic_test.py'
]

train_list = {{_base_.train_list}}
test_list = {{_base_.test_list}}

train_pipeline = {{_base_.train_pipeline}}
test_pipeline = {{_base_.test_pipeline}}

data = dict(
    samples_per_gpu=8,
    workers_per_gpu=4,
    val_dataloader=dict(samples_per_gpu=8),
    test_dataloader=dict(samples_per_gpu=8),
    train=dict(
        type='UniformConcatDataset',
        datasets=train_list,
        pipeline=train_pipeline),
    val=dict(
        type='UniformConcatDataset',
        datasets=test_list,
        pipeline=test_pipeline),
    test=dict(
        type='UniformConcatDataset',
        datasets=test_list,
        pipeline=test_pipeline))

evaluation = dict(interval=1, metric='acc')

'''

**Comment by MingyuLau** [comment]
@Mountchicken 
I know where the error lies in ，I debug and find in the ST_SA_MJ_train.py ,the parameters of train3 cover the parameters of train1
Can you help me to fix this error?
![7TJIH3GB HMHCO49FD(D~DO](https://user-images.githubusercontent.com/88388495/175843329-8d0c6ff6-7169-43af-beb9-93637311e8d7.png)

**Comment by Mountchicken** [comment]
@MingyuLau 
Thanks for pointing that out. That's a really well hidden bug. Using the following config can fix the problem.
```python
# Text Recognition Training set, including:
# Synthetic Datasets: SynthText, Syn90k

train_root = 'data/mixture'

train_img_prefix1 = f'{train_root}/Syn90k/mnt/ramdisk/max/90kDICT32px'
train_ann_file1 = f'{train_root}/Syn90k/label.lmdb'

train1 = dict(
    type='OCRDataset',
    img_prefix=train_img_prefix1,
    ann_file=train_ann_file1,
    loader=dict(
        type='AnnFileLoader',
        repeat=1,
        file_format='lmdb',
        parser=dict(type='LineJsonParser', keys=['filename', 'text'])),
    pipeline=None,
    test_mode=False)

train_img_prefix2 = f'{train_root}/SynthText/' + \
    'synthtext/SynthText_patch_horizontal'
train_ann_file2 = f'{train_root}/SynthText/label.lmdb'

train_img_prefix3 = f'{train_root}/SynthText_Add'
train_ann_file3 = f'{train_root}/SynthText_Add/label.txt'

train2 = {key: value for key, value in train1.items()}
train2['img_prefix'] = train_img_prefix2
train2['ann_file'] = train_ann_file2

train3 = dict(
    type='OCRDataset',
    img_prefix=train_img_prefix3,
    ann_file=train_ann_file3,
    loader=dict(
        type='AnnFileLoader',
        repeat=1,
        file_format='txt',
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=False)

train_list = [train1, train2, train3]
```

**Comment by Mountchicken** [comment]
BTW, it will be appreciate if you can also raise a PR to help us fix it.

**Comment by MingyuLau** [comment]
It's my pleasure, and I'm sincerely grateful for all your help in this problem!
