### ISSUE TITLE
how to use cpu for inference instead of gpu?

### ISSUE THREAD

**Issue by yptheangel** [open-mmlab/mmocr#111]
when I switch to cpu using `model.eval().cpu()` for running the KIE(key info extraction)

why is there a shape mismatch issue? 
`RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 3, 3, 3], but got 5-dimensional input of size [1, 1, 3, 928, 512] instead`.

**Comment by innerlee** [comment]
Hi, could you please post the command to reproduce the error, and post the full log?

**Comment by yptheangel** [comment]
@innerlee thx for your fast response, attached the code and error log. Thanks
[code_n_errorlog.zip](https://github.com/open-mmlab/mmocr/files/6355709/code_n_errorlog.zip)

**Comment by innerlee** [comment]
I see, its KIE. There has been several issues regarding KIE. I will debug this soon (tonight maybe)

**Comment by innerlee** [comment]
Sorry for the late reply. Please modify codes as this branch https://github.com/open-mmlab/mmocr/pull/215 to see if cpu inference works.

**Comment by cuhk-hbsun** [comment]
fix
