### ISSUE TITLE
official document installation which supports latest pytorch

### ISSUE THREAD

**Issue by Ao-Lee** [open-mmlab/mmocr#1120]
the install instruction on readme.md only supports pytorch=1.10, kindly ask that would there be an offical install instruction that can support late pytorch? like 1.11.0 or 1.10.0

many thanks

**Comment by gaotongxiao** [comment]
The installation instruction in README was just using PyTorch 1.10 as a typical example. You can use any PyTorch whose version is greater than 1.6 and install MMOCR successfully following the guide.

**Comment by Ao-Lee** [comment]
thanks
