### ISSUE TITLE
ABINet accuracy in full precision vs half precision

### ISSUE THREAD

**Issue by Hegelim** [open-mmlab/mmocr#1125]
Theoretically speaking, as far as I am concerned (please correct me if I am wrong), the current ABINet pretrained model is in full precision (float32), what would be the accuracy of the model if I decided to run inference in half precision (float16)? Is there any benchmark such as the ones listed here https://mmocr.readthedocs.io/en/latest/deployment.html#evaluate-onnx-and-tensorrt-models-experimental?

**Comment by gaotongxiao** [comment]
We currently don't have a benchmark for it. And we haven't tested ABINet in fp16 yet, but you can turn on the fp16 switch and give it a shot as in https://github.com/open-mmlab/mmocr/issues/590. Technically the performance should be almost the same.

**Comment by gaotongxiao** [comment]
And you might want to take a look at [MMDeploy](https://github.com/open-mmlab/mmdeploy). Their team is now responsible for all deployment-related questions.

**Comment by Hegelim** [comment]
Thanks! That answers my questions
