### ISSUE TITLE
which label-tool should I choose

### ISSUE THREAD

**Issue by JunYao1020** [open-mmlab/mmocr#1129]
I'm planning to label my own training set to training FCE net
I have tried use 'labelme' to label data,but the lebel format seems to be different from the official.
so, in my case, which label tool should I choose?

**Comment by balandongiv** [comment]
You can refer the [convert-annotations-from-labelme](https://mmocr.readthedocs.io/en/latest/tools.html#convert-annotations-from-labelme)

**Comment by JunYao1020** [comment]
> You can refer the [convert-annotations-from-labelme](https://mmocr.readthedocs.io/en/latest/tools.html#convert-annotations-from-labelme)

thks :)

**Comment by JunYao1020** [comment]
> You can refer the [convert-annotations-from-labelme](https://mmocr.readthedocs.io/en/latest/tools.html#convert-annotations-from-labelme)

I successfully converted the annotation file, but the FCE configuration file does not seem to support the converted annotation file format, what else do I need to do?

**Comment by JunYao1020** [comment]
here is my cfg about data format
![image](https://user-images.githubusercontent.com/65162523/177111843-c1a6865a-d4e1-446f-bffd-69fa57b3af1b.png)

**Comment by JunYao1020** [comment]
some content in 'instance_training.txt' 
![image](https://user-images.githubusercontent.com/65162523/177112157-bbe7f3c3-fc42-4c41-afc1-fa9cdb3f4ef2.png)

**Comment by gaotongxiao** [comment]
@JunYao1020 The annotation looks fine to me. What error message did you get from FCENet?
