### ISSUE TITLE
There is a chance for the contour area equals 0, which will raise error when training and testing.

### ISSUE THREAD

**Issue by Bovey0809** [open-mmlab/mmocr#113]
I found the bug when testing the textsnake with my own dataset, the bug randomly occurred during training and testing. After serveral hours reading the code and paper, I managed to fix it by adding a check inside.
change this
https://github.com/open-mmlab/mmocr/blob/ce98d23ba2b5323348679dc19614d35c747c6a3c/mmocr/models/textdet/postprocess/wrapper.py#L390
to 
```python
if len(contours) > 0 and cv2.contourArea(contours[0]) > 0:
```
The contour for the boundary may be a single point sometime.

**Comment by innerlee** [comment]
Thanks! Would you like to making a pull request, so that your contribution would be recorded? Adding a test case would be greatly appreciated :) Also, we can add the change if you choose so

**Comment by Bovey0809** [comment]
> Thanks! Would you like to making a pull request, so that your contribution would be recorded? Adding a test case would be greatly appreciated :) Also, we can add the change if you choose so

Sorry. I can't make pull request due to some limitations of the network.

**Comment by innerlee** [comment]
Thanks 😊

**Comment by Bovey0809** [comment]
And also the contour returned by cv2 may not be a 8 points polygon.
which means 
```python
if len(contours) > 0 and cv2.contourArea(contours[0]) > 0:
    boundary = contours[0].flatten().tolist()
    if len(boundary) >= 8:
        boundaries.append(boundary)
```
