### ISSUE TITLE
Will changing the `crop_img` default parameter of `labelme_converter` affect subsequent pipeline?

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmocr#1131]
![ques_image](https://user-images.githubusercontent.com/22090092/176895076-9d2d3935-e22c-4116-a7dc-527865395fc5.jpg)

For some reason, Github unable to show the attached image properly. But the following discussion is base on the image that is accessible via the [link](https://user-images.githubusercontent.com/22090092/176895076-9d2d3935-e22c-4116-a7dc-527865395fc5.jpg).

Given an image with the characters `ILOVE` and `MMOCR`, stack vertically as shown in the `image A`. The image also smeared with multiple curvy horizontal lines (red lines).

The characters were annotated with `labelme`. A green bounding box were defined within the character, The bounding box was drawn in green color at the borderline of outer character as shown in `Figure B` in order to maintain consistency during annotating batches of images as well as avoiding the `red lines`. In this case, there is no padding (~ 0 pixel) between the character and green color rectangle.

The `labelme_converter.py` was then utilize to convert the `coco` to `mmocr-compatible` annotation format. For `recog`, the `labelme_converter` will automatically crop the image and produce an output as in Figure C. Please note that the ant green line in `Figure C` should in close contact (zero padding) with the characters as shown in `Figure B`. For some reason, there is a gap (Figure C) when I upload the image.

The specific line responsible for this is 

https://github.com/open-mmlab/mmocr/blob/64fb6fffc06f168355c8e3d28f5b31f26536f485/tools/data/common/labelme_converter.py#L96

The `crop_img` has the following default values

https://github.com/open-mmlab/mmocr/blob/64fb6fffc06f168355c8e3d28f5b31f26536f485/mmocr/datasets/pipelines/crop.py#L87

I notice, using the default value  for the  `long_edge_pad_ratio` and `short_edge_pad_ratio`, which has the value `0.4` and `0.2`, respectively, will result in the crop image with the `red_line`.

To remove the `red_line`, the following line was amended, from

https://github.com/open-mmlab/mmocr/blob/64fb6fffc06f168355c8e3d28f5b31f26536f485/tools/data/common/labelme_converter.py#L96

to 

`cropped_img = crop_img(src_img, quad,long_edge_pad_ratio=0.1, short_edge_pad_ratio=0.1)`

The value `0.1` for both `long_edge_pad_ratio` and `short_edge_pad_ratio` was selected subjectively. These changes yield a clean crop image (without the red lines).

My question are the following

1. Since a custom values were selected for the parameter  `long_edge_pad_ratio` and `short_edge_pad_ratio` , and these values were modified through the modification at the line [L96](https://github.com/open-mmlab/mmocr/blob/64fb6fffc06f168355c8e3d28f5b31f26536f485/tools/data/common/labelme_converter.py#L96), I wonder whether this changes might affect in a negative way downstream pipelines such as during training of the `detection` model, or inferencing process? My concern is, there might be another process down the line that call the `crop_img` function that rely on the default `crop_img`, instead of the new predefined value.
2. Is it customary/recommended to avoid such lines in the `training` images. Or perhaps, we can include image+noise(red lines) during both the text `detection` and `recognition` training process?

**Comment by Mountchicken** [comment]
Hi @balandongiv 
1. `crop_img` is also used in `ocr.py` to crop the detection results and feed them to recognition models. In practice, the detection result may be smaller than the actual text box, so setting a default margin can better crop the text for correct recognition, which I think is the reason that the default margin of this `crop_image` is large. And don't worry, during the training process, `crop_img` will not be used.

https://github.com/open-mmlab/mmocr/blob/64fb6fffc06f168355c8e3d28f5b31f26536f485/mmocr/utils/ocr.py#L712

2. For detection, the labeled box may not contain the red line, and for recognition, the red line as noise can theoretically improve the robustness of the recognizer.

**Comment by balandongiv** [comment]
Thanks for the insight, really appreciate it @Mountchicken
