### ISSUE TITLE
model warm-up options

### ISSUE THREAD

**Issue by Hegelim** [open-mmlab/mmocr#1132]
### Issue
I tried using the `mmocr.readtext()` function to do some inference, and interestingly, I found that if I do 5 inferences in a loop, then the first one will take significantly longer time than the rest of the iterations. My guess is the model itself will take some time to be loaded, then once it's loaded, it can do the inference. 

### Reproduce
I tried using the code that looks something like below
```
ocr = MMOCR(det=None, recog='ABINet')
times = []
#Inference
for i in range(5):
    start = time.time()
    results = ocr.readtext(args.directory, batch_mode=True, single_batch_size=128)
    if args.verbose:
        print(results)
    elapse = time.time() - start
    times.append(elapse)
    logging.warning(f"Time(s): {elapse}")
```
You can easily modify it to make it work on your machine. Then you will see that `times[0]` is significantly larger than the rest. In my case the list looks like
```
[4.117945432662964, 2.323190927505493, 2.4579269886016846, 2.4290578365325928, 2.3469598293304443]
```
### System 
* system: ubuntu 20.04
* python version: 3.8.12
* mmocr version: 0.6.0
* pytorch version: 1.11.0a0+17540c5
* mmcv version: 1.5.3

### Question
Is there a way to "warm-up" the model so that when I do the inference, it can just do it without spending time loading it?

**Comment by xinke-wang** [comment]
Hi, I noticed that you are using `args.directory`, the current inference interface pre-load all images in the directory at the first iteration, which may induce a longer running time. We are designing a more robust and faster inference interface, which will be released late this month.

**Comment by Hegelim** [comment]
Thanks for your explanation, look forward to the new version!
