### ISSUE TITLE
MMOCR Installation Documentation Outdated

### ISSUE THREAD

**Issue by Hegelim** [open-mmlab/mmocr#1133]
I think there are some discrepancies about installing MMOCR here on github: https://github.com/open-mmlab/mmocr between here https://mmocr.readthedocs.io/en/latest/install.html with the latter one being a bit outdated. 

I am just wondering if the latter one could be updated?

**Comment by xinke-wang** [comment]
Hi, the document is indeed a bit outdated. If you are interested, welcome to raise a PR to update it.
By the way, we are going to release a new version of mmocr soon, which also includes document updates, please stay tuned.

**Comment by gaotongxiao** [comment]
It has been updated in our latest release.
