### ISSUE TITLE
What is the difference between checkpoint and load_from

### ISSUE THREAD

**Issue by JunYao1020** [open-mmlab/mmocr#1137]
I’m tring to train a FCE net, so I refer to the official documentation, but some cfgs about pre-trained confuse me.
here it is :
    There is a ’load_from’ field in the ’default_runtime.py’ file to indicate the loaded pretrained model parameters, In addition, there is also a checkpoint field in the ‘fcenet_r50dcnv2_fpn.py’ file to represent the pre-trained model parameters.
    What is the difference between checkpoint and load_from? And if I want to set pre-trained cfg, which one cfg should I edit?

**Comment by xinke-wang** [comment]
1. The checkpoint param `checkpoint='torchvision://resnet50'` in `fcenet_r50dcnv2_fpn.py` (and other model configs) only initializes the backbone network (which is resnet50 here), this checkpoint is usually pre-trained on ImageNet (We usually don't modify this).
2. `load_from` in `default_runtime.py` specify the model you would like to resume your training from. That is to say, if you want to train from scratch, then you don't need to modify this; however, if you want to resume a training from previously trained FCE net, then you set a path to the pretrained model.
