### ISSUE TITLE
安装后demo测试无法运行

### ISSUE THREAD

**Issue by wedlight** [open-mmlab/mmocr#114]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

ImportError: /disk1/mh/software/anaconda3/envs/mmocr/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5emptyEN3c108ArrayRefIlEERKNS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE

**Reproduction**

1. What command or script did you run?
python demo/image_demo.py demo/demo_text_recog.jpg configs/textrecog/robust_scanner/robustscanner_r31_academic.py checkpoints/robustscanner_r31_academic-5f05874f.pth demo/res.jpg

python mmocr/utils/collect_env.py

2. Did you make any modifications on the code or config? Did you understand what you have modified?
no
3. What dataset did you use?
no dataset
**Environment**

1. Please run `python mmocr/utils/collect_env.py` to collect necessary environment information and paste it here.
can't run this command
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source] 
    - conda install pytorch==1.5.0 torchvision==0.6.0 cudatoolkit=9.2 -c pytorch
      pip install mmcv-full==1.3.1
      pip install mmdet==2.11.0
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.

```bash
(mmocr) mh@mustdl-3:/disk1/mh/projects/mmocr$ python demo/image_demo.py demo/demo_text_recog.jpg configs/textrecog/robust_scanner/robustscanner_r31_academic.py checkpoints/robustscanner_r31_academic-5f05874f.pth demo/res.jpg
Traceback (most recent call last):
  File "demo/image_demo.py", line 5, in <module>
    from mmdet.apis import init_detector
  File "/disk1/mh/software/anaconda3/envs/mmocr/lib/python3.7/site-packages/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/disk1/mh/software/anaconda3/envs/mmocr/lib/python3.7/site-packages/mmdet/apis/inference.py", line 6, in <module>
    from mmcv.ops import RoIPool
  File "/disk1/mh/software/anaconda3/envs/mmocr/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/disk1/mh/software/anaconda3/envs/mmocr/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/disk1/mh/software/anaconda3/envs/mmocr/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/disk1/mh/software/anaconda3/envs/mmocr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /disk1/mh/software/anaconda3/envs/mmocr/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5emptyEN3c108ArrayRefIlEERKNS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by innerlee** [comment]
mmcv was not installed successfully. You may uninstall it, and try again with https://github.com/open-mmlab/mmcv#installation
![image](https://user-images.githubusercontent.com/9464825/115703879-376cc400-a39d-11eb-8892-95e5ba5b0fe3.png)

**Comment by wedlight** [comment]
> mmcv was not installed successfully. You may uninstall it, and try again with https://github.com/open-mmlab/mmcv#installation
> ![image](https://user-images.githubusercontent.com/9464825/115703879-376cc400-a39d-11eb-8892-95e5ba5b0fe3.png)

谢谢回答，但是我无法通过 pip install mmcv-full=={mmcv_version} -f https://download.openmmlab.com/mmcv/dist/cu92/torch1.5.0/index.html 来安装mmcv
ERROR: Could not find a version that satisfies the requirement mmcv-full=={mmcv_version}
ERROR: No matching distribution found for mmcv-full=={mmcv_version}

**Comment by wedlight** [comment]
> mmcv was not installed successfully. You may uninstall it, and try again with https://github.com/open-mmlab/mmcv#installation
> ![image](https://user-images.githubusercontent.com/9464825/115703879-376cc400-a39d-11eb-8892-95e5ba5b0fe3.png)

thank you! 需要降低mmcv的版本

**Comment by cuhk-hbsun** [comment]
fixed
