### ISSUE TITLE
misleading default value

### ISSUE THREAD

**Issue by easilylazy** [open-mmlab/mmocr#1142]
https://github.com/open-mmlab/mmocr/blob/688d72fdc4b8b64282fc2af9bb0676c96f954ca1/tools/data/utils/lmdb_converter.py#L39
109951162776 may refer to 1TB（109951162**777**6 in fact）, digit `7` left

**Comment by Mountchicken** [comment]
Hi @easilylazy 
Thanks for pointing it out! If possible, you can raise a PR to fix it, and that would be appreciated.
