### ISSUE TITLE
Getting libpng warning bkgd invalid

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmocr#1148]
I have a list of images in `.png`. While train the `det` model, the compiler return `libpng warning bkgd invalid`.

I notice,  the accompnying `tod_dataset` in `tests/data/toy_dataset/imgs/test` are all in `.jpg` format. So my question is, what is the recommended image format for mmocr, is it `.jpg`? If not, then how to address the issue of  ` libpng warning bkgd invalid`. I notice atleast in the net, there is lot OP about this specific issue, but not within `mmocr` environment.

**Comment by gaotongxiao** [comment]
You might be using PNG files with four channels (https://blog.katastros.com/a?ID=a048d92c-a39d-4921-8b63-24231d34c1a8) whereas we usually assume the images have 3 channels. 

As a workaround, you might either convert all your png files to jpg formats or hack [`mmdet.LoadImageFromFile`](https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/datasets/pipelines/loading.py#L18) and do the conversion on the fly. https://stackoverflow.com/questions/35859140/remove-transparency-alpha-from-any-image-using-pil

**Comment by balandongiv** [comment]
Thanks for insight @gaotongxiao , really appreciate it
