### ISSUE TITLE
Help: How can I get the ouput json format?

### ISSUE THREAD

**Issue by truongchau2602** [open-mmlab/mmocr#1149]
<img width="616" alt="Screen Shot 2022-07-13 at 01 09 58" src="https://user-images.githubusercontent.com/64648373/178563556-57e98a15-ce6f-4f6e-ac95-bcdc478e0cd0.png">
<img width="1085" alt="Screen Shot 2022-07-13 at 01 10 17" src="https://user-images.githubusercontent.com/64648373/178563713-bb82c661-c984-4e69-b9a6-87935b376c71.png">
Hi, could you help me to display the bounding boxes and box's scores in JSON format of the image? How can I save the output JSON in a file?

**Comment by Harold-lkk** [comment]
You can use 'export='xx'' to save the output
