### ISSUE TITLE
A error in documentation

### ISSUE THREAD

**Issue by APX103** [open-mmlab/mmocr#1150]
Hey, I find a error [here](https://mmocr.readthedocs.io/en/latest/api.html#module-mmocr.datasets) in Documentation. It looks like a syntax error.

[ Docs ](https://mmocr.readthedocs.io/en/latest/index.html) > mmocr.apis > mmocr.datasets.BaseDataset

![image](https://user-images.githubusercontent.com/61487970/178636804-ad84449b-232b-4d0f-b698-eee1a365d8ec.png)

**Comment by Harold-lkk** [comment]
Thanks for pointing it out! If possible, you can raise a PR to fix it, and that would be appreciated.
