### ISSUE TITLE
Definition of pipeline `class Collect`

### ISSUE THREAD

**Issue by doem97** [open-mmlab/mmocr#1152]
Thanks for your efforts! I have three questions,

1. Where is the definition of pipeline `class Collect`? Not in MMCV or MMOCR.
2. How to check all of pre-registered/customized modules? I usually search for `@MODULETYPE.register_module()` through the entire MMOCR folder but am afraid to miss some. Do you have CLI like `python registered_module.py --list` to list available modules/info?
3. Does anyone have ViT-based text encoder/pipeline available?'

Thank you in advance!

**Comment by Mountchicken** [comment]
Hi @doem97 
1. As a downstream repo of MMDet, some pipelines are inherited from MMDet in MMOCR. [class Collect](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/formatting.py#L279).
2. I'm not sure whether MMOCR has such a tool. Maybe MMCV has one and if not, you are always welcome to help us to design such a tool and raise a PR.
3. So far MMOCR doesn't have pipelines or encoders that are related to ViT-architectur, but we do have transformer-encoder-based recognizers, E.g., ABINet, SATRN. NRTR.

**Comment by doem97** [comment]
> 

Thanks. 

For follower's convenience, I found MMOCR provides some module/API lists in the [document](https://mmocr.readthedocs.io/en/latest/api.html). It is much easier to search in this doc. (It is somehow out-of-date)

I adopt ViT encoder and re-designed encoder-decoder following ACMMM'22 DiG. People can PM me for a config/module file.
