### ISSUE TITLE
An Error raised when doing test

### ISSUE THREAD

**Issue by MingyuLau** [open-mmlab/mmocr#1155]
When I use 
``
python tools/test.py configs/_base_/recog_pipelines/master_pipeline.py 123/master_r31_12e_ST_MJ_SA-787edd36.pth --eval hmean-iou
``
to evaluate the model , it raises the error below:
![%WKZ74YVNYG8(X2FO1@LO7M](https://user-images.githubusercontent.com/88388495/178990927-49d54234-5c26-47b9-bac4-dd98c422bed5.png)

**Comment by balandongiv** [comment]
Can you share your `cfg` file here?

**Comment by gaotongxiao** [comment]
The correct config should be `configs/textrecog/master/master_r31_12e_ST_MJ_SA.py`
