### ISSUE TITLE
关于 TPS

### ISSUE THREAD

**Issue by 2793145003** [open-mmlab/mmocr#116]
我的项目中使用了 TPS（https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/transformation.py）
将 crnn 的 word_acc 从 0.56 提升到了 0.94。
但因为使用了其他人的代码，所以我不是很确定能不能直接提交到 mmocr（第一次试图参与开源贡献……）
如果不能的话，希望大佬们能够实现 TPS，因为真的很好用……

**Comment by innerlee** [comment]
TPS has Apache-2.0 License (the same as ours), so you can adapt it to here as long as the source and licence info is marked explicitly. You may also ask the original authors to see if they are willing to collaborate 😃

**Comment by jeffreykuang** [comment]
> 我的项目中使用了 TPS（[https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/transformation.py）](https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/transformation.py%EF%BC%89)
> 将 crnn 的 word_acc 从 0.56 提升到了 0.94。
> 但因为使用了其他人的代码，所以我不是很确定能不能直接提交到 mmocr（第一次试图参与开源贡献……）
> 如果不能的话，希望大佬们能够实现 TPS，因为真的很好用……

are your texts curved or noncurved?

TPS works on curved text recognition

**Comment by 2793145003** [comment]
> > 我的项目中使用了 TPS（[https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/transformation.py）](https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/transformation.py%EF%BC%89)
> > 将 crnn 的 word_acc 从 0.56 提升到了 0.94。
> > 但因为使用了其他人的代码，所以我不是很确定能不能直接提交到 mmocr（第一次试图参与开源贡献……）
> > 如果不能的话，希望大佬们能够实现 TPS，因为真的很好用……
> 
> are your texts curved or noncurved?
> 
> TPS works on curved text recognition

Yes it's curved. Or weired...
Many texts in my data are straight but just not perfectly horizontal...
