### ISSUE TITLE
Some images in png can be detected by PS_CTW but DBNetpp failed. 

### ISSUE THREAD

**Issue by di0002ya** [open-mmlab/mmocr#1160]
Hi team, 

I tried to use DBpp_r50 + ABINet for detecting scene text in some png images, model returns empty output.  

![makrologo_16](https://user-images.githubusercontent.com/42434100/179393717-d8d5e1a5-4926-419f-a75f-67a6d3aaa687.png)
![makrologo_6](https://user-images.githubusercontent.com/42434100/179393719-7733193a-32f0-49e1-81be-f95df68d36ee.png)

However, when I used PS_CTW + SAR, model returns promising output. 

May I know what's the reason results in this difference that DBpp_r50 has empty output on dealing with png files but PS_CTW can do it?

**Comment by balandongiv** [comment]
I remember in one discussion which indicate `mmocr` prefer `jpg` than `png`

**Comment by di0002ya** [comment]
@balandongiv  thanks for your hints. But PS_CTW is also one model in mmocr. It indeed works well in dealing with png files.

**Comment by di0002ya** [comment]
@balandongiv  could you share the link of this discussion? Thanks in advance!

**Comment by gaotongxiao** [comment]
The discussion: https://github.com/open-mmlab/mmocr/issues/1148

But it might not be the cause. It's probably because DBNet++ does not perform quite well on your png file. You can try DBNet++ on your data and check the detection result.
