### ISSUE TITLE
Augmentations on Recognition Training Data

### ISSUE THREAD

**Issue by bely66** [open-mmlab/mmocr#1167]
I'm noticing that when I'm training data on any of the recognition models, the data size is increased dramatically.
So I wanted to know if there's any kind of automatic augmentations applied on the data?

If there's how can I turn off because my data is already augmented, and what're the applied augmentations?

Regards,

**Comment by gaotongxiao** [comment]
Could you elaborate on the "data size" and how did you measure it? AFAIK MMOCR would never apply any automatic augmentation to data. There might be some transforms left in your `pipeline` configuration.

**Comment by bely66** [comment]
I’m using a 10k samples dataset.
In the training of SAR for examples using the default configuration the number of batches in one epoch is 123k

**Comment by bely66** [comment]
I found the error there was a variable called repeat in the dataset configuration file and it was set to 100, I added it as 1 and everything worked fine
Thanks
