### ISSUE TITLE
不提供预训练模型吗？比如百度ppocr，提供了所有的预训练模型，这边找了半天，没找到。

### ISSUE THREAD

**Issue by xinsuinizhuan** [open-mmlab/mmocr#1168]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when \[....\].
Ex2. There is a recent paper \[....\], which is very helpful for \[....\].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by Mountchicken** [comment]
Hi @xinsuinizhuan 
The links to the pre-trained models are under the config file of each algorithm, E.g. [ABINet](https://github.com/open-mmlab/mmocr/tree/main/configs/textrecog/abinet#results-and-models) [DBNet](https://github.com/open-mmlab/mmocr/tree/main/configs/textdet/dbnet#icdar2015)
