### ISSUE TITLE
MMOCR Freeze Layer for fixed feature extractor in Transfer Learning

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmocr#1169]
I would like to fine-tune a [pre-trained model](https://download.openmmlab.com/mmocr/textrecog/robustscanner/robustscanner_r31_academic-5f05874f.pth) on a custom dataset. To accelerate training, I would like to freeze some of the early layers and only update the later layers.

May I know whether is available helper script to do necessarily setting? If not, may I know which `function` I need to modify, at least within `mmocr` context.

**Comment by gaotongxiao** [comment]
You might refer to https://github.com/open-mmlab/mmocr/issues/1032
