### ISSUE TITLE
iou3d_boxes_iou_bev_forward miss in module _ext

### ISSUE THREAD

**Issue by OPzealot** [open-mmlab/mmocr#1177]
I've successfully build the docker image and run the container. Howerver, when i tried the demo, firstly it showed that mmcv==1.6.0 was used   and incompatible. I downgraded the mmcv to 1.5.0, and run the demo another assertionError showed up: 
```
 File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: iou3d_boxes_iou_bev_forward miss in module _ext
```
Btw, with this issues, i can't even import MMOCR and run the collect_env script.

**Comment by gaotongxiao** [comment]
To resolve your issue, try to install `mmcv-full` with
```bash
pip install mim
mim install mmcv-full==1.5.0
```

The reason why MMCV's version seems to be bounded is that MMDet is a bit outdated.

 https://github.com/open-mmlab/mmocr/blob/73222b270c53891d0223f976d2dbdd36d8770545/docker/Dockerfile#L22. 

It is an unnecessary version limit for mmdet and it can be freed as
```python
RUN pip install mmdet
```
