### ISSUE TITLE
onnx

### ISSUE THREAD

**Issue by sssimpleboy** [open-mmlab/mmocr#1179]
Do you know about onnx?
I trained Aster but I can't convert it to onnx. The beam_search and attention encoder decoder parts always error.But I can convert the TPS and STN part .So I can only get a modified image.  I am not sure if this is my problem or the model.

**Comment by sssimpleboy** [comment]
grid_sample of torch can't be converted to onnx.
And I use mmcv's bilinear_grid_sample to replace it . I succeed creating .onnx but when inference with  it, the error occurs:
INVALID_ARGUMENT : Non-zero status code returned while running Gather node. Name:'' Status Message: indices element out of data bounds, idx=0 must be within the inclusive range [0,-1]
I don't know where the problem is , I searched about this but got less message.  Could you help me？

**Comment by xinke-wang** [comment]
Hi, for Deployment-related questions, you may raise issues to [MMDeploy](https://github.com/open-mmlab/mmdeploy) for faster and more accurate responses.
