### ISSUE TITLE
Unable to Perform inference on Some Recognition Models

### ISSUE THREAD

**Issue by narenderkumarnain** [open-mmlab/mmocr#118]
When I use **demo/image_demo.py** script for inference on **seg_r31_1by16_fpnocr_academic** Model, this error message flashes, I am unable to resolve this problem even after some changes in the config file. After trying other recognition models, I found the same problem in CRNN Model also, but the rest models like Robust Scanner are working Fine.
Input to the model I am using is a Numpy array, not an image path.
![issue_mmocr](https://user-images.githubusercontent.com/59769621/115720516-c4fae480-a39a-11eb-9af5-d835c7a21111.png)

**Comment by innerlee** [comment]
Hi pls pull the latest master. We just merged a better demo script https://github.com/open-mmlab/mmocr/blob/main/demo/ocr_image_demo.py
