### ISSUE TITLE
Character not in dict

### ISSUE THREAD

**Issue by MingyuLau** [open-mmlab/mmocr#1180]
I met a problem when I train the ABINet

`raise Exception(f'Chararcter: {char} not in dict,'
Exception: Chararcter: , not in dict, please check gt_label and use custom dict file, or set "with_unknown=True"
`

**Comment by gaotongxiao** [comment]
It's because your dataset contains characters outside the dictionary. Set `num_chars=38` and `with_unknown=True` can address your issue.
https://github.com/open-mmlab/mmocr/blob/d901b37035a00738ea9d2f60cb1908640591af26/configs/_base_/recog_models/abinet.py#L5-L14

**Comment by wagoriginal** [comment]
please tell me how to solve this problem now, the folder changed, and i can't find them
