### ISSUE TITLE
Visualization of datasets

### ISSUE THREAD

**Issue by hzhuangdy** [open-mmlab/mmocr#1201]
Is there any way to visualize my training datasets? For example, when I train my own datasets with DBNet, is there any way to visualize the cropped image/shrink/threshold map?

Or can I show my ground truth image on tensorboard during training?

**Comment by gaotongxiao** [comment]
Currently not, but it's a feature in the upcoming release. Stay tuned!

**Comment by gaotongxiao** [comment]
The tool is now s available at MMCOR 1.0: https://mmocr.readthedocs.io/en/dev-1.x/user_guides/useful_tools.html#dataset-visualization-tool. You can find more usage at https://mmocr.readthedocs.io/en/dev-1.x/user_guides/visualization.html
