### ISSUE TITLE
Confusion about BGR vs RGB

### ISSUE THREAD

**Issue by davidmasek** [open-mmlab/mmocr#1202]
Hello,

I am a bit confused about channel order in MMOCR. If I understand it correctly the default is BGR. So I have images in RGB on disk (as I assume everyone does), they get loaded as BGR by MMOCR by default. This leads to outputing BGR images when using `./tools/test.py` with `--show-dir`. I could use `channel_order='bgr'` for `LoadImageFromFile` but I guess that would be bad, because the models expect BGR, right? 

Is my description correct? How should I handle this in MMOCR? Use BGR and then do my own postprocessing to get RGB? Some flag / config I don't know about?

Thank you

**Comment by Mountchicken** [comment]
Hi @davidmasek 
Sry for the late reply. You don't need to worry about the `BGR` problem. MMOCR use `mmcv.imread()` and `mmcv.imwrite()` to load and save image, respectively. So before loading and after saving, the channel order of images are kept as RGB.

**Comment by davidmasek** [comment]
@Mountchicken  this however does not match my experience, where the images that are output of `tools/test.py` are saved as BGR ... I specificaly tested this with red text that gets then saved as blue text.

**Comment by gaotongxiao** [comment]
The only configuration you need is to specify `to_rgb=True` in `Normalize` transform, as done in most of MMOCR's models. Take DBNet as an example:

https://github.com/open-mmlab/mmocr/blob/150cb13443134e4fd55e4f349954e024e116cbd7/configs/_base_/det_pipelines/dbnet_pipeline.py#L45-L48

https://github.com/open-mmlab/mmocr/blob/150cb13443134e4fd55e4f349954e024e116cbd7/configs/_base_/det_pipelines/dbnet_pipeline.py#L58

**Comment by davidmasek** [comment]
@gaotongxiao Ah, but I'm using only recognizer which uses "NormalizeOCR" does not even accept the "to_rgb" argument. I guess I could switch to "Normalize", but all of the reference configs use "NormalizeOCR" and quick replace led to another error.

As a side note, I'm not sure how to search for documentation when I see something like `dict(type='Normalize')` ... I often find it when it's directly from MMOCR, but often it's something from MMDet (or whatever) - is there is way to quickly find the correct class?

**Comment by gaotongxiao** [comment]
`NormalizeOCR` is confusing and essentially a duplicate implementation of `Normalize`. We had planned to replace them with `Normalize`, but the resulting changes were too many to be acceptable compared to another unified implementation which will soon be released. For now, you can replace it locally following the instruction in this PR: https://github.com/open-mmlab/mmocr/pull/740

Jumping to the module's implementation from a config has long been an issue. This would be alleviated in the upcoming release where each module's location can be printed at the initialization stage. But now we don't have any better solution than searching "class XXX" globally in MMOCR, MMDetection, and MMCV.
