### ISSUE TITLE
想问一下为什么ABINet中的ABILanguageDecoder 注释显示是来自satrn这篇论文的复现呢？

### ISSUE THREAD

**Issue by 1193700079** [open-mmlab/mmocr#1211]
![image](https://user-images.githubusercontent.com/43908729/180963449-c3ea4cce-94d8-4b11-879c-792b0aac9cc7.png)

**Comment by Mountchicken** [comment]
Hi @1193700079 
That's a mistake. Sorry for the confusion and we will fix it soon.
