### ISSUE TITLE
How to get a bounding box of 4 co-ordinates from boundary_result in mmocr?

### ISSUE THREAD

**Issue by arhamshah** [open-mmlab/mmocr#1214]
I am using TextSnake detection algorithm using MMOCR toolkit. I want to draw a bounding box around that detected text and perform various operations. 

Is there any way to obtain a bounding box with 4 co-ordinates representing the detected text?

**Comment by Mountchicken** [comment]
Hi @arhamshah 
Sry for the late reply.

There are basically two types of bounding box from an arbitray-shape polygon, namely external rectangle and minimum external rectangle.

To get the minimum external rectangle, you may refer to [fce_postprocessor](https://github.com/open-mmlab/mmocr/blob/main/mmocr/models/textdet/postprocess/fce_postprocessor.py#L11)
https://github.com/open-mmlab/mmocr/blob/150cb13443134e4fd55e4f349954e024e116cbd7/mmocr/models/textdet/postprocess/fce_postprocessor.py#L100-L108

To get the external rectangle, simply replace `minAreaRect` with `boundingRect` should works.
```python
 if self.text_repr_type == 'quad': 
     new_boundaries = [] 
     for boundary in boundaries: 
         poly = np.array(boundary[:-1]).reshape(-1, 
                                                2).astype(np.float32) 
         score = boundary[-1] 
         x, y, w, h = cv2.minAreaRect(poly)) 
         new_boundaries.append([x, y, x+w, y, x+w, y+h. x. y+h] + [score]) 
```
