### ISSUE TITLE
how  to open the file of mdb?

### ISSUE THREAD

**Issue by zdjaddress** [open-mmlab/mmocr#1218]
mmocr/tree/main/tests/data/ocr_toy_dataset/imgs.lmdb/data.mdb
mmocr/tree/main/tests/data/ocr_toy_dataset/imgs.lmdb/lock.mdb
mmocr/tree/main/tests/data/ocr_toy_dataset/label.lmdb/data.mdb
mmocr/tree/main/tests/data/ocr_toy_dataset/label.lmdb/lock.mdb

i can not open the files above,i try to use Access to open the files above,but it told me that the file was corrupted，please tell me how to open them.

**Comment by Mountchicken** [comment]
Hi @zdjaddress 
Accutually, we don't really open the lmdb file directly as it is just a kind of database file. And as far as I know, there is no software that can open lmdb files.

However, you can use a simple python script to browse lmdb files, here is an example：
https://github.com/HCIILAB/Scene-Text-Recognition-Recommendations/blob/main/datasets.md#visualize-dataset
