### ISSUE TITLE
How to pin_memory for OCRDataset/AnnFileLoader

### ISSUE THREAD

**Issue by doem97** [open-mmlab/mmocr#1222]
May I know how to [pin memory](https://pytorch.org/docs/stable/data.html#memory-pinning) as usual in torch.dataloaders? 

I recently faced a memory inefficient/crash problem, which is due to an elastic memory assigning.

Many thanks!

**Comment by Mountchicken** [comment]
Hi @doem97 
You can set `pin_memory=True` in data config. E.g.:
https://github.com/open-mmlab/mmocr/blob/150cb13443134e4fd55e4f349954e024e116cbd7/configs/textrecog/abinet/abinet_academic.py#L17-L21

```python
 data = dict( 
     samples_per_gpu=192, 
     workers_per_gpu=8, 
     pin_memory=True,
     val_dataloader=dict(samples_per_gpu=1), 
     test_dataloader=dict(samples_per_gpu=1), 
```

**Comment by doem97** [comment]
> Hi @doem97 You can set `pin_memory=True` in data config. E.g.:
> 
> https://github.com/open-mmlab/mmocr/blob/150cb13443134e4fd55e4f349954e024e116cbd7/configs/textrecog/abinet/abinet_academic.py#L17-L21
> 
> ```python
>  data = dict( 
>      samples_per_gpu=192, 
>      workers_per_gpu=8, 
>      pin_memory=True,
>      val_dataloader=dict(samples_per_gpu=1), 
>      test_dataloader=dict(samples_per_gpu=1), 
> ```

Many thanks! To whom it concern, the corresponding dataloader constructor locates at [mmdet.datasets.builder](https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/mmdet/datasets/builder.py#L195)
