### ISSUE TITLE
How to only use KIE model?

### ISSUE THREAD

**Issue by cvchongci** [open-mmlab/mmocr#1229]
We only want to use the KIE model provided in MMOCR.  Because we have commercial general OCR API which can output text's bounding box and content, and in line level. Is there any demo code which can tell me  how to plug the results of our commercial OCR API into KIE model for inference.

Thanks a lot.

**Comment by gaotongxiao** [comment]
We support Tesseract as an OCR backend whose predictions can be utilized by KIE models seamlessly.
https://github.com/open-mmlab/mmocr/blob/150cb13443134e4fd55e4f349954e024e116cbd7/mmocr/utils/ocr.py#L744-766

Though all the codes are available in `ocr.py`, you might be interested to check out the design doc for this implementation: https://docs.google.com/document/d/1Zxjm7n4-L-Rrw4nziZ0GKbzLqPfF-Sqo0JLCgn16lV0/edit#heading=h.mzjhfi42fc16
