### ISSUE TITLE
Does IMG_LIST have any formatting requirements?

### ISSUE THREAD

**Issue by kerisbor** [open-mmlab/mmocr#125]
Test Multiple Images :
sh tools/test_imgs.sh ${CONFIG_FILE} ${CHECKPOINT_FILE} ${IMG_ROOT_PATH} ${IMG_LIST} ${RESULTS_DIR}

**Comment by jeffreykuang** [comment]
> Test Multiple Images :
> sh tools/test_imgs.sh ${CONFIG_FILE} ${CHECKPOINT_FILE} ${IMG_ROOT_PATH} ${IMG_LIST} ${RESULTS_DIR}

IMG_LIST is a txt file, where each line is the filename of one img.  The concatenation of the IMG_ROOT_PATH and the filename is the full path of the img.

**Comment by kerisbor** [comment]
> > Test Multiple Images :
> > sh tools/test_imgs.sh ${CONFIG_FILE} ${CHECKPOINT_FILE} ${IMG_ROOT_PATH} ${IMG_LIST} ${RESULTS_DIR}
> 
> IMG_LIST is a txt file, where each line is the filename of one img. The concatenation of the IMG_ROOT_PATH and the filename is the full path of the img.

thank you✔
