### ISSUE TITLE
dbnetpp 8GPU loss_db=1.000

### ISSUE THREAD

**Issue by jiarenyf** [open-mmlab/mmocr#1264]
Same dataset, dbnet without pretrained model, using 8GPU get 85% hmean ...
Same dataset, dbnetpp without pretrained model, using 8GPU get loss_db = 1.000 during 10 epoch ...
Same dataset, dbnetpp without pretrained model, using 1GPU, training seems ok because loss_db = 0.3 at the first epoch ...

I found that the pretrained dbnet and dbnetpp models provided are all trained with 1 GPU ...

I wonder why using 8GPU cause dbnetpp not converge ...

**Comment by gaotongxiao** [comment]
Using 8 GPUs means the actual batch size is 8x greater than that of 1 GPU. If you don't scale the batch size, convergence is expected to be much slower.

**Comment by chengchenng** [comment]
I change the batch size of val_dataset from 16 to 1, because out of memory sometimes while testing.  But I find that when batch size of val_dataset changes, the db_loss will equal to 1.00. Why val_dataset batch size will affect training? Anyone have ideas? Thanks!
