### ISSUE TITLE
Difference between dbnet and dbnetpp

### ISSUE THREAD

**Issue by jiarenyf** [open-mmlab/mmocr#1265]
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/12405578/183273115-08c93ae0-c365-414f-9c7d-9a11719c7324.png">
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/12405578/183273165-9f3d29af-e5e2-42e6-b96d-90883c28eff8.png">

I wonder why dbnetpp using `epsilon_ratio=0.002` and `samples_per_gpu=32`, not the same with dbnet, causing the result is not comparable ...

**Comment by xinke-wang** [comment]
Hi, this was set to keep consistent with the official implementation of DBNet++.

You may would like to check it [here](https://github.com/MhLiao/DB/blob/e5a12f5c2f0c2b4a345b5b8392307ef73481d5f6/structure/representers/seg_detector_representer.py#L83).
