### ISSUE TITLE
Why are uppercase letters identified as lowercase letters?

### ISSUE THREAD

**Issue by zdjaddress** [open-mmlab/mmocr#1273]
![image](https://user-images.githubusercontent.com/64459712/183796084-3265d1a4-285b-4287-95b0-2e7934abbab3.png)
![image](https://user-images.githubusercontent.com/64459712/183796146-6b641daa-db0e-4d56-8957-5cd5e2cab42f.png)
![image](https://user-images.githubusercontent.com/64459712/183796297-37ff6ec0-7619-4efe-9fd3-60f6e93e0047.png)

I use ABINET to train text recognition (including English case, digits and special characters)，without using the pre-trained model, The dictionary uses 'DICT91', but in the actual recognition effect, the upper case of English is identified as lower case. Please tell me how to solve this problem, thank you.

**Comment by xinke-wang** [comment]
Please set `lower=False`, otherwise the gt texts will be converted to lower case.

**Comment by zdjaddress** [comment]
It was my carelessness，thank you very much.
