### ISSUE TITLE
How to test the FPS of dbnet?

### ISSUE THREAD

**Issue by ahsdx** [open-mmlab/mmocr#1277]
Hello, I want to test the FPS of dbnet. How can I test it correctly? 
Here are two ways I test FPS:
![image](https://user-images.githubusercontent.com/39435512/184058456-890e529f-1fab-4620-8b38-9d57cb5e86a1.png)
and
![image](https://user-images.githubusercontent.com/39435512/184060089-015c8f97-f6f1-4ad5-bedd-b4eb0825bc1d.png)
I would like to ask whether it is correct to do so.

**Comment by xinke-wang** [comment]
It depends on the case. If you only want to measure the forwarding time of the model, then the first method is enough. However, if you would like to consider all time cost factors, the second is better.

**Comment by ahsdx** [comment]
> It depends on the case. If you only want to measure the forwarding time of the model, then the first method is enough. However, if you would like to consider all time cost factors, the second is better.

Okay! I understand. Thank you!
