### ISSUE TITLE
How to restore your Robust Scanner checkpoint and fine-tune it on my own data?

### ISSUE THREAD

**Issue by antoniolanza1996** [open-mmlab/mmocr#128]
I'm trying to fine-tune your [Robust Scanner checkpoint](https://download.openmmlab.com/mmocr/textrecog/robustscanner/robustscanner_r31_academic-5f05874f.pth) on my own data. However when I use `--resume-from` option, a `KeyError` is thrown because there's no `epoch` in your checkpoint.

**Reproduction**
`python3 tools/train.py  ./configs/textrecog/robust_scanner/robustscanner_custom_training.py --work-dir=../output_train --resume-from robustscanner_r31_academic-5f05874f.pth --seed 42`

**Error traceback**
```
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    main()
  File "tools/train.py", line 201, in main
    meta=meta)
  File "/content/gdrive/MyDrive/MMOCR_toolbox/mmocr/mmocr/apis/train.py", line 146, in train_detector
    runner.resume(cfg.resume_from)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_runner.py", line 340, in resume
    self._epoch = checkpoint['meta']['epoch']
KeyError: 'epoch'
```

**Comment by innerlee** [comment]
Use load_from in configs

**Comment by antoniolanza1996** [comment]
Solved, thank you.

**Comment by f-izzat** [comment]
Id like to repoen the issue as I faced the same problem but for totaltext
```
python3.8/site-packages/mmengine/runner/runner.py", line 1931, in resume
    self.train_loop._epoch = checkpoint['meta']['epoch']
KeyError: 'epoch'
```
I put `load_from` in my config file with the absolute path to the downloaded checkpoint
```
# dataset settings
textdet_train = _base_.textdet_train
textdet_test = _base_.textdet_test
textdet_train.pipeline = train_pipeline
textdet_test.pipeline = test_pipeline
load_from = "/Desktop/CODE/computer_vision/text_detection/dbnet_resnet18_fpnc_1200e_totaltext-3ed3233c.pth"
```
