### ISSUE TITLE
error when training text detect model with config ScaleAspectJitter  (branch v0.6.1)

### ISSUE THREAD

**Issue by JohnTang93** [open-mmlab/mmocr#1286]
tag v0.6.1
when training text detection model with maskrcnn or psenet (which has ScaleAspectJitter in training config), 
error:
  raise type(e)(f'{obj_cls.name}: {e}')
  AssertionError: UniformConcatDataset: IcdarDataset: ScaleAspectJitter:

**Comment by JohnTang93** [comment]
build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: UniformConcatDataset: IcdarDataset: ScaleAspectJitter:

**Comment by gaotongxiao** [comment]
Hi, I wasn't able to reproduce this issue on a clean v0.6.1. Please double-check if you have modified any part of the code and/or config.

**Comment by JohnTang93** [comment]
sorry, I made a mistake
