### ISSUE TITLE
FCENet

### ISSUE THREAD

**Issue by seekingdeep** [open-mmlab/mmocr#129]
@jeffreykuang Hi there,
FCENet seems promising, the following are some questions:
- FCENet uses ResNet50 backbone, but why doesn't it use a ResNet18 backbone with a better architecture such as:
[DDRNet-23-slim](https://github.com/ydhongHIT/DDRNet), or [BiSeNet V2](https://github.com/CoinCheung/BiSeNet).
- What is the FPS prediction speed of FCENet using CPU-only
- How much RAM memory does it require for prediction on CPU-only

**Comment by jeffreykuang** [comment]
> @jeffreykuang Hi there,
> FCENet seems promising, the following are some questions:
> 
>     * FCENet uses ResNet50 backbone, but why doesn't it use a ResNet18 backbone with a better architecture such as:
>       [DDRNet-23-slim](https://github.com/ydhongHIT/DDRNet), or [BiSeNet V2](https://github.com/CoinCheung/BiSeNet).
> 
>     * What is the FPS prediction speed of FCENet using CPU-only
> 
>     * How much RAM memory does it require for prediction on CPU-only

It is a good idea to try DDRNet-23-slim and BiSeNet V2. We will add two configs with the two as backbones when FCENET is released @HolyCrap96 

We did not measure the speed with cpu-only and the runtime RAM.  We will try to report this two metrics when it is released @HolyCrap96

**Comment by seekingdeep** [comment]
Thanks, good luck
