### ISSUE TITLE
How to train my own chinese data with recognize?

### ISSUE THREAD

**Issue by Nuralill** [open-mmlab/mmocr#1291]
I want train my own dataset ,and I choose the command 
> python tools/train.py configs/textrecog/satrn/satrn_academic.py --work-dir workplace/recog
I change the code in `satrn_academic.py `, use `'../../_base_/recog_datasets/toy_data.py',`,and the dataset format is same as `\tests\data\ocr_toy_dataset`
the error information is :
`lmdb.Error: UniformConcatDataset: OCRDataset: AnnFileLoader: tests/data/ocr_toy_dataset/test_label.txt: ϵͳ�Ҳ���ָ����·����
`
How can I train successfully?
Is there a way to train det+recog module ,rather than  seperately train?
我想训练自己的含有中文的识别加检测数据集，我已经训练了检测模型，然后把检测模型中的文字裁剪标注做成了识别的数据集，按照bilibili中的方法进行训练，但是无法识别中文，请问我应该如何训练中文的识别模型呢？
是否存在方法可以直接训练检测加识别模型，而不用单独分别训练检测，识别呢？

**Comment by gaotongxiao** [comment]
It was because your dataset format was in text format, whereas you had loaded it with `lmdb` backend. Try the following configuration, and don't forget to remove `repeat=100` from your config, otherwise your training set will be 100x greater than that you actually have.
https://github.com/open-mmlab/mmocr/blob/d8549ade850b85e369e753480772d7b24218c6e1/configs/_base_/recog_datasets/toy_data.py#L7-L22

**Comment by gaotongxiao** [comment]
And currently, there is no way to train the text detection model and recognition model simultaneously.

**Comment by Nuralill** [comment]
Thank u for your help.
I change the config ,it begin to run,but there is another error 
`load index 422 with error Extra data: line 1 column 9 (char 8)`
my label.txt in 422 is `20220608_blue_h_100(3).jpg  OPEN HERE 请由此撕/打开`
It seems still can not read chinese.
What can I do with this error?

**Comment by gaotongxiao** [comment]
It's because your annotation contains blank spaces, which cannot be represented by this simple format. Read this [tutorial](https://mmocr.readthedocs.io/en/latest/tutorials/blank_recog.html) for more info

**Comment by Nuralill** [comment]
Thanks a lot.
I delete the space，but when  I started train ,there will occur `RuntimeError`
`RuntimeError: CUDA out of memory. Tried to allocate 80.00 MiB (GPU 0; 12.00 GiB total capacity; 11.14 GiB already allocated; 0 bytes free; 11.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
but I think my GPU device is enough to train.
`Mon Aug 22 11:15:01 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.15       Driver Version: 512.15       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
|  0%   41C    P8     9W / 170W |    182MiB / 12288MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       988    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      1128    C+G                                   N/A      |
|    0   N/A  N/A      1892    C+G   ...kyb3d8bbwe\HxAccounts.exe    N/A      |
|    0   N/A  N/A      3540    C+G   ...cw5n1h2txyewy\LockApp.exe    N/A      |
|    0   N/A  N/A      4200    C+G   ...ekyb3d8bbwe\YourPhone.exe    N/A      |
|    0   N/A  N/A      5116    C+G   ...ekyb3d8bbwe\HxOutlook.exe    N/A      |
|    0   N/A  N/A      7768    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A      9752    C+G   ...2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A     10560    C+G   ...ge\Application\msedge.exe    N/A      |
|    0   N/A  N/A     11252    C+G   ...8wekyb3d8bbwe\Cortana.exe    N/A      |
|    0   N/A  N/A     11816    C+G                                   N/A      |
|    0   N/A  N/A     12072    C+G   ...lPanel\SystemSettings.exe    N/A      |
+-----------------------------------------------------------------------------+`
Inside my img floder ,there are 1224 photos which size is about 380*46(The image size is not uniform)
Is there something wrong in my dataset？Or Where should I change in the code？

**Comment by gaotongxiao** [comment]
There's nothing wrong with your dataset. You might want to reduce the batch size to fit the data to your GPU memory.

Take CRNN as an example, changing this line can address this issue:
https://github.com/open-mmlab/mmocr/blob/e98d69f2aadd76884c249f0c027d46698c5b5bb1/configs/textrecog/crnn/crnn_academic_dataset.py#L16

**Comment by Nuralill** [comment]
thx a lot !
