### ISSUE TITLE
Test ERROR with ‘The model and loaded state dict do not match exactly‘

### ISSUE THREAD

**Issue by Nuralill** [open-mmlab/mmocr#1310]
I want to train my chinese recog  module , when  I use following code train success ,I find test will show error.

load checkpoint from local path: workplace/recog/latest.pth
The model and loaded state dict do not match exactly
train command is `python tools/train.py configs/textrecog/sar/sar_r31_parallel_decoder_chinese.py --work-dir workplace/recog`
test command is ` python tools/test.py configs/textrecog/sar/sar_r31_parallel_decoder_chinese.py workplace/recog/latest.pth  --eval hmean-iou --show-dir workplace/aaaaa`
> size mismatch for decoder.embedding.weight: copying a param with shape torch.Size([94, 512]) from checkpoint, the shape in current model is torch.Size([11380, 512]).
> size mismatch for decoder.prediction.weight: copying a param with shape torch.Size([93, 1536]) from checkpoint, the shape in current model is torch.Size([11379, 1536]).
> size mismatch for decoder.prediction.bias: copying a param with shape torch.Size([93]) from checkpoint, the shape in current model is torch.Size([11379]).
> [                                                  ] 0/268, elapsed: 0s, ETA:Traceback (most recent call last):
>   File "tools/test.py", line 235, in <module>
>     main()
>   File "tools/test.py", line 205, in main
>     is_kie, args.show_score_thr)
>   File "e:\pycharmprojects\mmocr-main\mmocr\apis\test.py", line 122, in single_gpu_test
>     retrieve_img_tensor_and_meta(data)
>   File "e:\pycharmprojects\mmocr-main\mmocr\apis\test.py", line 52, in retrieve_img_tensor_and_meta
>     f'Please add {key} to the "meta_keys" in the pipeline')
> KeyError: 'Please add img_shape to the "meta_keys" in the pipeline'`

**my** root is train_root='data/chineseocr/labels'
train_prefix =  f'{train_root}/imgs'
train_ann_file =f'{train_root}/labels/train.txt'

And I use the cofigs/sar/sar_r31_parallel_decoder_chinese.py  I change some codes.
And the image size is not uniform, most about 380*46.
```
_base_ = [
    '../../_base_/default_runtime.py',
    '../../_base_/schedules/schedule_adam_step_5e.py'
]

dict_file = 'data/chineseocr/labels/dict_printed_chinese_english_digits.txt'
label_convertor = dict(
    type='AttnConvertor', dict_file=dict_file, with_unknown=True)

model = dict(
    type='SARNet',
    backbone=dict(type='ResNet31OCR'),
    encoder=dict(
        type='SAREncoder',
        enc_bi_rnn=False,
        enc_do_rnn=0.1,
        enc_gru=False,
    ),
    decoder=dict(
        type='ParallelSARDecoder',
        enc_bi_rnn=False,
        dec_bi_rnn=False,
        dec_do_rnn=0,
        dec_gru=False,
        pred_dropout=0.1,
        d_k=512,
        pred_concat=True),
    loss=dict(type='SARLoss'),
    label_convertor=label_convertor,
    max_seq_len=30)

img_norm_cfg = dict(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='ResizeOCR',
        height=48,
        min_width=48,
        max_width=256,
        keep_aspect_ratio=True,
        width_downsample_ratio=0.25),
    dict(type='ToTensorOCR'),
    dict(type='NormalizeOCR', **img_norm_cfg),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'filename', 'ori_shape', 'resize_shape', 'text', 'valid_ratio','resize_shape'
        ]),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiRotateAugOCR',
        rotate_degrees=[0, 90, 270],
        transforms=[
            dict(
                type='ResizeOCR',
                height=48,
                min_width=48,
                max_width=256,
                keep_aspect_ratio=True,
                width_downsample_ratio=0.25),
            dict(type='ToTensorOCR'),
            dict(type='NormalizeOCR', **img_norm_cfg),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=[
                    'filename', 'ori_shape', 'resize_shape', 'valid_ratio','resize_shape', 'img_norm_cfg', 'ori_filename'
                ]),
        ])
]

dataset_type = 'OCRDataset'
train_root='data/chineseocr/labels'
train_prefix =  f'{train_root}/imgs'
train_ann_file =f'{train_root}/labels/train.txt'

train = dict(
    type=dataset_type,
    img_prefix=train_prefix,
    ann_file=train_ann_file,
    loader=dict(
        type='AnnFileLoader',
        repeat=1,
        file_format='txt',
        file_storage_backend='disk',
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=False)

test_prefix = f'{train_root}/imgs'

test_ann_file = f'{train_root}/labels/test.txt'

test = dict(
    type=dataset_type,
    img_prefix=test_prefix,
    ann_file=test_ann_file,
    loader=dict(
        type='AnnFileLoader',
        repeat=1,
        file_format='txt',
        file_storage_backend='disk',
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=False)

data = dict(
    samples_per_gpu=40,
    workers_per_gpu=2,
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1),
    train=dict(
        type='UniformConcatDataset', datasets=[train],
        pipeline=train_pipeline),
    val=dict(
        type='UniformConcatDataset', datasets=[test], pipeline=test_pipeline),
    test=dict(
        type='UniformConcatDataset', datasets=[test], pipeline=test_pipeline))

evaluation = dict(interval=1, metric='acc')
```
Is there something wrong with my image?Should I resize and uniform the image size?
What can I do to run it successfully?Please help me.Tks.

**Comment by gaotongxiao** [comment]
There are two issues to address.

First, according to the log,
```python
KeyError: 'Please add img_shape to the "meta_keys" in the pipeline'`
```
You need to add `img_shape` to `Collect.meta_keys` in your test pipeline to eliminate the error.

About the size mismatch error, it seems your checkpoint doesn't match the config. Are you sure you trained with this config and checkpoint is the right one? All I can tell is that `workplace/recog/latest.pth` uses a dictionary containing 94 keys.

**Comment by Nuralill** [comment]
I have resolved the problem，thanks a lot!
