### ISSUE TITLE
训练mmocr识别模型时候 evaluation = dict(interval=1, metric='acc',save_best = 'auto')  无法像mmclassicifition 保存最优模型

### ISSUE THREAD

**Issue by ViviKing414** [open-mmlab/mmocr#1378]
训练mmocr识别模型时候 evaluation = dict(interval=1, metric='acc',save_best = 'auto')  无法像mmclassicifition 保存最优模型

**Comment by xinke-wang** [comment]
Hi, the metric used in MMOCR is not `acc`, you have to specify the metric name as `0_word_acc_ignore_case` for example, for recognition task. Please also refer to issue #1130 .

**Comment by ViviKing414** [comment]
Thanks for your answer, I'll try it now

**Comment by wenhui66** [comment]
save_best的指标值在哪里可以找到，我是用的coco-wholebody数据集但我只提取了身体和手部用于训练，所以我不知道save_best应该设置什么值来保存最优模型
