### ISSUE TITLE
AssertionError: TensorRT plugin should be compiled Error

### ISSUE THREAD

**Issue by Paschapy** [open-mmlab/mmocr#1382]
I am developing on nvidia jetson nano. When i try to onnx to tensorrt deployment with the psnet_ctw detection model, i take this error. I read the documents about this issue but i couldn't find anything.

![trt_error](https://user-images.githubusercontent.com/60448321/189331606-7dff8cfe-300a-4a3a-8f81-05a8978efed4.png)

**Comment by xinke-wang** [comment]
Hi, for deployment-related questions, please refer to [MMDeploy](https://github.com/open-mmlab/mmdeploy) where you could get more professional answers.
