### ISSUE TITLE
Is data augmentation used in mmocr

### ISSUE THREAD

**Issue by superPangpang** [open-mmlab/mmocr#139]

**Comment by innerlee** [comment]
dup of https://github.com/open-mmlab/mmocr/issues/138

**Comment by innerlee** [comment]
Hi @superPangpang do you need any help? Please give more details :)

**Comment by superPangpang** [comment]
I'm really sorry that I didn't notice that I sent the question twice. Thank you for your answer!  I'll look at it carefully
