### ISSUE TITLE
ocr中文识别，在合成识别数据集的时候，怎么保证字符数的平衡呢？

### ISSUE THREAD

**Issue by njustczr** [open-mmlab/mmocr#1394]
ocr中文识别，在合成识别数据集的时候，合成数据的语料通常是我们自己准备的，可以是一本电子书，但是在统计中文字符数的时候，不同的中文字符在语料中出现的次数差别很大，怎么解决这个字符数不均衡呢？

**Comment by njustczr** [comment]
> ocr中文识别，在合成识别数据集的时候，合成数据的语料通常是我们自己准备的，可以是一本电子书，但是在统计中文字符数的时候，不同的中文字符在语料中出现的次数差别很大，怎么解决这个字符数不均衡呢？

如果只是简单的采样的话，那样会破坏语义信息

**Comment by Mountchicken** [comment]
Hi @njustczr 
Actually, the category imbalance is not a big concern. As long as the corpus is large enough, the trained recognizers can work very well. The long-tail distribution problem is not significant in commonly used Chinese characters.
