### ISSUE TITLE
About the training of Chinese text recognition model in version 1.x

### ISSUE THREAD

**Issue by htaoruan** [open-mmlab/mmocr#1396]
Hello,Where should I write the code about the dictionary in the new version? The old version is written as follows.
dict_file = 'data/chineseocr/labels/dict_printed_chinese_english_digits.txt'
label_convertor = dict(type='AttnConvertor', dict_file=dict_file, with_unknown=True)

**Comment by xinke-wang** [comment]
Hi,

All of the dictionaries are now stored under the [`dicts/`](https://github.com/open-mmlab/mmocr/tree/dev-1.x/dicts) folder. You can specify the dictionary path in the configs. For example, 

https://github.com/open-mmlab/mmocr/blob/93d883e7dc33d01f97e4fd1ba8cfcb62e3820985/configs/textrecog/master/_base_master_resnet31.py#L3-L10

**Comment by htaoruan** [comment]
OK  Thank you very much.
