### ISSUE TITLE
ONNX and TRT conversion Support for recog models

### ISSUE THREAD

**Issue by kishcs** [open-mmlab/mmocr#1397]
**Describe the feature**
- Converting recognition models such as `SAR`, `NRTR_*` and `RobustScanner` to `ONNX` and `TensorRT` format.

**Motivation**
As we know TensorRT models are faster on Nvidia GPUs compared to Torch Models, hence many prefers to use the `trt` models.
As I explored MMOcr library, I found that few recog models performs better compared to others. However currently there is no official support yet with `onnx` and `tensorrt` model format.

**Additional context**
Also it would be great, if you can publish a generic guide explaining the conversion process which can help other developers in the community to pitch in and contribute these features.

**Comment by xinke-wang** [comment]
Hi, please refer to [MMDeploy](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/04-supported-codebases/mmocr.md) where several recognition models are supported in TensorRT, ONNX, and etc.

**Comment by kishcs** [comment]
> Hi, please refer to [MMDeploy](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/04-supported-codebases/mmocr.md) where several recognition models are supported in TensorRT, ONNX, and etc.

Thanks for your response. I will try with `MMDeploy` for `SAR` model.
Any idea, when support will be provided for `NRTR` and `RobustScanner` models ?
