### ISSUE TITLE
ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by czb7046** [open-mmlab/mmocr#1403]
when I execute the command "pip install -r requirements.txt", the error happens：
 **Building wheel for lanms-neo (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for lanms-neo (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\lanms
      copying lanms\__init__.py -> build\lib.win-amd64-cpython-38\lanms
      running build_ext
      building 'lanms._C' extension
      creating build\temp.win-amd64-cpython-38
      creating build\temp.win-amd64-cpython-38\Release
      creating build\temp.win-amd64-cpython-38\Release\lanms
      creating build\temp.win-amd64-cpython-38\Release\lanms\csrc
      creating build\temp.win-amd64-cpython-38\Release\lanms\csrc\clipper
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874af
aeaafcb\lanms\csrc -IC:\Users\CZB\AppData\Local\Temp\pip-build-env-opzy7kr5\overlay\Lib\site-packages\pybind11\include -ID:\ProgramFiles\Anaconda3\envs\openmmlab\include -ID:\ProgramFiles\Anaconda3\envs\openmmlab\Include "-IC:\Program Files (x86
)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um
" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Ki
ts\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tplanms/csrc/clipper\clipper.cpp /Fobuild\temp.win-amd64-cpython-38\Release\lanms/csrc/clipper\clipper.obj /std:c++latest /EHsc /bi
gobj
      clipper.cpp
      lanms/csrc/clipper\clipper.cpp(3795): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874af
aeaafcb\lanms\csrc -IC:\Users\CZB\AppData\Local\Temp\pip-build-env-opzy7kr5\overlay\Lib\site-packages\pybind11\include -ID:\ProgramFiles\Anaconda3\envs\openmmlab\include -ID:\ProgramFiles\Anaconda3\envs\openmmlab\Include "-IC:\Program Files (x86
)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um
" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Ki
ts\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tplanms/csrc\lanms.cpp /Fobuild\temp.win-amd64-cpython-38\Release\lanms/csrc\lanms.obj /std:c++latest /EHsc /bigobj
      lanms.cpp
      C:\Users\CZB\AppData\Local\Temp\pip-build-env-opzy7kr5\overlay\Lib\site-packages\pybind11\include\pybind11\detail/common.h(1040): error C2737: “pybind11::overload_cast”: 必须初始化“constexpr”对象
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(18): warning C4244: “+=”: 从“double”转换到“float”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(66): warning C4244: “+=”: 从“float”转换到“int64_t”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(67): warning C4244: “+=”: 从“float”转换到“int64_t”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(69): warning C4244: “+=”: 从“float”转换到“int64_t”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(70): warning C4244: “+=”: 从“float”转换到“int64_t”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(72): warning C4244: “+=”: 从“float”转换到“int64_t”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(73): warning C4244: “+=”: 从“float”转换到“int64_t”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(75): warning C4244: “+=”: 从“float”转换到“int64_t”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(76): warning C4244: “+=”: 从“float”转换到“int64_t”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(147): warning C4244: “=”: 从“float”转换到“ClipperLib::cInt”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(148): warning C4244: “=”: 从“float”转换到“ClipperLib::cInt”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(149): warning C4244: “=”: 从“float”转换到“ClipperLib::cInt”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(150): warning C4244: “=”: 从“float”转换到“ClipperLib::cInt”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(151): warning C4244: “=”: 从“float”转换到“ClipperLib::cInt”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(152): warning C4244: “=”: 从“float”转换到“ClipperLib::cInt”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(153): warning C4244: “=”: 从“float”转换到“ClipperLib::cInt”，可能丢失数据
      C:\Users\CZB\AppData\Local\Temp\pip-install-evqbkjy3\lanms-neo_8633a17f2c2a41fc9575874afaeaafcb\lanms\csrc\lanms.h(154): warning C4244: “=”: 从“float”转换到“ClipperLib::cInt”，可能丢失数据
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lanms-neo
Failed to build lanms-neo
ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects**

**Comment by gaotongxiao** [comment]
Please refer to https://github.com/open-mmlab/mmocr/issues/1263

**Comment by czb7046** [comment]
> Please refer to #1263

Thanks, It's also solved by the link https://github.com/argman/EAST/issues/120
