### ISSUE TITLE
ema相关问题

### ISSUE THREAD

**Issue by oszn** [open-mmlab/mmocr#1419]
我在使用ema去进行跟新参数的时候，loss是正常下降，但是到了eval（evaluation = dict(interval=10, metric='hmean-iou')）的时候会出现结果为0的情况，请问这个该如何解决。

**Comment by gaotongxiao** [comment]
It happens occasionally for detection models, and it's probably because the model just needs a few more rounds of training. See [DBNet's log](https://download.openmmlab.com/mmocr/textdet/dbnet/dbnet_r18_fpnc_sbn_1200e_icdar2015_20210329-ba3ab597.log.json) for example

**Comment by oszn** [comment]
the prob loss is not down at first, so the inference will be 0,but i use panet, and the loss down is normal,but when i try ema mechanie, the eval state is 0,0,0. i think when using ema ,the training state is ok,but the eval paraments copy might have some promble. mabey the code struct is not suit for the ema.
