### ISSUE TITLE
SAR Confidence is always the same

### ISSUE THREAD

**Issue by bely66** [open-mmlab/mmocr#1420]
I'm trying to pick the lowest confidence examples SAR is getting but the surprise was It always outputs the same confidence.
It always output:
'text_score': 0.04334113448858261

and the results of the model are pretty good, so it seems something is going wrong with the output confidence score

**Comment by xinke-wang** [comment]
It was a bug which has been fixed in PR#1333. Please pull the latest code ans try again.
