### ISSUE TITLE
ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by cbwznb** [open-mmlab/mmocr#1421]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmocr/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.

```none
A placeholder for traceback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by xinke-wang** [comment]
Please check your `gcc` and `g++` version by running the following command in bash, and make sure both of their versions are higher than `v7.5`.
```bash
gcc --version
g++ --version
```

**Comment by cbwznb** [comment]
I am using windows and the environment configured by anaconda.


2223025466
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月30日(星期五) 晚上9:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmocr] ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects (Issue #1421)





 
Please check your gcc and g++ version by running the following command in bash, and make sure both of their versions are higher than v7.5.
 gcc --version g++ --version

**Comment by gaotongxiao** [comment]
Hi, please refer to https://github.com/open-mmlab/mmocr/issues/1403 for the solution
