### ISSUE TITLE
KeyError: 'MultiRotateAugOCR is not in the pipeline registry'

### ISSUE THREAD

**Issue by cbwznb** [open-mmlab/mmocr#1424]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmocr/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.

```none
A placeholder for traceback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by gaotongxiao** [comment]
Hi, please provide all the necessary information following this issue template. Without sufficient information we are not able to identify the issue.

**Comment by cbwznb** [comment]
/-------------------------------------------------------------------------------------------------------------------------------
I have trained the pt file, and this error will occur when I run it according to the code of Mr. Zhang Zihao.
/-------------------------------------------------------------------------------------------------------------------------------

this is my code

from mmocr.apis import init_detector, model_inference
from mmcv import Config
# 导入 opencv-python
import cv2

# 导入可视化工具包 matplotlib，并让绘制的图像嵌入在 notebook 中
import matplotlib.pyplot as plt



# 定义可视化图像函数，输入图像路径，可视化图像
def show_img_from_path(img_path):
    '''opencv 读入图像，matplotlib 可视化格式为 RGB，因此需将 BGR 转 RGB，最后可视化出来'''
    img = cv2.imread(img_path)
    img_RGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.imshow(img_RGB)
    plt.show()


# 定义可视化图像函数，输入图像 array，可视化图像
def show_img_from_array(img):
    '''输入 array，matplotlib 可视化格式为 RGB，因此需将 BGR 转 RGB，最后可视化出来'''
    img_RGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.imshow(img_RGB)
    plt.show()


if __name__ == '__main__':

    # 指定模型 checkpoint 权重文件
    checkpoint = "./demo/tutorial_exps/epoch_5.pth"
    # print(checkpoint)
    # cfg = Config.fromfile('./configs/textrecog/sar/sar_r31_parallel_decoder_toy_dataset.py')
    # cfg = Config.fromfile('./configs/_base_/recog_datasets/toy_data.py')
    cfg = './configs/textrecog/sar/sar_r31_parallel_decoder_toy_dataset.py'

    model = init_detector(cfg, checkpoint, device="cuda:0")

    input_path = 'tests/data/ocr_toy_dataset/imgs/3bx86.png'
    result = model_inference(model, input_path)
    # out_img = model.show_result(input_path, result, out_file='outputs/demo-out.jpg', show=False)
    # show_img_from_array(out_img)
