### ISSUE TITLE
dev-1.x版本，用dbnet训练icdar2017mlt的问题

### ISSUE THREAD

**Issue by ConflictPeople** [open-mmlab/mmocr#1426]
您好，我想问下关于dev-1.x版本训练数据集的问题。
我将     dict(type='FixInvalidPolygon', mode='fix', min_poly_points=3)   添加到   train_pipeline  中，训练出现错误：
           Exception: Cannot determine whether the polygon is inside the image, because it contains no points.
不知道是什么问题，数据集转换是用官方提供的迁移代码，应该是没有问题的。
具体的错误如下：
10/05 21:19:27 - mmengine - INFO - Epoch(train) [1][260/1200]  lr: 7.0000e-03  eta: 2 days, 7:02:27  time: 0.8387  data_time: 0.1538  memory: 3608  loss_prob: 2.1957  loss_thr: 0.8966  loss_db: 0.3960  loss: 3.4883
10/05 21:19:32 - mmengine - INFO - Epoch(train) [1][265/1200]  lr: 7.0000e-03  eta: 2 days, 7:02:27  time: 0.8552  data_time: 0.1697  memory: 3608  loss_prob: 2.0312  loss_thr: 0.8293  loss_db: 0.3572  loss: 3.2177
10/05 21:19:35 - mmengine - INFO - Epoch(train) [1][270/1200]  lr: 7.0000e-03  eta: 2 days, 6:54:57  time: 0.7768  data_time: 0.0946  memory: 3608  loss_prob: 2.1056  loss_thr: 0.8052  loss_db: 0.3712  loss: 3.2820
10/05 21:19:39 - mmengine - INFO - Epoch(train) [1][275/1200]  lr: 7.0000e-03  eta: 2 days, 6:54:57  time: 0.7252  data_time: 0.0585  memory: 3608  loss_prob: 2.0963  loss_thr: 0.8200  loss_db: 0.3674  loss: 3.2836
10/05 21:19:43 - mmengine - INFO - Epoch(train) [1][280/1200]  lr: 7.0000e-03  eta: 2 days, 6:52:15  time: 0.8068  data_time: 0.1522  memory: 3608  loss_prob: 2.1957  loss_thr: 0.8609  loss_db: 0.3913  loss: 3.4479
10/05 21:19:47 - mmengine - INFO - Epoch(train) [1][285/1200]  lr: 7.0000e-03  eta: 2 days, 6:52:15  time: 0.7906  data_time: 0.1313  memory: 3608  loss_prob: 2.4018  loss_thr: 0.9013  loss_db: 0.4518  loss: 3.7548
10/05 21:19:52 - mmengine - INFO - Epoch(train) [1][290/1200]  lr: 7.0000e-03  eta: 2 days, 6:55:10  time: 0.8462  data_time: 0.1735  memory: 3608  loss_prob: 2.3692  loss_thr: 0.9078  loss_db: 0.4511  loss: 3.7281
10/05 21:19:55 - mmengine - INFO - Epoch(train) [1][295/1200]  lr: 7.0000e-03  eta: 2 days, 6:55:10  time: 0.8288  data_time: 0.1478  memory: 3608  loss_prob: 2.2352  loss_thr: 0.8624  loss_db: 0.4046  loss: 3.5022
10/05 21:19:58 - mmengine - INFO - Epoch(train) [1][300/1200]  lr: 7.0000e-03  eta: 2 days, 6:36:06  time: 0.6827  data_time: 0.0100  memory: 3608  loss_prob: 2.1241  loss_thr: 0.8419  loss_db: 0.3641  loss: 3.3300
10/05 21:20:02 - mmengine - INFO - Epoch(train) [1][305/1200]  lr: 7.0000e-03  eta: 2 days, 6:36:06  time: 0.6773  data_time: 0.0196  memory: 3608  loss_prob: 2.0909  loss_thr: 0.8389  loss_db: 0.3672  loss: 3.2970
10/05 21:20:05 - mmengine - INFO - Epoch(train) [1][310/1200]  lr: 7.0000e-03  eta: 2 days, 6:18:06  time: 0.6814  data_time: 0.0224  memory: 3608  loss_prob: 2.0570  loss_thr: 0.8367  loss_db: 0.3739  loss: 3.2676
10/05 21:20:09 - mmengine - INFO - Epoch(train) [1][315/1200]  lr: 7.0000e-03  eta: 2 days, 6:18:06  time: 0.7543  data_time: 0.0872  memory: 3608  loss_prob: 1.9904  loss_thr: 0.8566  loss_db: 0.3480  loss: 3.1950
10/05 21:20:14 - mmengine - INFO - Epoch(train) [1][320/1200]  lr: 7.0000e-03  eta: 2 days, 6:20:12  time: 0.8335  data_time: 0.1751  memory: 3608  loss_prob: 2.1454  loss_thr: 0.8461  loss_db: 0.3840  loss: 3.3755
10/05 21:20:17 - mmengine - INFO - Epoch(train) [1][325/1200]  lr: 7.0000e-03  eta: 2 days, 6:20:12  time: 0.7810  data_time: 0.1101  memory: 3608  loss_prob: 2.2708  loss_thr: 0.8527  loss_db: 0.4330  loss: 3.5566
10/05 21:20:21 - mmengine - INFO - Epoch(train) [1][330/1200]  lr: 7.0000e-03  eta: 2 days, 6:13:30  time: 0.7620  data_time: 0.0823  memory: 3608  loss_prob: 2.3136  loss_thr: 0.8722  loss_db: 0.4279  loss: 3.6137
10/05 21:20:26 - mmengine - INFO - Epoch(train) [1][335/1200]  lr: 7.0000e-03  eta: 2 days, 6:13:30  time: 0.8631  data_time: 0.2113  memory: 3608  loss_prob: 2.1267  loss_thr: 0.8069  loss_db: 0.3580  loss: 3.2915
10/05 21:20:29 - mmengine - INFO - Epoch(train) [1][340/1200]  lr: 7.0000e-03  eta: 2 days, 6:13:40  time: 0.8170  data_time: 0.1689  memory: 3608  loss_prob: 2.0431  loss_thr: 0.7892  loss_db: 0.3512  loss: 3.1836
10/05 21:20:34 - mmengine - INFO - Epoch(train) [1][345/1200]  lr: 7.0000e-03  eta: 2 days, 6:13:40  time: 0.7674  data_time: 0.0914  memory: 3608  loss_prob: 2.1607  loss_thr: 0.8578  loss_db: 0.3912  loss: 3.4097
10/05 21:20:38 - mmengine - INFO - Epoch(train) [1][350/1200]  lr: 7.0000e-03  eta: 2 days, 6:20:18  time: 0.8739  data_time: 0.1962  memory: 3608  loss_prob: 2.0222  loss_thr: 0.8473  loss_db: 0.3536  loss: 3.2231
10/05 21:20:43 - mmengine - INFO - Epoch(train) [1][355/1200]  lr: 7.0000e-03  eta: 2 days, 6:20:18  time: 0.9039  data_time: 0.2308  memory: 3608  loss_prob: 2.2421  loss_thr: 0.8553  loss_db: 0.4112  loss: 3.5086
10/05 21:20:47 - mmengine - INFO - Epoch(train) [1][360/1200]  lr: 7.0000e-03  eta: 2 days, 6:24:58  time: 0.8596  data_time: 0.1616  memory: 3608  loss_prob: 2.3680  loss_thr: 0.8573  loss_db: 0.4513  loss: 3.6766
10/05 21:20:51 - mmengine - INFO - Epoch(train) [1][365/1200]  lr: 7.0000e-03  eta: 2 days, 6:24:58  time: 0.8784  data_time: 0.1607  memory: 3608  loss_prob: 2.2537  loss_thr: 0.8293  loss_db: 0.4050  loss: 3.4881
10/05 21:20:55 - mmengine - INFO - Epoch(train) [1][370/1200]  lr: 7.0000e-03  eta: 2 days, 6:27:26  time: 0.8417  data_time: 0.1110  memory: 3608  loss_prob: 2.2662  loss_thr: 0.8372  loss_db: 0.4056  loss: 3.5090
10/05 21:20:59 - mmengine - INFO - Epoch(train) [1][375/1200]  lr: 7.0000e-03  eta: 2 days, 6:27:26  time: 0.7678  data_time: 0.0669  memory: 3608  loss_prob: 2.0675  loss_thr: 0.8166  loss_db: 0.3650  loss: 3.2490
10/05 21:21:03 - mmengine - INFO - Epoch(train) [1][380/1200]  lr: 7.0000e-03  eta: 2 days, 6:28:56  time: 0.8336  data_time: 0.1327  memory: 3608  loss_prob: 1.8555  loss_thr: 0.7945  loss_db: 0.3093  loss: 2.9592
10/05 21:21:07 - mmengine - INFO - Epoch(train) [1][385/1200]  lr: 7.0000e-03  eta: 2 days, 6:28:56  time: 0.8152  data_time: 0.0837  memory: 3608  loss_prob: 1.8711  loss_thr: 0.7725  loss_db: 0.3170  loss: 2.9606
10/05 21:21:12 - mmengine - INFO - Epoch(train) [1][390/1200]  lr: 7.0000e-03  eta: 2 days, 6:32:07  time: 0.8509  data_time: 0.1476  memory: 3608  loss_prob: 2.1423  loss_thr: 0.8119  loss_db: 0.3819  loss: 3.3361
10/05 21:21:16 - mmengine - INFO - Epoch(train) [1][395/1200]  lr: 7.0000e-03  eta: 2 days, 6:32:07  time: 0.8322  data_time: 0.1655  memory: 3608  loss_prob: 2.3436  loss_thr: 0.8531  loss_db: 0.4355  loss: 3.6323
10/05 21:21:20 - mmengine - INFO - Epoch(train) [1][400/1200]  lr: 7.0000e-03  eta: 2 days, 6:31:06  time: 0.8106  data_time: 0.1600  memory: 3608  loss_prob: 2.1862  loss_thr: 0.8320  loss_db: 0.3989  loss: 3.4170
10/05 21:21:25 - mmengine - INFO - Epoch(train) [1][405/1200]  lr: 7.0000e-03  eta: 2 days, 6:31:06  time: 0.9392  data_time: 0.2712  memory: 3608  loss_prob: 2.1511  loss_thr: 0.8559  loss_db: 0.3867  loss: 3.3937
10/05 21:21:28 - mmengine - INFO - Epoch(train) [1][410/1200]  lr: 7.0000e-03  eta: 2 days, 6:31:14  time: 0.8220  data_time: 0.1428  memory: 3608  loss_prob: 2.2351  loss_thr: 0.8673  loss_db: 0.4131  loss: 3.5155
10/05 21:21:33 - mmengine - INFO - Epoch(train) [1][415/1200]  lr: 7.0000e-03  eta: 2 days, 6:31:14  time: 0.8078  data_time: 0.1377  memory: 3608  loss_prob: 2.0459  loss_thr: 0.8302  loss_db: 0.3643  loss: 3.2404
10/05 21:21:37 - mmengine - INFO - Epoch(train) [1][420/1200]  lr: 7.0000e-03  eta: 2 days, 6:31:35  time: 0.8242  data_time: 0.1669  memory: 3608  loss_prob: 1.9860  loss_thr: 0.8068  loss_db: 0.3377  loss: 3.1305
10/05 21:21:41 - mmengine - INFO - Epoch(train) [1][425/1200]  lr: 7.0000e-03  eta: 2 days, 6:31:35  time: 0.8016  data_time: 0.1540  memory: 3608  loss_prob: 2.1773  loss_thr: 0.8492  loss_db: 0.3998  loss: 3.4263
10/05 21:21:45 - mmengine - INFO - Epoch(train) [1][430/1200]  lr: 7.0000e-03  eta: 2 days, 6:33:20  time: 0.8396  data_time: 0.1785  memory: 3608  loss_prob: 2.0677  loss_thr: 0.8466  loss_db: 0.3787  loss: 3.2930
10/05 21:21:50 - mmengine - INFO - Epoch(train) [1][435/1200]  lr: 7.0000e-03  eta: 2 days, 6:33:20  time: 0.8759  data_time: 0.2174  memory: 3608  loss_prob: 1.9348  loss_thr: 0.7984  loss_db: 0.3279  loss: 3.0611
10/05 21:21:53 - mmengine - INFO - Epoch(train) [1][440/1200]  lr: 7.0000e-03  eta: 2 days, 6:33:45  time: 0.8260  data_time: 0.1766  memory: 3608  loss_prob: 1.9858  loss_thr: 0.8121  loss_db: 0.3452  loss: 3.1430
10/05 21:21:57 - mmengine - INFO - Epoch(train) [1][445/1200]  lr: 7.0000e-03  eta: 2 days, 6:33:45  time: 0.7188  data_time: 0.0646  memory: 3608  loss_prob: 2.0046  loss_thr: 0.8104  loss_db: 0.3583  loss: 3.1733
10/05 21:22:01 - mmengine - INFO - Epoch(train) [1][450/1200]  lr: 7.0000e-03  eta: 2 days, 6:26:05  time: 0.7350  data_time: 0.0774  memory: 3608  loss_prob: 2.1618  loss_thr: 0.8221  loss_db: 0.3964  loss: 3.3803
10/05 21:22:04 - mmengine - INFO - Epoch(train) [1][455/1200]  lr: 7.0000e-03  eta: 2 days, 6:26:05  time: 0.7057  data_time: 0.0388  memory: 3608  loss_prob: 2.1805  loss_thr: 0.8318  loss_db: 0.4089  loss: 3.4212
10/05 21:22:08 - mmengine - INFO - Epoch(train) [1][460/1200]  lr: 7.0000e-03  eta: 2 days, 6:16:33  time: 0.7099  data_time: 0.0352  memory: 3608  loss_prob: 2.1053  loss_thr: 0.7993  loss_db: 0.3858  loss: 3.2904
10/05 21:22:13 - mmengine - INFO - Epoch(train) [1][465/1200]  lr: 7.0000e-03  eta: 2 days, 6:16:33  time: 0.8600  data_time: 0.1931  memory: 3608  loss_prob: 2.0168  loss_thr: 0.7886  loss_db: 0.3508  loss: 3.1562
10/05 21:22:16 - mmengine - INFO - Epoch(train) [1][470/1200]  lr: 7.0000e-03  eta: 2 days, 6:18:54  time: 0.8448  data_time: 0.1822  memory: 3608  loss_prob: 1.9688  loss_thr: 0.8208  loss_db: 0.3414  loss: 3.1309
10/05 21:22:19 - mmengine - INFO - Epoch(train) [1][475/1200]  lr: 7.0000e-03  eta: 2 days, 6:18:54  time: 0.6835  data_time: 0.0249  memory: 3608  loss_prob: 1.9766  loss_thr: 0.8260  loss_db: 0.3447  loss: 3.1473
10/05 21:22:23 - mmengine - INFO - Epoch(train) [1][480/1200]  lr: 7.0000e-03  eta: 2 days, 6:10:24  time: 0.7159  data_time: 0.0581  memory: 3608  loss_prob: 1.9463  loss_thr: 0.8088  loss_db: 0.3391  loss: 3.0942
10/05 21:22:27 - mmengine - INFO - Epoch(train) [1][485/1200]  lr: 7.0000e-03  eta: 2 days, 6:10:24  time: 0.7512  data_time: 0.1016  memory: 3608  loss_prob: 1.9787  loss_thr: 0.8188  loss_db: 0.3488  loss: 3.1463
10/05 21:22:32 - mmengine - INFO - Epoch(train) [1][490/1200]  lr: 7.0000e-03  eta: 2 days, 6:12:18  time: 0.8392  data_time: 0.1822  memory: 3608  loss_prob: 2.0050  loss_thr: 0.7991  loss_db: 0.3529  loss: 3.1570
10/05 21:22:35 - mmengine - INFO - Epoch(train) [1][495/1200]  lr: 7.0000e-03  eta: 2 days, 6:12:18  time: 0.8318  data_time: 0.1622  memory: 3608  loss_prob: 1.9462  loss_thr: 0.7593  loss_db: 0.3383  loss: 3.0438
10/05 21:22:40 - mmengine - INFO - Epoch(train) [1][500/1200]  lr: 7.0000e-03  eta: 2 days, 6:13:17  time: 0.8288  data_time: 0.1673  memory: 3608  loss_prob: 1.8975  loss_thr: 0.7517  loss_db: 0.3310  loss: 2.9802
10/05 21:22:44 - mmengine - INFO - Epoch(train) [1][505/1200]  lr: 7.0000e-03  eta: 2 days, 6:13:17  time: 0.8495  data_time: 0.1657  memory: 3608  loss_prob: 1.9522  loss_thr: 0.7846  loss_db: 0.3414  loss: 3.0783
10/05 21:22:47 - mmengine - INFO - Epoch(train) [1][510/1200]  lr: 7.0000e-03  eta: 2 days, 6:06:12  time: 0.7263  data_time: 0.0357  memory: 3608  loss_prob: 2.0866  loss_thr: 0.7922  loss_db: 0.3594  loss: 3.2381
10/05 21:22:51 - mmengine - INFO - Epoch(train) [1][515/1200]  lr: 7.0000e-03  eta: 2 days, 6:06:12  time: 0.7389  data_time: 0.0656  memory: 3608  loss_prob: 2.2619  loss_thr: 0.7750  loss_db: 0.3917  loss: 3.4286
10/05 21:22:55 - mmengine - INFO - Epoch(train) [1][520/1200]  lr: 7.0000e-03  eta: 2 days, 6:02:16  time: 0.7637  data_time: 0.0941  memory: 3608  loss_prob: 2.2336  loss_thr: 0.7867  loss_db: 0.3985  loss: 3.4188
10/05 21:22:59 - mmengine - INFO - Epoch(train) [1][525/1200]  lr: 7.0000e-03  eta: 2 days, 6:02:16  time: 0.7648  data_time: 0.0912  memory: 3608  loss_prob: 2.1293  loss_thr: 0.7905  loss_db: 0.3883  loss: 3.3082
10/05 21:23:02 - mmengine - INFO - Epoch(train) [1][530/1200]  lr: 7.0000e-03  eta: 2 days, 5:56:53  time: 0.7427  data_time: 0.0684  memory: 3608  loss_prob: 1.9903  loss_thr: 0.7819  loss_db: 0.3454  loss: 3.1177
10/05 21:23:07 - mmengine - INFO - Epoch(train) [1][535/1200]  lr: 7.0000e-03  eta: 2 days, 5:56:53  time: 0.7712  data_time: 0.1055  memory: 3608  loss_prob: 1.9632  loss_thr: 0.7751  loss_db: 0.3240  loss: 3.0623
10/05 21:23:10 - mmengine - INFO - Epoch(train) [1][540/1200]  lr: 7.0000e-03  eta: 2 days, 5:54:18  time: 0.7778  data_time: 0.1161  memory: 3608  loss_prob: 2.1571  loss_thr: 0.7986  loss_db: 0.3770  loss: 3.3326
10/05 21:23:14 - mmengine - INFO - Epoch(train) [1][545/1200]  lr: 7.0000e-03  eta: 2 days, 5:54:18  time: 0.7238  data_time: 0.0699  memory: 3608  loss_prob: 2.0050  loss_thr: 0.7701  loss_db: 0.3496  loss: 3.1246
10/05 21:23:19 - mmengine - INFO - Epoch(train) [1][550/1200]  lr: 7.0000e-03  eta: 2 days, 6:01:16  time: 0.9083  data_time: 0.2615  memory: 3608  loss_prob: 1.8577  loss_thr: 0.7602  loss_db: 0.3072  loss: 2.9252
Traceback (most recent call last):
  File "/home/wqb/WQB/mmocr/tools/train.py", line 124, in <module>
    main()
  File "/home/wqb/WQB/mmocr/tools/train.py", line 120, in main
    runner.train()
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1631, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/mmengine/runner/loops.py", line 88, in run
    self.run_epoch()
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/mmengine/runner/loops.py", line 103, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1204, in _next_data
    return self._process_data(data)
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
Exception: Caught Exception in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/mmengine/dataset/dataset_wrapper.py", line 131, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 408, in __getitem__
    data = self.prepare_data(idx)
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 789, in prepare_data
    return self.pipeline(data_info)
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 58, in __call__
    data = t(data)
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/mmcv/transforms/base.py", line 11, in __call__
    return self.transform(results)
  File "/home/wqb/WQB/mmocr/mmocr/datasets/transforms/wrappers.py", line 76, in transform
    if not self._augment_annotations(aug, ori_shape, results):
  File "/home/wqb/WQB/mmocr/mmocr/datasets/transforms/wrappers.py", line 103, in _augment_annotations
    transformed_polygons, removed_poly_inds = self._augment_polygons(
  File "/home/wqb/WQB/mmocr/mmocr/datasets/transforms/wrappers.py", line 153, in _augment_polygons
    if poly.is_out_of_image(imgaug_polys.shape):
  File "/home/wqb/anaconda3/envs/mmocr_dev1x/lib/python3.8/site-packages/imgaug/augmentables/polys.py", line 512, in is_out_of_image
    raise Exception("Cannot determine whether the polygon is inside "
Exception: Cannot determine whether the polygon is inside the image, because it contains no points.
希望能够得到回复，谢谢！

**Comment by gaotongxiao** [comment]
We have received many bug reports about this dataset. I am looking into this issue as well and will get back to you asap.

**Comment by gaotongxiao** [comment]
It should be fixed in #1434. Feel free to open a new issue if your request hasn't been addressed.

**Comment by ConflictPeople** [comment]
> It should be fixed in #1434. Feel free to open a new issue if your request hasn't been addressed.

Thank you very much.
