### ISSUE TITLE
Difference between label_convertor.max_seq_len and model.max_seq_len

### ISSUE THREAD

**Issue by antoniolanza1996** [open-mmlab/mmocr#1428]
Reading your codebase, I got it that we have to set two different `max_seq_len` parameters.
1. In the `AttnConvertor`'s `__init__` function [here](https://github.com/open-mmlab/mmocr/blob/v0.6.0/mmocr/models/textrecog/convertors/attn.py#L32) to prepare input data with `str2tensor` function
2. in the `model` config in order to set the shape of `decoder.position_decoder.embedding` layer

Furthermore, from your `robust_scanner` config example, the first one is [set by default to 40](https://github.com/open-mmlab/mmocr/blob/v0.6.0/configs/_base_/recog_models/robust_scanner.py#L2) and the second one is programmatically [set to 30](https://github.com/open-mmlab/mmocr/blob/v0.6.0/configs/_base_/recog_models/robust_scanner.py#L24). Is it a normal behaviour that these two values are different?

**Comment by gaotongxiao** [comment]
That's a nice catch, I believe that it was a mistake. We have addressed this design flaw in MMOCR 1.0 by integrating `XXXConvertor` into `XXXModuleLoss`, which is now a part of the model, and sharing the same `max_seq_len` parameter across all the decoders in RobustScanner.  https://github.com/open-mmlab/mmocr/blob/dev-1.x/configs/textrecog/robust_scanner/_base_robustscanner_resnet31.py 
Here is the [migration guide](https://mmocr.readthedocs.io/en/dev-1.x/migration/code.html#text-recognition) for more details.

You are welcome to check out our latest [RC](https://github.com/open-mmlab/mmocr/tree/1.x) as well as the renewed [docs](https://mmocr.readthedocs.io/en/dev-1.x/get_started/overview.html).

**Comment by antoniolanza1996** [comment]
Good idea to share the same `max_seq_len` parameter, it will avoid confusion for future users.

Regarding MMOCR 0.x, I've quickly checked and there are two convertors that use `max_seq_len` parameter: `ABIConvertor` and `AttnConvertor`.

List of configs files that use these convertors:
```
- configs/_base_/recog_models/sar.py
- configs/_base_/recog_models/satrn.py
- configs/_base_/recog_models/master.py
- configs/_base_/recog_models/nrtr_modality_transform.py
- configs/_base_/recog_models/robust_scanner.py
- configs/textrecog/nrtr/nrtr_r31_1by8_1by4_academic.py
- configs/textrecog/nrtr/nrtr_r31_1by16_1by8_academic.py
- configs/textrecog/sar/sar_r31_parallel_decoder_chinese.py
- configs/textrecog/sar/sar_r31_sequential_decoder_academic.py
- configs/textrecog/satrn/satrn_academic.py
- configs/textrecog/satrn/satrn_small.py
- configs/_base_/recog_models/abinet.py
- configs/textrecog/abinet/abinet_vision_only_academic.py
 ```

Could be useful to check these files and set the same `max_seq_len` for both `label_convertor.max_seq_len` and `model.max_seq_len`. If you are interested in making it compliant, I can open a PR. Otherwise, let's stick with the new MMOCR 1.0 implementation.

**Comment by gaotongxiao** [comment]
We will keep maintaining MMOCR 0.x for a few months more, so it would be nice if this little inconsistency could still be fixed. Your help is appreciated :)

**Comment by antoniolanza1996** [comment]
Sounds good. I've opened a PR (#1433). Let me know if more is needed.
