### ISSUE TITLE
CTW1500 for DBNet

### ISSUE THREAD

**Issue by seekingdeep** [open-mmlab/mmocr#143]
Hi,
are there plans to release the DBNet model for CTW1500

**Comment by jeffreykuang** [comment]
> Hi,
> are there plans to release the DBNet model for CTW1500

Yes, we are planning to release it. However, it is not in our high priority list at present.  You can try to train it according to our documents and we will try our best to support you if you cannot wait for it.

**Comment by seekingdeep** [comment]
thanks
