### ISSUE TITLE
Significance of assessment metrics？

### ISSUE THREAD

**Issue by htaoruan** [open-mmlab/mmocr#1438]
During the model training process, the following metrics are available on the validation set to evaluate the model,：
0_char_recall， 0_char_precision,  0_word_acc,  0_word_acc_ignore_case, 0_word_acc_ignore_case_symbol, 0_1-N.E.D。
Ask what they mean exactly and which one of them can better reflect the performance of the model？

**Comment by xinke-wang** [comment]
Usually, we use `word_acc_ignore_case_symbol` to compare different models, which is a widely used metric in both academia and industry. For more details about these metrics, you may check our [doc](https://mmocr.readthedocs.io/en/dev-1.x/basic_concepts/evaluation.html).

**Comment by gaotongxiao** [comment]
As a side note, the doc that @xinke-wang referred to is for MMOCR 1.0 and apparently you are using MMOCR 0.x. While the functionalities of these metrics are equivalent, the config structure is significantly changed and therefore they look different than that in your local copy.

**Comment by htaoruan** [comment]
ok  thank you
