### ISSUE TITLE
tensorboard visualize error

### ISSUE THREAD

**Issue by YanHao22** [open-mmlab/mmocr#1439]
hi, i wish to visualize the loss curve so i add 'dict(type='TensorboardLoggerHook')' in the log_config. but i got the error:

> Traceback (most recent call last):
>   File "/home/wanggang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/logger/tensorboard.py", line 48, in before_run
>     from torch.utils.tensorboard import SummaryWriter
>   File "/home/wanggang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 9, in <module>
>     raise ImportError('TensorBoard logging requires TensorBoard version 1.15 or above')
> ImportError: TensorBoard logging requires TensorBoard version 1.15 or above
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tools/train.py", line 243, in <module>
>     run_train_cmd(args)
>   File "tools/train.py", line 238, in run_train_cmd
>     meta=meta)
>   File "/home/wanggang/data/yanhao/mmocr/mmocr/apis/train.py", line 155, in train_detector
>     runner.run(data_loaders, cfg.workflow)
>   File "/home/wanggang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 108, in run
>     self.call_hook('before_run')
>   File "/home/wanggang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
>     getattr(hook, fn_name)(self)
>   File "/home/wanggang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 94, in wrapper
>     return func(*args, **kwargs)
>   File "/home/wanggang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/logger/tensorboard.py", line 51, in before_run
>     'Please run "pip install future tensorboard" to install '
> ImportError: Please run "pip install future tensorboard" to install the dependencies to use torch.utils.tensorboard (applicable to PyTorch 1.1 or higher) 
> 

i've searched online, and done something: uninstall all tensorboard related packages and install tb-nightly and tensorboard. that didn't work. below is my pip list:

> absl-py                     1.0.0
> addict                      2.4.0
> aiofiles                    22.1.0
> albumentations              1.1.0
> anyio                       3.6.1
> argcomplete                 2.0.0
> asynctest                   0.13.0
> attrs                       21.4.0
> backports.cached-property   1.0.2
> backports.zoneinfo          0.2.1
> boto3                       1.24.89
> botocore                    1.27.89
> cachetools                  5.0.0
> certifi                     2021.10.8
> charset-normalizer          2.0.12
> click                       8.1.3
> codecov                     2.1.12
> coverage                    6.3.2
> cycler                      0.11.0
> Cython                      0.29.28
> dacite                      1.6.0
> Deprecated                  1.2.13
> dill                        0.3.5.1
> dnspython                   2.2.1
> eventlet                    0.33.1
> fiftyone                    0.17.2
> fiftyone-brain              0.9.1
> fiftyone-db                 0.3.0
> flake8                      4.0.1
> fonttools                   4.29.1
> future                      0.18.2
> glob2                       0.7
> google-auth                 2.6.0
> google-auth-oauthlib        0.4.6
> graphql-core                3.1.7
> greenlet                    1.1.3
> grpcio                      1.44.0
> h11                         0.12.0
> h2                          4.1.0
> hpack                       4.0.0
> httpcore                    0.15.0
> httpx                       0.23.0
> hypercorn                   0.14.3
> hyperframe                  6.0.1
> idna                        3.3
> imageio                     2.16.0
> imgaug                      0.4.0
> importlib-metadata          4.11.3
> iniconfig                   1.1.1
> isort                       5.10.1
> Jinja2                      3.1.2
> jmespath                    1.0.1
> joblib                      1.1.0
> kaleido                     0.2.1
> kiwisolver                  1.3.2
> kwarray                     0.5.21
> lanms-neo                   1.0.2
> llvmlite                    0.38.0
> lmdb                        1.3.0
> Markdown                    3.3.6
> MarkupSafe                  2.1.1
> matplotlib                  3.5.1
> mccabe                      0.6.1
> mmcv-full                   1.4.5
> mmdet                       2.22.0
> mmocr                       0.6.1           /home/wanggang/data/yanhao/mmocr
> mongoengine                 0.20.0
> motor                       2.5.1
> ndjson                      0.3.1
> networkx                    2.6.3
> numba                       0.55.1
> numpy                       1.21.5
> oauthlib                    3.2.0
> opencv-python               4.6.0.66
> opencv-python-headless      4.6.0.66
> ordered-set                 4.1.0
> packaging                   21.3
> pandas                      1.3.5
> patool                      1.12
> Pillow                      9.0.1
> pip                         22.0.3
> plotly                      5.10.0
> pluggy                      1.0.0
> pprintpp                    0.4.0
> priority                    2.0.0
> protobuf                    3.19.4
> psutil                      5.9.2
> py                          1.11.0
> pyasn1                      0.4.8
> pyasn1-modules              0.2.8
> pyclipper                   1.3.0.post2
> pycocotools                 2.0.2
> pycodestyle                 2.8.0
> pyflakes                    2.4.0
> Pygments                    2.13.0
> pymongo                     3.12.3
> pyparsing                   3.0.7
> pytest                      7.0.1
> pytest-cov                  3.0.0
> pytest-runner               6.0.0
> python-dateutil             2.8.2
> python-multipart            0.0.5
> pytz                        2021.3
> pytz-deprecation-shim       0.1.0.post0
> PyWavelets                  1.2.0
> PyYAML                      6.0
> qudida                      0.0.4
> rapidfuzz                   2.0.5
> requests                    2.27.1
> requests-oauthlib           1.3.1
> retrying                    1.3.3
> rfc3986                     1.5.0
> rsa                         4.8
> s3transfer                  0.6.0
> scikit-image                0.19.2
> scikit-learn                1.0.2
> scipy                       1.7.3
> seaborn                     0.11.2
> sentinel                    0.3.0
> setuptools                  60.9.3
> Shapely                     1.8.1.post1
> six                         1.16.0
> sniffio                     1.3.0
> sortedcontainers            2.4.0
> sse-starlette               0.10.3
> sseclient-py                1.7.2
> starlette                   0.16.0
> strawberry-graphql          0.96.0
> tabulate                    0.9.0
> tb-nightly                  2.11.0a20221009
> tenacity                    8.1.0
> tensorboard                 2.10.1
> tensorboard-data-server     0.6.1
> tensorboard-plugin-wit      1.8.1
> terminaltables              3.1.10
> threadpoolctl               3.1.0
> tifffile                    2021.11.2
> toml                        0.10.2
> tomli                       2.0.1
> torch                       1.10.2
> torchvision                 0.11.3
> tqdm                        4.63.0
> typing_extensions           4.1.1
> tzdata                      2022.4
> tzlocal                     4.2
> ubelt                       1.0.1
> universal-analytics-python3 1.1.1
> urllib3                     1.26.8
> voxel51-eta                 0.8.1
> Werkzeug                    2.0.3
> wheel                       0.37.1
> wrapt                       1.14.1
> wsproto                     1.2.0
> xdoctest                    0.15.10
> xmltodict                   0.13.0
> yapf                        0.32.0
> zipp                        3.7.0

so, what's the problem? thanks in advance.

**Comment by Harold-lkk** [comment]
It should be PyTorch or TensorBoard's problem. 
In my env, it works fine. Here is my env without tb-nightly:
```shell
tensorboard                   2.10.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
torch                         1.9.1+cu111
```
Make sure the environment you use with the correct version of TensorBoard.
you can try the below command to make sure to uninstall TensorBoard thoroughly

```sheel
conda uninstall tensorboard
conda uninstall tensorboardx
conda uninstall tensorboard-plugin-wit
conda uninstall cloud-tpu-client
conda uninstall tb-nightly

pip uninstall tensorboard
pip uninstall tensorboardx
pip uninstall tensorboard-plugin-wit
pip uninstall cloud-tpu-client
pip uninstall tb-nightly
```
and reinstall with
```shell
pip install tensorboard --no-cache
```
You can check TensorBoard with the below command.
```python
from torch.utils.tensorboard import SummaryWriter
```
