### ISSUE TITLE
[doc] Doc page not found if switched to 1.x version

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmocr#1441]
![image](https://user-images.githubusercontent.com/56623710/195073241-454cd6dd-e63e-4f4d-9e20-dd76c3ca210c.png)
then I got the following error https://mmocr.readthedocs.io/en/dev-1.x/install.html

**Comment by gaotongxiao** [comment]
The documentation directory structure in dev-1.x has been changed and unified according to OpenMMLab 2.0 standard, and there is nowhere to maintain such a page mapping for direct version switching. The suggested way to switch the version is only through the top menu now, though it's not that elegant.
![image](https://user-images.githubusercontent.com/22607038/195075357-a1aa168b-f69f-462e-b709-0abb4e8c4e69.png)
