### ISSUE TITLE
EastRandomCrop

### ISSUE THREAD

**Issue by hzhuangdy** [open-mmlab/mmocr#1443]
Hello
For MMOCR 1.x, I notice that the EastRandomCrop op is replaced by a resize op in DBNetpp configs. 

What's the reason for changing this? if this replacement improves the performance.

**Comment by xinke-wang** [comment]
Hi,

`EastRandomCrop` was implemented by applying `cropping`, `scaling` and `padding` to the input image. Now, the same effect can be achieved by combining three data transforms.

In MMOCR 0.x:
```
dict(
  type='EastRandomCrop',
  max_tries=10,
  min_crop_side_ratio=0.1,
  target_size=(640, 640))
```
In MMOCR 1.x:
```
dict(type='RandomCrop', min_side_ratio=0.1),
dict(type='Resize', scale=(640,640), keep_ratio=True),
dict(type='Pad', size=(640,640))
```
whose behavior is the same as in MMOCR 0.x


You may also check the [Transform Migration Guide](https://mmocr.readthedocs.io/en/dev-1.x/migration/transforms.html) to learn more about the changes.

**Comment by gaotongxiao** [comment]
There are many variants of RandomCrop operations in MMOCR 0.x and could be very confusing for users who want to use them in their models. We wanted to keep the transforms concise and avoid further confusion. Keeping these transforms atomic also contribs to the code quality.

**Comment by gaotongxiao** [comment]
> if this replacement improves the performance.

And yes - the performance of DB and DB++ are improved in MMOCR 1.0 with no other difference except for the transform-wise changes.
