### ISSUE TITLE
There is a incorrect word in the document

### ISSUE THREAD

**Issue by JunYao1020** [open-mmlab/mmocr#1445]
**Describe the bug**
In the Simplified Chinese doc of mmocr with v0.X, There is a misspelling of a word in the startup service annotation under the Server Deployment section.
properties is misspelled as preperties
[https://mmocr.readthedocs.io/zh_CN/latest/model_serving.html](url)
![mmocr_doc_err](https://user-images.githubusercontent.com/65162523/195264370-dd9ac6dd-1b0e-47a7-b1ce-a27415fd9ed2.png)

**Comment by xinke-wang** [comment]
Thank you for report that! Would you like to raise a PR to help us fix it? You may check our new [guide](https://github.com/open-mmlab/mmocr/pull/1442/files#diff-2f7d80361e5dbead0393f942185c3c30d3a97f218efa8597fb3af0c407d6221f) of how to contribute to MMOCR.
