### ISSUE TITLE
 In mmocr version 1.x, set the training set to repeat the training several times

### ISSUE THREAD

**Issue by htaoruan** [open-mmlab/mmocr#1467]
In mmocr version 1.x, if i want to repeat the training data, where should i set ?

**Comment by Harold-lkk** [comment]
You can refer to https://github.com/open-mmlab/mmocr/blob/52a787397363835bf1dd3bfe12999b7aadeb7e49/configs/textrecog/robust_scanner/robustscanner_resnet31_5e_st-sub_mj-sub_sa_real.py#L33
