### ISSUE TITLE
GRAD CAM For OCR[Feature] 

### ISSUE THREAD

**Issue by bely66** [open-mmlab/mmocr#1482]
### What is the feature?

After training the model it would be amazing to have the ability to visualize why the model made such predictions.
This helps to understand:
1. Any overfitting that's happening
2. What're the shortcomings you need to address in the dataset
3. Identify specific cases where your model performs logically

**Comment by bely66** [comment]
I'm still exploring this but is there a possibility to use the PyTorch grad cam directly with your models at this stage?

**Comment by Harold-lkk** [comment]
We have implemented many visualization tools for visualizing the datasets and prediction in dev-1.x.
You can refer to https://mmocr.readthedocs.io/en/dev-1.x/user_guides/visualization.html and https://mmocr.readthedocs.io/en/dev-1.x/user_guides/useful_tools.html for more detail.
For feature visualization, we are still in progress. Temporarily， you can visualize the feature with [Visualizer](https://mmengine.readthedocs.io/zh_CN/latest/api/visualization.html) or CAM by hardcode at the feature generated.

**Comment by bely66** [comment]
> We have implemented many visualization tools for visualizing the datasets and prediction in dev-1.x.
> 
> You can refer to https://mmocr.readthedocs.io/en/dev-1.x/user_guides/visualization.html and https://mmocr.readthedocs.io/en/dev-1.x/user_guides/useful_tools.html for more detail.
> 
> For feature visualization, we are still in progress. Temporarily， you can visualize the feature with [Visualizer](https://mmengine.readthedocs.io/zh_CN/latest/api/visualization.html) or CAM by hardcode at the feature generated.

Thanks for your reply
I'd like to know more about mmengine visualizer to visualize network layers
I can't find any code examples 
Can you direct me to something useful?

**Comment by Harold-lkk** [comment]
Temporarily, we only have Chinese document [here](https://mmengine.readthedocs.io/zh_CN/latest/advanced_tutorials/visualization.html)

**Comment by bely66** [comment]
Thanks I'll try it and get back to you
