### ISSUE TITLE
[Feature] mmdeploy with mmocr 1.x

### ISSUE THREAD

**Issue by hzhuangdy** [open-mmlab/mmocr#1485]
### What is the feature?

I wonder how to convert my dbnetpp_resnet50-dcnv2.pth to onnx using mmdeploy 1.x.
I got the following error when I tried.

Failed to search registry with scope "mmocr" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.

**Comment by gaotongxiao** [comment]
Hi, please raise this issue to [MMDeploy](https://github.com/open-mmlab/mmdeploy/issues) for faster & more accurate response.
