### ISSUE TITLE
lmdb dataset

### ISSUE THREAD

**Issue by ChaoRuk** [open-mmlab/mmocr#1486]
Can i crate lmdb dataset on this repo? How can i do it?
like this link (https://github.com/open-mmlab/mmocr/tree/main/tests/data/ocr_toy_dataset/imgs.lmdb)

**Comment by xinke-wang** [comment]
If you are using the main branch, please refer to this [doc](https://mmocr.readthedocs.io/en/latest/tools.html#convert-text-recognition-dataset-to-lmdb-format).

**Comment by ChaoRuk** [comment]
@xinke-wang It's solve. Thank you
