### ISSUE TITLE
device bug

### ISSUE THREAD

**Issue by oszn** [open-mmlab/mmocr#1495]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

it comes RuntimeError: CUDA error: device-side assert triggered.
so i want find the bug in cpu mode ,how to change to cpu model.

### Reproduces the problem - code sample

like the demo command

### Reproduces the problem - command or script

a unexacpt code come error

### Reproduces the problem - error message

RuntimeError: CUDA error: device-side assert triggered,
how to change cpu mode, i want find the bug in the cpu mode ,in gpu mode , i cant find the bug.
so if i use the command line like the offical way, how to work cpu in the command

**Comment by Harold-lkk** [comment]
Thanks for your reporting.
You can add the argument `--device cpu` for cpu. like
```python
python mmocr/utils/ocr.py demo/demo_text_det.jpg --output demo/ --det TextSnake --recog None 
--device cpu
```
The `device` augment control the device that the algorithm runs on.
