### ISSUE TITLE
[Bug] ONNX export issue

### ISSUE THREAD

**Issue by rogachevai** [open-mmlab/mmocr#1516]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

Official Docker

### Reproduces the problem - code sample

```shell
! python tools/deployment/pytorch2onnx.py configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2015.py \
    /home/.cache/torch/checkpoints/psenet_r50_fpnf_600e_icdar2015_pretrain-eefd8fe6.pth \
    'det' \
    demo/demo_text_det.jpg \
    --output-file dbnet.onnx \
    --verify \
    --verbose \
    --show \
    --dynamic-export
```

### Reproduces the problem - command or script

```shell
! python tools/deployment/pytorch2onnx.py configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2015.py \
    /home/.cache/torch/checkpoints/psenet_r50_fpnf_600e_icdar2015_pretrain-eefd8fe6.pth \
    'det' \
    demo/demo_text_det.jpg \
    --output-file dbnet.onnx \
    --verify \
    --verbose \
    --show \
    --dynamic-export
```

### Reproduces the problem - error message

```
RuntimeError: Error when binding input: There's no data transfer registered for copying tensors from Device:[DeviceType:1 MemoryType:0 DeviceId:7] to Device:[DeviceType:0 MemoryType:0 DeviceId:0]
```

### Additional information

I'm trying to convert models into ONNX format and face the same issue regardless which model i use the model, same error occurs in case of DBNet

**Comment by gaotongxiao** [comment]
Hi, you can use MMDeploy instead of these deprecated scripts for deployment stuff. Also, PSENet is not officially supported by MMDeploy yet. 

As prompted at the beginning of the issue template, further discussion can be carried out at [their repo](https://github.com/open-mmlab/mmdeploy/issues). You may raise a feature request or ask for their help there.
