### ISSUE TITLE
[Bug] OCR1.x dataset prepare don't support textspotting

### ISSUE THREAD

**Issue by jorie-peng** [open-mmlab/mmocr#1534]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmocr/tree/dev-1.x

### Environment

mmocr==1.0.0rc3
openmim==0.3.2

ps:  python mmocr/utils/collect_env.py will get error in 1.x, so I just paste important pkg version

### Reproduces the problem - code sample

`python tools/dataset_converters/prepare_dataset.py icdar2015 --task textspotting`

### Reproduces the problem - command or script

python tools/dataset_converters/prepare_dataset.py icdar2015 --task textspotting

### Reproduces the problem - error message

FileNotFoundError: [Errno 2] No such file or directory: 'configs/textspotting/_base_/datasets/icdar2015.py'

### Additional information

and when download icdar2015,  there is no URL in textspotting.py

**Comment by gaotongxiao** [comment]
Thanks for reporting! It should have been fixed now.
