### ISSUE TITLE
Toy text recognition: confusing gt labels

### ISSUE THREAD

**Issue by FraPochetti** [open-mmlab/mmocr#154]
Hi, 
I am sure I am missing something super basic, so apologies in advance.

I am deep-diving into the text recognition toy task and I am confused by the following.
```python
config = Path("mmocr/configs/textrecog/seg/seg_r31_1by16_fpnocr_toy_dataset.py")
cfg = Config.fromfile(config)
datasets = build_dataset(cfg.data.train)
r = datasets[0]
print(r)
```

```python
{'img_metas': DataContainer({'filename': 'tests/data/ocr_char_ann_toy_dataset/imgs/resort_88_101_1.png', 'ori_shape': (12, 69, 3), 'img_shape': (12, 78, 3)}),
 'img': tensor([[[ 2.2406,  2.2406,  2.2406,  ..., -2.1262, -2.1262, -2.1262],
          [ 2.2406,  2.2406,  2.2406,  ..., -2.1262, -2.1262, -2.1262],
          [ 2.2406,  2.2406,  2.2406,  ..., -2.1262, -2.1262, -2.1262],
          ...,
          [ 2.1379,  2.1379,  2.1379,  ..., -2.1262, -2.1262, -2.1262],
          [ 2.1379,  2.1379,  2.1379,  ..., -2.1262, -2.1262, -2.1262],
          [ 2.1379,  2.1379,  2.1379,  ..., -2.1262, -2.1262, -2.1262]],
 
         [[ 2.3064,  2.3064,  2.3064,  ..., -2.0529, -2.0529, -2.0529],
          [ 2.3064,  2.3064,  2.3064,  ..., -2.0529, -2.0529, -2.0529],
          [ 2.3064,  2.3064,  2.3064,  ..., -2.0529, -2.0529, -2.0529],
          ...,
          [ 2.0262,  2.0262,  2.0262,  ..., -2.0529, -2.0529, -2.0529],
          [ 2.0262,  2.0262,  2.0262,  ..., -2.0529, -2.0529, -2.0529],
          [ 2.0262,  2.0262,  2.0262,  ..., -2.0529, -2.0529, -2.0529]],
 
         [[-1.8280, -1.8280, -1.8280,  ..., -1.8280, -1.8280, -1.8280],
          [-1.8280, -1.8280, -1.8280,  ..., -1.8280, -1.8280, -1.8280],
          [-1.8280, -1.8280, -1.8280,  ..., -1.8280, -1.8280, -1.8280],
          ...,
          [-1.8280, -1.8280, -1.8280,  ..., -1.8280, -1.8280, -1.8280],
          [-1.8280, -1.8280, -1.8280,  ..., -1.8280, -1.8280, -1.8280],
          [-1.8280, -1.8280, -1.8280,  ..., -1.8280, -1.8280, -1.8280]]]),
 'gt_kernels': DataContainer(BitmapMasks(num_masks=3, height=64, width=512))}
```
The first item of the dataset refers to the file `resort_88_101_1.png`.
If I look up the annotations related to the file inside `mmocr/tests/data/ocr_char_ann_toy_dataset/instances_train.txt`
I find the following:
```
{"file_name": "resort_88_101_1.png", "annotations": 
    [{"char_text": "F", "char_box": [11.0, 0.0, 22.0, 0.0, 12.0, 12.0, 0.0, 12.0]}, 
     {"char_text": "r", "char_box": [23.0, 2.0, 31.0, 1.0, 24.0, 11.0, 16.0, 11.0]}, 
     {"char_text": "o", "char_box": [33.0, 2.0, 43.0, 2.0, 36.0, 12.0, 25.0, 12.0]}, 
     {"char_text": "m", "char_box": [46.0, 2.0, 61.0, 2.0, 53.0, 12.0, 39.0, 12.0]}, 
     {"char_text": ":", "char_box": [61.0, 2.0, 69.0, 2.0, 63.0, 12.0, 55.0, 12.0]}], "text": "From:"}
```
But the item from the dataset just has a `gt_kernels` key containing a single `BitmapMasks` object.
What does this `BitmapMasks` object refer to?
Given the text present in the image is `From:`, shouldn't we have 5 masks (one per char)?
Most importantly where are the chars labels stored, e.g. the indices encoding `F`, `r`, `o`, `m`, `:`?

**Comment by cuhk-hbsun** [comment]
1. `BitmapMasks` is the mask map (same size of the image) container 5 masks you mentioned above. It's a type of data like numpy.ndarray. 
2. You can check its content with numpy.ndarray by `r['gt_kernels'].data.masks[0]`.
3. Please check `configs/textrecog/seg/seg_r31_1by16_fpnocr_toy_dataset.py` for the pipeline of data process.
4. Please check `mmocr/datasets/pipelines/ocr_seg_targets.py` for the transform of the box to BitmapMasks.

**Comment by FraPochetti** [comment]
Thanks for your reply.
If I check the contents of `r['gt_kernels'].data.masks` I get an array of shape `(3, 64, 512)`, which is exactly what the object `BitmapMasks(num_masks=3, height=64, width=512)` suggests it would contain.
Why 3 masks though and not 5?
And where are the chars labels stored?

I had already looked into `mmocr/datasets/pipelines/ocr_seg_targets.py` but I don't seem to find any `char2idx` mapping.
Some mapping seems to occur inside `BaseConvertor` and `SegConvertor` ([here](https://github.com/open-mmlab/mmocr/blob/main/mmocr/models/textrecog/convertors/seg.py#L11)) but I am not sure how that propagates into the dataset.

**Comment by cuhk-hbsun** [comment]
1. In the line197 of `mmocr/datasets/pipelines/ocr_seg_targets.py`, you can see there are 3 kernels containing `binary_target, seg_target, mask`, where `seg_target` is for the segmentation loss calculation usually. `binary_target` contains 0 and 1 only.
2. The mapping (char2idx) occurs in `SegConvertor`.
3. All the pipelines in `train_pipeline` of `configs/_base_/recog_datasets/seg_toy_dataset.py` will be run one-by-one in dataset. All these happen in line87 and line89 of `mmocr/datasets/ocr_seg_dataset.py`.

**Comment by cuhk-hbsun** [comment]
Please follow the `mmocr/datasets/base_dataset.py` to have an understanding to the operation of dataset.

**Comment by FraPochetti** [comment]
Thanks!

**Comment by cuhk-hbsun** [comment]
fix
