### ISSUE TITLE
[Bug] 数据集预处理中，对于含","的特殊文本未特殊处理

### ISSUE THREAD

**Issue by jorie-peng** [open-mmlab/mmocr#1586]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmocr/tree/dev-1.x

### Environment

本次bug和环境无关
torch                   1.7.0
torchvision             0.8.1
mmcv                    2.0.0rc3
mmcv-full               1.7.0
mmdet                   3.0.0rc0
mmengine                0.1.0
mmocr                   1.0.0rc3 

### Reproduces the problem - code sample

相关代码在mmocr/datasets/preparers/parsers/icdar_txt_parser.py

### Reproduces the problem - command or script

python tools/dataset_converters/prepare_dataset.py icdar2015 --task textspotting

### Reproduces the problem - error message

no error message，检查发现部分图片预处理后的文本gt不对

### Additional information

1. 使用mmocr 1.x版本进行预处理icdar2015数据集为统一格式的json文件
2. 发现对文本处理时，未处理含分隔符的情况，如原始数据集的100,000文本，在统一格式中为100，即分隔符将文本分开后仅取了第一个文本
3. 具体例子如mmocr/data/icdar2015/textspotting_train.json中，在图片data/icdar2015/textdet_imgs/train/img_39.jpg的gt中，原始数据集文本标注为402,85,460,86,457,106,399,105,100,000，其中402,85,460,86,457,106,399,105为polygon标注，100,000为文本标注。但是预处理后的ocr数据集中，文本标注为100。
（因为在区分polygon标注和text标注时，通过分隔符","来区分，导致text文本被截断）

**Comment by gaotongxiao** [comment]
Thanks for the detailed information! We're looking into this issue and will get back to you asap.
