### ISSUE TITLE
Difference between Mask R-CNN in MMOCR vs MMDET

### ISSUE THREAD

**Issue by FraPochetti** [open-mmlab/mmocr#160]
Hi, 
are there any differences between the Mask R-CNN implemented in [MMOCR](https://github.com/open-mmlab/mmocr/tree/main/configs/textdet/maskrcnn) compared to the one found in [MMDET](https://github.com/open-mmlab/mmdetection/tree/master/configs/mask_rcnn)?
Given we use the model for text detection, which is nothing else than a form of instance segmentation, I presume the implementation is exactly the same, but I still wanted to check with you guys.
Thanks

**Comment by jeffreykuang** [comment]
> Hi,
> are there any differences between the Mask R-CNN implemented in [MMOCR](https://github.com/open-mmlab/mmocr/tree/main/configs/textdet/maskrcnn) compared to the one found in [MMDET](https://github.com/open-mmlab/mmdetection/tree/master/configs/mask_rcnn)?
> Given we use the model for text detection, which is nothing else than a form of instance segmentation, I presume the implementation is exactly the same, but I still wanted to check with you guys.
> Thanks

They are different in terms of :

- data augmentation during training.
- parameter setting of anchor boxes in config.
- The detected result decoding method and evaluation method.

I suggest you to use maskrcnn in mmocr  if you want to detect texts while using that in mmdet if want to detect general objects.


-

**Comment by FraPochetti** [comment]
Thanks a lot!

**Comment by FraPochetti** [comment]
Closing
