### ISSUE TITLE
Beam search cannot improve the performance of SAR model

### ISSUE THREAD

**Issue by williamking5** [open-mmlab/mmocr#162]
I trained the SAR word recognition model and evaluated it on test datasets, the performance is very close to results on MMOCR documentation. Then I evaluated the checkpoint using the beam search decoder, expected it would be higher than the original performance (which is mentioned in the paper). But the results seem to lower than greedy decoding. I also noticed that there is no public results using beam searching in the documentation.

![image](https://user-images.githubusercontent.com/16954932/117664165-10532680-b1d4-11eb-888a-c1b8a90c51e1.png)

Do you have any idea?

**Comment by cuhk-hbsun** [comment]
@williamking5 Thanks for your feedback.
I also noticed the problem so we didn't release the results with beam search.
I will review the implementation of beam search again, and if you find some bugs in the code, please let me known or raise a PR.

**Comment by williamking5** [comment]
OK, thank you for your reply:)
