### ISSUE TITLE
[Bug] Missing _word_spotting_filter implementation in E2EHmeanIOUMetric

### ISSUE THREAD

**Issue by wenwenyu** [open-mmlab/mmocr#1666]
### Prerequisite

- [x] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmocr/tree/dev-1.x

### Environment

TODO

### Reproduces the problem - code sample

TODO

### Reproduces the problem - command or script

TODO

### Reproduces the problem - error message

TODO

### Additional information

When word_spotting is True, the implementation of [_word_spotting_filter](https://github.com/open-mmlab/mmocr/blob/27b6a68586b9a040678fe083bcf60662ae1b9261/projects/ABCNet/abcnet/metric/e2e_hmean_iou_metric.py#L115) function is needed. I have searched the projects but did not find the implementation of `_word_spotting_filter` in E2EHmeanIOUMetric metric.

**Comment by Harold-lkk** [comment]
The E2EHmeanIOUMetric now only implements None-Hmean. Full-Hmean and Word Spotting will be implemented soon.

**Comment by wenwenyu** [comment]
Thanks.
