### ISSUE TITLE
[Docs] Link for ct80 test labels are down

### ISSUE THREAD

**Issue by doem97** [open-mmlab/mmocr#1668]
### Branch

1.x branch https://mmocr.readthedocs.io/en/dev-1.x/

### 📚 The doc issue

https://download.openmmlab.com/mmocr/data/1.x/recog/ct80/test_labels.json

is down. Anyone please provide a usable link （currently want to test something)?

Manny thanks in advance.

**Comment by gaotongxiao** [comment]
Thanks for reporting, it has been moved to https://download.openmmlab.com/mmocr/data/1.x/recog/ct80/textrecog_test.json. 

And you're welcome to try out [Dataset Preparer](https://mmocr.readthedocs.io/en/dev-1.x/user_guides/data_prepare/datasetzoo.html), which supports ct80 now.

**Comment by doem97** [comment]
> Thanks for reporting, it has been moved to https://download.openmmlab.com/mmocr/data/1.x/recog/ct80/textrecog_test.json.
> 
> And you're welcome to try out [Dataset Preparer](https://mmocr.readthedocs.io/en/dev-1.x/user_guides/data_prepare/datasetzoo.html), which supports ct80 now.

Thanks gaotong

BTW the link for ICDAR 2015 test is also down.. [check this](https://mmocr.readthedocs.io/en/dev-1.x/user_guides/data_prepare/recog.html#icdar-2015)

**Comment by gaotongxiao** [comment]
We'll remove these outdated sections, thanks for letting us know
