### ISSUE TITLE
Error occurred when inferring OCR operation

### ISSUE THREAD

**Issue by daigang896** [open-mmlab/mmocr#1713]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

python3.8
mmcv                          2.0.0rc4
mmdet                         3.0.0rc5
mmengine                      0.5.0
mmocr                         1.0.0rc5

### Reproduces the problem - code sample

from mmocr.ocr import MMOCR
ocr = MMOCR(det='DB_r18', recog='CRNN')
results = ocr.readtext('test.jpg') 
print('results=', results)

### Reproduces the problem - command or script

python test.py

### Reproduces the problem - error message

File "~/mmocr-1.0.0rc5/mmocr/datasets/transforms/loading.py", line 157, in transform
    img = mmcv.image.rgb2gray(img)
  File "~/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/image/colorspace.py", line 52, in rgb2gray
    out_img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Strange error occurred, I don't know why.

### Additional information

Any test image

**Comment by gaotongxiao** [comment]
It seems like the image is broken or empty.

**Comment by daigang896** [comment]
The image is not damaged and can be read by opencv alone.

**Comment by gaotongxiao** [comment]
It is because the text detection model cannot detect any boxes from the images and the text recognition part fails with empty inputs. It has been fixed in 1.0.0rc6. Thanks for reporting.
