### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by Jiayou-Chao** [open-mmlab/mmocr#1717]
### Branch

master branch  https://mmocr.readthedocs.io/en/latest/

### 📚 The doc issue

The [installation guide](https://mmocr.readthedocs.io/en/latest/install.html) does not work. I strictly followed the Best Practices and run the verification command:
```
python mmocr/utils/ocr.py --det DB_r18 --recog CRNN demo/demo_text_det.jpg --imshow
```
and it says 'the file doesn't exist'. So I changed 'mmocr/utils/ocr.py' to 'mmocr/ocr.py' and it says 'No module named 'mmengine''. After I installed the mmengine, it says 'AssertionError: MMCV 1.7.1 is incompatible with MMOCR 1.0.0rc5. Please use MMCV >= 2.0.0rc1, < 2.1.0 instead.'.

So I believe the guide should be updated.

### Suggest a potential alternative/fix

Update the installation guide.

**Comment by xinke-wang** [comment]
It seems you are following the `0.x` version document with a `1.x` version codebase. Please refer to `1.x` document [here](https://mmocr.readthedocs.io/en/dev-1.x/get_started/install.html).

**Comment by Jiayou-Chao** [comment]
> It seems you are following the `0.x` version document with a `1.x` version codebase. Please refer to `1.x` document [here](https://mmocr.readthedocs.io/en/dev-1.x/get_started/install.html).

Thank you. I understand. The documentation for `1.x` looks to be fine, but `0.x` is outdated.

**Comment by gaotongxiao** [comment]
May I know the way you got into the 0.x documentation? I'm asking because I'm not sure if we have mispointed users to `0.x` docs in `1.x` code

**Comment by Jiayou-Chao** [comment]
> May I know the way you got into the 0.x documentation? I'm asking because I'm not sure if we have mispointed users to `0.x` docs in `1.x` code

I just googled 'mmocr' and it's listed on the second. However, I think the simpler way to check the version is to see whether the url ends with `/latest/` or `/dev-1.x/`.

**Comment by Houangnt** [comment]
> python mmocr/utils/ocr.py --det DB_r18 --recog CRNN demo/demo_text_det.jpg --imshow

![image](https://user-images.githubusercontent.com/48252530/218432120-47323063-de8e-4e03-9d26-f7f6de0b6797.png)
i try convert dataset vintext but got this error :

**Comment by gaotongxiao** [comment]
@Houangnt Sorry for the inconvenience, here is the dependency sheet you may refer to: https://mmocr.readthedocs.io/en/dev-1.x/get_started/install.html#dependency-on-mmengine-mmcv-mmdetection

You can try to pull our latest `1.x` branch to use MMEngine 0.2.0.

**Comment by Houangnt** [comment]
> @Houangnt Sorry for the inconvenience, here is the dependency sheet that may be helpful: https://mmocr.readthedocs.io/en/dev-1.x/get_started/install.html#dependency-on-mmengine-mmcv-mmdetection
> 
> I think the quickest way to fix this issue is to reinstall `mmdet`:
> 
> ```shell
> pip uninstall mmdet
> pip install 'mmdet>=3.0.0rc0'
> ```

![image](https://user-images.githubusercontent.com/48252530/218636845-ba5bda03-12a8-461e-bb7f-b70e079d23e9.png)
what is version of mmcv, i try install mmcv>=2.0.0rc4 on gg colab but i cant install it

**Comment by gaotongxiao** [comment]
@Houangnt It's recommended to use `mim` to install mmcv now: https://mmocr.readthedocs.io/en/dev-1.x/get_started/install.html#best-practices

**Comment by Houangnt** [comment]
> @Houangnt It's recommended to use `mim` to install mmcv now: https://mmocr.readthedocs.io/en/dev-1.x/get_started/install.html#best-practices

![image](https://user-images.githubusercontent.com/48252530/218680096-559ae71f-8b15-4eb2-a468-2708cdfc1b2d.png)
i cant find issue to fix this error

**Comment by gaotongxiao** [comment]
@Houangnt Seems like you were tabbing for the auto-completion while typing the command, which is not yet supported by mim now. You can just copy-and-paste the commands in the docs and everything should work like a charm

**Comment by Houangnt** [comment]
> @Houangnt Seems like you were tabbing for the auto-completion while typing the command, which is not yet supported by mim now. You can just copy-and-paste the commands in the docs and everything should work like a charm

No i cant install it but i find a solution is install mmcv-lite with pip
