### ISSUE TITLE
[Bug] ImportError: cannot import name 'MMOCR' from 'mmocr.ocr' 

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmocr#1743]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmocr/tree/dev-1.x

### Environment

mmcv 2.0.0rc1
mmengine 0.5.0
mmocr 1.0.0rc5
mmdet 3.0.0rc5

### Reproduces the problem - code sample

```
from mmocr.ocr import MMOCR

# Load models into memory
ocr = MMOCR(det='TextSnake')

# Inference
results = ocr.readtext('demo/demo_text_det.jpg', img_out_dir='demo/')
```

### Reproduces the problem - command or script

```
python mmocr/ocr.py demo/demo_text_det.jpg --det TextSnake --img-out-dir demo/
```

### Reproduces the problem - error message

```
   from mmocr.ocr import MMOCR
  E   ImportError: cannot import name 'MMOCR' from 'mmocr.ocr'
```

### Additional information

the ocr.py don't include MMOCR

**Comment by gaotongxiao** [comment]
Thanks for reporting! We have upgraded our Inferencers in `dev-1.x` branch and the new docs is still on the way (which will be ready soon). The current docs still works for `1.x` branch, you may switch to `1.x` to circumvent this issue.

**Comment by riyajatar93** [comment]
i am also facing the same issue

**Comment by gaotongxiao** [comment]
@riyajatar93 I guess it was not exactly the same, at least `mmocr.ocr` is no longer in the documentation. You might raise a new issue and provide more details.
