### ISSUE TITLE
AssertionError[Bug] 

### ISSUE THREAD

**Issue by cheng1533** [open-mmlab/mmocr#1746]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

# training schedule for 1x
_base_ = [

    '../_base_/datasets/icdar2015.py',
    '../_base_/default_runtime.py',
    '../_base_/schedules/schedule_adadelta_5e.py',
    '_base_crnn_mini-vgg.py',
]
# dataset settings
train_list = [
    _base_.icdar2015_textrecog_train,
]
test_list = [
    _base_.icdar2015_textrecog_test,
]

default_hooks = dict(logger=dict(type='LoggerHook', interval=50), )
train_dataloader = dict(
    batch_size=4,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='ConcatDataset',
        datasets=train_list,
        pipeline=_base_.train_pipeline))
test_dataloader = dict(
    batch_size=1,
    num_workers=1,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='ConcatDataset',
        datasets=test_list,
        pipeline=_base_.test_pipeline))
val_dataloader = test_dataloader

val_evaluator = dict(
    dataset_prefixes=['CUTE80', 'IIIT5K', 'SVT', 'SVTP', 'IC13', 'IC15'])
test_evaluator = val_evaluator

auto_scale_lr = dict(base_batch_size=64 * 4)

### Reproduces the problem - code sample

tools/train.py configs/textrecog/crnn/crnn_mini-vgg_5e_icdar.py

### Reproduces the problem - command or script

python tools/train.py configs/textrecog/crnn/crnn_mini-vgg_5e_icdar.py

### Reproduces the problem - error message

Traceback (most recent call last):
  File "tools/train.py", line 117, in <module>
    main()
  File "tools/train.py", line 113, in main
    runner.train()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\mmengine\runner\runner.py", line 1631, in train
    model = self.train_loop.run()  # type: ignore
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\mmengine\runner\loops.py", line 94, in run
    self.runner.val_loop.run()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\mmengine\runner\loops.py", line 346, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "i:\code\mmocr-1.x\mmocr\evaluation\evaluator\multi_datasets_evaluator.py", line 55, in evaluate
    assert len(dataset_slices) == len(self.dataset_prefixes)
AssertionError

**Comment by cheng1533** [comment]
mmocr/evaluation/evaluator/multi_datasets_evaluator.py 中的断言
line 55: assert len(dataset_slices) == len(self.dataset_prefixes)
会报错

**Comment by RundongCao** [comment]
Did you solve this problem?
