### ISSUE TITLE
 If I want to extract key information, what tools can I use to annotate

### ISSUE THREAD

**Issue by luoyq6** [open-mmlab/mmocr#1748]
### Branch

master branch  https://mmocr.readthedocs.io/en/latest/

### 📚 The doc issue

If I want to extract key information, what tools can I use to annotate

**Comment by gaotongxiao** [comment]
Currently MMOCR only supports WildRecipet Dataset format, but we did not have experience in annotating this dataset. I guess emailing the authors of this dataset is the quickest way to get the answer.
