### ISSUE TITLE
[Docs] SynthText no longer available from linked site

### ISSUE THREAD

**Issue by EuanHoll** [open-mmlab/mmocr#1769]
### Branch

1.x branch  https://mmocr.readthedocs.io/en/dev-1.x/

### 📚 The doc issue

The link for SynthText no longer hosts the dataset.

Link to docs : [Link](https://mmocr.readthedocs.io/en/dev-1.x/user_guides/data_prepare/recog.html#synthtext-synth800k)
Link to dataset homepage: [Link](https://www.robots.ox.ac.uk/~vgg/data/scenetext/)

It now states:
```
Download instructions
The download links for the SynthText dataset are no longer available from this website.
```

### Suggest a potential alternative/fix

The dataset is still available via academictorrents.com at the following link : [Link](https://academictorrents.com/details/2dba9518166cbd141534cbf381aa3e99a087e83c)

Either changing the docs and instructions to use the following link and torrent or self-hosting are probably the main two options. 
Maybe a bit of both is the best. So seeding the torrent so other people can still have access aside from the MMOCR community.

**Comment by gaotongxiao** [comment]
Thanks for reporting again. We have been incorporating ST into our dataset preparer, but did not anticipate the sudden closure of the HTTP link. Torrenting sounds a good idea, we will update the instructions asap.

**Comment by EuanHoll** [comment]
No problem. Thanks for the update!

**Comment by gaotongxiao** [comment]
@lizhenye2017 The annotation file has to be generated by dataset preparer now.

**Comment by indigopyj** [comment]
Hi, I tried to download Synthtext by academic torrent but it was super slow. I recommend anyone who struggles from downloading go to this link(https://www.kaggle.com/datasets/wassefy/synthtext/data)  that I found.

**Comment by WudiJoey** [comment]
> 你好，我尝试通过学术种子下载 Synthtext，但速度非常慢。我建议任何无法下载的人访问我找到的这个链接（https://www.kaggle.com/datasets/wassefy/synthtext/data）。

Thanks, my friend
