### ISSUE TITLE
[Bug] Model not found on installation validation script

### ISSUE THREAD

**Issue by ni40in** [open-mmlab/mmocr#1780]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

sys.platform: linux
Python: 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) [GCC 11.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: Tesla V100-SXM2-16GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.10.2
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2022.1-Product Build 20220311 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.3
OpenCV: 4.7.0
MMEngine: 0.6.0
MMOCR: 1.0.0rc6+bfb36d8

### Reproduces the problem - code sample

```from mmocr.apis import MMOCRInferencer
ocr = MMOCRInferencer(det='DBNet', rec='CRNN')
ocr('demo/demo_txt_ocr.jpg', show=True, print_result=True)```

### Reproduces the problem - command or script

```ocr = MMOCRInferencer(det='DBNet', rec='CRNN')
```

### Reproduces the problem - error message

FileNotFoundError                         Traceback (most recent call last)
Cell In[2], line 2
      1 from mmocr.apis import MMOCRInferencer
----> 2 ocr = MMOCRInferencer(det='DBNet', rec='CRNN')

File /opt/conda/envs/open-mmlab/lib/python3.8/site-packages/mmocr/apis/inferencers/mmocr_inferencer.py:69, in MMOCRInferencer.__init__(self, det, det_weights, rec, rec_weights, kie, kie_weights, device)
     66 self.visualizer = None
     68 if det is not None:
---> 69     self.textdet_inferencer = TextDetInferencer(
     70         det, det_weights, device)
     71     self.mode = 'det'
     72 if rec is not None:

File /opt/conda/envs/open-mmlab/lib/python3.8/site-packages/mmocr/apis/inferencers/base_mmocr_inferencer.py:64, in BaseMMOCRInferencer.__init__(self, model, weights, device, scope)
     62 self.num_unnamed_imgs = 0
     63 init_default_scope(scope)
---> 64 super().__init__(
     65     model=model, weights=weights, device=device, scope=scope)

File /opt/conda/envs/open-mmlab/lib/python3.8/site-packages/mmengine/infer/infer.py:156, in BaseInferencer.__init__(self, model, weights, device, scope)
    152     cfg = Config.fromfile(model)
    153 else:
    154     # Load config and weights from metafile. If `weights` is
    155     # assigned, the weights defined in metafile will be ignored.
--> 156     cfg, _weights = self._load_model_from_metafile(model)
    157     if weights is None:
    158         weights = _weights

File /opt/conda/envs/open-mmlab/lib/python3.8/site-packages/mmengine/infer/infer.py:372, in BaseInferencer._load_model_from_metafile(self, model)
    365 assert self.scope is not None, (
    366     'scope should be initialized if you want '
    367     'to load config from metafile.')
    368 assert self.scope in MODULE2PACKAGE, (
    369     f'{self.scope} not in {MODULE2PACKAGE}!,'
    370     'please pass a valid scope.')
--> 372 repo_or_mim_dir = BaseInferencer._get_repo_or_mim_dir(self.scope)
    373 for model_cfg in BaseInferencer._get_models_from_metafile(
    374         repo_or_mim_dir):
    375     model_name = model_cfg['Name'].lower()

File /opt/conda/envs/open-mmlab/lib/python3.8/site-packages/mmengine/infer/infer.py:423, in BaseInferencer._get_repo_or_mim_dir(scope)
    421 mim_dir = osp.join(package_path, '.mim')
    422 if not osp.exists(osp.join(mim_dir, 'Configs')):
--> 423     raise FileNotFoundError(
    424         f'Cannot find Configs directory in {package_path}!, '
    425         f'please check the completeness of the {scope}.')
    426 return mim_dir

FileNotFoundError: Cannot find Configs directory in /opt/conda/envs/open-mmlab/lib/python3.8/site-packages/mmocr!, please check the completeness of the mmocr.

### Additional information

I installed mmocr via `mim install` command and have the github repo cloned on the server as well. Running into the problem above when trying to validate the installation

**Comment by gaotongxiao** [comment]
Thanks for the report. We have located the bug in MMEngine and it will be fixed in the next release. For now, a workaround is to install MMOCR from source.
