### ISSUE TITLE
How do I load pre-training weights?

### ISSUE THREAD

**Issue by wangzixiang99** [open-mmlab/mmocr#1785]
### What is the feature?

您好，我想问一下训练SVTR文本识别模型时如何加载你们提供的预训练权重文件呢？我在配置文件中用load_from = 'work_dirs/pretrain/svtr-small_20e_st_mj-35d800d6.pth'的方式，但是报错了(KeyError: 'epoch')，
请问是否有其他方式来加载官方提供的预训练权重进行训练呢？

Hello, I want to ask how to load the pre-training weight file you provided when training the SVTR text recognition model? I use load in the configuration file_ from = 'work_ dirs/pretrain/svtr-small_ 20e_ st_ Mj-35d800d6. pth ', but an error is reported. 
Is there any other way to load the official pre-training weight for training?

**Comment by Harold-lkk** [comment]
Can you provide detailed information on the error? The way to load pre-train weight is right

**Comment by wangzixiang99** [comment]
> Can you provide detailed information on the error? The way to load pre-train weight is right

中文：
谢谢你的回复，昨天我是在配置文件中加 “load_from” 的同时在训练指令中加了“--resume”，这样可能就是断点续训练了，我刚刚尝试去掉“--resume”，这样可能就是正确的加载预训练模型的方式了。

但是我现在有一个新的问题，我加载了官方提供的预训练权重，在“ic11”, “ic13” 和 “ic15” 这三个数据集上训练了1000epoch，但是每个数据集的“word_acc”结果很低，请问可能是什么原因呢？

以下是训练过程中进行验证的结果：
 IC11/recog/word_acc: 0.2592  
IC11/recog/word_acc_ignore_case: 0.7033  IC11/recog/word_acc_ignore_case_symbol: 0.7074  
IC13/recog/word_acc: 0.0000  
IC13/recog/word_acc_ignore_case: 0.0000  IC13/recog/word_acc_ignore_case_symbol: 0.1517  
IC15/recog/word_acc: 0.0000  
IC15/recog/word_acc_ignore_case: 0.0000  IC15/recog/word_acc_ignore_case_symbol: 0.0308  
IC11/recog/char_recall: 0.9693  
IC11/recog/char_precision: 0.8430  
IC13/recog/char_recall: 0.9449  
IC13/recog/char_precision: 0.6369  
IC15/recog/char_recall: 0.8983  IC15/recog/char_precision: 0.5605

这是我的配置文件：
_base_ = [
    'svtr-tiny_20e_st_mj.py',
]

model = dict(
    encoder=dict(
        embed_dims=[96, 192, 256],
        depth=[3, 6, 6],
        num_heads=[3, 6, 8],
        mixer_types=['Local'] * 8 + ['Global'] * 7))

optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(
        type='AdamW',
        lr=5 / (10**4) * 2048 / 2048,
        betas=(0.9, 0.99),
        eps=8e-8,
        weight_decay=0.05))

param_scheduler = [
    dict(
        type='LinearLR',
        start_factor=0.5,
        end_factor=1.,
        end=2,
        verbose=False,
        convert_to_iter_based=True),
    dict(
        type='CosineAnnealingLR',
        T_max=19,
        begin=2,
        end=20,
        verbose=False,
        convert_to_iter_based=True),
]

# dataset settings
train_list = [_base_.icdar2013_textrecog_train, _base_.icdar2011_textrecog_train, _base_.icdar2015_textrecog_train]
test_list = [
    _base_.icdar2011_textrecog_test, _base_.icdar2013_textrecog_test, _base_.icdar2015_textrecog_test
]

val_evaluator = dict(
    dataset_prefixes=['IC11', 'IC13', 'IC15'])
test_evaluator = val_evaluator

train_dataloader = dict(
    batch_size=64,
    num_workers=4,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='ConcatDataset',
        datasets=train_list,
        pipeline=_base_.train_pipeline))

val_dataloader = dict(
    batch_size=64,
    num_workers=4,
    persistent_workers=True,
    pin_memory=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='ConcatDataset',
        datasets=test_list,
        pipeline=_base_.test_pipeline))

test_dataloader = val_dataloader

default_hooks = dict(checkpoint=dict(type='CheckpointHook', interval=50), )
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=1000, val_interval=20)
load_from = 'work_dirs/pretrain/svtr-small_20e_st_mj-35d800d6.pth'
resume = False
param_scheduler = [dict(type='ConstantLR', factor=1.0),]


English:
Thank you for your reply. Yesterday, I added "load_from" to the configuration file and "-- resume" to the training command. This may be a breakpoint continuation training. I just tried to remove "-- resume", which may be the correct way to load the pre training model.

However, I now have a new problem. I loaded the official pre training weights and trained 1000 epochs on three datasets: "ic11", "ic13", and "ic15". However, the "word_acc" results for each dataset are very low. What may be the reason?

The following are the results of validation during the training process:

IC11/recog/word_ acc: 0.2592
IC11/recog/word_ acc_ ignore_ case: 0.7033 
IC11/recog/word_ acc_ ignore_ case_ symbol: 0.7074
IC13/recog/word_ acc: 0.0000
IC13/recog/word_ acc_ ignore_ case: 0.0000 
IC13/recog/word_ acc_ ignore_ case_ symbol: 0.1517
IC15/recog/word_ acc: 0.0000
IC15/recog/word_ acc_ ignore_ case: 0.0000 
IC15/recog/word_ acc_ ignore_ case_ symbol: 0.0308
IC11/recog/char_ recall: 0.9693
IC11/recog/char_ precision: 0.8430
IC13/recog/char_ recall: 0.9449
IC13/recog/char_ precision: 0.6369
IC15/recog/char_ recall: 0.8983 
IC15/recog/char_ precision: 0.5605
