### ISSUE TITLE
[Feature] Separate det_batch_size and rec_batch_size in class MMOCRInferencer

### ISSUE THREAD

**Issue by hugotong6425** [open-mmlab/mmocr#1799]
### What is the feature?

I split batch_size in MMOCRInferencer into det_batch_size and rec_batch_size. Increasing rec_batch_size can significantly improve the inference speed in my use case. I also make chunk_size changeable but it does not affect much.

| det_batch_size | rec_batch_size | chunk_size |                                 time                                |
|:--------------:|:--------------:|:----------:|:-------------------------------------------------------------------:|
|        1       |        1       |      1     | 20.9 s ± 186 ms per loop (mean ± std. dev. of 10 runs, 1 loop each) |
|        1       |       16       |      1     | 13.3 s ± 163 ms per loop (mean ± std. dev. of 10 runs, 1 loop each) |
|        1       |        1       |     16     | 20.4 s ± 169 ms per loop (mean ± std. dev. of 10 runs, 1 loop each) |
|        1       |       16       |     16     | 13.1 s ± 456 ms per loop (mean ± std. dev. of 10 runs, 1 loop each) |

If I remember correctly, det_batch_size and rec_batch_size are 2 separate config in 0.x version. Is there any reason to remove them in 1.x? I can submit my code changes if they are not removed on purpose.

p.s. I used MMOCRInferencer instead of separated TextDetInferencer and TextRecInferencer because it helps me to handle the transition between det model and rec model (e.g. crop image) and handle the end-to-end visualization. Please advice if there is a better way to do them. Thanks.

**Comment by gaotongxiao** [comment]
There is no outstanding reason for dropping this feature, and your contribution will be greatly appreciated. :) And it's good to keep batch_size still as the default value of `det_batch_size` and `rec_batch_size`.

As a side note, don't forget to install pre-commit hooks (https://mmocr.readthedocs.io/en/dev-1.x/notes/contribution_guide.html#procedures-in-detail) before the commit.
