### ISSUE TITLE
[Bug] TypeError: _dispatch_kwargs() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by Anu1205** [open-mmlab/mmocr#1812]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmocr/tree/dev-1.x

### Environment

conda install pytorch torchvision cpuonly -c pytorch

pip install -U openmim
mim install mmengine
mim install 'mmcv==2.0.0rc1'
mim install 'mmdet==3.0.0rc0'

mim install 'mmocr==1.0.0rc0'

### Reproduces the problem - code sample

>>> from mmocr.apis import MMOCRInferencer
>>> ocr = MMOCRInferencer(det='DBNet', rec='CRNN')

### Reproduces the problem - command or script

>>> from mmocr.apis import MMOCRInferencer
>>> ocr = MMOCRInferencer(det='DBNet', rec='CRNN')

### Reproduces the problem - error message

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxx\anaconda3\envs\mmocr_test\lib\site-packages\mmocr\apis\inferencers\mmocr_inferencer.py", line 32, in __init__
    self.base_params = self._dispatch_kwargs(*kwargs)
TypeError: _dispatch_kwargs() takes 1 positional argument but 3 were given

**Comment by gaotongxiao** [comment]
> mim install 'mmcv==2.0.0rc1'
> mim install 'mmdet==3.0.0rc0'
> mim install 'mmocr==1.0.0rc0'

`==` should have been `>=`. Besides, installing mmocr via MIM is known to cause a bug on inferencing with text recognition model, which is fixed in `dev-1.x` branch and will be officially released in the upcoming version. As of now, installing from source is a safe option.

https://mmocr.readthedocs.io/en/dev-1.x/get_started/install.html

**Comment by Anu1205** [comment]
If I use ">=" to install mmcv/mmdet/mmdet, proper versions have not been installed.
when I checked the versions,
for eg: pip show mmcv
Name: mmcv
Version: 1.7.1
Summary: OpenMMLab Computer Vision Foundation
Home-page: https://github.com/open-mmlab/mmcv
Author: MMCV Contributors
Author-email: openmmlab@gmail.com
License:
Location: c:\users\xxxxxx\anaconda3\envs\mmocr_v1\lib\site-packages
Requires: addict, numpy, packaging, Pillow, pyyaml, regex, yapf
Required-by:

**Comment by gaotongxiao** [comment]
There is a bug in the current `mmocr` pypi package, with which mim can install the wrong MMCV version. Installing MMOCR from source or use `pip install 'mmocr>=1.0.0rc0'`after you have the right version of MMCV and MMDet installed can prevent this from happening.

**Comment by Anu1205** [comment]
Hi there,
I'm able to install all the prerequisites and **I have installed MMOCR from source**, So the issue (TypeError: _dispatch_kwargs() takes 1 positional argument but 3 were given)  has been resolved.
