### ISSUE TITLE
[Feature] 请教一下，mmocr支持pdf文档(非图片，文字可编辑)解析，比如提取key-value键值对的提取？

### ISSUE THREAD

**Issue by ahong007007** [open-mmlab/mmocr#1826]
### What is the feature?

100000+的pdf文档是电子版，希望可以用算法批量提取key-value键值信息，不知mmocr， 现在或者未来有这样的支持计划？感谢。

**Comment by gaotongxiao** [comment]
Sounds like an interesting feature, but we don't have such a plan in the short term. You can try to implement one with [`KIEInferencer`](https://mmocr.readthedocs.io/en/dev-1.x/api/generated/mmocr.apis.inferencers.KIEInferencer.html?highlight=kieinfer#mmocr.apis.inferencers.KIEInferencer)
