### ISSUE TITLE
[Bug] Register decoration not take effect when using tools/infer.py

### ISSUE THREAD

**Issue by JunLeecus** [open-mmlab/mmocr#1831]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

python                    3.9.2
mmcv                     2.0.0
mmdet                    3.0.0rc6
mmengine                 0.7.0
mmocr                    1.0.0rc6
torch                    2.0.0

### Reproduces the problem - code sample

your official code `tools/infer.py` without any change

### Reproduces the problem - command or script

```shell
python3 tools/infer.py any.png --det configs/textdet/fcenet/fcenet_resnet50_fpn_1500e_totaltext.py
```

### Reproduces the problem - error message

KeyError: 'FixInvalidPolygon is not in the transform registry. Please check whether the value of `FixInvalidPolygon` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

### Additional information

There is not a specific import of `mmocr` so that decorators of register are not take effect. And it will be work well after `from mmocr.datasets import *` in `tools/infer.py`, and then `FixInvalidPolygon` can be found.

**Comment by gaotongxiao** [comment]
Not sure if you have changed something else. I did a quick test on a colab session and it turned out to work well.
