### ISSUE TITLE
docker环境bug

### ISSUE THREAD

**Issue by wangzixiang99** [open-mmlab/mmocr#1837]
### What is the feature?

您好，我在docker中配置mmocr的环境，我已经遵守文档中要求的版本对应，但是还是报错
我用的是1.0.0rc5的代码分支
报错如下：
usr/local/lib/python3.6/dist-packages/mmengine/model/utils.py:138: UserWarning: Cannot import torch.fx, `merge_dict` is a simple function to merge multiple dicts
  warnings.warn('Cannot import torch.fx, `merge_dict` is a simple function '
Traceback (most recent call last):
  File "tools/test.py", line 10, in <module>
    from mmocr.utils import register_all_modules
  File "/home/mmocr-1.0.0rc5/mmocr/__init__.py", line 4, in <module>
    import mmdet
  File "/usr/local/lib/python3.6/dist-packages/mmdet/__init__.py", line 23, in <module>
    f'MMEngine=={mmengine.__version__} is used but incompatible. ' \
AssertionError: MMEngine==0.4.0 is used but incompatible. Please install mmengine>=0.0.0, <0.2.0.

我的环境如下：其中mmcv   2.0.0rc3   和   mmdet   3.0.0rc0   和     mmengine   0.4.0这三个版本是相对应的，但总是报上面的错误，请问这是因为啥？？？
absl-py                0.11.0
addict                 2.4.0
argon2-cffi            20.1.0
async-generator        1.10
asynctest              0.13.0
attrs                  20.3.0
backcall               0.2.0
bleach                 3.2.1
cached-property        1.5.2
cachetools             4.1.1
certifi                2020.11.8
cffi                   1.14.3
chardet                3.0.4
click                  8.0.4
cloudpickle            1.6.0
codecov                2.1.12
colorama               0.4.5
commonmark             0.9.1
coverage               6.2
cycler                 0.10.0
dataclasses            0.8
decorator              4.4.2
defusedxml             0.6.0
entrypoints            0.3
flake8                 5.0.4
future                 0.18.2
google-auth            1.23.0
google-auth-oauthlib   0.4.2
grpcio                 1.33.2
h5py                   3.1.0
horovod                0.20.0
idna                   2.10
imageio                2.14.0
imgaug                 0.4.0
importlib-metadata     2.0.0
iniconfig              1.1.1
interrogate            1.5.0
ipykernel              5.3.4
ipython                7.16.1
ipython-genutils       0.2.0
ipywidgets             7.5.1
isort                  5.10.1
jedi                   0.17.2
Jinja2                 2.11.2
json5                  0.9.5
jsonpatch              1.26
jsonpointer            2.0
jsonschema             3.2.0
jupyter                1.0.0
jupyter-client         6.1.7
jupyter-console        6.2.0
jupyter-core           4.7.0
jupyterlab             2.2.9
jupyterlab-pygments    0.1.2
jupyterlab-server      1.2.0
kiwisolver             1.3.1
kwarray                0.6.9
lanms-neo              1.0.2
lmdb                   1.4.0
Markdown               3.3.3
MarkupSafe             1.1.1
matplotlib             3.3.3
mccabe                 0.7.0
mistune                0.8.4
mmcv                   2.0.0rc3
mmdet                  3.0.0rc0
mmengine               0.4.0
mmocr                  1.0.0rc5        /home/mmocr-1.0.0rc5
model-index            0.1.11
mpi4py                 3.0.3
mxboard                0.1.0
nbclient               0.5.1
nbconvert              6.0.7
nbformat               5.0.8
nest-asyncio           1.4.3
networkx               2.5.1
notebook               6.1.5
numpy                  1.19.4
oauthlib               3.1.0
opencv-python          4.4.0.46
openmim                0.3.6
ordered-set            4.0.2
packaging              20.4
pandas                 1.1.5
pandocfilters          1.4.3
parameterized          0.8.1
parso                  0.7.1
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 8.4.0
pip                    20.2.4
pluggy                 1.0.0
prometheus-client      0.9.0
prompt-toolkit         3.0.8
protobuf               3.14.0
psutil                 5.7.3
ptyprocess             0.6.0
py                     1.11.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pyclipper              1.3.0.post4
pycocotools            2.0.6
pycodestyle            2.9.1
pycparser              2.20
pyflakes               2.5.0
Pygments               2.7.2
pygobject              3.26.1
pyparsing              2.4.7
pyrsistent             0.17.3
pytest                 7.0.1
pytest-cov             4.0.0
pytest-runner          5.3.2
python-apt             1.6.5+ubuntu0.3
python-dateutil        2.8.1
pytz                   2022.7.1
PyWavelets             1.1.1
PyYAML                 5.3.1
pyzmq                  20.0.0
qtconsole              4.7.7
QtPy                   1.9.0
rapidfuzz              2.11.1
requests               2.25.0
requests-oauthlib      1.3.0
rich                   12.6.0
rsa                    4.6
scikit-image           0.17.2
scipy                  1.5.4
Send2Trash             1.5.0
setuptools             50.3.2
Shapely                1.8.5.post1
six                    1.15.0
tabulate               0.8.10
tensorboard            2.4.0
tensorboard-plugin-wit 1.7.0
tensorboardX           2.1
termcolor              1.1.0
terminado              0.9.1
terminaltables         3.1.10
testpath               0.4.4
tifffile               2020.9.3
toml                   0.10.2
tomli                  1.2.3
torch                  1.7.0+cu110
torchaudio             0.7.0
torchfile              0.1.0
torchvision            0.8.1+cu110
tornado                6.1
tqdm                   4.52.0
traitlets              4.3.3
typing                 3.7.4.3
typing-extensions      4.1.1
ubelt                  1.2.4
urllib3                1.26.2
visdom                 0.1.8.9
wcwidth                0.2.5
webencodings           0.5.1
websocket-client       0.57.0
Werkzeug               1.0.1
wheel                  0.35.1
widgetsnbextension     3.5.1
xdoctest               1.1.1
yapf                   0.32.0
zipp                   3.4.0

**Comment by gaotongxiao** [comment]
> File "/usr/local/lib/python3.6/dist-packages/**mmdet**/init.py", line 23, in

It's the constraint from MMDet. Upgrading MMDet can fix it.
