### ISSUE TITLE
Input dimension in textdet

### ISSUE THREAD

**Issue by priyanshu-sinha-trysolvio** [open-mmlab/mmocr#185]
How to change the input dimension to the psenet model?
Because the original psenet repo had two different image sizes. 768,2240
It should be a Parameter in the train pipeline.

**Comment by priyanshu-sinha-trysolvio** [comment]
@innerlee Is there a way I can change it manually for now.

**Comment by innerlee** [comment]
Does this line help? https://github.com/open-mmlab/mmocr/blob/main/configs/textdet/psenet/psenet_r50_fpnf_600e_ctw1500.py#L65

**Comment by priyanshu-sinha-trysolvio** [comment]
But you are padding it afterwords right? and if you will see then in the config for test pipeline it is resizing it to 2240,2200.

**Comment by priyanshu-sinha-trysolvio** [comment]
https://github.com/open-mmlab/mmocr/blob/main/configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2015.py
Line 81

**Comment by cuhk-hbsun** [comment]
@priyanshu-sinha-trysolvio You can modify line 78 [config](https://github.com/open-mmlab/mmocr/blob/main/configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2015.py) to `img_scale=[(2240, 2240), (768, 768)]`

**Comment by priyanshu-sinha-trysolvio** [comment]
@cuhk-hbsun but isnt that for test_pipeline.
