### ISSUE TITLE
SegOCR paper

### ISSUE THREAD

**Issue by FraPochetti** [open-mmlab/mmocr#187]
Hi, 
I see [here](https://github.com/open-mmlab/mmocr/tree/main/configs/textrecog/seg) that SegOCR is unpublished.
Is this still the case?
E.g. is there a way to access the paper?

Thanks

**Comment by innerlee** [comment]
No its not published/public yet. You may communicate with @jeffreykuang for more info :D

**Comment by FraPochetti** [comment]
Thanks!
