### ISSUE TITLE
[Bug] SATRN-The model and loaded state dict do not match exactly 

### ISSUE THREAD

**Issue by XinDing5** [open-mmlab/mmocr#1879]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

sys.platform: linux
Python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) [GCC 10.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1: Tesla P100-PCIE-16GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.13.0a0+340c412
PyTorch compiling details: PyTorch built with:

GCC 9.4
C++ Version: 201402
Intel(R) Math Kernel Library Version 2020.0.4 Product Build 20200917 for Intel(R) 64 architecture applications
Intel(R) MKL-DNN v2.6.0 (Git Hash N/A)
OpenMP 201511 (a.k.a. OpenMP 4.5)
LAPACK is enabled (usually provided by MKL)
NNPACK is enabled
CPU capability usage: AVX512
CUDA Runtime 11.7
NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
CuDNN 8.4.1 (built against CUDA 11.6)
Magma 2.6.2
Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.4.1, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS=-fno-gnu-unique -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,
TorchVision: 0.13.0a0
OpenCV: 4.2.0
MMEngine: 0.7.2
MMOCR: 1.0.0+d7c59f3

### Reproduces the problem - code sample

Here is my config file:

_base_ = [
    '../_base_/datasets/rects.py',
    '../_base_/datasets/icdar2015.py',
    '../_base_/datasets/lsvt.py',
    '../_base_/datasets/art.py',
    '../_base_/datasets/rctw.py',
    '../_base_/default_runtime.py',
    '../_base_/schedules/schedule_adam_step_5e.py',
    '_base_satrn_shallow_chinese.py',
]

train_list = [_base_.icdar2015_textrecog_train, _base_.rects_textrecog_train, _base_.lsvt_textrecog_train, _base_.art_textrecog_train, _base_.rctw_textrecog_train]
test_list = [_base_.icdar2015_textrecog_test, _base_.rctw_textrecog_test]

train_dataset = dict(
    type='ConcatDataset', datasets=train_list, pipeline=_base_.train_pipeline)
test_dataset = dict(
    type='ConcatDataset', datasets=test_list, pipeline=_base_.test_pipeline)

optim_wrapper = dict(type='OptimWrapper', optimizer=dict(type='Adam', lr=3e-4))

train_dataloader = dict(
    batch_size=128,
    num_workers=16,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=train_dataset)

test_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=test_dataset)

val_dataloader = test_dataloader

val_evaluator = dict(
    dataset_prefixes=['ICDAR2015', 'RCTW'])
test_evaluator = val_evaluator

auto_scale_lr = dict(base_batch_size=128)

train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=100, val_interval=10)

load_from = "work_dirs/models/satrn_shallow_5e_st_mj_20220915_152443-5fd04a4c.pth"
resume = True

### Reproduces the problem - command or script

Here is my command:

tools/dist_train.sh configs/textrecog/satrn/satrn_shallow_5e_st_mj_rects_icdar2015_lsvt_art_rctw.py 2

### Reproduces the problem - error message

Loads checkpoint by local backend from path: work_dirs/models/satrn_shallow_5e_st_mj_20220915_152443-5fd04a4c.pth
Loads checkpoint by local backend from path: work_dirs/models/satrn_shallow_5e_st_mj_20220915_152443-5fd04a4c.pth
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main()
  File "tools/train.py", line 110, in main
    runner.train()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1694, in train
    self.load_or_resume()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1640, in load_or_resume
    self.resume(resume_from)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1951, in resume
    self.train_loop._epoch = checkpoint['meta']['epoch']
KeyError: 'epoch'
The model and loaded state dict do not match exactly

size mismatch for decoder.trg_word_emb.weight: copying a param with shape torch.Size([93, 512]) from checkpoint, the shape in current model is torch.Size([11380, 512]).
size mismatch for decoder.classifier.weight: copying a param with shape torch.Size([93, 512]) from checkpoint, the shape in current model is torch.Size([11380, 512]).
size mismatch for decoder.classifier.bias: copying a param with shape torch.Size([93]) from checkpoint, the shape in current model is torch.Size([11380]).
unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std

04/25 21:03:57 - mmengine - INFO - Load checkpoint from work_dirs/models/satrn_shallow_5e_st_mj_20220915_152443-5fd04a4c.pth
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main()
  File "tools/train.py", line 110, in main
    runner.train()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1694, in train
    self.load_or_resume()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1640, in load_or_resume
    self.resume(resume_from)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1951, in resume
    self.train_loop._epoch = checkpoint['meta']['epoch']
KeyError: 'epoch'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 14658) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-04-25_21:04:00
  host      : workspace
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 14659)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-25_21:04:00
  host      : workspace
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 14658)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

### Additional information

When I try to train SATRN from the provided pre-trained SATRN model, it says the model and loaded state dict do not match exactly. The training does not start. Could you please help to have a look?

**Comment by XinDing5** [comment]
Thanks. May I also ask some questions about the dictionary. The model's prediction result has many unknown traditional chinese in the dictionary. If I would like to avoid this case, is it wise to delect those charactors in the dictioanry and retrain the model use the revised dictionary?

**Comment by gaotongxiao** [comment]
Sure
