### ISSUE TITLE
[Docs] SAR_CN Chinese recognition model no longer exists?

### ISSUE THREAD

**Issue by Hegelim** [open-mmlab/mmocr#1890]
### Branch

master branch  https://mmocr.readthedocs.io/en/latest/

### 📚 The doc issue

I am trying to run some experiments on a pre-trained Chinese recognition model. 
I read #992 #243 
However, it seems some directories and the model no longer exists. For example

1. there is no such directory `data/chineseocr/labels/`
2. there is no longer SAR_CN pre-trained model here `https://github.com/open-mmlab/mmocr/blob/main/configs/textrecog/sar/README.md#chinese-dataset`

The only thing I could find is the the mysterious dictionary file https://download.openmmlab.com/mmocr/textrecog/sar/dict_printed_chinese_english_digits.txt
which I have no idea where is the right place to put it in because of the out-dated instructions.

Did you guys remove the pre-trained SAR_CN model? If so, please update the documentation. If not, please let me know where I can still download the model.

### Suggest a potential alternative/fix

Update documentation

**Comment by gaotongxiao** [comment]
The Chinese weight available for MMOCR 1.0 has yet to be posted. The weight these issues referring to are in `0.x` branch now (https://github.com/open-mmlab/mmocr/blob/0.x/configs/textrecog/sar/README.md#chinese-dataset)
