### ISSUE TITLE
Memory Leak: PANet

### ISSUE THREAD

**Issue by seekingdeep** [open-mmlab/mmocr#192]
- When trying to predict a dense image using PANet, the prediction gets stuck, and the memory usage constantly increase.
```
sh tools/test_imgs.sh configs/textdet/panet/panet_r18_fpem_ffm_600e_ctw1500.py ./panet_r18_fpem_ffm_sbn_600e_ctw1500_20210219-3b3a9aa3.pth ./input ./input/list.txt ./output
```

- But, when modifying [Line72](https://github.com/open-mmlab/mmocr/blob/main/configs/textdet/panet/panet_r18_fpem_ffm_600e_ctw1500.py#L72) in the config, from 3000 into 940, then it works. Also anything below 940 works.
-  Anything above 940 will get stuck.
- **There is something that is causing a Memory Leak with PANet.**

Input image used:
![input](https://user-images.githubusercontent.com/71519088/118366021-b2de2180-b5a7-11eb-849c-cedbf7822b8e.jpg)

**Comment by jeffreykuang** [comment]
1 did upgrade your mmcv to 1.3.4?
2 when predicting this dense text img, I suggest to using pannet icdar2015 config

I will try to recover your bug to check what's happen.

**Comment by seekingdeep** [comment]
hmmmmm....interesting.
i created a new environment using the [conda environment](https://github.com/open-mmlab/mmocr/blob/52edff44e8d8b5a737df132e1d91edb6fda62839/environment_torch170_cuda11.yml)
now it works, thanks
