### ISSUE TITLE
KeyError: "Duplicate key is not allowed among bases. Duplicate keys: {'default_hooks'}"[Bug] 

### ISSUE THREAD

**Issue by cbwznb** [open-mmlab/mmocr#1923]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

KeyError: "Duplicate key is not allowed among bases. Duplicate keys: {'default_hooks'}"

### Reproduces the problem - code sample

python tools/train.py configs/textdet/dbnet/dbnet_resnet18_fpnc_1200e_icdar2015.py

### Reproduces the problem - command or script

python tools/train.py configs/textdet/dbnet/dbnet_resnet18_fpnc_1200e_icdar2015.py

### Reproduces the problem - error message

python tools/train.py configs/textdet/dbnet/dbnet_resnet18_fpnc_1200e_icdar2015.py

### Additional information

python tools/train.py configs/textdet/dbnet/dbnet_resnet18_fpnc_1200e_icdar2015.py

**Comment by gaotongxiao** [comment]
As indicated by the error message itself, the `_base_` configurations you have inherited have the same key redefined twice or more in separate files. You should check the base configs carefully and fix it.
