### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by hiwaveSupport** [open-mmlab/mmocr#1940]
### Branch

master branch  https://mmocr.readthedocs.io/en/latest/

### 📚 The doc issue

Followed the installation using docker image, provided in DockerFile.
![image](https://github.com/open-mmlab/mmocr/assets/39630233/0b9784dd-3c62-4a16-8058-4e69b85d7376)

It keeps hanging at inference.
The longest I have waited is 30 mins, no movement.
Any ideas why?

**Comment by gaotongxiao** [comment]
Docker usually cannot run X11 applications, remove `--show` from the command and try again

**Comment by hiwaveSupport** [comment]
Yes, oops - TY!
