### ISSUE TITLE
Can't download the fcenet and drrg pretrained models

### ISSUE THREAD

**Issue by seekingdeep** [open-mmlab/mmocr#196]
Can't download the fcenet and drrg pretrained models

https://download.openmmlab.com/mmocr/textdet/fcenet/fcenet_r50dcnv2_fpn_1500e_ctw1500-05d740bb.pth
https://download.openmmlab.com/mmocr/textdet/drrg/drrg_r50_fpn_unet_1200e_ctw1500-1abf4f67.pth

![image](https://user-images.githubusercontent.com/71519088/118393400-9a254880-b647-11eb-9f99-7043ccf182ad.png)

**Comment by jeffreykuang** [comment]
not upload them yet. pls wait patiently.

**Comment by seekingdeep** [comment]
alright
