### ISSUE TITLE
以前的数据集下载链接去哪里了，越更新越难用，我也是服了。

### ISSUE THREAD

**Issue by xieliaolieji** [open-mmlab/mmocr#1967]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

。。

### Reproduces the problem - code sample

。。

### Reproduces the problem - command or script

。。

### Reproduces the problem - error message

。。

### Additional information

。。

**Comment by gaotongxiao** [comment]
Dataset downloading is now fully automated by Dataset Preparer. Please read the docs here: https://mmocr.readthedocs.io/zh_CN/dev-1.x/user_guides/data_prepare/dataset_preparer.html

We welcome kind discussion, suggestions, and ideas here, please try to focus on the issue itself.

**Comment by dhddxdhd** [comment]
> Dataset downloading is now fully automated by Dataset Preparer. Please read the docs here: https://mmocr.readthedocs.io/zh_CN/dev-1.x/user_guides/data_prepare/dataset_preparer.html
> 
> We welcome kind discussion, suggestions, and ideas here, please try to focus on the issue itself.

同感，瞎折腾，越来越难用
