### ISSUE TITLE
中文识别预测提示没有找到文件data/chineseocr/labels/dict_printed_chinese_english_digits.txt

### ISSUE THREAD

**Issue by futureflsl** [open-mmlab/mmocr#197]
中文识别预测提示没有找到文件data/chineseocr/labels/dict_printed_chinese_english_digits.txt

**Comment by cuhk-hbsun** [comment]
@futureflsl Please download the dict file by the link in `configs/textrecog/sar/README.md`

**Comment by cuhk-hbsun** [comment]
[download](https://mmocr.readthedocs.io/en/latest/textrecog_models.html#chinese-dataset)

**Comment by cuhk-hbsun** [comment]
fix
