### ISSUE TITLE
[Feature] Does MMOCR Support Python-API Like EasyOCR?

### ISSUE THREAD

**Issue by songyuc** [open-mmlab/mmocr#1975]
### What is the feature?

I am interested in knowing if MMOCR supports Python-API calls similar to EasyOCR. Specifically, I would like to know if there are Python functions or classes that allow for easy integration of MMOCR into Python-based projects.

Having Python-API support similar to EasyOCR would make it easier for developers to integrate MMOCR into their existing Python projects without having to deal with lower-level details. This would broaden the user base of MMOCR and make it more accessible for Python developers. It would also streamline the process of text detection and recognition in various applications, from simple scripts to complex machine learning pipelines.

### Any other context?

I have tried using EasyOCR for my project, but I am interested in MMOCR due to its additional features and capabilities. However, the lack of Python-API support similar to EasyOCR is a barrier for integration into my existing Python project.

Here is how I currently integrate EasyOCR:
```
pythonCopy codeimport easyocr
reader = easyocr.Reader(['en'])
result = reader.readtext('image.jpg')
```

I would love to have a similar level of simplicity with MMOCR.

**Comment by gaotongxiao** [comment]
You may use `Inferencer` in your project: https://mmocr.readthedocs.io/en/dev-1.x/user_guides/inference.html

**Comment by songyuc** [comment]
@gaotongxiao , thanks sincerely for your guidance!
I will try it.
