### ISSUE TITLE
[Bug] AssertionError: MMDetection 3.2.0 is incompatible with MMOCR 1.0.1.

### ISSUE THREAD

**Issue by 02shanks** [open-mmlab/mmocr#1998]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

Traceback (most recent call last):
  File "/content/mmocr/mmocr/utils/collect_env.py", line 5, in <module>
    import mmocr
  File "/content/mmocr/mmocr/__init__.py", line 50, in <module>
    and mmdet_version < digit_version(mmdet_maximum_version)), \
AssertionError: MMDetection 3.2.0 is incompatible with MMOCR 1.0.1. Please use MMDetection >= 3.0.0rc5, < 3.2.0 instead.

### Reproduces the problem - code sample

##First I installed all necessary libraries
!pip install -U openmim
!mim install mmengine
!mim install 'mmcv>=2.0.0rc1'
!mim install 'mmdet>=3.0.0rc0'

##Then
!git clone https://github.com/open-mmlab/mmocr.git
%cd mmocr
!pip install -v -e .

##Then
from mmocr.apis import MMOCRInferencer
ocr = MMOCRInferencer(det='DBNet', rec='CRNN')
ocr('demo/demo_text_ocr.jpg', show=True, print_result=True)

### Reproduces the problem - command or script

%%bash
!pip install -U openmim
!mim install mmengine
!mim install 'mmcv>=2.0.0rc1'
!mim install 'mmdet>=3.0.0rc5'

##then
!git clone https://github.com/open-mmlab/mmocr.git
%cd mmocr
!pip install -v -e .

### Reproduces the problem - error message

AssertionError: MMDetection 3.2.0 is incompatible with MMOCR 1.0.1. Please use MMDetection >= 3.0.0rc5, < 3.2.0 instead.

### Additional information

I am using [colab](https://colab.research.google.com/drive/1Y1ZlKtabdYRMIpXujrPjqeKqiMCg2cwR?usp=sharing) notebook where I encounter this error
After running `from mmocr.apis import MMOCRInferencer` I received `AssertionError: MMDetection 3.2.0 is incompatible with MMOCR 1.0.1. Please use MMDetection >= 3.0.0rc5, < 3.2.0 instead.`

I changed from
` !mim install 'mmdet>=3.0.0rc0'`
to 
`!mim install 'mmdet>=3.0.0rc5'`

but still I get same error!

**Comment by letruongngochai** [comment]
I've got the same problem

**Comment by 02shanks** [comment]
I resolved this issue just by lowering pytorch version to 2.0
`##check version 
!python -c 'import torch;print(torch.__version__);print(torch.version.cuda)'

##check [link](https://colab.research.google.com/corgiredirector?site=https%3A%2F%2Fpytorch.org%2Fget-started%2Fprevious-versions%2F) for suitable version 

!pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118 -q

##then
!pip3 install openmim
!git clone https://github.com/open-mmlab/mmocr.git
%cd mmocr
!mim install -e .

##finally
from mmocr.apis import MMOCRInferencer
ocr = MMOCRInferencer(det='DBNet', rec='CRNN')
ocr('demo/demo_text_ocr.jpg', show=True, print_result=True)
`

This worked for me without any error in any piece of code

**Comment by 02shanks** [comment]
It was mainly due to mmcv and pytorch version issue which is explained in this [issue](https://github.com/open-mmlab/mmcv/issues/2938). This dependency issue would be solved within weeks as mentioned in issue itself
Hope so it might help other to!

**Comment by JumpingRobin** [comment]
I have lowered my pytorch version, but the problem is still there.
`AssertionError: MMDetection 3.2.0 is incompatible with MMOCR 1.0.1. Please use MMDetection >= 3.0.0rc5, < 3.2.0 instead.
>>> import torch
>>> print(torch.__version__)
2.0.0
>>> print(torch.version.cuda)
11.7`

**Comment by raintowing** [comment]
You can comment out the Assert code to solve the problem temporarily.
