### ISSUE TITLE
安装MMCV报错，OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by aishangmaxiaoming** [open-mmlab/mmocr#20]
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/67897601/114023937-0b821680-98a6-11eb-9a56-b078de2bba51.png">

**Comment by innerlee** [comment]
To avoid compilation, you can install the pre-built mmcv from pip. Follow instructions at mmcv's README page https://github.com/open-mmlab/mmcv, somewhere near

![image](https://user-images.githubusercontent.com/9464825/114024962-328d1800-98a7-11eb-8ecd-77c6b8bfc3ba.png)

**Comment by aishangmaxiaoming** [comment]
> To avoid compilation, you can install the pre-built mmcv from pip. Follow instructions at mmcv's README page https://github.com/open-mmlab/mmcv, somewhere near
> 
> ![image](https://user-images.githubusercontent.com/9464825/114024962-328d1800-98a7-11eb-8ecd-77c6b8bfc3ba.png)

谢谢我提个建议，咱们mmocr的环境安装过于复杂，mmdet,mmcv,mmocr都要装，这中间会有很多坑，用户的粘性就会降低很多，paddleocr的安装就很容易，所以咱们后面是否可以将文档写的更容易让用户理解，和安装方式更简单些呢。推升咱们开源项目的认可度

**Comment by innerlee** [comment]
Will close this for now since it is an upstream issue
