### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by ooo-lwj** [open-mmlab/mmocr#200]
running in  notebook,i wonder if the results can visualized as a graph.And the result i got is below,what should i do to realize avisualization
![image](https://user-images.githubusercontent.com/73279725/118446270-04122080-b722-11eb-9d54-0b331f0d42c0.png)

**Comment by innerlee** [comment]
See if this can help https://github.com/open-mmlab/mmocr/pull/199

**Comment by ooo-lwj** [comment]
thanks
