### ISSUE TITLE
关于dbnet训练的问题

### ISSUE THREAD

**Issue by andy7166** [open-mmlab/mmocr#201]
训练过程能够显示准确率和检测框的情况吗？
单卡2080ti,6万张检测数据训练160epoch需要训练9天，有办法加速吗,
双卡训练发现电脑会卡住甚至死机。

**Comment by jeffreykuang** [comment]
It didn't get stuck when multiple gpus were used in my experiments.   Can you try it again by setting workers_per_gpu to a smaller number, 0, 2, or 4?

**Comment by jeffreykuang** [comment]
can you provide the script you used so that we can recover your issue?

**Comment by andy7166** [comment]
> can you provide the script you used so that we can recover your issue?

./tools/dist_train.sh '/data/mmocr/configs/textdet/dbnet/dbnet_r18_fpnc_1200e_mydata.py' '/data/mmocr/train_det' 1
训练时，感觉显卡利用率特别低

**Comment by cuhk-hbsun** [comment]
@andy7166 How about the GPU memory usage? If low, please use a larger batch size.

**Comment by andy7166** [comment]
> @andy7166 How about the GPU memory usage? If low, please use a larger batch size.

GPU memory已经95%以上，感觉训练过程特别消耗cpu资源，GPU使用率低

**Comment by jeffreykuang** [comment]
Can you help to locate where the bottleneck is via python profiling?

**Comment by Co4AI** [comment]
同样，感觉某次更新之后就这样了。GPU利用率一致0

**Comment by innerlee** [comment]
Is this related? https://github.com/open-mmlab/mmocr/pull/98

@Co4AI pls change the max_candidates back to 1000 and try again

**Comment by Co4AI** [comment]
> Is this related? #98
> 
> @Co4AI @andy7166 pls change the max_candidates back to 1000 and try again

Now I get the normal training speed by cloning a new repo. When I run 'git pull' in my old repo, I will encounter this problem. Maybe I run it in the wrong way...

**Comment by cuhk-hbsun** [comment]
fix
