### ISSUE TITLE
no anno_files 

### ISSUE THREAD

**Issue by ooo-lwj** [open-mmlab/mmocr#202]
when i uncompressed the wildreceipt.tar file,I cannot find the anno_file you guys mentioned as below,where can i find that file?
![image](https://user-images.githubusercontent.com/73279725/118458360-3ffeb300-b72d-11eb-927f-1d5aeaa3b5d2.png)
![image](https://user-images.githubusercontent.com/73279725/118458457-599ffa80-b72d-11eb-9d8c-14180ccb0af5.png)

**Comment by innerlee** [comment]
The anno_files is not needed. We will fix the documentation. Thanks for the report!
