### ISSUE TITLE
[Bug] MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.

### ISSUE THREAD

**Issue by Gaaaaam** [open-mmlab/mmocr#2041]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

----system env----
CUDA: 12.3
System: Linux(Centos8)
Python: 3.8
Pytorch: 2.1.2

### Reproduces the problem - code sample

from mmocr.apis import MMOCRInferencer
ocr = MMOCRInferencer(det='DBNet', rec='CRNN')
ocr('demo/demo_text_ocr.jpg', show=True, print_result=True)

### Reproduces the problem - command or script

1. 运行安装文档中的代码
git clone https://github.com/open-mmlab/mmocr.git
cd mmocr
pip install -v -e .
2. 安装openmim、mmengine、mmcv、mmdet
pip install -U openmim
mim install mmengine
mim install mmcv
mim install mmdet
3. 运行安装文档中的示例代码
from mmocr.apis import MMOCRInferencer
ocr = MMOCRInferencer(det='DBNet', rec='CRNN')
ocr('demo/demo_text_ocr.jpg', show=True, print_result=True)
4. 安装mmocr

### Reproduces the problem - error message

根据安装文档安装得到的mm库版本：
mmengine: 0.10.3
mmcv: 2.2.0
mmdet: 3.3.0
mmocr: 1.0.1
运行文档的示例代码会报错，提示mmdet版本与mmocr不兼容
MMDetection 3.3.0 is incompatible with MMOCR 1.0.1. Please use MMDetection >= 3.0.0rc5, < 3.2.0 instead.
于是卸载mmdet重新下载了3.0.0rc5版本
再次运行示例代码，提示mmcv版本被使用，但不兼容
MMCV==2.2.0 is used but incompatible. please install mmcv>=2.0.0rc4,<2.2.0.
卸载mmcv重新下载2.0.0rcx（x表示1/2/3/4任意版本）或2.0.1等版本会在命令行提示如下报错
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for mmcv
Running setup.py clean for mmcv
Failed to build mmcv
ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects
---mmcv 的下载---
 try to install mmcv from source. https://mmcv.readthedocs.io/en/latest/get_started/build.html#build-mmcv
可以build但版本仍然是2.2.0，也会报错
MMCV==2.2.0 is used but incompatible. please install mmcv>=2.0.0rc4,<2.2.0.

**Comment by drzraf** [comment]
Similar to https://github.com/open-mmlab/mmdetection/issues/11668

**Comment by TanHaonan** [comment]
Solved the same problems by specifying  the version of mmcv during installation.

1. uninstall mmcv with code below in your virtual env for mmdetection:
`mim uninstall mmcv`
2. to specify the version of mmcv, you can use the following command:
`mim install "mmcv==2.1.0"`
_It's not necessary to use 2.1.0, but I just tried this one and it works for me_

or maybe just change the maximum version as [#11668](https://github.com/open-mmlab/mmdetection/issues/11668) suggested
Hope this could help! I guess OpenMMLab will fix it soon.

**Comment by Gaaaaam** [comment]
> Solved the same problems by specifying the version of mmcv during installation.
> 
> 1. uninstall mmcv with code below in your virtual env for mmdetection:
>    `mim uninstall mmcv`
> 2. to specify the version of mmcv, you can use the following command:
>    `mim install "mmcv==2.1.0"`
>    _It's not necessary to use 2.1.0, but I just tried this one and it works for me_
> 
> or maybe just change the maximum version as [#11668](https://github.com/open-mmlab/mmdetection/issues/11668) suggested Hope this could help! I guess OpenMMLab will fix it soon.

I specified the version of mmcv as you suggested, then I followed the suggestion in #11668. It works now, thank you!!!

**Comment by Gaaaaam** [comment]
> Similar to [open-mmlab/mmdetection#11668](https://github.com/open-mmlab/mmdetection/issues/11668)

I followed the suggestion in [#11668](https://github.com/open-mmlab/mmdetection/issues/11668). It works now, thank you!!!

**Comment by aspaul20** [comment]
Running the following command shows that mmcv 2.1.0 was installed but when I import it and check the version, it shows 2.2.0 (???) 

` mim install "mmcv==2.1.0"`

I've been trying to install this tool for the last 4 hours and still stuck on this error. I've tried installing with pip, mim, and from source.

**Comment by WEI9957** [comment]
> Running the following command shows that mmcv 2.1.0 was installed but when I import it and check the version, it shows 2.2.0 (???) and the error persists.
> 
> ` mim install "mmcv==2.1.0"`
> 
> I've been trying to install this tool for the last 4 hours and still stuck on this error. I've tried installing with pip, mim, and from source.

same error, have you fixed it?

**Comment by sparshgarg23** [comment]
@WEI9957  I just tried @TanHaonan  's solution and it works.Will test it further.
