### ISSUE TITLE
利用crnn推理时报错

### ISSUE THREAD

**Issue by aishangmaxiaoming** [open-mmlab/mmocr#21]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/67897601/114030819-56535c80-98ad-11eb-8a3e-707028996535.png">

**Comment by innerlee** [comment]
Thanks for the report! Will fix this soon

**Comment by cuhk-hbsun** [comment]
bug fixed in the latest commit, pls pull the latest code and try again
