### ISSUE TITLE
SegOCR Simple Baseline Uppercase and special character not detected

### ISSUE THREAD

**Issue by SutirthaChakraborty** [open-mmlab/mmocr#219]
**The capital letter and special characters are not included**

**Motivation**
Can you include a trained model to detect the uppercase and  special characters? Or any alternative way to do so ?

**Related resources**
![image](https://user-images.githubusercontent.com/47362033/118725055-0ae98200-b84d-11eb-9a94-e0ed2acfedf4.png)

Used checkpoint and config
checkpoint4='/content/seg_r31_1by16_fpnocr_academic-72235b11.pth'
config4= '/content/mmocr/configs/textrecog/seg/seg_r31_1by16_fpnocr_academic.py'

**Comment by jeffreykuang** [comment]
I guess the model supports capital letters.  However, it does not distinguish capital letters and small ones.  To solve it, it needs retraining via distinguishing them in dictionary.   To recognize special characters, you need training data which has special characters, and char level annotations.

**Comment by SutirthaChakraborty** [comment]
Thanks, can it be done by us? or any availability of an updated trained model for this?

**Comment by jeffreykuang** [comment]
> Thanks, can it be done by us? or any availability of an updated trained model for this?

Not yet.  Can you provide the character set you want to support, and language corpus (the more the better) which contains character set?  The language corpus is used to synthesize training data.   It would be better if you can you provide real images with char level annoations.

**Comment by SutirthaChakraborty** [comment]
I don't have it. I was just exploring the models for my work, I needed a good ocr and this turned out the best one.
