### ISSUE TITLE
OCR on CPU device

### ISSUE THREAD

**Issue by VpkPrasanna** [open-mmlab/mmocr#225]
I know that ocr_image_demo will work only on GPU device , is there any chance to support on "**CPU**" devices as well ?

**Comment by innerlee** [comment]
Some models does not have cpu ops. So you have to try models to see if they can run on cpu. After pr https://github.com/open-mmlab/mmocr/pull/227, try

```bash
python demo/ocr_image_demo.py demo/demo_text_det.jpg demo/output.jpg --device cpu --det-config configs/textdet/textsnake/textsnake_r50_fpn_unet_1200e_ctw1500.py --det-ckpt https://download.openmmlab.com/mmocr/textdet/textsnake/textsnake_r50_fpn_unet_1200e_ctw1500-27f65b64.pth
```

**Comment by cuhk-hbsun** [comment]
fixed
