### ISSUE TITLE
how to use my dataset

### ISSUE THREAD

**Issue by epiphany97** [open-mmlab/mmocr#229]
hi, I want to use my dataset to detect and recognize ,what should i do to handle this dataset?thanks for you reply

**Comment by cuhk-hbsun** [comment]
1. You can prepare your dataset like `tests/data/ocr_toy_dataset` for textrecognition and `tests/data/toy_dataset` for text detection.
2. For text recognition, you may need to use a new dictionary file (cover the characters that occurred in the dataset labels) like `https://github.com/open-mmlab/mmocr/blob/main/configs/textrecog/sar/sar_r31_parallel_decoder_chinese.py#L5`

**Comment by innerlee** [comment]
If this colab tutorial can help https://github.com/open-mmlab/mmocr/blob/main/demo/MMOCR_Tutorial.ipynb

**Comment by cuhk-hbsun** [comment]
@epiphany97 
1. For text recognition, the dataset format is very simple (see `tests/data/ocr_toy_dataset/label.txt` for details).
2. For text detection, the annotation file is like `tests/data/toy_dataset/instances_test.txt`. Since we don't know how your original annotation file is organized, we can not provide a converter script for you. The converter scripts we provide are just for the academic dataset.

**Comment by cuhk-hbsun** [comment]
fix

**Comment by mobassir94** [comment]
dear @innerlee  and @cuhk-hbsun 
can you provide us a demo for training text detection models?
we have total text format like data, we have found demo for text recognition model training here : https://github.com/open-mmlab/mmocr/blob/main/demo/MMOCR_Tutorial.ipynb
but no information has been provided about how to train a text detector model in that demo notebook,
i tried : 

```
from mmcv import Config
cfg = Config.fromfile('/home/apsisdev/IMPORTANT/mmocr/configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py') 
from mmdet.apis import set_random_seed

# Set up working dir to save files and logs.
cfg.work_dir = '../outputs/detection_model'

# The original learning rate (LR) is set for 8-GPU training.
# We divide it by 8 since we only use one GPU.
cfg.optimizer.lr = 0.001 / 8
cfg.lr_config.warmup = None
# Choose to log training results every 128 images to reduce the size of log file. 
cfg.log_config.interval = 1

# Set seed thus the results are more reproducible
cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.gpu_ids = range(1)

# We can initialize the logger for training and have a look
# at the final config used for training
#
#cfg.label_convertor["dict_file"]="/home/apsisdev/IMPORTANT/banglasynthShort/bangla_dict.txt"
print(f'Config:\n{cfg.pretty_text}')

from mmocr.datasets import build_dataset
from mmocr.models import build_detector
from mmocr.apis import train_detector
import os.path as osp
cfg.total_epochs = 2
# Build dataset
datasets = [build_dataset(cfg.data.train)]


# Build the detector
model = build_detector(
    cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

# Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
```
and faced this error : 

loading annotations into memory...
Done (t=0.51s)
creating index...
index created!
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/ocr/lib/python3.8/site-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
     50     try:
---> 51         return obj_cls(**args)
     52     except Exception as e:

~/IMPORTANT/mmocr/mmocr/datasets/icdar_dataset.py in __init__(self, ann_file, pipeline, classes, data_root, img_prefix, seg_prefix, proposal_file, test_mode, filter_empty_gt, select_first_k)
     27 
---> 28         super().__init__(ann_file, pipeline, classes, data_root, img_prefix,
     29                          seg_prefix, proposal_file, test_mode, filter_empty_gt)

~/anaconda3/envs/ocr/lib/python3.8/site-packages/mmdet/datasets/custom.py in __init__(self, ann_file, pipeline, classes, data_root, img_prefix, seg_prefix, proposal_file, test_mode, filter_empty_gt)
     87         # load annotations (and proposals)
---> 88         self.data_infos = self.load_annotations(self.ann_file)
     89 

~/IMPORTANT/mmocr/mmocr/datasets/icdar_dataset.py in load_annotations(self, ann_file)
     41         self.coco = COCO(ann_file)
---> 42         self.cat_ids = self.coco.get_cat_ids(cat_names=self.CLASSES)
     43         self.cat2label = {cat_id: i for i, cat_id in enumerate(self.cat_ids)}

AttributeError: 'COCO' object has no attribute 'get_cat_ids'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-33-e94eea546aac> in <module>
      5 cfg.total_epochs = 2
      6 # Build dataset
----> 7 datasets = [build_dataset(cfg.data.train)]
      8 
      9 

~/anaconda3/envs/ocr/lib/python3.8/site-packages/mmdet/datasets/builder.py in build_dataset(cfg, default_args)
     69         dataset = _concat_dataset(cfg, default_args)
     70     else:
---> 71         dataset = build_from_cfg(cfg, DATASETS, default_args)
     72 
     73     return dataset

~/anaconda3/envs/ocr/lib/python3.8/site-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
     52     except Exception as e:
     53         # Normal TypeError does not print class name.
---> 54         raise type(e)(f'{obj_cls.__name__}: {e}')
     55 
     56 

AttributeError: IcdarDataset: 'COCO' object has no attribute 'get_cat_ids'


a detection demo script could help a lot of novices like me,thanks

**Comment by gaotongxiao** [comment]
> dear @innerlee and @cuhk-hbsun
> can you provide us a demo for training text detection models?
> we have total text format like data, we have found demo for text recognition model training here : https://github.com/open-mmlab/mmocr/blob/main/demo/MMOCR_Tutorial.ipynb
> but no information has been provided about how to train a text detector model in that demo notebook,
> i tried :
> 
> ```
> from mmcv import Config
> cfg = Config.fromfile('/home/apsisdev/IMPORTANT/mmocr/configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py') 
> from mmdet.apis import set_random_seed
> 
> # Set up working dir to save files and logs.
> cfg.work_dir = '../outputs/detection_model'
> 
> # The original learning rate (LR) is set for 8-GPU training.
> # We divide it by 8 since we only use one GPU.
> cfg.optimizer.lr = 0.001 / 8
> cfg.lr_config.warmup = None
> # Choose to log training results every 128 images to reduce the size of log file. 
> cfg.log_config.interval = 1
> 
> # Set seed thus the results are more reproducible
> cfg.seed = 0
> set_random_seed(0, deterministic=False)
> cfg.gpu_ids = range(1)
> 
> # We can initialize the logger for training and have a look
> # at the final config used for training
> #
> #cfg.label_convertor["dict_file"]="/home/apsisdev/IMPORTANT/banglasynthShort/bangla_dict.txt"
> print(f'Config:\n{cfg.pretty_text}')
> 
> from mmocr.datasets import build_dataset
> from mmocr.models import build_detector
> from mmocr.apis import train_detector
> import os.path as osp
> cfg.total_epochs = 2
> # Build dataset
> datasets = [build_dataset(cfg.data.train)]
> 
> 
> # Build the detector
> model = build_detector(
>     cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
> # Add an attribute for visualization convenience
> model.CLASSES = datasets[0].CLASSES
> 
> # Create work_dir
> mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
> ```
> 
> and faced this error :
> 
> ## loading annotations into memory...
> Done (t=0.51s)
> creating index...
> index created!
> AttributeError Traceback (most recent call last)
> ~/anaconda3/envs/ocr/lib/python3.8/site-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
> 50 try:
> ---> 51 return obj_cls(**args)
> 52 except Exception as e:
> 
> ~/IMPORTANT/mmocr/mmocr/datasets/icdar_dataset.py in **init**(self, ann_file, pipeline, classes, data_root, img_prefix, seg_prefix, proposal_file, test_mode, filter_empty_gt, select_first_k)
> 27
> ---> 28 super().**init**(ann_file, pipeline, classes, data_root, img_prefix,
> 29 seg_prefix, proposal_file, test_mode, filter_empty_gt)
> 
> ~/anaconda3/envs/ocr/lib/python3.8/site-packages/mmdet/datasets/custom.py in **init**(self, ann_file, pipeline, classes, data_root, img_prefix, seg_prefix, proposal_file, test_mode, filter_empty_gt)
> 87 # load annotations (and proposals)
> ---> 88 self.data_infos = self.load_annotations(self.ann_file)
> 89
> 
> ~/IMPORTANT/mmocr/mmocr/datasets/icdar_dataset.py in load_annotations(self, ann_file)
> 41 self.coco = COCO(ann_file)
> ---> 42 self.cat_ids = self.coco.get_cat_ids(cat_names=self.CLASSES)
> 43 self.cat2label = {cat_id: i for i, cat_id in enumerate(self.cat_ids)}
> 
> AttributeError: 'COCO' object has no attribute 'get_cat_ids'
> 
> During handling of the above exception, another exception occurred:
> 
> AttributeError Traceback (most recent call last)
> in
> 5 cfg.total_epochs = 2
> 6 # Build dataset
> ----> 7 datasets = [build_dataset(cfg.data.train)]
> 8
> 9
> 
> ~/anaconda3/envs/ocr/lib/python3.8/site-packages/mmdet/datasets/builder.py in build_dataset(cfg, default_args)
> 69 dataset = _concat_dataset(cfg, default_args)
> 70 else:
> ---> 71 dataset = build_from_cfg(cfg, DATASETS, default_args)
> 72
> 73 return dataset
> 
> ~/anaconda3/envs/ocr/lib/python3.8/site-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
> 52 except Exception as e:
> 53 # Normal TypeError does not print class name.
> ---> 54 raise type(e)(f'{obj_cls.**name**}: {e}')
> 55
> 56
> 
> AttributeError: IcdarDataset: 'COCO' object has no attribute 'get_cat_ids'
> 
> a detection demo script could help a lot of novices like me,thanks

Hi, you can try replacing your pycocotools with our forked version by running `pip install -U "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"`. We already noticed this bug and will fix it soon.

**Comment by mobassir94** [comment]
dear @gaotongxiao 
thank you,it solves my earlier error and now i can see training started ,thank you but i have faced another issue during training that i am going to share in my next comment here..

**Comment by mobassir94** [comment]
this is my config of dbnet : 

`
Config:
optimizer = dict(type='SGD', lr=0.000125, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='poly', power=0.9, min_lr=1e-07, by_epoch=True, warmup=None)
total_epochs = 1200
checkpoint_config = dict(interval=10)
log_config = dict(interval=1, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
model = dict(
    type='DBNet',
    pretrained='torchvision://resnet18',
    backbone=dict(
        type='ResNet',
        depth=18,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=False,
        style='caffe'),
    neck=dict(
        type='FPNC', in_channels=[64, 128, 256, 512], lateral_channels=256),
    bbox_head=dict(
        type='DBHead',
        text_repr_type='quad',
        in_channels=256,
        loss=dict(type='DBLoss', alpha=5.0, beta=10.0, bbce_loss=True)),
    train_cfg=None,
    test_cfg=None)
dataset_type = 'IcdarDataset'
data_root = '/home/apsisdev/IMPORTANT/totaltext/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='LoadTextAnnotations',
        with_bbox=True,
        with_mask=True,
        poly2mask=False),
    dict(type='ColorJitter', brightness=0.12549019607843137, saturation=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(
        type='ImgAug',
        args=[['Fliplr', 0.5], {
            'cls': 'Affine',
            'rotate': [-10, 10]
        }, ['Resize', [0.5, 3.0]]]),
    dict(type='EastRandomCrop', target_size=(640, 640)),
    dict(type='DBNetTargets', shrink_ratio=0.4),
    dict(type='Pad', size_divisor=32),
    dict(
        type='CustomFormatBundle',
        keys=['gt_shrink', 'gt_shrink_mask', 'gt_thr', 'gt_thr_mask'],
        visualize=dict(flag=False, boundary_key='gt_shrink')),
    dict(
        type='Collect',
        keys=['img', 'gt_shrink', 'gt_shrink_mask', 'gt_thr', 'gt_thr_mask'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 736),
        flip=False,
        transforms=[
            dict(type='Resize', img_scale=(2944, 736), keep_ratio=True),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=32,
    workers_per_gpu=8,
    train=dict(
        type='IcdarDataset',
        ann_file='/home/apsisdev/IMPORTANT/totaltext//instances_training.json',
        img_prefix='/home/apsisdev/IMPORTANT/totaltext//imgs',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='LoadTextAnnotations',
                with_bbox=True,
                with_mask=True,
                poly2mask=False),
            dict(
                type='ColorJitter',
                brightness=0.12549019607843137,
                saturation=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(
                type='ImgAug',
                args=[['Fliplr', 0.5], {
                    'cls': 'Affine',
                    'rotate': [-10, 10]
                }, ['Resize', [0.5, 3.0]]]),
            dict(type='EastRandomCrop', target_size=(640, 640)),
            dict(type='DBNetTargets', shrink_ratio=0.4),
            dict(type='Pad', size_divisor=32),
            dict(
                type='CustomFormatBundle',
                keys=['gt_shrink', 'gt_shrink_mask', 'gt_thr', 'gt_thr_mask'],
                visualize=dict(flag=False, boundary_key='gt_shrink')),
            dict(
                type='Collect',
                keys=[
                    'img', 'gt_shrink', 'gt_shrink_mask', 'gt_thr',
                    'gt_thr_mask'
                ])
        ]),
    val=dict(
        type='IcdarDataset',
        ann_file='/home/apsisdev/IMPORTANT/totaltext//instances_test.json',
        img_prefix='/home/apsisdev/IMPORTANT/totaltext//imgs',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 736),
                flip=False,
                transforms=[
                    dict(
                        type='Resize', img_scale=(2944, 736), keep_ratio=True),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='IcdarDataset',
        ann_file='/home/apsisdev/IMPORTANT/totaltext//instances_test.json',
        img_prefix='/home/apsisdev/IMPORTANT/totaltext//imgs',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 736),
                flip=False,
                transforms=[
                    dict(
                        type='Resize', img_scale=(2944, 736), keep_ratio=True),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
evaluation = dict(interval=100, metric='hmean-iou')
work_dir = '../outputs/detection_model'
seed = 0
gpu_ids = range(0, 1)
`
when i start training i get log like this : 

loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
2021-06-23 12:00:18,020 - mmocr - INFO - Epoch [1][1/533]	lr: 1.250e-04, eta: 3:59:48, time: 13.510, data_time: 11.375, memory: 13134, loss_prob: 0.0000, loss_db: 1.0000, loss_thr: 0.0000, loss: 1.0000
2021-06-23 12:00:21,739 - mmocr - INFO - Epoch [1][2/533]	lr: 1.250e-04, eta: 2:32:23, time: 3.677, data_time: 3.130, memory: 13230, loss_prob: 0.0000, loss_db: 1.0000, loss_thr: 0.0000, loss: 1.0000
2021-06-23 12:00:22,776 - mmocr - INFO - Epoch [1][3/533]	lr: 1.250e-04, eta: 1:47:40, time: 1.045, data_time: 0.443, memory: 13230, loss_prob: 0.0000, loss_db: 1.0000, loss_thr: 0.0000, loss: 1.0000
2021-06-23 12:00:23,805 - mmocr - INFO - Epoch [1][4/533]	lr: 1.250e-04, eta: 1:25:13, time: 1.026, data_time: 0.413, memory: 13230, loss_prob: 0.0000, loss_db: 1.0000, loss_thr: 0.0000, loss: 1.0000
2021-06-23 12:00:24,678 - mmocr - INFO - Epoch [1][5/533]	lr: 1.250e-04, eta: 1:11:10, time: 0.869, data_time: 0.407, memory: 13230, loss_prob: 0.0000, loss_db: 1.0000, loss_thr: 0.0000, loss: 1.0000

you can see that i am always getting : 

**lr: 1.250e-04, eta: 1:11:10, time: 0.869, data_time: 0.407, memory: 13230, loss_prob: 0.0000, loss_db: 1.0000, loss_thr: 0.0000, loss: 1.0000**

seems like something is wrong,what it could be?

**Comment by JNUChenYiHong** [comment]
> 1. You can prepare your dataset like `tests/data/ocr_toy_dataset` for textrecognition and `tests/data/toy_dataset` for text detection.
> 2. For text recognition, you may need to use a new dictionary file (cover the characters that occurred in the dataset labels) like [this](https://github.com/open-mmlab/mmocr/blob/main/configs/textrecog/sar/sar_r31_parallel_decoder_chinese.py#L5)

Thank you very much for such a great project. Is there a similar command for training text detection? like this command
`./tools/dist_train.sh configs/textrecog/sar/sar_r31_parallel_decoder_toy_dataset.py work_dirs/sar 1`

**Comment by gaotongxiao** [comment]
@JNUChenYiHong Sure, you only need to change the paths to the config and (optionally) the working directory. For example, 
```
./tools/dist_train.sh configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py dbnet 1
```
will train dbnet and save the logs and checkpoints to `dbnet/`.

**Comment by JNUChenYiHong** [comment]
> @JNUChenYiHong Sure, you only need to change the paths to the config and (optionally) the working directory. For example,
> 
> ```
> ./tools/dist_train.sh configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py dbnet 1
> ```
> 
> will train dbnet and save the logs and checkpoints to `dbnet/`.

Thank you for your answer！

**Comment by JNUChenYiHong** [comment]
> @JNUChenYiHong Sure, you only need to change the paths to the config and (optionally) the working directory. For example,
> 
> ```
> ./tools/dist_train.sh configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py dbnet 1
> ```
> 
> will train dbnet and save the logs and checkpoints to `dbnet/`.

请问代码中是否有将数据集转化为lmdb的脚步（以sar为例子，训练自己准备的数据集） 
tests/data/ocr_toy_dataset/label.lmdb/  data.mdb 和 lock.mdb

**Comment by JNUChenYiHong** [comment]
> @JNUChenYiHong Sure, you only need to change the paths to the config and (optionally) the working directory. For example,
> 
> ```
> ./tools/dist_train.sh configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py dbnet 1
> ```
> 
> will train dbnet and save the logs and checkpoints to `dbnet/`.

请问代码中是否有将数据集转化为label.lmdb 里面的 data.mdb和lock.mdb 代码？（好比如sar为例子，训练自己准备的数据集），非常感谢！

**Comment by gaotongxiao** [comment]
@JNUChenYiHong  `tools/data/utils/txt2lmdb.py`

**Comment by JNUChenYiHong** [comment]
> @JNUChenYiHong `tools/data/utils/txt2lmdb.py`

Thanks！yyds！

**Comment by xuezc** [comment]
> 
your datasets may have something wrong, you can try set iscrowd is 0
