### ISSUE TITLE
Speed up KIE training

### ISSUE THREAD

**Issue by innerlee** [open-mmlab/mmocr#238]

**Comment by innerlee** [comment]
Current:

```bash
python -m cProfile -o p.prof tools/train.py configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py --work-dir workdirs/sdmgr_novisual_60e_wildreceipt_20210525_1
snakeviz p.prof
```

* Remove image loading for novisual (expected reduce 36% time)
* Speed up sort_vertex (expected reduce 40% time)

![image](https://user-images.githubusercontent.com/9464825/119437590-0a6f5080-bd51-11eb-8857-9f3242e357f8.png)

**Comment by innerlee** [comment]
![image](https://user-images.githubusercontent.com/9464825/119443835-d7cb5500-bd5c-11eb-946d-360c83e4a22f.png)

**Comment by jeffreykuang** [comment]
GOOD JOB

**Comment by innerlee** [comment]
After ignoring the image processing

![image](https://user-images.githubusercontent.com/9464825/120652657-905a6c80-c4b2-11eb-9480-4b147f31774e.png)

**Comment by innerlee** [comment]
After removing the sort vertex call

![image](https://user-images.githubusercontent.com/9464825/120653484-4b830580-c4b3-11eb-9f7d-38e29d0bdb46.png)
