### ISSUE TITLE
static TLS error

### ISSUE THREAD

**Issue by dy1998** [open-mmlab/mmocr#240]
**Describe the bug**
I follow the install.md, when I try 'train with toy dataset'. The error occured as " ImportError: dlopen: cannot load any more object with static TLS". It seems like conflict between opencv and mmcv.

Detail:
  File "/data/dy/anaconda3/envs/mmocr/lib/python3.7/site-packages/mmcv/utils/env.py", line 8, in <module>
    import cv2
  File "/data/dy/anaconda3/envs/mmocr/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *

**Reproduction**

1. What command or script did you run?

```none
./tools/dist_train.sh configs/textrecog/seg/seg_r31_1by16_fpnocr_toy_dataset.py work_dirs/seg 1
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

   No modification.

3. What dataset did you use?

   tests/data

**Environment**

PS：run the "python mmocr/utils/collect_env.py" also rise same error

Package            Version             Location
------------------ ------------------- -------------------
addict             2.4.0
asynctest          0.13.0
attrs              21.2.0
certifi            2020.12.5
chardet            4.0.0
codecov            2.1.11
coverage           5.5
cycler             0.10.0
Cython             0.29.23
decorator          4.4.2
flake8             3.9.2
future             0.18.2
idna               2.10
imageio            2.9.0
imgaug             0.4.0
importlib-metadata 4.0.1
iniconfig          1.1.1
isort              5.8.0
kiwisolver         1.3.1
kwarray            0.5.19
lanms-proper       1.0.1
llvmlite           0.36.0
lmdb               1.2.1
matplotlib         3.4.2
mccabe             0.6.1
mmcv-full          1.3.4
mmdet              2.11.0
mmocr              0.2.0              
mmpycocotools      12.0.3
networkx           2.5.1
numba              0.53.1
numpy              1.20.3
opencv-python      4.5.2.52
ordered-set        4.0.2
packaging          20.9
Pillow             8.2.0
pip                21.1.1
pluggy             0.13.1
Polygon3           3.0.9.1
py                 1.10.0
pyclipper          1.2.1
pycodestyle        2.7.0
pyflakes           2.3.1
pyparsing          2.4.7
pytest             6.2.4
pytest-cov         2.12.0
pytest-runner      5.3.1
python-dateutil    2.8.1
PyWavelets         1.1.1
PyYAML             5.4.1
rapidfuzz          1.4.1
requests           2.25.1
scikit-image       0.18.1
scipy              1.6.3
setuptools         52.0.0.post20210125
Shapely            1.7.1
six                1.16.0
terminaltables     3.1.0
tifffile           2021.4.8
toml               0.10.2
torch              1.5.0
torchvision        0.6.0
typing-extensions  3.10.0.0
ubelt              0.9.5
urllib3            1.26.4
wheel              0.36.2
xdoctest           0.15.4
yapf               0.31.0
zipp               3.4.1

**Comment by cuhk-hbsun** [comment]
@dy1998 please try `pip install opencv-python==4.5.1.48`, and we will check the incompatibility between mmcv and opencv.

**Comment by dy1998** [comment]
> @dy1998 please try `pip install opencv-python==4.5.1.48`, and we will check the incompatibility between mmcv and opencv.

Thanks for reply,  I follow your advice, However, it still raise same error. 

Moreover, I change the version as 4.3.0.36, and it works well now.

**Comment by cuhk-hbsun** [comment]
ok, we will report this problem to `mmcv`.

**Comment by dy1998** [comment]
> ok, we will report this problem to `mmcv`.

Besides, scikit-image should change as 0.14.3, or it will raise:
`ImportError: dlopen: cannot load any more object with static TLS
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
https://scikit-image.org/docs/stable/install.html 
`

**Comment by cuhk-hbsun** [comment]
@dy1998 Could you please provide the infos from `python mmocr/utils/collect_env.py`?

**Comment by dy1998** [comment]
> @dy1998 Could you please provide the infos from `python mmocr/utils/collect_env.py`?

fatal: Not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: TITAN Xp
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.168
GCC: gcc (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0
OpenCV: 4.3.0
MMCV: 1.3.4
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMOCR: 0.2.0+

**Comment by cuhk-hbsun** [comment]
fix
