### ISSUE TITLE
performance of FCENet in ICDAR15

### ISSUE THREAD

**Issue by wushilian** [open-mmlab/mmocr#241]
Can you upload a model trained by fcenet on ic15？ I have trained FCENet 600 epoch，but only got 80 hmean

**Comment by jeffreykuang** [comment]
@Zyq-scut

**Comment by Zyq-scut** [comment]
Hi, we have not train FCENet on IC15 yet, but we will do it soon.
To improve proformance, you can test with larger 'img_scale' since text in IC15 are small. And 600 epoches are not enough for FCENet to converge, typically 1500 epoches.

**Comment by wushilian** [comment]
@Zyq-scut I have trained 1500 epoches，but only get 81 hmean. Here is my config
[fcenet_r50_fpn_1500e_ic15.txt](https://github.com/open-mmlab/mmocr/files/6550404/fcenet_r50_fpn_1500e_ic15.txt)

**Comment by Zyq-scut** [comment]
Thanks for your feedback. We are training FCENet on IC15 and locating the problem you mentioned above. If there is any progress, we will synchronize with you.

**Comment by Zyq-scut** [comment]
Problem solved. Our trained [model](https://github.com/open-mmlab/mmocr/tree/main/configs/textdet/fcenet) on ICDAR2015 is available now. Thanks!

**Comment by kbrajwani** [comment]
@Zyq-scut can you please check the link of fcenet ICDAR2015? The link of trained model ICDAR2015  and CTW1500 is same.
Can you please update it? Thanks

**Comment by Zyq-scut** [comment]
@kbrajwani Hi, it is correct now. Thanks you for feedback.
