### ISSUE TITLE
请问mmocr支持中文检测+识别么

### ISSUE THREAD

**Issue by gengyanlei** [open-mmlab/mmocr#243]

**Comment by innerlee** [comment]
yes. All models in mmocr supports training.

**Comment by cuhk-hbsun** [comment]
@gengyanlei Thanks for your feedback. 
1. Currently, the text detection models are trained mainly on English images, but they can detect Chinese as well. If you have annotated image with Chinese, you can train a model like `PANet` by yourself. And we will release a Chinese detect model.
2. For text recognition, we have released a model for Chinese recognition in `configs/textrecog/sar/README.md`
3. You can test your image with script `demo/ocr_image_demo.py`. For example,
```python
python demo/ocr_image_demo.py <your_image> <output_image> --recog-config configs/textrecog/sar/sar_r31_parallel_decoder_chinese.py --recog-ckpt https://download.openmmlab.com/mmocr/textrecog/sar/sar_r31_parallel_decoder_chineseocr_20210507-b4be8214.pth
```
Note, you need download [dictionary file](https://download.openmmlab.com/mmocr/textrecog/sar/dict_printed_chinese_english_digits.txt) and put it to folder `data/chineseocr/labels/`.

**Comment by gengyanlei** [comment]
哦，我没有表达清楚，我的意思是有没有训练好的支持中文检测+识别的模型发布了呢？tks

**Comment by innerlee** [comment]
See https://github.com/open-mmlab/mmocr/pull/245

**Comment by cuhk-hbsun** [comment]
@gengyanlei 
1. For Chinese text recognition, the model has been released. See `configs/textrecog/sar/README.md` for details.
2. For Chinese text detection, you can have a try using the released models.

**Comment by zcgg2zhmm** [comment]
> 哦，我没有表达清楚，我的意思是有没有训练好的支持中文检测+识别的模型发布了呢？tks

@cuhk-hbsun已经说的很清楚了
