### ISSUE TITLE
Does sdmgr support key-value pair relation extraction

### ISSUE THREAD

**Issue by guanshuicheng** [open-mmlab/mmocr#248]

**Comment by innerlee** [comment]
Yes and no. Basically the infrastructure is ready. There's simply no academic data yet.

1. You need to prepare data that contains key-value pair info. The current model supports edge loss.
2. You need to write a visualization to show the predicted edges.

**Comment by guanshuicheng** [comment]
> Yes and no. Basically the infrastructure is ready. There's simply no academic data yet.
> 
> 1. You need to prepare data that contains key-value pair info. The current model supports edge loss.
> 2. You need to write a visualization to show the predicted edges.

Thank you for your answer. If I want to train edges, what is the labeling format of edges

**Comment by amitbcp** [comment]
@innerlee  it would be very helpful to train edge loss if format is  known. Can you please help for the same

**Comment by innerlee** [comment]
Thanks for the interest, I will add an example this month.

**Comment by amitbcp** [comment]
@innerlee did you get time to have a look on this ? if I can help , let me know, I'll be glad to contribute

**Comment by gaotongxiao** [comment]
Finally done in #478. We also prepare a [tutorial for it](https://mmocr.readthedocs.io/en/latest/tutorials/kie_closeset_openset.html). Hope that helps.
