### ISSUE TITLE
icdar_converter.py

### ISSUE THREAD

**Issue by seekingdeep** [open-mmlab/mmocr#252]
Hi,
for the `icdar_converter.py` for icdar2015,
what should be the directory structure? how to name the files? example of command, etc...
because [getting_started.md](https://github.com/open-mmlab/mmocr/blob/main/docs/getting_started.md) coco converting is not clear to me

**Comment by cuhk-hbsun** [comment]
@seekingdeep For icdar2015 preparation, please refer to `docs/datasets.md` or [link](https://mmocr.readthedocs.io/en/latest/datasets.html#text-detection)
