### ISSUE TITLE
CPU Hardware Results

### ISSUE THREAD

**Issue by jkcg-learning** [open-mmlab/mmocr#256]
Is it possible to view the results for some test images in a CPU only enabled hardware 

or

Do we need  GPU enabled systems specifically for this purpose.

**Comment by cuhk-hbsun** [comment]
Nope. Most of the models support CPU as the backend for inference. You can have a try using the `image_demo.py` or `ocr_image_demo.py` by setting the parameter `--device cpu`.

**Comment by jkcg-learning** [comment]
> Nope. Most of the models support CPU as the backend for inference. You can have a try using the `image_demo.py` or `ocr_image_demo.py` by setting the parameter `--device cpu`.

I have tried executing this command, but getting error

No CUDA runtime is found, using CUDA_HOME ='xxxxxxxxxxx'; (There is no Graphics Card in my system..)

To be more precise, I was asking will the library support systems without Graphics card for the moment...

But I have executed it in Google Colab GPU runtime environment and the results are impressive... 👍

**Comment by cuhk-hbsun** [comment]
fixed
