### ISSUE TITLE
How to train mmOCR models on total text formatted dataset?

### ISSUE THREAD

**Issue by mobassir94** [open-mmlab/mmocr#262]
total text is a popular scene text format dataset,you will find more info about the dataset and it's format here : https://github.com/cs-chan/Total-Text-Dataset
however in this repo for detection task you used something like coco text formatting dataset,however i want to test some of your models on total text dataset for both detection,recognition task,on the other hand we have prepared synthetic dataset which follows total text formatting,we want to use that dataset to train some of mmOCR models to solve our data problem,can we do that? our dataset is not coco text formatted and we have created it synthetically by following total text format data.i need answer to these questions : 
1. can we directly use total text format data for mmOCR detection , recognition and  keyinformation extraction task?
2.if there is no way to use total text format data directly then can you tell me how to convert total text data format in coco text format using python code?

thank you in advance <3

**Comment by cuhk-hbsun** [comment]
btw, data preparation for text recognition is fix in [273](https://github.com/open-mmlab/mmocr/pull/273)

**Comment by mobassir94** [comment]
thank you
