### ISSUE TITLE
Check warnings

### ISSUE THREAD

**Issue by innerlee** [open-mmlab/mmocr#27]
When testing, there are some warns from wrapper.py

![image](https://user-images.githubusercontent.com/9464825/114124364-dff34080-9926-11eb-9dbd-eb61b83bcab6.png)

Pls double check if the code is rigorous

**Comment by jeffreykuang** [comment]
which model do you test?

**Comment by innerlee** [comment]
From https://github.com/open-mmlab/mmocr/issues/17
