### ISSUE TITLE
how to map line by line text detection and recognition? 

### ISSUE THREAD

**Issue by YC7225** [open-mmlab/mmocr#272]
do we have any function which can give you line by line extraction like tesseract output?

**Comment by cuhk-hbsun** [comment]
@YC7225 Thanks for your feedback. Do you mean a function that can merge multiple boxes into one? Currently not.  
Since the text detection models were trained on the ICDAR dataset, it may detect one-line text by several boxes.
If you have a dataset annotated by line-box, you can train a model by yourself. Or write a function to merge multiple boxes to one.

**Comment by YC7225** [comment]
Can you use this code? I copied from  Keras-ocr repo. if there is some changes can you suggest me on that?

def isOnSameLine(boxOne, boxTwo):
    boxOneStartY = boxOne[0,1]
    boxOneEndY = boxOne[2,1]
    boxTwoStartY = boxTwo[0,1]
    boxTwoEndY = boxTwo[2,1]
    if((boxTwoStartY <= boxOneEndY and boxTwoStartY >= boxOneStartY)
    or(boxTwoEndY <= boxOneEndY and boxTwoEndY >= boxOneStartY)
    or(boxTwoEndY >= boxOneEndY and boxTwoStartY <= boxOneStartY)):
        return True
    else:
        return False

def segmentLines(box_group):
    # sort by highest starty value (bottom left corner of box - [startX,startY], [endX,startY], [endX,endY], [startX, endY])
    box_group = box_group[np.argsort(box_group[:, 0, 1])]

    lined_box_group = np.zeros(box_group.shape)
    sorted_box_group = np.zeros(box_group.shape)

    # list of indexes
    temp = []
    i = 0

    # check if there is more than one box in the box_group
    if len(box_group) > 1:
        while i < len(box_group):
            for j in range(i + 1, len(box_group)):
                if(isOnSameLine(box_group[i],box_group[j])):
                    # print(str(i) + " and " + str(j) + " on same line")
                    if i not in temp:
                        temp.append(i)
                    if j not in temp:
                        temp.append(j)
                # else:
                    # print(str(i) + " and " + str(j) + " not on same line")
            # append temp with i if the current box (i) is not on the same line with any other box
            if len(temp) == 0:
                temp.append(i)
            
            # put boxes on same line into lined_box_group array
            lined_box_group = box_group[np.array(temp)]
            # sort boxes by startX value
            lined_box_group = lined_box_group[np.argsort(lined_box_group[:, 0, 0])]
            # copy sorted boxes on same line into sorted_box_group
            sorted_box_group[i:temp[-1]+1] = lined_box_group
            
            # skip to the index of the box that is not on the same line
            i = temp[-1] + 1
            # clear list of indexes
            temp = []
    else:
        # since there is only one box in the boxgroup do nothing but copying the box
        # print("only one box in boxgroup")
        sorted_box_group = box_group
        
    return sorted_box_group

**Comment by gaotongxiao** [comment]
Thanks! It seems could be added as one of the post-processing utils. You can submit a PR so that you would be one of the contributors, or we can do it for you.

**Comment by gaotongxiao** [comment]
BTW, could you also provide the link to the code? I could not find it in keras-ocr repo.

**Comment by YC7225** [comment]
it will be good if you can answer this question or provide me a data on that #257. Thanks!

**Comment by gaotongxiao** [comment]
Hi, thanks for your suggestion! Based on the idea you provided, we've implemented `stitch_boxes_into_lines()`. It has two parameters to tune to fit different types of scenes, but their default values should be fine in general. You can find the example usage here (https://github.com/open-mmlab/mmocr/blob/main/demo/ocr_image_demo.py). Besides, such a heuristic algorithm still has a large room to improve, and any constructive contribution is always appreciated.

**Comment by gaotongxiao** [comment]
> it will be good if you can answer this question or provide me a data on that #257. Thanks!

We currently don't have a plan to make an extensive comparison. But you are always welcome to be one of our contributors if you have made efforts on that :)

**Comment by YC7225** [comment]
Good work! @gaotongxiao.
