### ISSUE TITLE
tools/data/textdet/icdar_voncerter.py is really slow.

### ISSUE THREAD

**Issue by Bovey0809** [open-mmlab/mmocr#28]
Thanks for your great work. 
Here I came across an efficiency problem.
I'm trying to use the tools to convert my own dataset into coco format for text detection. It contains millions of images.
After playing with it for a while, I find out this line is extremely slow. https://github.com/open-mmlab/mmocr/blob/1d1cd9fd495d727b39148bc649c3af2a1ff367bc/tools/data/textdet/icdar_converter.py#L37
Do you have any ideas to make it faster? For my machine, the default backen for mmcv.imread is "cv2", but for 3500 images it takes a really long time (more than 10 mins) to read the images. I think it is helpful to read the images in paralle. Do you have any plan to update it? Thanks.

**Comment by innerlee** [comment]
For parallelism, there is a reference code here https://github.com/open-mmlab/mmediting/blob/master/tools/data/matting/comp1k/preprocess_comp1k_dataset.py

Do you want to parallelize it and make a pull request?

**Comment by innerlee** [comment]
Actually you can skip this line. It is used to check if there are orientation meta data in jpeg. This is not essential if you are not pursuing academic accuracy points

**Comment by Bovey0809** [comment]
> For parallelism, there is a reference code here https://github.com/open-mmlab/mmediting/blob/master/tools/data/matting/comp1k/preprocess_comp1k_dataset.py
> 
> Do you want to parallelize it and make a pull request?

Yes, I can try for a parallelize one, after that I may make a pull request.

**Comment by cuhk-hbsun** [comment]
ok, thanks, and we will improve it with your PR.
For train or test, you can download the annotation file from `docs/datasets.md` first

**Comment by Bovey0809** [comment]
We can simply wrap the function with the **mmcv.track_parallel_progress** function like this.

```python
def helper(img):
    if is_not_png(img):
        res = drop_orientation(img)
    else:
        res = img
    return res
```

```python
if nproc > 1:
        imgs_list = mmcv.track_parallel_progress(
            helper, imgs_list, nproc=nproc)
    else:
        imgs_list = [drop_orientation(f) if is_not_png(
            f) else f for f in imgs_list]
```
I didn't push a request, for I haven't written some unit tests, the code works fine for icdar_converte.py and totaltext_converter.py.
