### ISSUE TITLE
‘COCO’ object has no attribute 'cat_img_map'

### ISSUE THREAD

**Issue by MTRkeji** [open-mmlab/mmocr#280]
**Checklist**

1. ‘COCO’ object has no attribute 'cat_img_map'

**Describe the bug**
When I run `./tools/dist_train.sh configs/textrecog/seg/seg_r31_1by16_fpnocr_toy_dataset.py work_dirs/seg 1`,it reports this error.
![image](https://user-images.githubusercontent.com/36284900/121762269-67e40980-cb67-11eb-9478-113a7c1dd689.png)

**Reproduction**

1. `./tools/dist_train.sh configs/textdet/maskrcnn/mask_rcnn_r50_fpn_160e_icdar2015.py work_dirs/mask 1`

**Bug fix**
Substitute `from pycocotools.coco import COCO` for `from mmdet.datasets.api_wrappers import COCO` in mmocr.datasets.icdar_dataset.py.

**Comment by gaotongxiao** [comment]
Hi, thanks for the feedback! Since you've got the solution, you can submit a PR to be one of the contributors. We can also do the change if that's not convenient for you.

**Comment by innerlee** [comment]
@MTRkeji Please try mmdet 2.11.0 and see if it works.
