### ISSUE TITLE
End to End Detection and Recognition for Multiple Images in a folder

### ISSUE THREAD

**Issue by jkcg-learning** [open-mmlab/mmocr#283]
What is the code format to run the end to end Detection and Recognition for all images(say 100 images) in a local folder.

Documentation is not clear
---------------------------------------------------------------------------------------------------------------------------------------
(from readthedocs.io)

**Detection**

python demo/batch_image_demo.py configs/textdet/panet/panet_r18_fpem_ffm_600e_icdar2015.py https://download.openmmlab.com/mmocr/textdet/panet/panet_r18_fpem_ffm_sbn_600e_icdar2015_20210219-42dbe46a.pth save_results --images demo/demo_text_det.jpg demo/demo_text_det.jpg

**Recognition**

python demo/image_demo.py configs/textrecog/sar/sar_r31_parallel_decoder_academic.py https://download.openmmlab.com/mmocr/textrecog/sar/sar_r31_parallel_decoder_academic-dba3a4a3.pth save_results --images demo/demo_text_recog.jpg demo/demo_text_recog.jpg

------------------------------------------------------------------------------------------------------------------------------
(from getting started.md)

# for text detection
sh tools/test_imgs.sh ${CONFIG_FILE} ${CHECKPOINT_FILE} ${IMG_ROOT_PATH} ${IMG_LIST} ${RESULTS_DIR}

# for text recognition
sh tools/ocr_test_imgs.sh ${CONFIG_FILE} ${CHECKPOINT_FILE} ${IMG_ROOT_PATH} ${IMG_LIST} ${RESULTS_DIR}

-----------------------------------------------------------------------------------------------------------------------------
**End to End (Detection + Recognition)**

???

**All Images(instead of selected ones)***

???

**Comment by cuhk-hbsun** [comment]
Thanks for your feedback. Please refer to [demo doc](https://mmocr.readthedocs.io/en/latest/demo.html) for the usage of demo scripts. 
1. The `ocr_image_demo.py` supports one image for end2end inference now. If you want to test multiple images in a folder, you can modify the `ocr_image_demo.py` first. 
2. We will update scripts to support a single image or multiple images as soon as possible.
