### ISSUE TITLE
Low F1 score when running sdmgr_unet16_60e_wildreceipt.py

### ISSUE THREAD

**Issue by kyosocan** [open-mmlab/mmocr#286]
Everything is OK when runing the novisual version:
sh ./tools/dist_test.sh configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py ./model/sdmgr_unet16_60e_wildreceipt_20210520-f25bb5d6.pth 1 --eval macro_f1
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 472/472, 17.0 task/s, elapsed: 28s, ETA:  
{'macro_f1': 0.87005955}

But:

sh ./tools/dist_test.sh configs/kie/sdmgr/sdmgr_unet16_60e_wildreceipt.py ./model/sdmgr_unet16_60e_wildreceipt_20210520-f25bb5d6.pth 1 --eval macro_f1
Use load_from_local loader
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 472/472, 9.7 task/s, elapsed: 48s, ETA:     
**{'macro_f1': 0.07049084}**

Could you please help me?

**Comment by innerlee** [comment]
The wrong model was uploaded. @cuhk-hbsun I remembered that there was a similar issue?
