### ISSUE TITLE
How to train segocr on custom dataset?

### ISSUE THREAD

**Issue by mobassir94** [open-mmlab/mmocr#289]
by following the mmocr colab tutorial i was able to train SAR model on our custom bangla text recognition dataset, our custom dataset format is similar to toy dataset, as our dataset is very similar to Chinese and have dictionary as well so we add this extra line of code before training : 

cfg.label_convertor["dict_file"]="/home/apsisdev/IMPORTANT/banglasynthShort/bangla_dict.txt"

here is the full config thatwe  used for segocr : 
```

from mmcv import Config
from mmocr.datasets import build_dataset
from mmocr.models import build_detector
from mmocr.apis import train_detector
import os.path as osp

cfg = Config.fromfile('../configs/textrecog/seg/seg_r31_1by16_fpnocr_academic.py') #seg_r31_1by16_fpnocr_toy_dataset.py
from mmdet.apis import set_random_seed

# Set up working dir to save files and logs.
cfg.work_dir = '../outputs/recognizer_model'

# The original learning rate (LR) is set for 8-GPU training.
# We divide it by 8 since we only use one GPU.
cfg.optimizer.lr = 0.001 / 8
cfg.lr_config.warmup = None
# Choose to log training results every 128 images to reduce the size of log file. 
cfg.log_config.interval = 128

# Set seed thus the results are more reproducible
cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.gpu_ids = range(1)

# We can initialize the logger for training and have a look
# at the final config used for training
#
cfg.label_convertor["dict_file"]="/home/apsisdev/IMPORTANT/banglasynthShort/bangla_dict.txt"
print(f'Config:\n{cfg.pretty_text}')

cfg.model.label_convertor["dict_file"] = "/home/apsisdev/IMPORTANT/banglasynthShort/bangla_dict.txt"
cfg.gt_label_convertor["dict_file"] = "/home/apsisdev/IMPORTANT/banglasynthShort/bangla_dict.txt"

cfg.data.train.datasets[0].pipeline[6].label_convertor["dict_file"] = "/home/apsisdev/IMPORTANT/banglasynthShort/bangla_dict.txt"

cfg.train_pipeline[6].label_convertor["dict_file"] = "/home/apsisdev/IMPORTANT/banglasynthShort/bangla_dict.txt" #SegConvertor
cfg.train_img_root = "/home/apsisdev/IMPORTANT/"
cfg.train.pipeline[6].label_convertor["dict_file"] = "/home/apsisdev/IMPORTANT/banglasynthShort/bangla_dict.txt" 

cfg.train_img_prefix = '/home/apsisdev/IMPORTANT/banglasynthShort/'
cfg.train_ann_file = '/home/apsisdev/IMPORTANT/banglasynthShort/label.txt'


cfg.train.ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"
cfg.train.img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"

cfg.test1.ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"
cfg.test1.img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"

cfg.test2.ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"
cfg.test2.img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"

cfg.test3.ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"
cfg.test3.img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"

cfg.test4.ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"
cfg.test4.img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"


cfg.test_prefix = '/home/apsisdev/IMPORTANT/banglasynthShort/'
cfg.test_img_prefix1 =  '/home/apsisdev/IMPORTANT/banglasynthShort/'
cfg.test_img_prefix2 = '/home/apsisdev/IMPORTANT/banglasynthShort/'
cfg.test_img_prefix3 = '/home/apsisdev/IMPORTANT/banglasynthShort/'
cfg.test_img_prefix4 = '/home/apsisdev/IMPORTANT/banglasynthShort/'

cfg.test_ann_file1 = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"
cfg.test_ann_file2 = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"
cfg.test_ann_file3 = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"
cfg.test_ann_file4 = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"


cfg.prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/"
cfg.train.img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"
cfg.train.ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"




cfg.data.train.datasets[0].img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"
cfg.data.train.datasets[0].ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt" 

cfg.data.test.datasets[0].img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"
cfg.data.test.datasets[0].ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"

cfg.data.val.datasets[0].img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"
cfg.data.val.datasets[0].ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"




cfg.data.test.datasets[1].img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"
cfg.data.test.datasets[1].ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"

cfg.data.val.datasets[1].img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"
cfg.data.val.datasets[1].ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"



cfg.data.test.datasets[2].img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"
cfg.data.test.datasets[2].ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"

cfg.data.val.datasets[2].img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"
cfg.data.val.datasets[2].ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"



cfg.data.test.datasets[3].img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"
cfg.data.test.datasets[3].ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"

cfg.data.val.datasets[3].img_prefix = "/home/apsisdev/IMPORTANT/banglasynthShort/imgs"
cfg.data.val.datasets[3].ann_file = "/home/apsisdev/IMPORTANT/banglasynthShort/label.txt"



cfg.data.samples_per_gpu = 32
#cfg.data.workers_per_gpu = 8



#cfg.data.train.datasets.img_prefix = "/home/apsisdev/IMPORTANT/banglasynth/imgs"
print(f'Config:\n{cfg.pretty_text}')


# Build dataset
datasets = [build_dataset(cfg.data.train)]

# Build the detector
model = build_detector(
    cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

# Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_detector(model, datasets, cfg, distributed=False, validate=True)

torch.cuda.empty_cache()
gc.collect()


```
and we get the following error message log that runs like infinite loop : 

/home/apsisdev/IMPORTANT/mmocr/mmocr/apis/train.py:74: UserWarning: config is now expected to have a `runner` section, please set `runner` in your config.
  warnings.warn(
2021-06-16 14:06:13,672 - mmocr - INFO - Start running, host: apsisdev@ML, work_dir: /home/apsisdev/IMPORTANT/mmocr/outputs/recognizer_model
2021-06-16 14:06:13,673 - mmocr - INFO - workflow: [('train', 1)], max: 5 epochs
prepare index 20269 with error Extra data: line 1 column 6 (char 5)
load index 20269 with error Extra data: line 1 column 6 (char 5)
prepare index 16735 with error Extra data: line 1 column 6 (char 5)prepare index 20270 with error Extra data: line 1 column 6 (char 5)

load index 20270 with error Extra data: line 1 column 6 (char 5)load index 16735 with error Extra data: line 1 column 6 (char 5)

**Comment by mobassir94** [comment]
we also tried to train with toy_dataset.py file like this : 
```

cfg = Config.fromfile('../configs/textrecog/seg/seg_r31_1by16_fpnocr_toy_dataset.py') #seg_r31_1by16_fpnocr_toy_dataset.py seg_r31_1by16_fpnocr_academic.py

# Set up working dir to save files and logs.
cfg.work_dir = '../outputs/recognizer_model'

# The original learning rate (LR) is set for 8-GPU training.
# We divide it by 8 since we only use one GPU.
cfg.optimizer.lr = 0.001 / 8
cfg.lr_config.warmup = None
# Choose to log training results every 128 images to reduce the size of log file. 
cfg.log_config.interval = 128

# Set seed thus the results are more reproducible
cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.gpu_ids = range(1)

# We can initialize the logger for training and have a look
# at the final config used for training
#
cfg.label_convertor["dict_file"]="/home/apsisdev/IMPORTANT/banglasynthShort/bangla_dict.txt"
print(f'Config:\n{cfg.pretty_text}')


cfg.prefix = "/home/apsisdev/IMPORTANT/banglasynth/"
cfg.train.img_prefix = "/home/apsisdev/IMPORTANT/banglasynth/imgs"
cfg.train.ann_file = "/home/apsisdev/IMPORTANT/banglasynth/label.txt"


cfg.test.ann_file = "/home/apsisdev/IMPORTANT/banglasynth/label.txt"
cfg.test.img_prefix = "/home/apsisdev/IMPORTANT/banglasynth/imgs"



cfg.data.train.datasets[0].img_prefix = "/home/apsisdev/IMPORTANT/banglasynth/imgs"
cfg.data.train.datasets[0].ann_file = "/home/apsisdev/IMPORTANT/banglasynth/label.txt" 

cfg.data.test.datasets[0].img_prefix = "/home/apsisdev/IMPORTANT/banglasynth/imgs"
cfg.data.test.datasets[0].ann_file = "/home/apsisdev/IMPORTANT/banglasynth/label.txt"

cfg.data.val.datasets[0].img_prefix = "/home/apsisdev/IMPORTANT/banglasynth/imgs"
cfg.data.val.datasets[0].ann_file = "/home/apsisdev/IMPORTANT/banglasynth/label.txt"


cfg.data.samples_per_gpu = 128
#cfg.data.workers_per_gpu = 8



#cfg.data.train.datasets.img_prefix = "/home/apsisdev/IMPORTANT/banglasynth/imgs"
print(f'Config:\n{cfg.pretty_text}')

from mmocr.datasets import build_dataset
from mmocr.models import build_detector
from mmocr.apis import train_detector
import os.path as osp

# Build dataset
datasets = [build_dataset(cfg.data.train)]

# Build the detector
model = build_detector(
    cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

# Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))


train_detector(model, datasets, cfg, distributed=False, validate=True)

torch.cuda.empty_cache()
gc.collect()
```
and faced this error : 

/home/apsisdev/IMPORTANT/mmocr/mmocr/apis/train.py:74: UserWarning: config is now expected to have a `runner` section, please set `runner` in your config.
  warnings.warn(
2021-06-16 14:10:14,646 - mmocr - INFO - Start running, host: apsisdev@ML, work_dir: /home/apsisdev/IMPORTANT/mmocr/outputs/recognizer_model
2021-06-16 14:10:14,646 - mmocr - INFO - workflow: [('train', 1)], max: 5 epochs
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

~/IMPORTANT/mmocr/mmocr/apis/train.py in train_detector(model, dataset, cfg, distributed, validate, timestamp, meta)
    147     elif cfg.load_from:
    148         runner.load_checkpoint(cfg.load_from)
--> 149     runner.run(data_loaders, cfg.workflow)

~/anaconda3/envs/ocr/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py in run(self, data_loaders, workflow, max_epochs, **kwargs)
    123                     if mode == 'train' and self.epoch >= self._max_epochs:
    124                         break
--> 125                     epoch_runner(data_loaders[i], **kwargs)
    126 
    127         time.sleep(1)  # wait for some hooks like loggers to finish

~/anaconda3/envs/ocr/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py in train(self, data_loader, **kwargs)
     45         self.call_hook('before_train_epoch')
     46         time.sleep(2)  # Prevent possible deadlock during epoch transition
---> 47         for i, data_batch in enumerate(self.data_loader):
     48             self._inner_iter = i
     49             self.call_hook('before_train_iter')

~/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/utils/data/dataloader.py in __next__(self)
    515             if self._sampler_iter is None:
    516                 self._reset()
--> 517             data = self._next_data()
    518             self._num_yielded += 1
    519             if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1197             else:
   1198                 del self._task_info[idx]
-> 1199                 return self._process_data(data)
   1200 
   1201     def _try_put_index(self):

~/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1223         self._try_put_index()
   1224         if isinstance(data, ExceptionWrapper):
-> 1225             data.reraise()
   1226         return data
   1227 

~/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/_utils.py in reraise(self)
    427             # have message field
    428             raise self.exc_type(message=msg)
--> 429         raise self.exc_type(msg)
    430 
    431 

TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

**Comment by cuhk-hbsun** [comment]
@mobassir94 
1. For Q1, please set `cfg.data.train.datasets[0]['test_mode'] = True`to see what the real error is instead of that catched by `try...except`.
2. For Q2, how `cfg.data.train.datasets[0].ann_file` is like? You can use [train_ann_file](https://github.com/open-mmlab/mmocr/blob/main/tests/data/ocr_char_ann_toy_dataset/instances_train.txt) to have a try first, which is used in [seg_r31_1by16_fpnocr_toy_dataset.py](https://github.com/open-mmlab/mmocr/blob/main/configs/textrecog/seg/seg_r31_1by16_fpnocr_toy_dataset.py)

**Comment by mobassir94** [comment]
last time i saw your comment in some other issue where you mentioned annotation for text recognition will be like the toy dataset,my dataset annotation is exactly like toy dataset dataset for example : 
0.png প্রত্যেকদিন
1.png ম্পে
2.png শঙ্কামুক্তভাবে
3.png আছাদের

i was able to train SAR and robustscanner with this annotation,so i think for segocr i need different annotation like this : https://github.com/open-mmlab/mmocr/blob/main/tests/data/ocr_char_ann_toy_dataset/instances_train.txt

**Comment by cuhk-hbsun** [comment]
> last time i saw your comment in some other issue where you mentioned annotation for text recognition will be like the toy dataset,my dataset annotation is exactly like toy dataset , for example :
> 0.png প্রত্যেকদিন
> 1.png ম্পে
> 2.png শঙ্কামুক্তভাবে
> 3.png আছাদের
> 
> i was able to train SAR and robustscanner with this annotation,so i think for segocr i need different annotation like this : https://github.com/open-mmlab/mmocr/blob/main/tests/data/ocr_char_ann_toy_dataset/instances_train.txt

Yes, `SegOCR` need character-level box annotation.

**Comment by mobassir94** [comment]
hi @innerlee and @cuhk-hbsun we have prepared character-level box annotation for segocr and now i am able to train segocr
i am training segocr on 300000 images and testing on 1000 images but after 19 epoch i get result like this : 

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1000/1000, 99.9 task/s, elapsed: 10s, ETA:     0s2021-07-07 16:04:06,186 - mmocr - INFO - 
Evaluateing /home/apsisdev/IMPORTANT/BanglaSynthShort/test/instances_test.txt with 1000 images now
2021-07-07 16:04:06,193 - mmocr - INFO - Saving checkpoint at 19 epochs
2021-07-07 16:04:07,025 - mmocr - INFO - Epoch(val) [19][4688]	0_word_acc: 0.0080, 0_word_acc_ignore_case: 0.0080, 0_word_acc_ignore_case_symbol: 1.0000, 0_char_recall: 0.0000, 0_char_precision: 0.0000, 0_1-N.E.D: 1.0000
i have 2 questions : 
1. what are 0_word_acc,0_word_acc_ignore_case and 0_word_acc_ignore_case_symbol and why they are very low always?i am training segocr on custom bangla dataset where dataset annotation is verys similar to chinese dataset
2. what are 0_char_recall: 0.0000, 0_char_precision: 0.0000, 0_1-N.E.D: 1.0000? and why i always get 0_char_recall,0_char_precision 0.0000 and it's true for all other rcognition model i tried from this repo,,what can cause this issue?
please let me know what information i can provide so that you can help me

i am using seg_r31_1by16_fpnocr_academic.py for training : 

_base_ = ['../../_base_/default_runtime.py']

# optimizer
optimizer = dict(type='Adam', lr=1e-4)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[3, 4])
total_epochs = 5

label_convertor = dict(
    type='SegConvertor', dict_file="/home/apsisdev/IMPORTANT/BanglaSynthShort/bangla_dict.txt",  with_unknown=True, lower=True)

model = dict(
    type='SegRecognizer',
    backbone=dict(
        type='ResNet31OCR',
        layers=[1, 2, 5, 3],
        channels=[32, 64, 128, 256, 512, 512],
        out_indices=[0, 1, 2, 3],
        stage4_pool_cfg=dict(kernel_size=2, stride=2),
        last_stage_pool=True),
    neck=dict(
        type='FPNOCR', in_channels=[128, 256, 512, 512], out_channels=256),
    head=dict(
        type='SegHead',
        in_channels=256,
        upsample_param=dict(scale_factor=2.0, mode='nearest')),
    loss=dict(
        type='SegLoss', seg_downsample_ratio=1.0, seg_with_loss_weight=True),
    label_convertor=label_convertor)

find_unused_parameters = True

img_norm_cfg = dict(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])

gt_label_convertor = dict(
    type='SegConvertor', dict_file="/home/apsisdev/IMPORTANT/BanglaSynthShort/bangla_dict.txt",  with_unknown=True, lower=True)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='RandomPaddingOCR',
        max_ratio=[0.15, 0.2, 0.15, 0.2],
        box_type='char_quads'),
    dict(type='OpencvToPil'),
    dict(
        type='RandomRotateImageBox',
        min_angle=-17,
        max_angle=17,
        box_type='char_quads'),
    dict(type='PilToOpencv'),
    dict(
        type='ResizeOCR',
        height=64,
        min_width=64,
        max_width=512,
        keep_aspect_ratio=True),
    dict(
        type='OCRSegTargets',
        label_convertor=gt_label_convertor,
        box_type='char_quads'),
    dict(type='RandomRotateTextDet', rotate_ratio=0.5, max_angle=15),
    dict(type='ColorJitter', brightness=0.4, contrast=0.4, saturation=0.4),
    dict(type='ToTensorOCR'),
    dict(type='FancyPCA'),
    dict(type='NormalizeOCR', **img_norm_cfg),
    dict(
        type='CustomFormatBundle',
        keys=['gt_kernels'],
        visualize=dict(flag=False, boundary_key=None),
        call_super=False),
    dict(
        type='Collect',
        keys=['img', 'gt_kernels'],
        meta_keys=['filename', 'ori_shape', 'img_shape'])
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='ResizeOCR',
        height=64,
        min_width=64,
        max_width=None,
        keep_aspect_ratio=True),
    dict(type='ToTensorOCR'),
    dict(type='NormalizeOCR', **img_norm_cfg),
    dict(type='CustomFormatBundle', call_super=False),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=['filename', 'ori_shape', 'img_shape'])
]

train_img_root = "/home/apsisdev/IMPORTANT/BanglaSynthShort/train"

train_img_prefix = "/home/apsisdev/IMPORTANT/BanglaSynthShort/train/imgs"

train_ann_file = "/home/apsisdev/IMPORTANT/BanglaSynthShort/train/instances_train.txt"

train = dict(
    type='OCRSegDataset',
    img_prefix=train_img_prefix,
    ann_file=train_ann_file,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineJsonParser', keys=['file_name', 'annotations', 'text'])),
    pipeline=train_pipeline,
    test_mode=False)

dataset_type = 'OCRDataset'
test_prefix = "/home/apsisdev/IMPORTANT/BanglaSynthShort/test"

test_img_prefix1 = "/home/apsisdev/IMPORTANT/BanglaSynthShort/test/imgs"


test_ann_file1 = "/home/apsisdev/IMPORTANT/BanglaSynthShort/test/instances_test.txt"


test1 = dict(
    type=dataset_type,
    img_prefix=test_img_prefix1,
    ann_file=test_ann_file1,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=test_pipeline,
    test_mode=True)

data = dict(
    samples_per_gpu=16,
    workers_per_gpu=2,
    train=dict(type='ConcatDataset', datasets=[train]),
    val=dict(type='ConcatDataset', datasets=[test1]),
    test=dict(type='ConcatDataset', datasets=[test1]))

evaluation = dict(interval=1, metric='acc')

have prepared all the dataset exactly like this : https://github.com/open-mmlab/mmocr/tree/main/tests/data

**Comment by gaotongxiao** [comment]
Hi @mobassir94 ,

The comments here should answer your first question (https://github.com/open-mmlab/mmocr/blob/1a5a880abb8703556f496cd794f1962cfec6c69c/mmocr/core/evaluation/ocr_metric.py#L92).

Here we ignore non-alphanumeric and non-Chinese characters for evaluation (https://github.com/open-mmlab/mmocr/blob/1a5a880abb8703556f496cd794f1962cfec6c69c/mmocr/core/evaluation/ocr_metric.py#L48), and that's why the evaluation metrics failed on your dataset. You can modify the regular expression to support Bangla characters.

**Comment by mobassir94** [comment]
you are awesome @gaotongxiao ,
thank you
