### ISSUE TITLE
基于图神经网络的通用关键信息提取算法SDMG-R,怎么快速使用呢， 文档里好像没有写这部分的推理或者训练步骤

### ISSUE THREAD

**Issue by aishangmaxiaoming** [open-mmlab/mmocr#29]

**Comment by innerlee** [comment]
Thanks for your interest, We will add a demo code next week :)

**Comment by cuhk-hbsun** [comment]
hello, 
1. please download the dataset `wildreceipt` according to docs/datasets.md, and put (or link) it to data/wildreceipt
2. for test: download model by the link in config README; test the model with ./tools/dist_test.sh
3. for train: use ./tools/dist_train.sh
4. Just one GPU is ok for step2 and step3

**Comment by aishangmaxiaoming** [comment]
> hello,
> 
> 1. please download the dataset `wildreceipt` according to docs/datasets.md, and put (or link) it to data/wildreceipt
> 2. for test: download model by the link in config README; test the model with ./tools/dist_test.sh
> 3. for train: use ./tools/dist_train.sh
> 4. Just one GPU is ok for step2 and step3

嗯嗯谢谢，现在wildreceipt数据和 model都下载完了，输入和输出是什么呢，即运行的命令行是怎样的，inputdata怎么传进去。

**Comment by cuhk-hbsun** [comment]
1. pls refer to docs/getting_started.md for the usage of dist_train.sh and dist_test.sh
2. data is used by config file.
3. for example, test with `wildreceipt` data and ckpt you download,
./tools/dist_test.sh configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py <checkpoint_path> 1 --eval macro_f1

**Comment by cuhk-hbsun** [comment]
And to visualize the results,
sh tools/kie_test_imgs.sh configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py <checkpoint_path> <output_dir>

**Comment by cuhk-hbsun** [comment]
fix
