### ISSUE TITLE
Epoch [1] [1000 / 2795314] -- > Where is the number of 2795314 iterations modified? It's too long to iterate 200 times in training.

### ISSUE THREAD

**Issue by gittjob** [open-mmlab/mmocr#301]

**Comment by cuhk-hbsun** [comment]
@gittjob Pls give the following information:
1. the total number of training images
2. batch size per GPU
3. number of GPUs

**Comment by gittjob** [comment]
I can't find where to modify this parameter,Please help me.

**Comment by gittjob** [comment]
thank you .

**Comment by cuhk-hbsun** [comment]
fixed by change batch_size
