### ISSUE TITLE
TensorBoard Integration

### ISSUE THREAD

**Issue by amitbcp** [open-mmlab/mmocr#308]
Sorry I am still new to the open-mmlab environment, and have a question that is it possible to integrate TensorBoard or Similar visualization/profilers in the training process for KIE?

**Comment by innerlee** [comment]
How about putting `dict(type='TensorboardLoggerHook')` into the log_config/hooks list in the config file?

**Comment by cuhk-hbsun** [comment]
@amitbcp 
modify [log_config](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/default_runtime.py#L3)
from
```python
log_config = dict(interval=5,  hooks=[dict(type='TextLoggerHook')])
```

to

```python
log_config = dict(
    interval=5,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])
```

**Comment by amitbcp** [comment]
Thanks @innerlee @cuhk-hbsun thanks for the reply. I went ahead checked the TensorboardLoggerHook in mmcv to understand it. But was not able to figure out on how to add the model graph while logging in TensorBoard?

**Comment by amitbcp** [comment]
Closing this issue as Tensorboard Loggin works. Would add the request for model visualisation in the roadmap ticket.
