### ISSUE TITLE
KIE demo

### ISSUE THREAD

**Issue by innerlee** [open-mmlab/mmocr#312]

**Comment by manjrekarom** [comment]
Is this a development goal? If so I have written a kie_image_demo.py script to test out my own receipts with SDMG-R. 
I might submit a pull request if needed.

**Comment by innerlee** [comment]
Yeah it is on my todo list, but I haven't got time 😢 Contributions are great!

**Comment by shane-avh** [comment]
@manjrekarom Would love to see your PR 🙏

**Comment by alexander-soare** [comment]
@manjrekarom where might one find this demo please?
