### ISSUE TITLE
how to deal a custom dataset with arbitrary coordinate points？

### ISSUE THREAD

**Issue by FFoCC** [open-mmlab/mmocr#315]
I want to use my own data set to train the text detection model. My data set contains text of arbitrary shape, so the number of coordinates of each text may not be certain. Could you please tell me how to process the data set?

**Comment by mobassir94** [comment]
yeah i am also struggling with text detection models and mentioned that here : https://github.com/open-mmlab/mmocr/issues/314
we need demo script for text detection

**Comment by cuhk-hbsun** [comment]
Thanks for your feedback. Just prepare your annotation_file and dataset as mentioned in [TextDetDataset](https://github.com/open-mmlab/mmocr/blob/main/docs/getting_started.md#textdetdataset)

The value of `segmentation` can be any number of points (>=3).
`"bbox": [min_x, min_y, w, h], "segmentation": [[x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, ...]]`

**Comment by FFoCC** [comment]
@mobassir94 Thank you!
and 
@cuhk-hbsun Thank you！But when I was training fcenet, I encountered the following problems.Is it about the number of points?
![points_error](https://user-images.githubusercontent.com/35954830/123778380-9e5daa80-d903-11eb-9ad2-1f1cfeeab76f.png)

**Comment by FFoCC** [comment]
Thank you！
