### ISSUE TITLE
".txt" format ground truth file support for TOTAL-TEXT data 

### ISSUE THREAD

**Issue by mnansary** [open-mmlab/mmocr#318]
# ** COCO-Format / Instances.json creation  from .txt format ground truth for Total-Text Format data **

**Motivation**
This feature will use ".txt" format ground truth data instead of  ".mat"  data.  
* While creating ```custom dataset```  in "total-text" format, it's inconvenient to use Matlab for creating the ground Truth FIles. 

**Related resources**
the task can be achieved through simple steps:
* The folder structure remains the same as it is in the documentation. But now under the **annotations folder**, instead of ".mat"  files there will be ".txt" files
* The format [here](https://github.com/mnansary/mmocr/blob/main/tools/data/textdet/totaltext_converter.py#L49) in line 49 and 57 ".mat" will change to ".txt"
*  Instead of using a mat file reader, like this in code 

```python
    data = scio.loadmat(gt_path)
    if split == 'training':
        data_polygt = data['polygt']
    elif split == 'test':
        data_polygt = data['polygt']
```

the  following part can be used:

```python

   if split == 'training':
        data_polygt=[]
        with open(gt_path,"r") as f:
            data_polygt=f.readlines()    
        #data_polygt = data['polygt']
    elif split == 'test':
        data_polygt=[]
        with open(gt_path,"r") as f:
            data_polygt=f.readlines()  
```
* The X, Y, and word data can be retrieved as follows

```python
    # change
    parts=lines.split(",")
    X=parts[0].split(":")[-1].strip().replace("[","").replace("]","").split()
    X=np.array([[int(x) for x in X]])
    
   # chnage
    Y=parts[1].split(":")[-1].strip().replace("[","").replace("]","").split()
    Y=np.array([[int(y) for y in Y]])
   

   point_num = len(X[0])
    
   # change
    word=[parts[-1].split(":")[-1].strip().replace("[","").replace("]","").replace("u'","").replace("'","")]
```
**Additional context**
I can create a separate file for handling  ".txt" format ground truth

**Comment by cuhk-hbsun** [comment]
Thanks a lot. You can contribute by a pull request to modify the related scripts to support both `mat` and `txt` formats, with additional args like:
`parser.add_argument('label_format', help='Format of label format, can be either "txt" or "mat"')`

**Comment by gaotongxiao** [comment]
Thanks for your contribution! I've tested your script on totaltext and fixed two problems with it. You can find my revised version here (https://gist.github.com/gaotongxiao/8e655495db13199418a5886705abd1e2) Hope that helps!

**Comment by mnansary** [comment]
dear @gaotongxiao  the script you shared is actually the initial script I wrote for solving the problem [here](https://github.com/open-mmlab/mmocr/issues/314) in issue number 314. Mobassir Hossain is actually my teammate and he created the issue before me. :3 
There are a lot if problems with that version. For example: 
```python
# chnage
        Y = parts[1].split(":")[-1].strip()
        Y = np.array(Y)
        Y = parts[0].split(":")[-1].strip()
        Y = Y.replace("[", "")
        Y = Y.replace("]", "")
        Y = Y.split()
        Y = [int(y) for y in Y]
        Y = np.array([Y])
```
Here, ``` Y = parts[0].split(":")[-1].strip()``` if Y is from parts[0] , then how can ```X = parts[0].split(":")[-1].strip()``` also be parts[0]?[check these two lines](https://gist.github.com/gaotongxiao/8e655495db13199418a5886705abd1e2#file-totaltext_convert-py-L116)

Moreover, the word calculation is completely wrong by any margin imaginable [And this was the original problem I was trying to look for as a solution for 314 :3  ]: 
If you check with a ".mat" data and a ".txt" data according to that code words[0] will always be ```[``` this second bracket. Not a single time the word variable will get any valid word string. The error Mobassir was facing was because of these problems :3 

There is also another minor issue as well, replacing "u" with an empty string does not work for English. What happens in the text file is that the Unicode enforcing u token is treated as a string itself. I.e-  [u'WORD'], here [,u,' symbols are treated as a string. The only way to solve this is to replace this "u followed by a single quote"   i.e  ```" u' "```. Hope its clarifies all the issues. Thanks

**Comment by gaotongxiao** [comment]
Yeah I know you're in the same team :) I tested the original script locally on totaltext and found it failed at two points. First there were two typos in the annotation filenames (ploy -> poly). Second this script breaks when processing the test set since they wrote some annotations into two lines (e.g., test/poly_gt_img621.txt), so I modified part of its logic accordingly (L103-110). I haven't tested the script thoroughly and these are just some suggested changes. A more strict reviewing process will be conducted when you created a PR.

**Comment by mnansary** [comment]
# About the PR
Dear @gaotongxiao 
* I have followed the contributing instructions 
* The only file I needed was / I actually changed is ```tools/data/textdet/totaltext_converter.py```
* all pre-commits have been passed
While testing: (i.e pytest tests): errors are coming from the following files (which i did not use or modify in any way)  
* tests/test_core/test_deploy_utils.py
* tests/test_utils/test_box.py 
PLEASE see the attached image for : 
* ```git status```
* ```pre-commit run --all-files```
* ```pytest tests```
Should I ignore these errors an proceed with the PR?(i.e go to the next steps)
![Screenshot from 2021-06-24 18-00-57](https://user-images.githubusercontent.com/22679832/123260000-ebfaa180-d516-11eb-88a6-c6ac8f6ca34d.png)

**Comment by mnansary** [comment]
I am closing this issue as a PR already exists for the same work [here](https://github.com/open-mmlab/mmocr/pull/324)
My work is available here: https://gist.github.com/mnansary/2c052d9ef0301295757526e1d8b3e463
Thanks for your help, really appreciate it
