### ISSUE TITLE
Improve onnx test 

### ISSUE THREAD

**Issue by innerlee** [open-mmlab/mmocr#320]
* typo
![image](https://user-images.githubusercontent.com/9464825/123212152-fefd7980-d4f6-11eb-932e-55a0240a8b52.png)

* Make sure temp files in test are properly cleaned.
![image](https://user-images.githubusercontent.com/9464825/123212256-248a8300-d4f7-11eb-90cc-ea4a0f2a2f57.png)

**Comment by innerlee** [comment]
@AllentDan

**Comment by AllentDan** [comment]
Resolved and THX.
