### ISSUE TITLE
Error of training FCENet

### ISSUE THREAD

**Issue by silent357** [open-mmlab/mmocr#329]
Hi, I encounter this error when I train FCENet following the instructions. Could you please help me solve this issue?

![image](https://user-images.githubusercontent.com/68524154/123622378-bae3df00-d83e-11eb-8f10-1c7d0a94caae.png)

**Comment by innerlee** [comment]
dup https://github.com/open-mmlab/mmocr/issues/271

**Comment by silent357** [comment]
Hi, I updated pytorch version to 1.6.0 and addressed the problems mentioned above. However, I encounter another problem, as below. Do you have any ideas? Thank you.

![1](https://user-images.githubusercontent.com/68524154/123757925-06ef5c00-d8f1-11eb-9eaf-8399c9422732.png)
