### ISSUE TITLE
NaN losses for training FCENet on ICDAR2015

### ISSUE THREAD

**Issue by silent357** [open-mmlab/mmocr#332]
Hi, I train FCENet on ICDAR2015 but get NaN for all the losses. The training seems proper on CTW1500. Is there anything wrong?

**Comment by gaotongxiao** [comment]
Did you reinstall mmcv after you've updated PyTorch? Also, rerunning the training process might help as sometimes bad initialization may occur.

**Comment by innerlee** [comment]
It seems that FCENet needs more tests

**Comment by silent357** [comment]
> Did you reinstall mmcv after you've updated PyTorch? Also, rerunning the training process might help as sometimes bad initialization may occur.

Yes, I reinstalled mmcv after updating PyTorch. The NaN losses occur every time I run the FCENet training on ICDAR2015.

**Comment by silent357** [comment]
> It seems that FCENet needs more tests

Maybe.

**Comment by gaotongxiao** [comment]
Are you using `mmdet==1.13.0`? We only support `mmdet==1.11.0` at this time but will fix it soon.

**Comment by silent357** [comment]
I change the version of mmdet to 2.11.0 and it works! Thank you!

**Comment by silent357** [comment]
I have another question. I find that when I train an fcenet model with 2gpus, I cannot train other models with multiple gpus. Sometimes I cannot either test an fcenet model. However, it is okay to train a model with 1 gpu when I train an fcenet model with 2 gpus. The error is as below: 

![2](https://user-images.githubusercontent.com/68524154/123892791-d3164400-d98d-11eb-813f-fd0684e26e0c.png)

**Comment by innerlee** [comment]
You can modify the port number at https://github.com/open-mmlab/mmocr/blob/main/tools/dist_train.sh#L13

btw please post a new issue for new questions

**Comment by innerlee** [comment]
@gaotongxiao if you have interest, the default port number can be made random. Something like `$((12000 + $RANDOM % 20000))`

**Comment by silent357** [comment]
OK. Thank you!

**Comment by liangxiaoyun** [comment]
When I install mmdet==2.11.0, it occur an error: ModuleNotFoundError: No module named 'mmdet.datasets.api_wrappers'

**Comment by gaotongxiao** [comment]
@liangxiaoyun mmdet 2.11.0 has not been officially supported since 0.2.1. Please make sure your mmdet version fits the requirement [here](https://mmocr.readthedocs.io/en/latest/install.html)
