### ISSUE TITLE
hello,does mmocr support the following recognition of this character?

### ISSUE THREAD

**Issue by gittjob** [open-mmlab/mmocr#338]
![image](https://user-images.githubusercontent.com/82756842/123918851-dd990380-d9b6-11eb-9769-8908e346ac52.png)
![image](https://user-images.githubusercontent.com/82756842/123919061-19cc6400-d9b7-11eb-8b68-7917ee6bd63d.png)

**Comment by gaotongxiao** [comment]
Currently not
