### ISSUE TITLE
FCENET的fps是多少

### ISSUE THREAD

**Issue by WenmuZhou** [open-mmlab/mmocr#345]
如题

**Comment by Zyq-scut** [comment]
On SCUT-CTW1500 dataset, [fcenet](https://github.com/open-mmlab/mmocr/blob/main/configs/textdet/fcenet/fcenet_r50dcnv2_fpn_1500e_ctw1500.py) achieve about 20.8 fps with one 2080ti GPU. You can speed it up with smaller test size and larger score threshold.

**Comment by 6098669** [comment]
> On SCUT-CTW1500 dataset, [fcenet](https://github.com/open-mmlab/mmocr/blob/main/configs/textdet/fcenet/fcenet_r50dcnv2_fpn_1500e_ctw1500.py) achieve about 20.8 fps with one 2080ti GPU. You can speed it up with smaller test size and larger score threshold.

请问FPS是怎么测的呢，为什么我测的FCENet的FPS最高只有12
