### ISSUE TITLE
[Need help] [中文文档翻译] Chinese documentation 

### ISSUE THREAD

**Issue by gaotongxiao** [open-mmlab/mmocr#347]
Hi all,

We are asking for help from our community, hoping to provide Chinese documentation to all users. It's not difficult and here is the chance to be one of the contributors of MMOCR, an open-source rising star!

Here is a list of documentation needed to be translated:

- [ ] [docs/getting_started.md](https://github.com/open-mmlab/mmocr/blob/main/docs/getting_started.md)
- [x] [docs/install.md](https://github.com/open-mmlab/mmocr/blob/main/docs/install.md) (@A465539338)
- [x] [docs/datasets.md](https://github.com/open-mmlab/mmocr/blob/main/docs/datasets.md) (@doem97)
- [x] [docs/deployment.md](https://github.com/open-mmlab/mmocr/blob/main/docs/deployment.md) (@fatfishZhao)
- [ ] [demo/MMOCR_Tutorial.ipynb](https://github.com/open-mmlab/mmocr/blob/main/demo/MMOCR_Tutorial.ipynb) 
- [ ] [docs/demo.md](https://github.com/open-mmlab/mmocr/blob/main/demo/docs/ocr_demo.md)

Interested users can directly reply to this issue and tell us the documentation you would like to translate. Then, please read our guidence (will be announced later) before you finalize your translation and make the PR. Thank you for your interests and we really appreciate your contribution :)

# Guidence 
All the docs needed to be translated are now put in `docs_zh_CN/`. Upon finished, just create a PR and wait to see how your contribution makes the change. Additional info about the contribution process can be found at https://zhuanlan.zhihu.com/p/387116301 (written in Chinese).

Note: Some examples can be found in `demo/docs_zh_CN/`.

**Comment by doem97** [comment]
Thanks for the great works. Interested in `datasets.md` translation @gaotongxiao

**Comment by gaotongxiao** [comment]
> Thanks for the great works. Interested in `datasets.md` translation @gaotongxiao

Thanks! We'll share the link of guidance when it's ready.

**Comment by A465539338** [comment]
I have recently followed the instructions in `install.md` . I would be interested in `install.md` translation.

**Comment by gaotongxiao** [comment]
> I have recently followed the instructions in `install.md` . I would be interested in `install.md` translation.

Awesome! Just put you on the list.

**Comment by innerlee** [comment]
Add colab to the list

**Comment by gaotongxiao** [comment]
Hi @doem97 and @A465539338, complete guidance can now be found in the first post of this issue. Thanks!

**Comment by doem97** [comment]
> Hi @doem97 and @A465539338, complete guidance can now be found in the first post of this issue. Thanks!

Great, received with thanks. Update soon.

**Comment by fatfishZhao** [comment]
Hi, thanks for your great work. I just used the deployment tools and I would be interested in `deployment.md` translation.

**Comment by gaotongxiao** [comment]
@fatfishZhao Thanks for your interest! I've added you to the list.

**Comment by EugeneWong2002** [comment]
Hi! I am wondering if you guys still need translation help on this? If not, do you need any translation help anywhere else?

**Comment by Mountchicken** [comment]
Hi @EugeneWong2002 
Happy to hear that. We have recently added 18 new detection and recognition datasets, and we have updated the English documentation for the [detection](https://github.com/open-mmlab/mmocr/blob/main/docs/en/datasets/det.md) and [recognition](https://github.com/open-mmlab/mmocr/blob/main/docs/en/datasets/recog.md) datasets, but we haven't had time to update the Chinese documentation, so maybe you can help us out!

**Comment by EugeneWong2002** [comment]
@Mountchicken Sounds good. I'll work on them!

**Comment by Mountchicken** [comment]
Hi @EugeneWong2002
- Happy to hear that. We have recently added 18 new [detection](https://github.com/open-mmlab/mmocr/blob/main/docs/en/datasets/det.md) and [recognition](https://github.com/open-mmlab/mmocr/blob/main/docs/en/datasets/recog.md) datasets, and we have updated the English documentation for the detection and recognition datasets, but we haven't had time to update the Chinese documentation, so maybe you can help us out! 
- In addition to the dataset section that needs to be translated, we have other documents that need help as well, if you are interested.
- [model summary](https://github.com/open-mmlab/mmocr/blob/main/docs/en/model_summary.md)
- [tools](https://github.com/open-mmlab/mmocr/blob/main/docs/en/tools.md)
- [change log](https://github.com/open-mmlab/mmocr/blob/main/docs/en/changelog.md)
- etc
