### ISSUE TITLE
Integrate ABINet for Text Recognition

### ISSUE THREAD

**Issue by antoniolanza1996** [open-mmlab/mmocr#350]
**Describe the feature**
Paper title: Read Like Humans: Autonomous, Bidirectional and Iterative Language Modeling for Scene Text Recognition
Paper link: https://arxiv.org/pdf/2103.06495.pdf

**Motivation**
As you can see from table 6 in the paper, results are very promising. I think it could be interesting to integrate this model in MMOCR framework.

**Related resources**
- Source code: https://github.com/FangShancheng/ABINet
- [ABINet license file](https://github.com/FangShancheng/ABINet/blob/d3bfeec0042a23ba54357d4256c016f46c564201/LICENSE)
- cc @FangShancheng

**Comment by gaotongxiao** [comment]
Closing via #651
