### ISSUE TITLE
Single character text not detecting

### ISSUE THREAD

**Issue by Sasidev90** [open-mmlab/mmocr#354]
Hi,
Single character numbers are not detecting properly in 'psenet_r50_fpnf_600e_icdar2017.pth' unable to extract the numeric values, attached the sample image for your reference. Thanks in advance.
![C0831M_Feb2020_1_2_vv](https://user-images.githubusercontent.com/87021555/124704062-108c4b80-df11-11eb-94e4-c7421f0b0f17.png)

**Comment by cuhk-hbsun** [comment]
You may need to finetune the model on your own dataset. There is a large gap between your data and ICDAR dataset. 
Secondly, you can split the original image into several parts and test each part. The character is really small according to your image.

**Comment by Sasidev90** [comment]
Thanks for the update, I will check and revert the feedback.

**Comment by gaotongxiao** [comment]
Closing this issue as there is no update for months.
