### ISSUE TITLE
Can't download icdar_2013 train_label.txt

### ISSUE THREAD

**Issue by SiriusKY** [open-mmlab/mmocr#36]
I got error messages when trying to download [train_label.txt](https://download.openmmlab.com/mmocr/data/mixture/icdar_2013/train_label.txt) of icdar_2013 dataset.
```
<Error>
<Code>AccessDenied</Code>
<Message>
You have no right to access this object because of bucket acl.
</Message>
<RequestId>6070101B4EBCCF4B4201DC83</RequestId>
<HostId>download.openmmlab.com</HostId>
</Error>
```
I tried several times in different devices and the problem remains, is this still my network issue or something's wrong with the website? Thanks!

**Comment by cuhk-hbsun** [comment]
File not exists, will be fixed soon

**Comment by SiriusKY** [comment]
> File not exists, will be fixed soon

Thanks for your help! 

Just wanted to kindly remind you that as I tried, label files of some other datasets(icdar_2015, Syn90k, etc) are missing too.  : )

**Comment by cuhk-hbsun** [comment]
fixed, pls check and download again.

**Comment by SiriusKY** [comment]
> fixed, pls check and download again.

[shuffle_labels.txt](https://download.openmmlab.com/mmocr/data/mixture/Synth90k/shuffle_labels.txt) of `Syn90k` not exists, others are cool.

Thanks in advance!

**Comment by SiriusKY** [comment]
@cuhk-hbsun  Sorry for the omission, label.lmdb of [Syn90k](https://download.openmmlab.com/mmocr/data/mixture/Syn90k/label.lmdb) and [SynthText](https://download.openmmlab.com/mmocr/data/mixture/SynthText/label.lmdb) is still inaccessible, I didn't check these 2 files before last comment.

**Comment by innerlee** [comment]
@SiriusKY Thanks again, we will double check

**Comment by cuhk-hbsun** [comment]
> @cuhk-hbsun Sorry for the omission, label.lmdb of [Syn90k](https://download.openmmlab.com/mmocr/data/mixture/Syn90k/label.lmdb) and [SynthText](https://download.openmmlab.com/mmocr/data/mixture/SynthText/label.lmdb) is still inaccessible, I didn't check these 2 files before last comment.

sorry for the mistake,
you can download `label.txt` of Syn90k from https://download.openmmlab.com/mmocr/data/mixture/Syn90k/label.txt
and `label.txt` of SynthText from https://download.openmmlab.com/mmocr/data/mixture/SynthText/label.txt

And then, convert txt to lmdb by `python tools/data/utils/txt2lmdb.py -i <txt_label> -o <lmdb_label>`

We will upload the lmdb label file as soon as possible.

**Comment by SiriusKY** [comment]
> > @cuhk-hbsun Sorry for the omission, label.lmdb of [Syn90k](https://download.openmmlab.com/mmocr/data/mixture/Syn90k/label.lmdb) and [SynthText](https://download.openmmlab.com/mmocr/data/mixture/SynthText/label.lmdb) is still inaccessible, I didn't check these 2 files before last comment.
> 
> sorry for the mistake,
> you can download `label.txt` of Syn90k from https://download.openmmlab.com/mmocr/data/mixture/Syn90k/label.txt
> and `label.txt` of SynthText from https://download.openmmlab.com/mmocr/data/mixture/SynthText/label.txt
> 
> And then, convert txt to lmdb by `python tools/data/utils/txt2lmdb.py -i <txt_label> -o <lmdb_label>`
> 
> We will upload the lmdb label file as soon as possible.

Oh I see, thank you so much!
