### ISSUE TITLE
How to get class labels from KIE models

### ISSUE THREAD

**Issue by parulsingh23** [open-mmlab/mmocr#372]
I'm trying to get an understanding of the 'Key Information Extraction Models', and I'm able to run the following code in google colab:
`!python tools/kie_test_imgs.py configs/kie/sdmgr/sdmgr_unet16_60e_wildreceipt.py https://download.openmmlab.com/mmocr/kie/sdmgr/sdmgr_unet16_60e_wildreceipt_20210405-16a47642.pth --show-dir printingout`
Where an image file (at '/content/mmocr/printingout/IMG_20210629_110348654.jpg') provides class labels in the positions of the bounding box like so:
![Unknown](https://user-images.githubusercontent.com/55006754/126052043-ce055645-93ea-413d-8860-4d58b5f735fd.png)
 
However, I am unable to find any '.json' or '.txt' file clearly allocating the class labels to the respective bounding boxes. I even tried running the following with the 'no visual' (sdmgr_novisual) model:
`!python tools/kie_test_imgs.py configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py https://download.openmmlab.com/mmocr/kie/sdmgr/sdmgr_novisual_60e_wildreceipt_20210517-a44850da.pth --show-dir printingout/`

But this just outputs an 'ori_filename' missing key error. I am lost as to where I can get a file with the assigned class labels to the bounding boxes

The Traceback is:
```
File "tools/kie_test_imgs.py", line 123, in <module>
    main()
  File "tools/kie_test_imgs.py", line 119, in main
    test(model, data_loader, args.show, args.show_dir)
  File "tools/kie_test_imgs.py", line 47, in test
    out_file = osp.join(out_dir, img_meta['ori_filename'])
KeyError: 'ori_filename'
```

**Comment by adesgautam** [comment]
You can see bounding boxes, text and label in the train.txt and test.txt files. 
Also the classes are mentioned in class_list.txt.

**Comment by gaotongxiao** [comment]
@parulsingh23 BTW your unet model (sdmgr_unet16_60e_wildreceipt_20210405-16a47642.pth) is an outdated one which tends to output "others" class. You can download the latest one (https://download.openmmlab.com/mmocr/kie/sdmgr/sdmgr_unet16_60e_wildreceipt_20210520-7489e6de.pth) to correctly measure its performance.
