### ISSUE TITLE
lanms-proper

### ISSUE THREAD

**Issue by ASentry** [open-mmlab/mmocr#379]
lanms-proper现在有好的替代方案吗？windows没法安这个包

**Comment by innerlee** [comment]
Hi @ASentry , do you want to actually use the function, or simply try to install mmocr in windows?

**Comment by ASentry** [comment]
> Hi @ASentry , do you want to actually use the function, or simply try to install mmocr on windows?
I want to use other components, but the installation requires this package.But now I removed DRRG completely and it's fine.It would be better for the user to replace this package.

**Comment by innerlee** [comment]
Yeah its dup of https://github.com/open-mmlab/mmocr/issues/230 I will close this and we can continue discussion on that issue
