### ISSUE TITLE
txt2lmdb

### ISSUE THREAD

**Issue by lantx5** [open-mmlab/mmocr#384]
为什么用自带的txt2lmdb文件处理数据，会出现两个.mdb文件，以nrtr为例，应该怎么读取？

**Comment by gaotongxiao** [comment]
We refer to the directory that contains these two mdb files (`data.mdb` and `lock.mdb`) as lmdb dataset. Therefore, you can simply set the data path in NRTR's config file as the path to this directory and `LmdbLoader` should work.
