### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by SkotchZ** [open-mmlab/mmocr#385]
I`m trying to install mmocr and got stuck on these steps:

pip install -r requirements.txt
pip install -v -e . # or "python setup.py develop"
export PYTHONPATH=$(pwd):$PYTHONPATH

In first row pip trying to install polygon3 which is bindings for GPC(genereal polygon cliper library) which is not available since aug 2020. How to overcome these problem? Is there other way to install polygon3? Or may be i`m doing smth wrong ?

**Comment by gaotongxiao** [comment]
I installed polygon3 in a new environment but did not met this error. You can try to install MMOCR in a clean environment and see if the error persists. If that does not work, you may share your system specs and environment info here. Note that MMOCR may not support Windows or some older versions of python.

**Comment by SkotchZ** [comment]
Thanks for advice. Instaling in clean conda env helps me.
