### ISSUE TITLE
文字识别准确率和数据增强方面的问题

### ISSUE THREAD

**Issue by simplify23** [open-mmlab/mmocr#387]
想问一下，mmocr里复现的识别方法在使用数据集进行训练的时候是否使用了数据增强方面的方法呢（如colorjitter RandomAffine等）看代码似乎配置里并没有，但不同paper里似乎有一定的数据增强方法。如果使用了，统一的数据增强策略对模型的性能提升明显吗，期待确切的答案，非常感谢~

**Comment by cuhk-hbsun** [comment]
We didn't use data augmentations like color_jitter or random_affine during implementation, just following the original paper. 
I am not sure whether it will improve the performance or not on the academic dataset, but for other custom datasets, it is yes usually.
