### ISSUE TITLE
fcenet config

### ISSUE THREAD

**Issue by ASentry** [open-mmlab/mmocr#388]
Why are the settings for fcenet_r50_fpn_1500e_icdar2015.py and fcenet_r50dcnv2_fpn_1500e_ctw1500.py different?
```
    #fcenet_r50_fpn_1500e_icdar2015.py
    dict(
        type='FCENetTargets',
        fourier_degree=fourier_degree,
        level_proportion_range=((0, 0.4), (0.3, 0.7), (0.6, 1.0))),
```
```
   #fcenet_r50dcnv2_fpn_1500e_ctw1500.py
    dict(
        type='FCENetTargets',
        fourier_degree=fourier_degree,
        level_proportion_range=((0, 0.25), (0.2, 0.65), (0.55, 1.0))),
```
The settings in the paper are [0, 0.4], [0.3, 0.7], and [0.6, 1]，different datasets or dcn?

**Comment by gaotongxiao** [comment]
ping @Zyq-scut

**Comment by Zyq-scut** [comment]
Hi, I set different param to see whether it can improve the performance, but the result show that they are almost the same.

**Comment by ASentry** [comment]
> Hi, I set different param to see whether it can improve the performance, but the result show that they are almost the same.

What are the rules for setting the parameter img_scale of the test pipeline？How to set this parameter for the Total-text dataset?

**Comment by Zyq-scut** [comment]
> > Hi, I set different param to see whether it can improve the performance, but the result show that they are almost the same.
> 
> Thank you for your answer, I have one more question.
> What are the rules for setting the parameter img_scale of the test pipeline？How to set this parameter for the Total-text dataset? @Zyq-scut

There are no specific rules. Just try different param and find the best one.

**Comment by gaotongxiao** [comment]
I'm closing this issue as there is no further update.
