### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by lantx5** [open-mmlab/mmocr#389]
How to find the SVTP dataset?

**Comment by gaotongxiao** [comment]
https://mmocr.readthedocs.io/en/latest/datasets.html#text-recognition

**Comment by lantx5** [comment]
There are only annotated files, not pictures

**Comment by lantx5** [comment]
There are only annotation files, not pictures

**Comment by gaotongxiao** [comment]
The official link is down but you can find it at https://github.com/Jyouhou/Case-Sensitive-Scene-Text-Recognition-Datasets
