### ISSUE TITLE
The FCE-Net-ctw1500 log file is confusing.

### ISSUE THREAD

**Issue by williamking5** [open-mmlab/mmocr#390]
**Hi, I'm checking the log file of FCE-Net training process, but I am confused of the config file of FCE-net-ctw1500.**

**According to your official log json in your documentation [https://download.openmmlab.com/mmocr/textdet/fcenet/20210511_181328.log.json](https://download.openmmlab.com/mmocr/textdet/fcenet/20210511_181328.log.json), `samples_per_gpu=6`, `GPU 0, 1` and there are about 160 iterations each epoch. Hence the dataset size should be approximately `6 * 2 * 160 = 1920`. But as we know, the size of training part of ctw-1500 dataset is 1000.**

**The number of samples is 6 per GPU:**

![image](https://user-images.githubusercontent.com/16954932/126958585-17c9233a-e9e1-4705-b079-1c836de4a921.png)
**There are 2 GPU for training:**

![image](https://user-images.githubusercontent.com/16954932/126958684-0132f7ac-89e3-44cd-9003-d5fd8ea476f0.png)

**There are around 160 iterations each epoch:**
![image](https://user-images.githubusercontent.com/16954932/126959140-cc3e57ba-3c19-4696-9aa6-2eb3422b10bd.png)

I use the same config file to train on my own, finding the size is correct:

**There are 2 GPU for training:**
![image](https://user-images.githubusercontent.com/16954932/126959982-b8be5864-b45c-459b-8186-5c73e568831a.png)

**There are around 80 iterations each epoch:**
![image](https://user-images.githubusercontent.com/16954932/126959884-25f77cfc-c177-4021-9b03-740f122d606a.png)

**The number of samples is 6 per GPU**
![image](https://user-images.githubusercontent.com/16954932/126960158-52eaba7f-7a31-4d69-84c3-f31d5a5d6eae.png)

**Do you have any idea?**

**Comment by gaotongxiao** [comment]
We only used 1 GPU for training. `GPU 0,1: GeForce RTX 2080 Ti` only lists the GPUs available on the machine, but for the actual GPU(s) that we have used please refer to `gpu_ids`. In this example, `gpu_ids = [1]`, which means that we have used the GPU indexed as 1.

**Comment by williamking5** [comment]
@gaotongxiao Thank you for explanation!
