### ISSUE TITLE
Allow a way to specify configs dir globally

### ISSUE THREAD

**Issue by alexander-soare** [open-mmlab/mmocr#397]
User should be able to either provide the various functions/classes with a `config_dir`, or use an `export MMOCR_CONFIG_DIR`, or something like `mmocr.register_config_dir(path: str)`.

I would then grab all the configs and put them in `home/.mmocr_configs` and not have to worry about putting it in my projects.

Another use case might be that the project already has a `configs` folder used for another purpose and the user wishes to have mmocr configs in `mmocr_configs` instead.

If a user wishes to have a separate config folder for their own custom configs, in those cases they can explicitly specify it on a use-by-use basis.

**Motivation**
Working with the mmocr (or mmdet for that matter) in multiple projects can be a pain as one needs to copy the config into their project folder over and over. Moreover, it's not clear that it makes sense to use the name `configs` for the mmocr configs.

**Additional context**

One example is with `mmocr.utils.ocr.MMOCR`. There you can provide a `det_config` and a `recog_config` but you always have to change it depending on your `det` and `recog`. Could make it that a `config_dir` is provided without having to specify the exact file. But I think the env variable or global registration would be better.

**Comment by gaotongxiao** [comment]
First, thanks for raising this issue! However, I am quite confused - It seems that you want MMOCR to find configs given the path to the config folder, but which config file would the user want if there are more than 2 configs in the folder? If you simply do not want to put your config files everywhere, passing their absolution paths to MMOCR would also work. 
Let me know if I have misunderstood your point.

**Comment by alexander-soare** [comment]
@gaotongxiao Thanks for picking this up. So here's the use case:

I'm trying out various detection and recognition algorithms like this:
```
from mmocr.utils.ocr import MMOCR

ocr = MMOCR(det='DB_r50', recog='SAR')
```
And I am doing this in multiple projects because yesterday I was working with one client, and today I am working with another client.

Now MMOCR does [this](https://github.com/open-mmlab/mmocr/blob/a2af2b4d310bcfc6a6e7cfa934f23211a76ef4ee/mmocr/utils/ocr.py#L406-L408) to find the configs:
```
dir_path = str(Path.cwd())
if not recog_config:
    recog_config = dir_path + '/configs/textrecog/' + \
        textrecog_models[self.tr]['config']
```

So by default it looks at my current working directory. This is the part that I find not idea. Because it means:

1. I need to copy configs into each of my projects
2. I must call the folder "configs" and it must be in my working dir. This doesn't make sense for my project in most cases.

Your suggestion of passing the absolute paths like this works:

```
ocr = MMOCR(
    det='DB_r50', det_config='/home/alexander/Projects/mmocr/configs/textdet/dbnet/dbnet_r50dcnv2_fpnc_1200e_icdar2015.py',
    recog='SAR', recog_config='/home/alexander/Projects/mmocr/configs/textrecog/sar/sar_r31_parallel_decoder_academic.py',
    device=Config.device)
```

But isn't ideal for experimentation as I need to keep changing the config paths each time I want to test a different detection model or recognition model. It's also a bit redundant, as MMOCR should know the relative path (given a configs file) to the default config for each model.

**Comment by gaotongxiao** [comment]
Okay, so I guess something like
```
ocr = MMOCR(det='DB_r50', recog='SAR', config_dir='/home/alexander/Projects/mmocr/configs/')
```
is what you want? And users can test different models by just changing the names instead of lengthy paths.

**Comment by alexander-soare** [comment]
@gaotongxiao yep pretty much. Or the other alternatives are:

- `export MMOCR_CFG_DIR=/home/alexander/Projects/mmocr/configs/`
- `mmocr.set_config_dir('/home/alexander/Projects/mmocr/configs/'`

I'll leave that design choice with you though :) I think I've gotten the point across
