### ISSUE TITLE
Only use SyncBatchNorm for training

### ISSUE THREAD

**Issue by alexander-soare** [open-mmlab/mmocr#398]
SyncBatchNorm should only be used in training. This will avoid issues with CPU inference (I tried CPU inference with a few of the detection models and got `ValueError: SyncBatchNorm expected input tensor to be on GPU`). To achieve this, we should make use of the `convert_sync_batchnorm` class method of [nn.SyncBatchNorm](https://pytorch.org/docs/stable/generated/torch.nn.SyncBatchNorm.html). Here is an [example of how one would do this from the train script of the timm library](https://github.com/rwightman/pytorch-image-models/blob/d3f744065088ca9b6b3a0f968c70e90ed37de75b/train.py#L389-L400).

**Comment by gaotongxiao** [comment]
Sounds good! Before we have fixed it, a workaround is to replace SyncBN with BN in all the configs.
