### ISSUE TITLE
Performance of PSENET in training

### ISSUE THREAD

**Issue by parulsingh23** [open-mmlab/mmocr#399]
I'm training the PSENET on a dataset of 1267 images on Google Colab Pro (with samples_per_gpu=8). However, I've been running it for more than 18 hours (350+ epochs), and I've only achieved:
```hmean-iou:recall: 0.0003, hmean-iou:precision: 0.0004, hmean-iou:hmean: 0.0003```

I understand that Google Colab provides only 1 gpu, but it was mentioned in #391 that:
"You can increase the batch size by changing samples_per_gpu in the config file."

and the largest I can increase my samples_per_gpu is 8 in Google Colab (anything larger than that, I run into a CUDA out of memory error). I have the default learning params, set as:

```optimizer = dict(type='SGD', lr=1e-3, momentum=0.99, weight_decay=5e-4)```

I have trained CV models before on datasets of 120,000+ images that near training completion within 15 hours, yet here I am unable to even achieve a training accuracy difference within the thousandths decimal place after running for 18+ hours. I'm concerned that I may just be running the model incorrectly (please let me know if you think that is the reason for the poor training performance).

If this training time on Google Colab Pro is expected, then I'll probably look into using an EC2 instance on AWS that provides 8 gpu's to significantly speed things up. Do you have an idea of *how* much faster utilizing 8 gpus would be? And would I need to specify anything other than the `--gpus` and  `--gpu-ids` (in `tools/train.py`) to do this parallel training across 8 gpus? (ex. would I need to increase samples_per_gpu from 8 to 128 in the psenet's config file?)

I'm just confused about the general scope of training psenet: how fast I should expect training results to appear & how long that should take (<15 hours, 2 days, 1 week, etc.)?

**Comment by gaotongxiao** [comment]
How was your experiment on overfitting the test set? I would suggest you tuning the batch size and learning rate carefully.

FYI, we also have released training logs for all models, you can find PSENet's [here](https://mmocr.readthedocs.io/en/latest/textdet_models.html#psenet). We only used one GPU to train and it converged pretty fast under the **optimal hyperparameter setting**. You can compare the trend of loss and decide how to tune hyperparameters.
