### ISSUE TITLE
Why not produce a pipeline for text detection and channel recognition

### ISSUE THREAD

**Issue by LZZhideonbush** [open-mmlab/mmocr#40]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by jeffreykuang** [comment]
you mean a pipeline consists of text detection and text recognition?  We are planning to provide a test pipeline that contains the two for easy demonstration and evaluation.

**Comment by gaotongxiao** [comment]
We have provided `ocr.py` that supports end-to-end detection + recognition inference now. See its docs [here](https://mmocr.readthedocs.io/en/latest/demo.html)
