### ISSUE TITLE
[QUESTION] Am I forced to use MultiScaleFlipAug at test time?

### ISSUE THREAD

**Issue by alexander-soare** [open-mmlab/mmocr#402]
I'd like to do something like this:

```python
test_pipeline = [
    dict(type='LoadImageFromFile', color_type='color_ignore_orientation'),
    # dict(
    #     type='MultiScaleFlipAug',
    #     img_scale=(1333, 736),
    #     flip=False,
    #     transforms=[
    #         dict(type='Resize', img_scale=(1333, 736), keep_ratio=True),
    #         dict(type='Normalize', **img_norm_cfg),
    #         dict(type='Pad', size_divisor=32),
    #         dict(type='ImageToTensor', keys=['img']),
    #         dict(type='Collect', keys=['img']),
    #     ])
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img']),
]
```

Because I want to control the resizing myself prior to input to the model. This raises a `flip` `KeyError` and I've tried so many other combinations. Do I have to use MultiScaleFlipAug?

Leaving in the MultiScaleFlipAug but removing the `dict(type='Resize'...` ends up raising an `AssertionError` at some point `assert isinstance(scale_factor, np.ndarray)`.

**Comment by gaotongxiao** [comment]
Each module in the pipeline can add some meta-data to the data (as a new key-value pair) that might affect the following modules' decisions. If you want to remove a module from the pipeline, my suggestion is to look up its name in [MMdetection](https://mmdetection.readthedocs.io/en/latest/api.html#module-mmdet.datasets.pipelines) and [MMOCR](https://mmocr--406.org.readthedocs.build/en/406/api.html#module-mmocr.datasets.pipelines), read its code, and check if it adds any new entries to data. If so, you should write a custom module which at least adds these required keys back.

For your case, `MultiScaleFlipAug` adds `flip` to data that will be collected by `Collect` as one of the `meta_keys`. `MultiScaleFlipAug` also wraps the data into a list that is expected by the model. So you might at least write a module that does similar things as `MultiScaleFlipAug`. Don't forget to also add `scale_factor` to data as what `Resize` does.

See
[MultiScaleFlipAug](https://github.com/open-mmlab/mmdetection/blob/958252249dc7c1020ee2bae290c6a17348336b92/mmdet/datasets/pipelines/test_time_aug.py#L10), [Resize](https://github.com/open-mmlab/mmdetection/blob/958252249dc7c1020ee2bae290c6a17348336b92/mmdet/datasets/pipelines/transforms.py#L26) and [Collect](https://github.com/open-mmlab/mmdetection/blob/958252249dc7c1020ee2bae290c6a17348336b92/mmdet/datasets/pipelines/formating.py#L251)

**Comment by alexander-soare** [comment]
Thanks @gaotongxiao  I saw the KIE example which has a flip with probablity 0 in it, I think to make sure the flip key was present. I'll follow your advice.
