### ISSUE TITLE
Unable to recognize text consistently

### ISSUE THREAD

**Issue by parulsingh23** [open-mmlab/mmocr#410]
I've had some trouble apply MMOCR for text det + recog(using TextSnake & SAR), when simply passing in nearly identically specified bounding boxes to an MMOCR object for just text recog (using ONLY TextSnake) worked, and I'm not sure why.

Passing the image into `MMOCR(det=None, recog='SAR', recog_ckpt='sar_r31_parallel_decoder_academic-dba3a4a3.pth')`:
![Unknown-25](https://user-images.githubusercontent.com/55006754/128134690-9c40eb29-e3f5-4de8-841b-73cb77e3abab.png)
![Unknown-26](https://user-images.githubusercontent.com/55006754/128134796-48378f41-23b4-4e7d-a40d-875ce528e65b.png)
It correctly identified 4:11 and 04/18/21.

However, passing a very similar image into `MMOCR(det='TextSnake', recog='SAR', recog_ckpt='sar_r31_parallel_decoder_academic-dba3a4a3.pth')`:
![Unknown-28](https://user-images.githubusercontent.com/55006754/128135112-700c4bd2-fe42-4e52-9575-856adb1402d6.png)
It returns 'text': ['-', '18:12:1'].

The `MMOCR(det='TextSnake', recog='SAR')` simply fails to recognize all bounding boxes I pass to it and I'm not sure why it is. I had tried apply grayscale, blurring, thresholding to the latter, but I still fundamentally don't understand how applying text detection & text recognition doesn't return a correct result. Even then, for the latter MMOCR object, when I took out the `det = 'TextSnake'`, I got text identified as '04/18/', which is still very wrong. What am I missing here? Any feedback or ideas is greatly appreciated!

**Comment by gaotongxiao** [comment]
Unfortunately, our released text recognition models usually fail on recognizing images with too many blanks and characters. It's because the training data (SynthText and Syn90k) provide fine-grained annotations where each bounds a word without any blank and spaces, just like your first two images. We might need to augment datasets and retrain models to allow better tolerance of noises.

**Comment by parulsingh23** [comment]
Intersting, but even when the bounding boxes are around a text with no space I'm not able to get any text with the detection utilized. 
For `MMOCR(det='TextSnake', recog='SAR', recog_ckpt='sar_r31_parallel_decoder_academic-dba3a4a3.pth')` 
![Unknown-31](https://user-images.githubusercontent.com/55006754/128139309-149d15dc-4cb8-4a25-9d57-5eb97acd86b9.png)
![Unknown-30](https://user-images.githubusercontent.com/55006754/128139321-b48acebc-5d9c-4922-8afe-330d2b1377de.png)
![Unknown-29](https://user-images.githubusercontent.com/55006754/128139330-23c149e9-9a28-44f0-bc9d-941148e9c1ee.png)
All *3* images returned absolutely no text.

But for `MMOCR(det=None, recog='SAR', recog_ckpt='sar_r31_parallel_decoder_academic-dba3a4a3.pth')`:
![Unknown-34](https://user-images.githubusercontent.com/55006754/128139640-9e83280b-8825-4ffd-bba9-ca49e7889d34.png)
![Unknown-33](https://user-images.githubusercontent.com/55006754/128139649-bd053154-105b-4aee-a55e-42dbf19df924.png)
![Unknown-32](https://user-images.githubusercontent.com/55006754/128139663-c8b43bd4-137a-416c-b5f4-4a8f62940b9b.png)
These 3 images returned '$6.96', '$0.00', and '$6,96' respecitvely.
I don't want to apply recognition without detection, however, because in the portion of bboxes where there are phrases (so words with phrases), the recognition alone wouldn't be sufficient (as it treats everything within a bbox as a single word).

Is it that I should be returning my bboxes with some extra white padding around them (like add 10 white pixels to 'frame' it)?
Or do I need to make the bboxes be more 'smaller' so there isn't as much space between the characters within a word? I'm pulling these bboxes from documents, so if you have any ideas for processing that would work more favorable to having the det+recog MMOCR read, I would love to hear. Thanks!

**Comment by gaotongxiao** [comment]
I've run a quick test and it turned out that TextSnake can't get the text area right on your images. You may consider another detection algorithm in your project. FYI, You can turn on `imshow` for debugging.

**Comment by parulsingh23** [comment]
I see, because when I tried using PSENET, PANET, and MASKRCNN, I didn't fare any better. Is there a specific text det/recog model that would work for document bboxes ( so printed black monospace sans serif font on off-white/white background)?

**Comment by gaotongxiao** [comment]
I'm not sure. You may iterate through the list of provided models in ocr.py and check which one works best. I believe we should train some recognition models that support long text recognition, but it will take quite a long time.
