### ISSUE TITLE
ctw1500

### ISSUE THREAD

**Issue by myh12138** [open-mmlab/mmocr#412]
wget -O train_labels.zip https://universityofadelaide.box.com/shared/static/jikuazluzyj4lq6umzei7m2ppmt3afyw.zip

this comment is wrong, I can't load the json file

**Comment by gaotongxiao** [comment]
The link is still accessible. Consider using a proxy.

**Comment by myh12138** [comment]
> The link is still accessible. Consider using a proxy.
But,I get error like this,I can load the test annotation and others(my friends) get the same error like me.


--2021-08-06 07:10:21--  https://universityofadelaide.box.com/shared/static/py5uwlfyyytbb2pxzq9czvu6fuqbjdh8.zip
Resolving universityofadelaide.box.com (universityofadelaide.box.com)... 103.116.4.197
Connecting to universityofadelaide.box.com (universityofadelaide.box.com)|103.116.4.197|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/py5uwlfyyytbb2pxzq9czvu6fuqbjdh8.zip [following]
--2021-08-06 07:10:23--  https://universityofadelaide.box.com/public/static/py5uwlfyyytbb2pxzq9czvu6fuqbjdh8.zip
Reusing existing connection to universityofadelaide.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://universityofadelaide.app.box.com/public/static/py5uwlfyyytbb2pxzq9czvu6fuqbjdh8.zip [following]
--2021-08-06 07:10:23--  https://universityofadelaide.app.box.com/public/static/py5uwlfyyytbb2pxzq9czvu6fuqbjdh8.zip
Resolving universityofadelaide.app.box.com (universityofadelaide.app.box.com)... 203.98.7.65, 2001::4a75:b248
Connecting to universityofadelaide.app.box.com (universityofadelaide.app.box.com)|203.98.7.65|:443... failed: Connection timed out.
Connecting to universityofadelaide.app.box.com (universityofadelaide.app.box.com)|2001::4a75:b248|:443... failed: Network is unreachable.

**Comment by gaotongxiao** [comment]
I have tested the command and it works well for me. You should set up a proxy in your shell.

**Comment by myh12138** [comment]
> I have tested the command and it works well for me. You should set up a proxy in your shell.

yes,you are right,sorry forget to reply.
