### ISSUE TITLE
can't run demos through the docker - nvidia drivers are not installed

### ISSUE THREAD

**Issue by naarkhoo** [open-mmlab/mmocr#414]
I have installed the `mmocr` through the docker, however, when I try to use the demo

`python mmocr/utils/ocr.py demo/demo_text_ocr.jpg --imshow`

it gives me the error of 

```
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```
I wonder if you can guide me how to run the demos through the docker.

**Comment by gaotongxiao** [comment]
Did you use our dockerfile? Also, you need to specify `--gpus all` if you run the docker with GPU. Here is an example https://mmocr.readthedocs.io/en/latest/install.html#another-option-docker-image

**Comment by naarkhoo** [comment]
oh - sorry - I can see it was already in the documentation - thank you again.
