### ISSUE TITLE
请问下，我在训练nrtr的时候，已经把类别修改成6602，但是实际transformer_decode.py解码的时候num_class还是93，我还需要修改哪里呢？

### ISSUE THREAD

**Issue by cjt222** [open-mmlab/mmocr#423]
_base_ = [
    '../../_base_/default_runtime.py', '../../_base_/recog_models/nrtr.py'
]

dict_file="/home/kpl/mmocr/char_6599.txt"
label_convertor = dict(
    type='AttnConvertor', dict_type='dict_file', with_unknown=True)

model = dict(
    type='NRTR',
    backbone=dict(
        type='ResNet31OCR',
        layers=[1, 2, 5, 3],
        channels=[32, 64, 128, 256, 512, 512],
        stage4_pool_cfg=dict(kernel_size=(2, 1), stride=(2, 1)),
        last_stage_pool=False),
    encoder=dict(type='TFEncoder'),
    decoder=dict(type='TFDecoder'),
    loss=dict(type='TFLoss'),
    label_convertor=label_convertor,
    max_seq_len=40, pretrained="./nrtr_r31_1by8_1by4_academic_20210406-ce16e7cc.pth")

**Comment by gaotongxiao** [comment]
Have you modified the code? 
```
label_convertor = dict(type='AttnConvertor', dict_type='dict_file', with_unknown=True)
```
It cannot even pass the init assertion of `BaseConvertor`, the superclass of `AttnConvertor`. https://github.com/open-mmlab/mmocr/blob/7bbb14f0d1579463ed408e845a410850d25d8045/mmocr/models/textrecog/convertors/base.py#L26 
The right way to use your customized dictionary is
```
label_convertor = dict(type='AttnConvertor', dict_file=dict_file, with_unknown=True)
```
And you've noticed that `num_classes` of `TFDecoder` is 93 in default, so it can't generate more than 93 tokens. You can modify its value in the config:
```
model = dict(
    ...
   decoder=dict(type='TFDecoder', num_class=6602),
   ...
)
```
Finally, you were loading our pretrained model, which was trained on the 93-char dictionary. You need to remove the `pretrained` field and train NRTR from scratch.

**Comment by cjt222** [comment]
请问下，这里面的unknown是指代的什么呢，和空格会混淆吗？我预测时候空格很多都是unknown

**Comment by gaotongxiao** [comment]
"Unknown" refers to any character not existing in the dictionary. Have you explicitly put a space symbol in your dictionary?

**Comment by cjt222** [comment]
有的，在字典中是有空格这个字符的

**Comment by gaotongxiao** [comment]
It seems in `BaseConverter` the dictionary loader will skip the space:
https://github.com/open-mmlab/mmocr/blob/7bbb14f0d1579463ed408e845a410850d25d8045/mmocr/models/textrecog/convertors/base.py#L33-L34
You may apply a quick fix here:
```
if line == '':
    self.idx2char.append(' ')
else:
    self.idx2char.append(line)
```

**Comment by cjt222** [comment]
是的，我也发现了，已经改过来了，谢谢
