### ISSUE TITLE
issue of training NRTR

### ISSUE THREAD

**Issue by lantx5** [open-mmlab/mmocr#426]
I completed the NRTR training using only the Syn90K data set.I just changed how and where the data was read.However, the accuracy is almost zero.
![image](https://user-images.githubusercontent.com/73979084/129132766-d9e3051b-d5c5-4ebd-9d98-647e39acb61e.png)
my configs.py

**Comment by lantx5** [comment]
> I completed the NRTR training using only the Syn90K data set.I just changed how and where the data was read.However, the accuracy is almost zero.
> ![image](https://user-images.githubusercontent.com/73979084/129132766-d9e3051b-d5c5-4ebd-9d98-647e39acb61e.png)
> my configs.py
> `_base_ = [
> '../../_base_/default_runtime.py', '../../_base_/recog_models/nrtr.py'
> ]
> 
> label_convertor = dict(
> type='AttnConvertor', dict_type='DICT90', with_unknown=True)
> 
> model = dict(
> type='NRTR',
> backbone=dict(
> type='ResNet31OCR',
> layers=[1, 2, 5, 3],
> channels=[32, 64, 128, 256, 512, 512],
> stage4_pool_cfg=dict(kernel_size=(2, 1), stride=(2, 1)),
> last_stage_pool=True),
> encoder=dict(type='TFEncoder'),
> decoder=dict(type='TFDecoder'),
> loss=dict(type='TFLoss'),
> label_convertor=label_convertor,
> max_seq_len=40)
> 
> # optimizer
> optimizer = dict(type='Adam', lr=1e-3)
> optimizer_config = dict(grad_clip=None)
> 
> # learning policy
> lr_config = dict(policy='step', step=[3, 4])
> total_epochs = 6
> 
> img_norm_cfg = dict(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
> train_pipeline = [
> dict(type='LoadImageFromFile'),
> dict(
> type='ResizeOCR',
> height=32,
> min_width=32,
> max_width=160,
> keep_aspect_ratio=True,
> width_downsample_ratio=0.25),
> dict(type='ToTensorOCR'),
> dict(type='NormalizeOCR', **img_norm_cfg),
> dict(
> type='Collect',
> keys=['img'],
> meta_keys=[
> 'filename', 'ori_shape', 'img_shape', 'text', 'valid_ratio'
> ]),
> ]
> test_pipeline = [
> dict(type='LoadImageFromFile'),
> dict(
> type='MultiRotateAugOCR',
> rotate_degrees=[0, 90, 270],
> transforms=[
> dict(
> type='ResizeOCR',
> height=32,
> min_width=32,
> max_width=160,
> keep_aspect_ratio=True,
> width_downsample_ratio=0.25),
> dict(type='ToTensorOCR'),
> dict(type='NormalizeOCR', **img_norm_cfg),
> dict(
> type='Collect',
> keys=['img'],
> meta_keys=[
> 'filename', 'ori_shape', 'img_shape', 'valid_ratio'
> ]),
> ])
> ]
> 
> dataset_type = 'OCRDataset'
> 
> train_prefix = '/gdata1/lantx/data/mixture/'
> 
> # train_img_prefix1 = train_prefix + \
> # 'SynthText/synthtext/SynthText_patch_horizontal'
> train_img_prefix1 = train_prefix + 'Syn90k'
> 
> # train_ann_file1 = train_prefix + 'SynthText/label.lmdb'
> train_ann_file1 = train_prefix + 'Syn90k/shuffle_labels.txt'
> 
> train1 = dict(
> type=dataset_type,
> img_prefix=train_img_prefix1,
> ann_file=train_ann_file1,
> loader=dict(
> type='HardDiskLoader',
> repeat=1,
> parser=dict(
> type='LineStrParser',
> keys=['filename', 'text'],
> keys_idx=[0, 1],
> separator=' ')),
> pipeline=None,
> test_mode=False)
> 
> # train2 = {key: value for key, value in train1.items()}
> # train2['img_prefix'] = train_img_prefix2
> # train2['ann_file'] = train_ann_file2
> test_prefix = '/gdata1/lantx/data/mixture/'
> test_img_prefix1 = test_prefix + 'IIIT5K/'
> test_img_prefix2 = test_prefix + 'svt/svt/svt1'
> test_img_prefix3 = test_prefix + 'icdar_2013/'
> test_img_prefix4 = test_prefix + 'icdar_2015/'
> test_img_prefix5 = test_prefix + 'ct80/'
> test_img_prefix6 = test_prefix + 'svtp/'
> 
> test_ann_file1 = test_prefix + 'IIIT5K/test_label.txt'
> test_ann_file2 = test_prefix + 'svt/svt/svt1/shuffle_label.txt'
> test_ann_file3 = test_prefix + 'icdar_2013/test_label_1015.txt'
> test_ann_file4 = test_prefix + 'icdar_2015/test_label.txt'
> test_ann_file5 = test_prefix + 'ct80/test_label.txt'
> test_ann_file6 = test_prefix + 'svtp/label.txt'
> 
> test1 = dict(
> type=dataset_type,
> img_prefix=test_img_prefix1,
> ann_file=test_ann_file1,
> loader=dict(
> type='HardDiskLoader',
> repeat=1,
> parser=dict(
> type='LineStrParser',
> keys=['filename', 'text'],
> keys_idx=[0, 1],
> separator=' ')),
> pipeline=None,
> test_mode=True)
> 
> test2 = {key: value for key, value in test1.items()}
> test2['img_prefix'] = test_img_prefix2
> test2['ann_file'] = test_ann_file2
> 
> test3 = {key: value for key, value in test1.items()}
> test3['img_prefix'] = test_img_prefix3
> test3['ann_file'] = test_ann_file3
> 
> test4 = {key: value for key, value in test1.items()}
> test4['img_prefix'] = test_img_prefix4
> test4['ann_file'] = test_ann_file4
> 
> test5 = {key: value for key, value in test1.items()}
> test5['img_prefix'] = test_img_prefix5
> test5['ann_file'] = test_ann_file5
> 
> test6 = {key: value for key, value in test1.items()}
> test6['img_prefix'] = test_img_prefix6
> test6['ann_file'] = test_ann_file6
> 
> data = dict(
> samples_per_gpu=128,
> workers_per_gpu=4,
> val_dataloader=dict(samples_per_gpu=1),
> test_dataloader=dict(samples_per_gpu=1),
> train=dict(
> type='UniformConcatDataset',
> datasets=[train1],
> pipeline=train_pipeline),
> val=dict(
> type='UniformConcatDataset',
> datasets=[test1, test2, test3, test4, test5, test6],
> pipeline=test_pipeline),
> test=dict(
> type='UniformConcatDataset',
> datasets=[test1, test2, test3, test4, test5, test6],
> pipeline=test_pipeline))
> 
> evaluation = dict(interval=1, metric='acc')
> `

>

**Comment by lantx5** [comment]
`_base_ = [
    '../../_base_/default_runtime.py', '../../_base_/recog_models/nrtr.py'
]

label_convertor = dict(
    type='AttnConvertor', dict_type='DICT90', with_unknown=True)

model = dict(
    type='NRTR',
    backbone=dict(
        type='ResNet31OCR',
        layers=[1, 2, 5, 3],
        channels=[32, 64, 128, 256, 512, 512],
        stage4_pool_cfg=dict(kernel_size=(2, 1), stride=(2, 1)),
        last_stage_pool=True),
    encoder=dict(type='TFEncoder'),
    decoder=dict(type='TFDecoder'),
    loss=dict(type='TFLoss'),
    label_convertor=label_convertor,
    max_seq_len=40)


optimizer = dict(type='Adam', lr=1e-3)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[3, 4])
total_epochs = 6

img_norm_cfg = dict(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='ResizeOCR',
        height=32,
        min_width=32,
        max_width=160,
        keep_aspect_ratio=True,
        width_downsample_ratio=0.25),
    dict(type='ToTensorOCR'),
    dict(type='NormalizeOCR', **img_norm_cfg),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'filename', 'ori_shape', 'img_shape', 'text', 'valid_ratio'
        ]),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiRotateAugOCR',
        rotate_degrees=[0, 90, 270],
        transforms=[
            dict(
                type='ResizeOCR',
                height=32,
                min_width=32,
                max_width=160,
                keep_aspect_ratio=True,
                width_downsample_ratio=0.25),
            dict(type='ToTensorOCR'),
            dict(type='NormalizeOCR', **img_norm_cfg),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=[
                    'filename', 'ori_shape', 'img_shape', 'valid_ratio'
                ]),
        ])
]

dataset_type = 'OCRDataset'

train_prefix = '/gdata1/lantx/data/mixture/'


train_img_prefix1 = train_prefix + 'Syn90k'

train_ann_file1 = train_prefix + 'Syn90k/shuffle_labels.txt'

train1 = dict(
    type=dataset_type,
    img_prefix=train_img_prefix1,
    ann_file=train_ann_file1,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=False)


test_prefix = '/gdata1/lantx/data/mixture/'
test_img_prefix1 = test_prefix + 'IIIT5K/'
test_img_prefix2 = test_prefix + 'svt/svt/svt1'
test_img_prefix3 = test_prefix + 'icdar_2013/'
test_img_prefix4 = test_prefix + 'icdar_2015/'
test_img_prefix5 = test_prefix + 'ct80/'
test_img_prefix6 = test_prefix + 'svtp/'

test_ann_file1 = test_prefix + 'IIIT5K/test_label.txt'
test_ann_file2 = test_prefix + 'svt/svt/svt1/shuffle_label.txt'
test_ann_file3 = test_prefix + 'icdar_2013/test_label_1015.txt'
test_ann_file4 = test_prefix + 'icdar_2015/test_label.txt'
test_ann_file5 = test_prefix + 'ct80/test_label.txt'
test_ann_file6 = test_prefix + 'svtp/label.txt'

test1 = dict(
    type=dataset_type,
    img_prefix=test_img_prefix1,
    ann_file=test_ann_file1,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=True)

test2 = {key: value for key, value in test1.items()}
test2['img_prefix'] = test_img_prefix2
test2['ann_file'] = test_ann_file2

test3 = {key: value for key, value in test1.items()}
test3['img_prefix'] = test_img_prefix3
test3['ann_file'] = test_ann_file3

test4 = {key: value for key, value in test1.items()}
test4['img_prefix'] = test_img_prefix4
test4['ann_file'] = test_ann_file4

test5 = {key: value for key, value in test1.items()}
test5['img_prefix'] = test_img_prefix5
test5['ann_file'] = test_ann_file5

test6 = {key: value for key, value in test1.items()}
test6['img_prefix'] = test_img_prefix6
test6['ann_file'] = test_ann_file6

data = dict(
    samples_per_gpu=128,
    workers_per_gpu=4,
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1),
    train=dict(
        type='UniformConcatDataset',
        datasets=[train1],
        pipeline=train_pipeline),
    val=dict(
        type='UniformConcatDataset',
        datasets=[test1, test2, test3, test4, test5, test6],
        pipeline=test_pipeline),
    test=dict(
        type='UniformConcatDataset',
        datasets=[test1, test2, test3, test4, test5, test6],
        pipeline=test_pipeline))

evaluation = dict(interval=1, metric='acc')
`

**Comment by lantx5** [comment]
_base_ = [
    '../../_base_/default_runtime.py', '../../_base_/recog_models/nrtr.py'
]

label_convertor = dict(
    type='AttnConvertor', dict_type='DICT90', with_unknown=True)

model = dict(
    type='NRTR',
    backbone=dict(
        type='ResNet31OCR',
        layers=[1, 2, 5, 3],
        channels=[32, 64, 128, 256, 512, 512],
        stage4_pool_cfg=dict(kernel_size=(2, 1), stride=(2, 1)),
        last_stage_pool=True),
    encoder=dict(type='TFEncoder'),
    decoder=dict(type='TFDecoder'),
    loss=dict(type='TFLoss'),
    label_convertor=label_convertor,
    max_seq_len=40)


optimizer = dict(type='Adam', lr=1e-3)
optimizer_config = dict(grad_clip=None)

lr_config = dict(policy='step', step=[3, 4])
total_epochs = 6

img_norm_cfg = dict(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='ResizeOCR',
        height=32,
        min_width=32,
        max_width=160,
        keep_aspect_ratio=True,
        width_downsample_ratio=0.25),
    dict(type='ToTensorOCR'),
    dict(type='NormalizeOCR', **img_norm_cfg),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'filename', 'ori_shape', 'img_shape', 'text', 'valid_ratio'
        ]),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiRotateAugOCR',
        rotate_degrees=[0, 90, 270],
        transforms=[
            dict(
                type='ResizeOCR',
                height=32,
                min_width=32,
                max_width=160,
                keep_aspect_ratio=True,
                width_downsample_ratio=0.25),
            dict(type='ToTensorOCR'),
            dict(type='NormalizeOCR', **img_norm_cfg),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=[
                    'filename', 'ori_shape', 'img_shape', 'valid_ratio'
                ]),
        ])
]

dataset_type = 'OCRDataset'

train_prefix = '/gdata1/lantx/data/mixture/'


train_img_prefix1 = train_prefix + 'Syn90k'

train_ann_file1 = train_prefix + 'Syn90k/shuffle_labels.txt'

train1 = dict(
    type=dataset_type,
    img_prefix=train_img_prefix1,
    ann_file=train_ann_file1,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=False)


test_prefix = '/gdata1/lantx/data/mixture/'
test_img_prefix1 = test_prefix + 'IIIT5K/'
test_img_prefix2 = test_prefix + 'svt/svt/svt1'
test_img_prefix3 = test_prefix + 'icdar_2013/'
test_img_prefix4 = test_prefix + 'icdar_2015/'
test_img_prefix5 = test_prefix + 'ct80/'
test_img_prefix6 = test_prefix + 'svtp/'

test_ann_file1 = test_prefix + 'IIIT5K/test_label.txt'
test_ann_file2 = test_prefix + 'svt/svt/svt1/shuffle_label.txt'
test_ann_file3 = test_prefix + 'icdar_2013/test_label_1015.txt'
test_ann_file4 = test_prefix + 'icdar_2015/test_label.txt'
test_ann_file5 = test_prefix + 'ct80/test_label.txt'
test_ann_file6 = test_prefix + 'svtp/label.txt'

test1 = dict(
    type=dataset_type,
    img_prefix=test_img_prefix1,
    ann_file=test_ann_file1,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=True)

test2 = {key: value for key, value in test1.items()}
test2['img_prefix'] = test_img_prefix2
test2['ann_file'] = test_ann_file2

test3 = {key: value for key, value in test1.items()}
test3['img_prefix'] = test_img_prefix3
test3['ann_file'] = test_ann_file3

test4 = {key: value for key, value in test1.items()}
test4['img_prefix'] = test_img_prefix4
test4['ann_file'] = test_ann_file4

test5 = {key: value for key, value in test1.items()}
test5['img_prefix'] = test_img_prefix5
test5['ann_file'] = test_ann_file5

test6 = {key: value for key, value in test1.items()}
test6['img_prefix'] = test_img_prefix6
test6['ann_file'] = test_ann_file6

data = dict(
    samples_per_gpu=128,
    workers_per_gpu=4,
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1),
    train=dict(
        type='UniformConcatDataset',
        datasets=[train1],
        pipeline=train_pipeline),
    val=dict(
        type='UniformConcatDataset',
        datasets=[test1, test2, test3, test4, test5, test6],
        pipeline=test_pipeline),
    test=dict(
        type='UniformConcatDataset',
        datasets=[test1, test2, test3, test4, test5, test6],
        pipeline=test_pipeline))

evaluation = dict(interval=1, metric='acc')

**Comment by gaotongxiao** [comment]
shuffle_labels.txt is only a subset of syn90k containing only 2,400,000 sampled training examples for some other models' training. It would help if you used label.txt (https://download.openmmlab.com/mmocr/data/mixture/Syn90k/label.txt) for the full training cycle. We should have clarified that in the docs. Thanks for your feedback!

**Comment by simplify23** [comment]
我也遇到了同样的问题。我使用了本地的MJ+ST数据集作为训练集，在公共数据集上进行评估。在此之前，我在robust_scanner方法上使用同样的训练集和测试集，结果虽然不如robust_scanner报告结果（训练集不包括公共真实数据集）。但效果还行。结果如下：
![image](https://user-images.githubusercontent.com/39580716/129530165-092772a2-0ba0-432e-b078-ebb7bce4625a.png)

但同样的方式运用在NRTR的训练过程中，仍然是接近于0的评估结果，（所有配置均和robust_scanner保持一致）我不倾向于认为这是训练集的问题，希望可以有进一步的核查
![image](https://user-images.githubusercontent.com/39580716/129530422-1a391414-dad3-49eb-a241-26da06f0515d.png)

**Comment by gaotongxiao** [comment]
@simplify23 Are you using shuffle_labels.txt or labels.txt?

**Comment by simplify23** [comment]
> @simplify23 Are you using shuffle_labels.txt or labels.txt?

We use Syn90k 7,224,586 and ST 5,489,040（which is croped by ourselves).And this tranning data is also used in robust_scanner for fair comparison.  I don't know whether NRTR dataset's prepare has some difference for robust_scanner.

**Comment by gaotongxiao** [comment]
I see. Would you mind sharing your config?

**Comment by simplify23** [comment]
```
_base_ = [
    '../../_base_/default_runtime.py', '../../_base_/recog_models/nrtr.py'
]
# nohup ./tools/dist_train.sh configs/textrecog/nrtr/adapt_nrtr_r31_1by8_1by4_academic.py work_dirs/nrtr 6
#CUDA_VISIBLE_DEVICES=7 ./tools/dist_test.sh configs/textrecog/nrtr/adapt_nrtr_r31_1by8_1by4_academic.py work_dirs/nrtr/epoch_4.pth 1 --eval acc
# label_convertor = dict(
#     type='AttnConvertor', dict_type='DICT90', with_unknown=True)

model = dict(
    type='NRTR',
    backbone=dict(
        type='ResNet31OCR',
        layers=[1, 2, 5, 3],
        channels=[32, 64, 128, 256, 512, 512],
        stage4_pool_cfg=dict(kernel_size=(2, 1), stride=(2, 1)),
        last_stage_pool=False),
    encoder=dict(type='TFEncoder'),
    decoder=dict(type='TFDecoder'),
    loss=dict(type='TFLoss'),
    label_convertor=label_convertor,
    max_seq_len=40)

# optimizer
optimizer = dict(type='Adam', lr=1e-3)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[3, 4])
total_epochs = 6

img_norm_cfg = dict(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='ResizeOCR',
        height=32,
        min_width=32,
        max_width=160,
        keep_aspect_ratio=True,
        width_downsample_ratio=0.25),
    dict(type='ToTensorOCR'),
    dict(type='NormalizeOCR', **img_norm_cfg),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'filename', 'ori_shape', 'img_shape', 'text', 'valid_ratio'
        ]),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiRotateAugOCR',
        rotate_degrees=[0, 90, 270],
        transforms=[
            dict(
                type='ResizeOCR',
                height=32,
                min_width=32,
                max_width=160,
                keep_aspect_ratio=True,
                width_downsample_ratio=0.25),
            dict(type='ToTensorOCR'),
            dict(type='NormalizeOCR', **img_norm_cfg),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=[
                    'filename', 'ori_shape', 'img_shape', 'valid_ratio'
                ]),
        ])
]

dataset_type = 'OCRDataset'

train_prefix = 'data/NewVersion/'

train_img_prefix1 = train_prefix + '90kDICT32px'
train_ann_file1 = train_prefix + '90kDICT32px/annotation_train_two_Synth_shuf_clean.txt',
# train_prefix = 'data/'
#
# train_img_prefix1 = train_prefix + \
#     'ST/data'
# train_img_prefix2 = train_prefix + 'MJ/data'
#
# train_ann_file1 = train_prefix + 'ST/lock.mdb',
# train_ann_file2 = train_prefix + 'MJ/label.mdb'
train1 = dict(
    type=dataset_type,
    img_prefix=train_img_prefix1,
    ann_file=train_ann_file1,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=train_pipeline,
    test_mode=False)
# train1 = dict(
#     type=dataset_type,
#     img_prefix=train_img_prefix1,
#     ann_file=train_ann_file1,
#     loader=dict(
#         type='LmdbLoader',
#         repeat=1,
#         parser=dict(
#             type='LineStrParser',
#             keys=['filename', 'text'],
#             keys_idx=[0, 1],
#             separator=' ')),
#     pipeline=train_pipeline,
#     test_mode=False)

# train2 = {key: value for key, value in train1.items()}
# train2['img_prefix'] = train_img_prefix2
# train2['ann_file'] = train_ann_file2

test_prefix = 'data/NewVersion/'
test_img_prefix1 = test_prefix + 'IIIT5K/IIIT'
test_img_prefix2 = test_prefix + 'SVT/SVT'
test_img_prefix3 = test_prefix + 'ICDAR2013/IC13'
test_img_prefix4 = test_prefix + 'ICDAR2015/IC15'
test_img_prefix5 = test_prefix + 'SVT-P/SP'
test_img_prefix6 = test_prefix + 'CUTE80/CT'

test_ann_file1 = test_prefix + 'IIIT5K/IIIT/IIIT5k_clean.txt'
test_ann_file2 = test_prefix + 'SVT/SVT/SVT_origin.txt'
test_ann_file3 = test_prefix + 'ICDAR2013/IC13/filtered_IC13_clean_1.txt'
test_ann_file4 = test_prefix + 'ICDAR2015/IC15/IC15_clean.txt'
test_ann_file5 = test_prefix + 'SVT-P/SP/SVTP_clean.txt'
test_ann_file6 = test_prefix + 'CUTE80/CT/CUTE.txt'

test1 = dict(
    type=dataset_type,
    img_prefix=test_img_prefix1,
    ann_file=test_ann_file1,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=test_pipeline,
    test_mode=True)

test2 = {key: value for key, value in test1.items()}
test2['img_prefix'] = test_img_prefix2
test2['ann_file'] = test_ann_file2

test3 = {key: value for key, value in test1.items()}
test3['img_prefix'] = test_img_prefix3
test3['ann_file'] = test_ann_file3

test4 = {key: value for key, value in test1.items()}
test4['img_prefix'] = test_img_prefix4
test4['ann_file'] = test_ann_file4

test5 = {key: value for key, value in test1.items()}
test5['img_prefix'] = test_img_prefix5
test5['ann_file'] = test_ann_file5

test6 = {key: value for key, value in test1.items()}
test6['img_prefix'] = test_img_prefix6
test6['ann_file'] = test_ann_file6

data = dict(
    samples_per_gpu=128,
    workers_per_gpu=4,
    train=dict(type='ConcatDataset', datasets=[train1]),
    val=dict(
        type='ConcatDataset',
        datasets=[test1, test2, test3, test4, test5, test6]),
    test=dict(
        type='ConcatDataset',
        datasets=[test1, test2, test3, test4, test5, test6]))
checkpoint_config = dict(interval=1)
evaluation = dict(interval=1, metric='acc')
```

**Comment by gaotongxiao** [comment]
Hi @simplify23 @lantx5, I went through our training log and realized that the lack of labels is not the major reason causing such failure. Current configuration is customized for 64 GPUs (see the `gpu_ids` field) to train NRTR. Therefore, you need to scale up your data batch or trim the learning rate accordingly to achieve similar performance.

**Comment by gaotongxiao** [comment]
I'm closing this issue as there is no further update.
