### ISSUE TITLE
confused about the img_pad_value

### ISSUE THREAD

**Issue by andyjpaddle** [open-mmlab/mmocr#431]
hi，I'm confused about the param `img_pad_value` used in the func `ResizeOCR` in `ocr_transforms.py` when I used the SAR pre-trained model to test images. From the code, the default is 0, but when I print the image value ,it's -1? Did I missed some information about the param `img_pad_value`?

**Comment by cuhk-hbsun** [comment]
where do you set the breakpoint to print the image value? You should print it just after the `ResizeOCR` pipeline, but not after the whole train pipeline. (after normalizing, "0" will change to "-1")

**Comment by andyjpaddle** [comment]
OK， I got it， thanks

> where do you set the breakpoint to print the image value? You should print it just after the `ResizeOCR` pipeline, but not after the whole train pipelines. (after normalizing, "0" will change to "-1")
