### ISSUE TITLE
How to prepare dataset for custom text detection, and recognition for invoices

### ISSUE THREAD

**Issue by m-ali-awan** [open-mmlab/mmocr#435]
Hi, hope all of you are fine.
In colab notebook, we can see the toy dataset where one word annotations are there, but how we can train different models for the custom dataset, where we can train on invoices images or similar complex images.

Also if one wants to train custom key-value extraction, how to format the data.
It would be awesome if someone has done similar work and can share a colab notebook, it would be very helpful.

Thanks.

**Comment by amitbcp** [comment]
@innerlee  if possible can you also include instruction to assign edge related data and training as mentioned here : https://github.com/open-mmlab/mmocr/issues/248

**Comment by gaotongxiao** [comment]
Done in #478, and please check out the tutorial [here](https://mmocr.readthedocs.io/en/latest/tutorials/kie_closeset_openset.html).
