### ISSUE TITLE
Bad Performance Speed of KIE in inference

### ISSUE THREAD

**Issue by parulsingh23** [open-mmlab/mmocr#444]
When I am using the MMOCR object for only KIE (I am using `MMOCR(kie='SDMGR')`, which I modified to accept an argument of the dictionary of detected bboxes and extracted text), I am getting a runtime of 14.292 seconds (and this is when I call the function `readtext` once for one image).

Additionally, I noticed that when I am calling pytesseract on cropped image snippets versus calling `MMOCR(det=None, recog='SAR')` on cropped image snippets, tesseract only takes an average of .185 sec per image, whereas the MMOCR object call takes .263 sec per image. (and since I'm calling over ~120 cropped images, this results in a difference of around 9 sec). 

I am running this on a google colab's gpu (not sure if that makes any difference to runtime). I would greatly appreciate any advice on how it's possible to improve the speed of inferencing in calling MMOCR objects (_especially_  for using KIE as that is taking over 14 seconds for _just 1 image_). 

I'm not familiar with how to optimize for speed when calling such models, but would I have to make my own api wrapper to call the model scripts? I'm not sure this is the reason why the calls take so long, as I ran cProfile to get running times, and it showed 1 call to ` /content/mmocr/mmocr/models/kie/extractors/sdmgr.py:77(forward_test)` took 14.041 seconds. So this means the long run time is from the model script running itself. Is it possible to make custom edits so this model script runs faster (what/where would those be)?

Additionally, I would like to transition my program away from google colab, so should I have any consideration besides running parallel instances or multiple gpu's? I understand that this would help with my second example of calling MMOCR(recog='SAR') on many images in tandem, but this wouldn't help with improving the 14 sec runtime of KIE on 1 image, right?

Thanks for the help!

**Comment by gaotongxiao** [comment]
How many text boxes did you pass to SDMGR? So far as I understand, SDMGR builds a complete graph where each node maps to each text box, and refines all edge weights iteratively. Roughly speaking, the time complexity of SDMGR is Omega(n^2) where n is the node number, so SDMGR can be extremely slow when the number of nodes is large. I don't think the MMOCR object is to blame, or at least the latency introduced by it could be negligible.

We've received many complaints about the inference speed. Compared to concurrent OCR engines, which have optimized a specific model for practical use, MMOCR has put more effort into providing a universal pipeline that fits different models emerged from academia, so the inference speed is loyal to the model's original design. **But it doesn't mean that we don't want to speed the pipeline up** - our deployment team has been continuously working on model deployment and now we already support the deployment of 6 models. Our colleges are also optimizing the code structure to reduce unnecessary calls. We might also consider providing efficient lightweight OCR models if our community needs them.

For your third question, you don't need any extra steps to migrate your program to other machines.
