### ISSUE TITLE
KeyError: 'NRTR is not in the models registry'

### ISSUE THREAD

**Issue by luolugithub** [open-mmlab/mmocr#449]
conda create -n open-mmlab python=3.7 -y
conda activate open-mmlab

# install latest pytorch prebuilt with the default prebuilt CUDA version (usually the latest)
conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.1 -c pytorch

# install the latest mmcv-full
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html

# install mmdetection
pip install mmdet

# install mmocr
git clone https://github.com/open-mmlab/mmocr.git
cd mmocr

pip install -r requirements.txt
pip install -v -e .  # or "python setup.py develop"
export PYTHONPATH=$(pwd):$PYTHONPATH
then, run batch_image_demo.py get this error.

**Comment by gaotongxiao** [comment]
Hi, `batch_image_demo.py` is deprecated and will be removed from the repo soon. We use `mmocr/utils/ocr.py` instead which also supports batch image inference. Please check out its usage [here](https://mmocr.readthedocs.io/en/latest/demo.html).

In case you still want to use `batch_image_demo.py`, you can replace line 6 with
```
from mmocr.apis import init_detector
```
and it should work then.

**Comment by luolugithub** [comment]
Got it, thanks
