### ISSUE TITLE
MMCV安装失败

### ISSUE THREAD

**Issue by 1raintown** [open-mmlab/mmocr#450]
本人是win10系统
pytorch版本是1.6，cuda是10.1

![image](https://user-images.githubusercontent.com/89295363/130315749-dbfa0cfb-9667-47ee-9c79-31a20525143a.png)

按照安装文档安装MMCV出现如下问题

![image](https://user-images.githubusercontent.com/89295363/130315770-84abb364-47f8-496b-8960-a0bda481f2e4.png)

具体报错应该是OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.的问题
若能解决，本人将不胜感激

**Comment by gaotongxiao** [comment]
MMCV is not officially supported on Windows but will be very soon. Please wait for our colleague's release @zhouzaida
