### ISSUE TITLE
Unable to Install MMOCR on windows 

### ISSUE THREAD

**Issue by parulsingh23** [open-mmlab/mmocr#452]
I haven't been able to get the Full Set-up Script to successfully install MMOCR. I realize the installation isn't successful because  when I run `python mmocr/utils/ocr.py demo/demo_text_ocr.jpg --imshow`, I get the following Error:
```
Traceback (most recent call last):
  File "mmocr/utils/ocr.py", line 8, in <module>
    import mmcv
  File "C:\Users\parul\Anaconda3\lib\site-packages\mmcv\__init__.py", line 4, in <module>
    from .fileio import *
  File "C:\Users\parul\Anaconda3\lib\site-packages\mmcv\fileio\__init__.py", line 4, in <module>
    from .io import dump, load, register_handler
  File "C:\Users\parul\Anaconda3\lib\site-packages\mmcv\fileio\io.py", line 4, in <module>
    from ..utils import is_list_of, is_str
  File "C:\Users\parul\Anaconda3\lib\site-packages\mmcv\utils\__init__.py", line 22, in <module>
    import torch
  File "C:\Users\parul\Anaconda3\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\parul\Anaconda3\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.
```
I understand that in the prereqs you state 'Windows is not officially supported'. I'm afraid I'm not that familiar with the differences between operating systems (and why certain libraries wouldn't work on some OS), but is there no way to operate MMOCR on Windows? 

Since the OSError states something with cuda, in my conda enviornment, when I enter `conda list cudnn`, nothing returns. But entring `conda list cudatoolkit`  returns:
```
# Name                    Version                   Build  Channel
cudatoolkit               11.1.1               heb2d755_7    conda-forge
```
I would really appreciate any suggestions for what I should check, as I've tried installing on new conda envionrment multiple times, and I have been getting the same error result. Thanks in advance!

**Comment by gaotongxiao** [comment]
It seems your PyTorch and Cuda have not even been correctly installed? https://stackoverflow.com/questions/67122586/import-torch-oserror-winerror-127

**Comment by gaotongxiao** [comment]
Has it been successfully installed now?
