### ISSUE TITLE
kie模型输出结果可视化不支持中文

### ISSUE THREAD

**Issue by jiangds2018** [open-mmlab/mmocr#456]
在执行命令 
sh tools/kie_test_imgs.sh configs/kie/sdmgr/sdmgr_unet16_60e_wildreceipt.py models/kie-mode-1/epoch_60.pth outputs/
输出的可视化结果中无法正常显示中文字符，请问该如何修改？
![image](https://user-images.githubusercontent.com/44767932/130442311-502ebdc7-1b8b-4a72-89d6-89ef673f4729.png)

**Comment by gaotongxiao** [comment]
You can change https://github.com/open-mmlab/mmocr/blob/main/mmocr/core/visualize.py#L418-419 to something similar to
https://github.com/open-mmlab/mmocr/blob/main/mmocr/core/visualize.py#L365-371.

Let me know if that works for you. A new PR would also be appreciated :)

**Comment by cuhk-hbsun** [comment]
Support Chinese, English and number in this [pr](https://github.com/open-mmlab/mmocr/pull/464)
