### ISSUE TITLE
KIE bbox preprocessing may have an error

### ISSUE THREAD

**Issue by alexander-soare** [open-mmlab/mmocr#463]
`bboxes` are obtained from `polys` [here](https://github.com/open-mmlab/mmocr/blob/f9d158fafa368e8a5ff9bd41b6c37046df388d08/mmocr/datasets/kie_dataset.py#L215-L226) but I believe there is a fault in the logic.

These lines pick the top-left-most point in the poly, then then 2nd point counter-clockwise from that one.

```
x1, y1 = boxes[:, 0:1], boxes[:, 1:2]  # top-left
x2, y2 = boxes[:, 4:5], boxes[:, 5:6]  # 2nd point counter-clockwise
```

Then later a bounding box is obtained by using these two points:

```
bboxes = np.concatenate([x1, y1, x2, y2], -1).astype(np.float32)
```

BUT, in some cases of non-axis-aligned polygons like this one

![image](https://user-images.githubusercontent.com/16543381/130762188-def66ad2-2673-45cc-9a9a-656f57aa9dd0.png)

the second point is **higher** than the first, resulting in y2 < y1:

![image](https://user-images.githubusercontent.com/16543381/130762437-a10c930a-2ca2-4390-94b0-62645ca9c7b0.png)

Even when this is not the case, it's very possible that the bounding box is not a good representation of what the polygon encapsulates (because it is too narrow).

**I would suggest to instead take the bounding box that contains all points of the poly**. Something like this.

```
bboxes = np.concatenate([polys[:, 0::2].min(axis=1, keepdims=True), polys[:, 1::2].min(axis=1, keepdims=True),
                     polys[:, 0::2].max(axis=1, keepdims=True), polys[:, 1::2].max(axis=1, keepdims=True)], axis=1)
```
Note that this change would also require a change to the logic for the relations calculation (substitute x1, y1, x2, y2 with those from the new `bboxes` def)

Happy to make a PR if it makes sense

**Comment by gaotongxiao** [comment]
You're right, the assumption is oversimplified, tho it's enough to handle the WildReceipt dataset. You're welcome to make a PR :)
BTW, The feature extraction steps and KIE evaluation were designed based on this assumption. You may also check if they still make sense
