### ISSUE TITLE
how to draw PRC or ROC ...... on dev dataset ?

### ISSUE THREAD

**Issue by luolugithub** [open-mmlab/mmocr#468]
now --eval can get  acc in textrecogn，how to get PRC 、ROC、F1 ......? we want to get more visual analize result

**Comment by gaotongxiao** [comment]
We currently don't support them but you can add them to the codebase if necessary. See the [reference implementation](https://github.com/open-mmlab/mmocr/blob/main/mmocr/core/evaluation/ocr_metric.py) of the `acc` metric. You can add an if statement to support your own metric in OCRDataset [here](https://github.com/open-mmlab/mmocr/blob/f9d158fafa368e8a5ff9bd41b6c37046df388d08/mmocr/datasets/ocr_dataset.py#L15). Also, you're welcome to create a PR to help more people :)
