### ISSUE TITLE
I am not able to locate code in directory for the calculation part of edge relation in SDMGR

### ISSUE THREAD

**Issue by Nitin-Raghuvansi** [open-mmlab/mmocr#485]
![sdm](https://user-images.githubusercontent.com/49279471/132471517-40db78e6-25b4-4036-8192-07c0e307a662.PNG)

**Comment by gaotongxiao** [comment]
You can find the core logic in `mmocr/models/kie/heads/sdmgr_head.py`.

**Comment by Nitin-Raghuvansi** [comment]
[
![sd](https://user-images.githubusercontent.com/49279471/132670620-f6242783-8d0c-491f-8b7d-734d1296105f.PNG)
](url)

**Comment by gaotongxiao** [comment]
It's called from the BaseDetector in MMDetection (https://sourcegraph.com/github.com/open-mmlab/mmdetection@db85fd12afce2fe89d1c7b870874c02a90018a16/-/blob/mmdet/models/detectors/base.py?L172). 

So these arguments are the products from `train_pipeline` in `configs/kie/sdmgr/sdmgr_unet16_60e_wildreceipt.py`. Most of these pipelines are implemented in MMDetection except for `KIEFormatBundle` (https://github.com/open-mmlab/mmocr/blob/e9a5350f472772d5db08ed9860791b049a4ee18d/mmocr/datasets/pipelines/kie_transforms.py#L43). More descriptions of pipeline in MMDet's docs: https://mmdetection.readthedocs.io/en/latest/tutorials/data_pipeline.html

**Comment by cuhk-hbsun** [comment]
@Nitin-Raghuvansi The relation between nodes is calculated in dataset. You can check it in this (function)[https://github.com/open-mmlab/mmocr/blob/main/mmocr/datasets/kie_dataset.py#L215]

**Comment by Nitin-Raghuvansi** [comment]
@gaotongxiao @cuhk-hbsun 
Thank you so much I got it.
