### ISSUE TITLE
Could have the C++ forward example?

### ISSUE THREAD

**Issue by xinsuinizhuan** [open-mmlab/mmocr#490]
**Notice**

There are several common situations in the reimplementation issues as below

1. Reimplement a model in the model zoo using the provided configs
2. Reimplement a model in the model zoo on other dataset (e.g., custom datasets)
3. Reimplement a custom model but all the components are implemented in MMOCR
4. Reimplement a custom model with new modules implemented by yourself

There are several things to do for different cases as below.

- For case 1 & 3, please follow the steps in the following sections thus we could help to quick identify the issue.
- For case 2 & 4, please understand that we are not able to do much help here because we usually do not know the full code and the users should be responsible to the code they write.
- One suggestion for case 2 & 4 is that the users should first check whether the bug lies in the self-implemented code or the original code. For example, users can first make sure that the same model runs well on supported datasets. If you still need help, please describe what you have done and what you obtain in the issue, and follow the steps in the following sections and try as clear as possible so that we can better help you.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The issue has not been fixed in the latest version.

**Describe the issue**

A clear and concise description of what the problem you meet and what have you done.

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. What config dir you run?

```none
A placeholder for the config.
```

3. Did you make any modifications on the code or config? Did you understand what you have modified?
4. What dataset did you use?

**Environment**

1. Please run `python mmocr/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   1. How you installed PyTorch [e.g., pip, conda, source]
   2. Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Results**

If applicable, paste the related results here, e.g., what you expect and what you get.

```none
A placeholder for results comparison
```

**Issue fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by gaotongxiao** [comment]
Thanks for the suggestion, but I am afraid that we currently don't have enough resources to accomplish it. FYI, our deployment team has been working on a C++ deployment toolchain, but they say it will still take some time to release the code. So tutorials/examples will probably be added after that.

**Comment by apiaccess21** [comment]
@xinsuinizhuan 
If you're able to successfully export ONNX with verify option both Dbnet_r18 (default opset 11) and Satrn_Small (working opset 14) models via deployment/tools/pytorch2onnx.py... you may find next code helpful. It works with VS2019, ONNX from nuget and standard opencv binaries.

```C++
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/dnn.hpp>

#include <onnxruntime_cxx_api.h>
#pragma comment(lib, "onnxruntime.lib")

// DB_r18
class Detector {
public: 
	Detector(const std::string& model_path) {		
		session = Ort::Session{ env, std::wstring(model_path.begin(), model_path.end()).c_str(), Ort::SessionOptions{nullptr} };
	}

	std::vector<cv::Rect> inference(const cv::Mat& original, float threshold = 0.3f) {

		cv::Size original_size = original.size();

		const char* input_names[] = { "input" };
		const char* output_names[] = { "output" };

		std::array<int64_t, 4> input_shape{ 1, 3, height, width };

		cv::Mat image = cv::Mat::zeros(cv::Size(width, height), original.type());
		cv::resize(original, image, cv::Size(width, height), 0, 0, cv::INTER_AREA);

		image.convertTo(image, CV_32FC3);

		cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
		image = (image - cv::Scalar(123.675f, 116.28f, 103.53f)) / cv::Scalar(58.395f, 57.12f, 57.375f);

		cv::Mat blob = cv::dnn::blobFromImage(image);

		auto memory_info = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeDefault);
		Ort::Value input_tensor = Ort::Value::CreateTensor<float>(memory_info, (float*)blob.data, blob.total(), input_shape.data(), input_shape.size());

		std::vector<Ort::Value> output_tensor = session.Run(Ort::RunOptions{ nullptr }, input_names, &input_tensor, 1, output_names, 1);

		int sizes[] = { 1, 3, height, width };
		cv::Mat output(4, sizes, CV_32F, output_tensor.front().GetTensorMutableData<float>());

		std::vector<cv::Mat> images;
		cv::dnn::imagesFromBlob(output, images);

		std::vector<cv::Rect> areas = get_detected(images[0], threshold);
		std::vector<cv::Rect> results;

		float x_ratio = original_size.width / (float)width;
		float y_ratio = original_size.height / (float)height;

		for (int index = 0; index < areas.size(); ++index) {
			cv::Rect box = areas[index];

			box.x = int(box.x * x_ratio);
			box.width = int(box.width * x_ratio);
			box.y = int(box.y * y_ratio);
			box.height = int(box.height * y_ratio);

			results.push_back(box);
		}

		return results;
	}

private:	
	Ort::Env env;
	Ort::Session session{ nullptr };

	const int width = 1312, height = 736;	
	
	cv::Rect expand_box(const cv::Rect& original, int addition = 5) {
		cv::Rect box(original);
		box.x = std::max(0, box.x - addition);
		box.y = std::max(0, box.y - addition);
		box.width = (box.x + box.width + addition * 2 > width) ? (width - box.x) : (box.width + addition * 2);
		box.height = (box.y + box.height + addition * 2) > height ? (height - box.y) : (box.height + addition * 2);
		return box;
	}

	std::vector<cv::Rect> get_detected(const cv::Mat& output, float threshold) {
		cv::Mat text_mask = cv::Mat::zeros(height, width, CV_32F);
		std::vector<cv::Mat> maps;
		cv::split(output, maps);
		cv::Mat proba_map = maps[0];

		cv::threshold(proba_map, text_mask, threshold, 1.0f, cv::THRESH_BINARY);
		cv::multiply(text_mask, 255, text_mask);
		text_mask.convertTo(text_mask, CV_8U);

		std::vector<std::vector<cv::Point>> contours;
		cv::findContours(text_mask, contours, cv::RETR_EXTERNAL, cv::CHAIN_APPROX_SIMPLE);
		std::vector<cv::Rect> boxes;

		for (int index = 0; index < contours.size(); ++index) {
			cv::Rect box = expand_box(cv::boundingRect(contours[index]));
			boxes.push_back(box);
		}

		return boxes;
	}
};

// Satrn_small
class Recognizer {
public:
	Recognizer(const std::string& model_path) {
		session = Ort::Session{ env, std::wstring(model_path.begin(), model_path.end()).c_str(), Ort::SessionOptions{nullptr} };
	}

	std::string inference(const cv::Mat& original) {
		const char* input_names[] = { "input" };
		const char* output_names[] = { "output" };

		std::array<int64_t, 4> input_shape{ 1, 3, height, width };

		cv::Mat image;
		cv::resize(original, image, cv::Size(width, height), 0, 0, cv::INTER_AREA);
		image.convertTo(image, CV_32FC3);

		cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
		image = (image / 255.0f - cv::Scalar(0.485f, 0.456f, 0.406f)) / cv::Scalar(0.229f, 0.224f, 0.225f);

		cv::Mat blob = cv::dnn::blobFromImage(image);

		auto memory_info = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeDefault);
		Ort::Value input_tensor = Ort::Value::CreateTensor<float>(memory_info, (float*)blob.data, blob.total(), input_shape.data(), input_shape.size());

		std::vector<Ort::Value> output_tensor = session.Run(Ort::RunOptions{ nullptr }, input_names, &input_tensor, 1, output_names, 1);

		int sequence_length = 25;
		std::string dictionary = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!\"#$%&'()*+,-./:;<=>?@[\\]_`~";
		int characters = dictionary.length() + 2; // EOS + UNK

		std::vector<int> max_indices;
		for (int outer = 0; outer < sequence_length; ++outer) {
			int character_index = -1;
			float character_value = 0;
			for (int inner = 0; inner < characters; ++inner) {
				int counter = outer * characters + inner;
				float value = output_tensor[0].GetTensorMutableData<float>()[counter];
				if (value > character_value) {
					character_value = value;
					character_index = inner;
				}
			}
			max_indices.push_back(character_index);			
		}

		std::string recognized;
		for (int index = 0; index < max_indices.size(); ++index) {
			recognized += dictionary[max_indices[index]];
		}		

		return recognized;
	}

private:
	Ort::Env env;
	Ort::Session session{ nullptr };	

	const int height = 32;
	const int width = 100;
};
```

**Comment by gaotongxiao** [comment]
Hi, @apiaccess21. thanks for sharing! It's a nice snippet and I believe that having such an example in the documentation can help more people. If you have some time and would like to contribute to MMOCR, you can append a new session named like "a C++ forward example" to the end of [docs/deployment.md](https://github.com/open-mmlab/mmocr/blob/main/docs/deployment.md) and just paste your script to there. We would appreciate your PR and your contribution would be recorded and acknowledged.

**Comment by apiaccess21** [comment]
@gaotongxiao 
I've made a PR. No acknowledgement needed.
Thanks for your work and this repo.

**Comment by xinsuinizhuan** [comment]
> 
> 
> @gaotongxiao I've made a PR. No acknowledgement needed. Thanks for your work and this repo.

where is you PR？ could share your convered onnx models?

I try to convert, but don't know what the `model_ckpt`?
![图片](https://user-images.githubusercontent.com/40679769/142097906-6e6a5bc8-f86d-4a4c-b026-6f0973a7d85e.png)

**Comment by xinsuinizhuan** [comment]
> 
> 
> @xinsuinizhuan The PR is on review. #593
> 
> Prerequisites and how to convert commands (and improved end2end code) are included.

where, i can't find it?
![图片](https://user-images.githubusercontent.com/40679769/142117697-5f1072e4-3bff-4fc6-899f-ac15d459a20d.png)
![图片](https://user-images.githubusercontent.com/40679769/142117907-c0bc8527-25c5-4833-a078-237cd4bfd6e0.png)
![图片](https://user-images.githubusercontent.com/40679769/142118041-adf5b770-8d38-48d2-822a-b64e8f750c4f.png)

**Comment by apiaccess21** [comment]
@xinsuinizhuan 
What's the hurry? 

You can switch to "commits" tab and click link to code, than turn on the rich diff view (to the right of top of the viewer).
[So you'll get this link](https://github.com/open-mmlab/mmocr/pull/593/commits/36717b852a985bfa9235c207af11adf1f08ca9b4?short_path=7f6254f#diff-7f6254f34e124b6ff67f63aacb73b5252aa8e2b8afe712f48cdd3b32a24f908c)

**Comment by gaotongxiao** [comment]
@xinsuinizhuan You can preview this section in https://mmocr--593.org.readthedocs.build/en/593/deployment.html#c-inference-example-with-opencv

**Comment by gaotongxiao** [comment]
@apiaccess21 Thanks for your great PR!
