### ISSUE TITLE
SDMGR Paper vs Implementation

### ISSUE THREAD

**Issue by amitbcp** [open-mmlab/mmocr#491]
@cuhk-hbsun In the paper , it's discussed that we used Bi-LSTM for text embeddings, but recently we were trying to make some changes in the head and came across this : 
https://github.com/open-mmlab/mmocr/blob/main/mmocr/models/kie/heads/sdmgr_head.py L24

Seems for the LSTM the bi-directional flag is off and we don't pass it from the config file aswell. So essentially we are training the LSTM in directional fashion.

Is there any other place where we are updating it or default training is with false itself ?

**Comment by wdsd641417025** [comment]
https://github.com/open-mmlab/mmocr/blob/38bdc10f228a7c84a3604169ee6c9209b3b993f6/configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py#L73
bbox_head=dict(
        type='SDMGRHead', visual_dim=16, num_chars=92, num_classes=26, **bidirectional=True**)

The parameters not adding in config mean using default setting. You can change default parameters of SDMGRHead by adding them in bbox_head.

**Comment by amitbcp** [comment]
@wdsd641417025 I get that part. But, I wanted to confirm that the original results in the paper, did that use bi-directional LSTM or just single direction ?

**Comment by cuhk-hbsun** [comment]
@amitbcp Thanks for your question. The results in the paper used bi-directional LSTM. But we found that there is no big difference between `bidirectional=True` and `bidirectional=False`. You can have a try using `bidirectional=True` to train the model and see the results.

**Comment by amitbcp** [comment]
Thanks for the info @cuhk-hbsun
