### ISSUE TITLE
Arabic text data

### ISSUE THREAD

**Issue by haythemBD** [open-mmlab/mmocr#499]
**Describe the feature**

**Motivation**
Hello Community, I want to ask you if MMOCR supports the arabic text data?

**Comment by gaotongxiao** [comment]
Sure, but you need to prepare Arabic dataset and dictionary yourself.

**Comment by yauauau** [comment]
How would I know so I can look

**Comment by gaotongxiao** [comment]
You should prepare a dictionary file in txt where each line has a single Arabic character. Then you need to change the config of `label_convertor` of the model that you want to train. For example, https://github.com/open-mmlab/mmocr/blob/03720f46c328751fc11640f2851fe0b242ee0cc9/configs/textrecog/nrtr/nrtr_r31_academic.py#L6 configures `label_convertor` in NRTR. You should replace `dict_type=...` with `dict_file=PATH_TO_YOUR_DICT` to use your custom dictionary. You can find its implementation in https://github.com/open-mmlab/mmocr/blob/4ecd0cea8ab240977032ab8f62283f4f914b8efa/mmocr/models/textrecog/convertors/base.py#L24

**Comment by arminbiglari** [comment]
Hello, did you achieve good results for recognition Arabic datasets?

**Comment by sepehratwork** [comment]
> Hello, I just changed the dictionary as you said but I got very low accuracy, 45% Why?! did you achieve good results for recognition Arabic datasets? or anyone even tried to train SATRN-Small network on Persian or Arabic datasets?

حاجی ریپوشون به درد نمیخوره

**Comment by gaotongxiao** [comment]
@arminbiglari Sorry for the late reply. Arabic might be ignored by our evaluation metric if not explicitly included in the charset: https://github.com/open-mmlab/mmocr/issues/289#issuecomment-876234340

**Comment by gaotongxiao** [comment]
I'm closing this issue, feel free to reopen it if we have any follow-up discussion
