### ISSUE TITLE
Simplify the installation procedure 

### ISSUE THREAD

**Issue by jeffreykuang** [open-mmlab/mmocr#50]
**Describe the feature**

**Motivation**
mmocr installation needs to compile c++ and cuda code.
We'd better moving the c++/cuda functions or ops to mmcv. 

1.   assign_pixels  in panet
2.   estimate_text_confidence in panet
3.  get_pixel_num in panet
4.  pse in psenet
5.  rroi align

**Related resources**
Nil

**Additional context**
Nil

If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by Zumbalamambo** [comment]
+1 This is the most hardest installation I have encountered recently... Too much of dependencies and dependencies have sub dependencies which makes the code unmaintainable.
