### ISSUE TITLE
How to modify the color of the visualization result

### ISSUE THREAD

**Issue by whynot08** [open-mmlab/mmocr#504]
When I run the following code, the text proposals are green, how I can change the color from green to red ,thanks
sh /ghome/huyc/mmocr_drrg/tools/test_imgs.sh /gdata1/huyc/work_dirs/swin_drrg/totaltext_1200e_small/drrg_swin_1200e_totaltext.py /gdata1/huyc/work_dirs/swin_drrg/totaltext_1200e_small/epoch_1060.pth /gdata1/huyc/totaltext/imgs/test /gdata1/huyc/totaltext/imgs/img_list.txt /ghome/huyc/mmocr_2/data/icdar2015/imgs/262622_totaltext_result/

**Comment by gaotongxiao** [comment]
You can modify the color here https://github.com/open-mmlab/mmocr/blob/31f1c007c0c294ea5398a87b342b1fd18c29ee4e/mmocr/core/visualize.py#L79

**Comment by whynot08** [comment]
> You can modify the color here
> 
> https://github.com/open-mmlab/mmocr/blob/31f1c007c0c294ea5398a87b342b1fd18c29ee4e/mmocr/core/visualize.py#L79

I have modified, but it didn't work.

**Comment by gaotongxiao** [comment]
You should override the argument `bbox_color` in `model.show_result` in your test script. See the implementation here https://github.com/open-mmlab/mmocr/blob/31f1c007c0c294ea5398a87b342b1fd18c29ee4e/mmocr/models/textdet/detectors/text_detector_mixin.py#L39

**Comment by whynot08** [comment]
> You should override the argument `bbox_color` in `model.show_result` in your test script. See the implementation here
> 
> https://github.com/open-mmlab/mmocr/blob/31f1c007c0c294ea5398a87b342b1fd18c29ee4e/mmocr/models/textdet/detectors/text_detector_mixin.py#L39

It works, thank you so much
