### ISSUE TITLE
The Link of the pretrained weight of DBNet CTW1500 is wrong.

### ISSUE THREAD

**Issue by Bovey0809** [open-mmlab/mmocr#51]
Please check the address of the [DBnetCTW1500](https://download.openmmlab.com/mmocr/textdet/dbnet/dbnet_r18_fpnc_sbn_1200e_icdar2015_20210329-ba3ab597.pth) provided in https://mmocr.readthedocs.io/en/latest/textdet_models.html, the weight is for ICDAR2015, not CTW1500.

**Comment by jeffreykuang** [comment]
Sorry for typo,  it is actually the model of res18 trained on ic15.  We will revise the readme document soon.
