### ISSUE TITLE
Validation log

### ISSUE THREAD

**Issue by yjLeeee** [open-mmlab/mmocr#511]
I run this code and i get the validation log for each epoch.

But i want to get the validation log for each iteration.

{"mode": "train", "epoch": 1, "iter": 31600, "lr": 0.0003, "memory": 16599, "data_time": 0.00201, "loss_ce": 0.01473, "loss": 0.01473, "time": 0.75464}
{"mode": "train", "epoch": 1, "iter": 31605, "lr": 0.0003, "memory": 16599, "data_time": 0.06057, "loss_ce": 0.01855, "loss": 0.01855, "time": 2.37718}
{"mode": "train", "epoch": 1, "iter": 31610, "lr": 0.0003, "memory": 16599, "data_time": 0.07567, "loss_ce": 0.01279, "loss": 0.01279, "time": 0.61418}
{"mode": "val", "epoch": 1, "iter": 959, "lr": 0.0003, "0_word_acc": 0.0617, "0_word_acc_ignore_case": 0.8293, "0_word_acc_ignore_case_symbol": 0.9257, "0_char_recall": 0.9748, "0_char_precision": 0.9715, "0_1-N.E.D": 0.9708, "1_word_acc": 0.8655, "1_word_acc_ignore_case": 0.8655, "1_word_acc_ignore_case_symbol": 0.8779, "1_char_recall": 0.9618, "1_char_precision": 0.9705, "1_1-N.E.D": 0.9545, "2_word_acc": 0.2857, "2_word_acc_ignore_case": 0.9261, "2_word_acc_ignore_case_symbol": 0.936, "2_char_recall": 0.9861, "2_char_precision": 0.9805, "2_1-N.E.D": 0.967, "3_word_acc": 0.1261, "3_word_acc_ignore_case": 0.7694, "3_word_acc_ignore_case_symbol": 0.7992, "3_char_recall": 0.9349, "3_char_precision": 0.9254, "3_1-N.E.D": 0.9137, "4_word_acc": 0.0, "4_word_acc_ignore_case": 0.8124, "4_word_acc_ignore_case_symbol": 0.8264, "4_char_recall": 0.9316, "4_char_precision": 0.9466, "4_1-N.E.D": 0.9246, "5_word_acc": 0.1458, "5_word_acc_ignore_case": 0.8056, "5_word_acc_ignore_case_symbol": 0.816, "5_char_recall": 0.9116, "5_char_precision": 0.9315, "5_1-N.E.D": 0.9161}

I want to print {"mode": "val", ...} for each iter, not each epoch.
How can i change the option???

**Comment by gaotongxiao** [comment]
You should be able to see something like the following line in your model's config:
```
evaluation = dict(interval=1, metric=...)
```
which specifies the arguments being passed to `EvalHook` in MMCV. To call the evaluation hook every iteration, you only need to specify one more argument:
```
evaluation = dict(interval=1, by_epoch=False, metric=...)
```
If you want to learn more available parameters of `EvalHook`, check out its docstring [here](https://github.com/open-mmlab/mmcv/blob/be6541d480be3490dbf8acf9f067b79f5f496cd1/mmcv/runner/hooks/evaluation.py#L13)
