### ISSUE TITLE
‘Img_metas’ is a non-iterative object. Is this a bug?

### ISSUE THREAD

**Issue by kleopard** [open-mmlab/mmocr#513]
On the line 95 of file **'mmocr/mmocr/models/textrecog/recognizer/encode_decode_recognizer.py'**

`for img_meta in img_metas:`

When i train with 'mmocr/configs/textrecog/robust_scanner/robustscanner_r31_academic.py ', an error about 'DataContainer' object is not iterable' has occurred.

Later, I found that the **Collect** pipeline is used in this configuration file, and it will put img_meta becomes the object of **DataContainer**, and **DataContainer** itself cannot be iterated.

So I wonder if this is a bug??

Can anyone help me?

Thank you!

**Comment by kleopard** [comment]
Thank you for your answer! 

You're right. I did modify it.

1. Because my machine has no GPU, I use CPU to train the model. So I modified line 68 in tools/train.py. 
`  model=model.cpu()`

2. I used my own customized data set to train. The code of the model structure has not been changed, and the pipeline has not been modified, but the configuration related to the dataset has been modified.

3. When I add **'img_metas=img_metas.data[0]'** on the line 95 of file 'mmocr/mmocr/models/textrecog/recognizer/encode_decode_recognizer.py' the model can run normally.

**Comment by gaotongxiao** [comment]
I don't think the dataset has anything to do with this bug if you have not modified anything inside the dataset class. But as I moved the model to CPU, everything still worked fine. I'll put aside this issue for now as your modification is somehow untrackable. Let me know if you encounter similar situations in the future.
