### ISSUE TITLE
RuntimeError: Only one file(not dir) is allowed in the zipfile - SATRN

### ISSUE THREAD

**Issue by naarkhoo** [open-mmlab/mmocr#516]
I am running the following
```
        python mmocr/utils/ocr.py \
                data/vivino/data/images/0.jpg \
                --output data/0_output_$recog_method.jpg \
                --det TextSnake \
                --recog SATRN \
                --print-result

```
and it returns the following error - seems it downloads the checkpoint but has problem in unpacking it.
```

Downloading: "https://download.openmmlab.com/mmocr/textrecog/satrn/satrn_academic_20210809-59c8c92d.pth" to /root/.cache/torch/hub/checkpoints/satrn_academic_20210809-59c8c92d.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 252M/252M [00:23<00:00, 11.3MB/s]
Traceback (most recent call last):
  File "mmocr/utils/ocr.py", line 692, in <module>
    main()
  File "mmocr/utils/ocr.py", line 687, in main
    ocr = MMOCR(**vars(args))
  File "mmocr/utils/ocr.py", line 356, in __init__
    recog_config, recog_ckpt, device=self.device)
  File "/mmocr/mmocr/apis/inference.py", line 44, in init_detector
    checkpoint = load_checkpoint(model, checkpoint, map_location=map_loc)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 513, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 284, in load_from_http
    filename, model_dir=model_dir, map_location=map_location)
  File "/opt/conda/lib/python3.7/site-packages/torch/hub.py", line 490, in load_state_dict_from_url
    raise RuntimeError('Only one file(not dir) is allowed in the zipfile')
RuntimeError: Only one file(not dir) is allowed in the zipfile

```

I have made sure my mmocr is the up to date by doing `git pull`

**Comment by gaotongxiao** [comment]
> mmm, I don't remember how I installed it perhaps not in development mode - s you advise me t re-insall the whole thing in development mode ?

It's quite simple - you just need to run `pip uninstall mmocr` and then `pip install -e .` in `mmocr/` folder.

> BTW - isn't a better practice to read these path from a config file instead (e.g that make file inside those folders?) :) I don't mind to do those changes if you think it is not the most stupid idea.

You mean adding a key-value pair like `model_url=CKPT_URL` in the config file to avoid hardcoding? That's a better design but I won't recommend it based on two reasons: 
1) There's no automatic way to maintain these links for now so it has been done by hand. Distributing these links could increase the maintenance difficulty; 
2) We have actually saved relevant information, including checkpoint links, to `metafiles.yml` under every model's folder (e.g. [SATRN](https://github.com/open-mmlab/mmocr/blob/4c43f3fc4729df42d073e779f50488d63bbf7bd3/configs/textrecog/satrn/metafile.yml)). Our ultimate goal is to fully utilize the information inside, but we haven't got a chance to come up an elegant way to, at the very least, use it in `ocr.py`. You are very welcome to contribute if you have any idea about it :)

Back to your question - have you checked if your `ocr.py` looks like the latest one, especially the line that I pointed to? If not, replacing it with the latest one can definitely solve your question. Make sure that your script is correctly calling the latest one.
