### ISSUE TITLE
Discussion for April Plan

### ISSUE THREAD

**Issue by innerlee** [open-mmlab/mmocr#52]
Here is a list of candidate topics that we could focus on in April. We will discuss and select **a portion** of them in a meeting later on. Feel free to add or comment on :)

### Installation
- [x] Compilation-free: Move cpps to mmcv @jeffreykuang
- [x] Simplify installation instructions @innerlee 
- [x] Release to pypi (wait for unittest) @jeffreykuang 

### Documentation
- [ ] Tutorials on fine-tuning/training on user's data
- [x] Chinese documentation @quincylin1

### Demo
- [ ] Documentation for demos
- [x] End2end demo for text detection & recognition @cuhk-hbsun 
- [x] End2end demo of KIE @innerlee 
- [x] Colab @quincylin1 
- [x] Online demo @yuexy 
- [x] Add demo cfg @innerlee @cuhk-hbsun 

### Auxiliary Tools
- [ ] Log analysis
- [ ] Model complexity
- [ ] onnx
- [ ] config printer
- [ ] model publishing

### Benchmark
- [ ] benchmarks with paddleocr, chineseocr, easyocr, chineseocr_lite
  * [ ] Speed 
  * [ ] Accuracy 
  * [x] Algorithm coverage @jeffreykuang 
  * [x] Feature set @jeffreykuang 

### Multilingual
- [ ] General discussion

### Datasets
- [ ] Improve preparation scripts & documents

### More Algorithms
- [x] NER @huaqiang
- [x] FCENet @HolyCrap96 
- [x] DRRG @HolyCrap96

**Comment by 2793145003** [comment]
Any plan about SATRN? (On Recognizing Texts of Arbitrary Shapes with 2D Self-Attention, https://github.com/Media-Smart/vedastr)

**Comment by jeffreykuang** [comment]
> Any plan about SATRN? (On Recognizing Texts of Arbitrary Shapes with 2D Self-Attention, https://github.com/Media-Smart/vedastr)

If you are interested in reimplementing it, welcome to join us!

**Comment by innerlee** [comment]
@2793145003 Thanks for the propasal, we will consider it in later iterations :D

**Comment by priyanshu-sinha-trysolvio** [comment]
@innerlee @cuhk-hbsun  Did you add the onnx support? as it is not visible in the iteration plans of May-June.

**Comment by innerlee** [comment]
Not yet. Please raise/up-vote this feature at https://github.com/open-mmlab/mmocr/issues/39 to help us prioritize

**Comment by priyanshu-sinha-trysolvio** [comment]
Done.
