### ISSUE TITLE
why the backbone is resnet31?   How to calculate the num 31? 

### ISSUE THREAD

**Issue by ezio1320** [open-mmlab/mmocr#53]
https://github1s.com/open-mmlab/mmocr/blob/HEAD/mmocr/models/textrecog/backbones/resnet31_ocr.py

i can't calculate the resnet's num is 31. 
1+1+(3×1)+(2×2)+(3×1+2×4)+(2×3) = 26

what's wrong with my process of calculating?
thank you very much if you can reply me!

**Comment by cuhk-hbsun** [comment]
In the paper, "The designed 31-layer ResNet (He et al. 2016a) is presented in Table 1" 
Pls check session "Model->ResNet CNN" in SAR paper https://arxiv.org/pdf/1811.00751.pdf

**Comment by ezio1320** [comment]
> The designed 31-layer ResNet

Thanks a lot! Your answer helps me!

The "31 layers" includes not only "conv layer", but also "maxpooling"!

**Comment by cuhk-hbsun** [comment]
yes, `Table 1` is straightforward
