### ISSUE TITLE
Error in testing SegOCR on CT80

### ISSUE THREAD

**Issue by Artif-Inteller** [open-mmlab/mmocr#536]
Hi, I was gonna test the default pretrained SegOCR model(`seg_r31_1by16_fpnocr_academic-72235b11.pth` on CT80 dataset by using `mmocr/tools/test.py`.
I already configured the default config file(`mmocr/configs/textrecog/seg/seg_r31_1by16_fpnocr_academic.py`).

When I run the test, I faced a `TypeError: 'DataContainer' object is not subscriptable.

Could you please help me with fixing this error?

Thanks
![screenshot_38](https://user-images.githubusercontent.com/77495360/138086857-4973632d-84a9-48ec-9989-419b98deac79.png)

**Comment by doem97** [comment]
> 

Hi thanks for providing cropped imgs.

Just mention, the CT80 doc is still not updated and the lmdb_converter.py is not updated in data preparing section.
