### ISSUE TITLE
Treated space as "."

### ISSUE THREAD

**Issue by KwanYu** [open-mmlab/mmocr#542]
When using MMOCR to recognize a license plate number, the situation is that, for example, the number is "SC 483", and it would fulfill the position of space with a ".", so it becomes to SCI.48 generally, sometimes SCI-483 after grayscaling, but the situation just appears in some cases, not all license plates. Anyone knows why?
![2_license_plate_3](https://user-images.githubusercontent.com/17681071/139188913-ad7ea1f5-e9c8-4fb4-a3ac-9f16cf702eda.png)

**Comment by moewiee** [comment]
You can just use any special character to add 1 dim to the output vector and reconvert it to [space] later.
