### ISSUE TITLE
SynthText preprocessing error

### ISSUE THREAD

**Issue by TNA8** [open-mmlab/mmocr#545]
I faced an error in preprocessing SynthText dataset for training of SegOCR.
I followed this instruction: https://mmocr.readthedocs.io/en/latest/datasets/recog.html
![screenshot_3](https://user-images.githubusercontent.com/58914448/139373212-e554bf5c-e4ad-45c8-b6c6-31ff1764cb5e.png)
![mmocr-error](https://user-images.githubusercontent.com/58914448/139373223-e9d93fae-19fd-4f5d-b2bc-5f3e80eda5a9.png)

Thanks in advance.

**Comment by gaotongxiao** [comment]
If there are no other follow-up comments I'll close this issue soon.
