### ISSUE TITLE
請問repeat的確切作用

### ISSUE THREAD

**Issue by p890040** [open-mmlab/mmocr#551]
您好 依照[mmocr代碼](https://github.com/open-mmlab/mmocr/blob/main/mmocr/datasets/utils/loader.py#L9-L32)

``` python
class Loader:
    """Load annotation from annotation file, and parse instance information to
    dict format with parser.
    Args:
        ann_file (str): Annotation file path.
        parser (dict): Dictionary to construct parser
            to parse original annotation infos.
        repeat (int): Repeated times of annotations.
    """

    def __init__(self, ann_file, parser, repeat=1):
        assert isinstance(ann_file, str)
        assert isinstance(repeat, int)
        assert isinstance(parser, dict)
        assert repeat > 0
        assert osp.exists(ann_file), f'{ann_file} is not exist'

        self.ori_data_infos = self._load(ann_file)
        self.parser = build_parser(parser)
        self.repeat = repeat

    def __len__(self):
        return len(self.ori_data_infos) * self.repeat
```
想請問一下**repeat**這個參數的實際作用
代碼看起來只是單純地將1張圖片*repeat數量，也就是舉例1張變成100張的感覺
請問還有其他作用嗎? 這個repeat參數的意義是?

**Comment by gaotongxiao** [comment]
You're right, `repeat` tiles the dataset for n times, which is a shortcut for training the model on this dataset for n times in an epoch.

**Comment by p890040** [comment]
@gaotongxiao 
Hi, thanks your kindly answer.
So I just make sure, repeat 100 is same as epoch *100?

**Comment by gaotongxiao** [comment]
Yes. Say the original dataset is [1, 2], and if `repeat=2`, what the model gets in an epoch is [1, 2, 1, 2].

BTW, such behavior depends on the parser. If you are building your own parser which doesn't handle those out-of-bound indexes, `repeat` makes no sense at all. https://github.com/open-mmlab/mmocr/blob/b8f7ead74cb0200ad5c422e82724ca6b2eb1c543/mmocr/datasets/utils/parser.py
