### ISSUE TITLE
swin backbone

### ISSUE THREAD

**Issue by zheli0088** [open-mmlab/mmocr#552]
你好，我想问一下  mmocr  dbnet  是否支持mmdet里面的swin backbone

**Comment by gaotongxiao** [comment]
Yes, as long as you specify `mmdet.SwinTransformer` in the config and make sure its output is in the same format as ResNet. Usually, ResNet returns a tuple of (C2, C3, C4, C5) features.

**Comment by zheli0088** [comment]
Thank you.

**Comment by zheli0088** [comment]
@gaotongxiao 
Thank you.
