### ISSUE TITLE
Excuse me, if you use sdmgr to extract key information, there are many identical and repeated categories like invoices. What if you make up the key value of the acceptance?

### ISSUE THREAD

**Issue by cjt222** [open-mmlab/mmocr#553]
Excuse me, if you use sdmgr to extract key information, there are many identical and repeated categories like invoices. What if you make up the key value of the acceptance?

**Comment by cuhk-hbsun** [comment]
> Excuse me, if you use sdmgr to extract key information, there are many identical and repeated categories like invoices. What if you make up the key value of the acceptance?

hi, please give an example (attach an image for example) to show the identical and repeated categories.

**Comment by cjt222** [comment]
Just like image https://github.com/open-mmlab/mmocr/blob/main/demo/resources/demo_kie_pred.png,so many item_value and price value is repeated. How to get key value pair in those data? I tried to match from the layout, and found that if the image is slanted, a matching error will occur

**Comment by gaotongxiao** [comment]
SDMGR only tells which text boxes should be the key or value, but can't find the relations between boxes. But PR #498 may address what you want

**Comment by gaotongxiao** [comment]
This PR has been merged. We also prepare a tutorial [here](https://mmocr.readthedocs.io/en/latest/tutorials/kie_closeset_openset.html). Hope that helps.

**Comment by ariefwijaya** [comment]
> This PR has been merged. We also prepare a tutorial [here](https://mmocr.readthedocs.io/en/latest/tutorials/kie_closeset_openset.html). Hope that helps.

@gaotongxiao tutorial link is invalid , do you have another one?
