### ISSUE TITLE
如何用文字检测中训练好的模型权重去检测实际图片中的文字？

### ISSUE THREAD

**Issue by hellmo718** [open-mmlab/mmocr#556]

**Comment by gaotongxiao** [comment]
Please go through our docs about [Demo](https://mmocr.readthedocs.io/zh_CN/latest/demo.html#example-1-text-detection).

**Comment by hellmo718** [comment]
我更换成dbnet的模型时，它报错说不支持。
ValueError: ('dbnet', 'is not a supported text detection algorthm')

**Comment by gaotongxiao** [comment]
DBNet has two available options, `DB_r15` and `DB_r50` as listed in https://mmocr.readthedocs.io/en/latest/demo.html#models

**Comment by hellmo718** [comment]
这使用的都是下载官方的权重文件，我怎么使用自己的权重文件进行检测呢

**Comment by cuhk-hbsun** [comment]
> 这使用的都是下载官方的权重文件，我怎么使用自己的权重文件进行检测呢

Just set argument `--det-ckpt`

**Comment by hellmo718** [comment]
thanks , i get it
