### ISSUE TITLE
question about pipeline

### ISSUE THREAD

**Issue by Fei-Wang** [open-mmlab/mmocr#557]
I use ```OCRDataset``` and ```ConcatDataset``` in config file.

I saw 
https://github.com/open-mmlab/mmocr/blob/5fb1268a06cd12a3c539a29612be61aabecfd3f8/mmocr/apis/inference.py#L73
and 
https://github.com/open-mmlab/mmocr/blob/5fb1268a06cd12a3c539a29612be61aabecfd3f8/mmocr/datasets/base_dataset.py#L69
both use pipeline.
Does it mean that I have to set both?
```python
train1 = dict(pipeline=train_pipeline, ...)
```
```python
data = dict(
    train=dict(type='ConcatDataset', datasets=[train1], pipeline=train_pipeline),
    val=dict(type='ConcatDataset', datasets=[valid], pipeline=valid_pipeline),
    test=dict(type='ConcatDataset', datasets=[test], pipeline=test_pipeline),
    ...)
```

**Comment by gaotongxiao** [comment]
By using `UniformConcatDataset` rather than `ConcatDataset`, you only need to specify the pipeline in `UniformConcatDataset` once and it will be applied to all concatenated datasets. See an example here: https://github.com/open-mmlab/mmocr/blob/3707d671061f4d75ba4d7357e8908fabb59f9798/configs/textrecog/nrtr/nrtr_r31_1by16_1by8_academic.py

**Comment by cuhk-hbsun** [comment]
hi @Fei-Wang , for class `ConcatDataset `, it has no arguments `pipeline`, so just set data as follows:
```python
data = dict(
    train=dict(type='ConcatDataset', datasets=[train1]),
    val=dict(type='ConcatDataset', datasets=[valid]),
    test=dict(type='ConcatDataset', datasets=[test]),
    ...)
```

If you use `UniformConcatDataset `, you can set universal pipeline for all datasets or just dataset with `pipeline=None`
```python
pipeline_1 = ...
pipeline_2 = ...
train1 = dict(pipeline=pipeline_1, ...)
train2 = dict(pipeline=None, ...)
data = dict(train=dict(type='ConcatDataset', datasets=[train1, train2], pipeline=pipeline_2))
```
For above code block, `train1` will use `pipeline_1`, `train2` will use `pipeline_2`

**Comment by Fei-Wang** [comment]
> ```python
> data = dict(
>     train=dict(type='ConcatDataset', datasets=[train1]),
>     val=dict(type='ConcatDataset', datasets=[valid]),
>     test=dict(type='ConcatDataset', datasets=[test]),
>     ...)
> ```
This will get error because https://github.com/open-mmlab/mmocr/blob/5fb1268a06cd12a3c539a29612be61aabecfd3f8/mmocr/apis/inference.py#L58
> 
> If you use `UniformConcatDataset `, you can set universal pipeline for all datasets or just dataset with `pipeline=None`
> 
> ```python
> pipeline_1 = ...
> pipeline_2 = ...
> train1 = dict(pipeline=pipeline_1, ...)
> train2 = dict(pipeline=None, ...)
> data = dict(train=dict(type='ConcatDataset', datasets=[train1, train2], pipeline=pipeline_2))
> ```
> 
> For above code block, `train1` will use `pipeline_1`, `train2` will use `pipeline_2`

This is what I want, Thank you.
