### ISSUE TITLE
How to make SynthText dataset?

### ISSUE THREAD

**Issue by ncoll** [open-mmlab/mmocr#558]
when i use my own dataset ,i need to make the annotations file like SynthText;now i have the label.txt, but how can i get  the box of each letter in a word,is there any tools or anway?

**Comment by Russ699** [comment]
Readem text/call/messages/Facebook _google,com /all passwords..from 518.536.1303.name is krista zindler..email is kristazindler47@gmail.com..

**Comment by Russ699** [comment]
> Readem text/call/messages/Facebook _google,com /all passwords..from 518.536.1303.name is krista zindler..email is [kristazindler47@gmail.com](mailto:kristazindler47@gmail.com).. to 518.569.3630../russelldup71@gmail.com

**Comment by gaotongxiao** [comment]
You need to use Labelme to annotate boxes on images, then use a script to convert the output into mmocr's format. We're cleaning up the script and it will be available soon.

**Comment by ncoll** [comment]
> You need to use Labelme to annotate boxes on images, then use a script to convert the output into mmocr's format. We're cleaning up the script and it will be available soon.

ok,thanks a lot!

**Comment by gaotongxiao** [comment]
Reopening it as a reminder :)

**Comment by ENjoy924** [comment]
for the recognition, the train file format is 

{"file_name": "1.jpg", "annotations": [{"char_box": [1111, 618, 1538, 266], "char_text": "1175648.931"}, {"char_box": [1268, 1046, 584, 291], "char_text": "19.51"}, {"char_box": [2568, 1040, 475, 290], "char_text": "7.12"}, {"char_box": [1274, 1474, 403, 278], "char_text": "14.5"}, {"char_box": [2361, 1471, 685, 278], "char_text": "271.4"}], "text": ""}
{"file_name": "2.jpg", "annotations": [{"char_box": [1124, 637, 1519, 284], "char_text": "1175648.942"}, {"char_box": [1286, 1059, 569, 281], "char_text": "19.51"}, {"char_box": [2546, 1059, 462, 275], "char_text": "7.12"}, {"char_box": [1293, 1484, 393, 271], "char_text": "14.5"}, {"char_box": [2339, 1474, 666, 281], "char_text": "271.4"}], "text": ""}

where annotations is all label in one image、 char_box is text box and char_text is text content

**Comment by gaotongxiao** [comment]
Now we have a format conversion tool for lableme https://mmocr.readthedocs.io/en/latest/tools.html#convert-annotations-from-labelme
