### ISSUE TITLE
Can i fine-tune model text recognition with different classes ?

### ISSUE THREAD

**Issue by ThorPham** [open-mmlab/mmocr#569]
My language have more  character than english (example : àáâãèéêìíòóôõùú ) . Can i fine-tune model  use weight pre-training with remove head ?

**Comment by gaotongxiao** [comment]
We can't choose which part of the model to load. But it can be accomplished by wiping out weights whose names start with `head.`:
```python
model = torch.load(PATH_TO_CKPT)
for k in model.keys():
    if k.startswith('head.'):
        del model[k]
torch.save(model, PATH_OUT)
```

BTW, loading part of the checkpoint could be an interesting feature. Ping @zhouzaida to see if it can be added to mmcv.

**Comment by cuhk-hbsun** [comment]
> My language have more character than english (example : àáâãèéêìíòóôõùú ) . Can i fine-tune model use weight pre-training with remove head ?

You can load the released model as a pre-train on your dataset by adding `load_from = "xxx"` in your configs. `load_from` will ignore the mismatched layers like `fc`.
But it cannot be called `finetune` since something changed.

**Comment by ThorPham** [comment]
Thank you sir
