### ISSUE TITLE
请问在训练过程中可以修改一些配置吗?

### ISSUE THREAD

**Issue by zhonguoliuzhe** [open-mmlab/mmocr#586]
比如lr_config, checkpoint_config, interval 这些参数是否可以在训练时手动修改呢?

**Comment by gaotongxiao** [comment]
You can do it indirectly: Save an intermediate checkpoint, then resume your training process with the new config using `--load-from` to load your checkpoint.

**Comment by zhonguoliuzhe** [comment]
> You can do it indirectly: Save an intermediate checkpoint, then resume your training process with the new config using `--load-from` to load your checkpoint.

懂了，感谢你的回复！
