### ISSUE TITLE
How to prepare the SVT dataset correctly?

### ISSUE THREAD

**Issue by williamking5** [open-mmlab/mmocr#59]
The link provided by your documentation is not available.

I have the SVT dataset, but the names and indexes do not match the test labels of yours.

![image](https://user-images.githubusercontent.com/16954932/114534539-b23d2d00-9c81-11eb-949f-46bc2c2fce80.png)

![image](https://user-images.githubusercontent.com/16954932/114534780-f03a5100-9c81-11eb-81ca-08faa5a87109.png)

![image](https://user-images.githubusercontent.com/16954932/114534819-f92b2280-9c81-11eb-98f7-3a0eef699455.png)

**Comment by cuhk-hbsun** [comment]
We will provide the scripts (crop box image from original image) soon.
