### ISSUE TITLE
How to use fp16 precision ?

### ISSUE THREAD

**Issue by saribolagh** [open-mmlab/mmocr#590]
How I can set the training mode to use fp16 precision ?

**Comment by gaotongxiao** [comment]
Add the following line to config:
```python
fp16 = dict(loss_scale=512.)
```
And it can activate the fp16 training mode. The arguments in `fp16` will be passed to [mmcv.runner.Fp16OptimizerHook](https://mmcv.readthedocs.io/en/latest/api.html#mmcv.runner.Fp16OptimizerHook)

**Comment by Auth0rM0rgan** [comment]
@gaotongxiao, Im doing text recognition with mmocr but all the model and the input are loading in FP32. I tried to load them on FP16 but I couldnt. Can you help me how to do mmocr inference with fp16??

Thanks!

**Comment by gaotongxiao** [comment]
Hi @Auth0rM0rgan, you can inference with fp16 as long as you've specified `fp16` in the config. It's handled at 
https://github.com/open-mmlab/mmocr/blob/0a1787d6bcbec25649441a1f26e928ea7158e4c4/tools/test.py#L285-L287
