### ISSUE TITLE
How to inference only detection or OCR model with batch ?

### ISSUE THREAD

**Issue by ThorPham** [open-mmlab/mmocr#594]
I want to inference independent model detection and recognition with batch size. How can i do that . Thank you

**Comment by gaotongxiao** [comment]
For inference, you can run `ocr.py` in batch mode. Please check out its [API docs](https://mmocr.readthedocs.io/en/latest/demo.html#readtext). If you only need metric results, [batch testing](https://mmocr.readthedocs.io/en/latest/testing.html#batch-testing) would be enough.

**Comment by ThorPham** [comment]
@gaotongxiao Thank you for reply . I  want to get output from each model independent to ensemble some model to increase results. So i want to time inference fast as possible .
