### ISSUE TITLE
RECOGNIZERS Registry Code Design

### ISSUE THREAD

**Issue by BuxianChen** [open-mmlab/mmocr#595]
I find the Registry RECOGNIZERS defined in mmocr/models/builder.py never be used in somewhere else, and the "recognizer" model like SARNet was registered in DETECTOR Register. Is here some reason about this code design?

**Comment by gaotongxiao** [comment]
Thanks for catching that. It's certainly a mistake from the implementation side, which we even failed to realize during the past intensive development process. Registering recognizer models to RECOGNIZERS is the right practice. We've been undergoing a massive refactoring process and this will be fixed.
