### ISSUE TITLE
could share the exported onnx model?

### ISSUE THREAD

**Issue by xinsuinizhuan** [open-mmlab/mmocr#596]
I try to convert the onnx model,but some error:
(open-mmlab) root@lllstandout-System-Product-Name:/home/lllstandout/mmocr# python ../mmocr/tools/deployment/pytorch2onnx.py --opset 14 --verify --output-file recognizer.onnx ../mmocr/configs/textrecog/satrn/satrn_small.py ./satrn_small_20211009-2cf13355.pth recog ./1.png
load checkpoint from local path: ./satrn_small_20211009-2cf13355.pth
Traceback (most recent call last):
  File "../mmocr/tools/deployment/pytorch2onnx.py", line 348, in <module>
    main()
  File "../mmocr/tools/deployment/pytorch2onnx.py", line 344, in main
    dynamic_export=args.dynamic_export)
  File "../mmocr/tools/deployment/pytorch2onnx.py", line 201, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 515, in _export
    _set_opset_version(opset_version)
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 481, in _set_opset_version
    raise ValueError("Unsupported ONNX opset version: " + str(opset_version))
ValueError: Unsupported ONNX opset version: 14

**Comment by xinsuinizhuan** [comment]
detector.onnx have exported, but the satm_small Unsupported ONNX opset version: 14, i try the 11,12,13,14,15 all of them Unsupported

**Comment by AllentDan** [comment]
Hi, what is your pytorch version? Can you export crnn successfully?

**Comment by AllentDan** [comment]
Hi, `satm_small` is not in our supported [model list](https://github.com/open-mmlab/mmocr/blob/main/docs/deployment.md#list-of-supported-models-exportable-to-onnx) that can be exported to backends. BTW, if you want to export this model, you can modify the `torch.triu` operation to other ops that can be exported to onnx. Here is a [link](https://github.com/pytorch/pytorch/issues/32968) for your information.

**Comment by xinsuinizhuan** [comment]
> 
> 
> Hi, what is your pytorch version? Can you export crnn successfully?

my python version is 3.7, i guide this :https://github.com/open-mmlab/mmocr/blob/main/docs/install.md

**Comment by xinsuinizhuan** [comment]
> 
> 
> Hi, `satm_small` is not in our supported [model list](https://github.com/open-mmlab/mmocr/blob/main/docs/deployment.md#list-of-supported-models-exportable-to-onnx) that can be exported to backends. BTW, if you want to export this model, you can modify the `torch.triu` operation to other ops that can be exported to onnx. Here is a [link](https://github.com/pytorch/pytorch/issues/32968) for your information.

what? satm_small is not support? look at this, this is guide:
![图片](https://user-images.githubusercontent.com/40679769/142359312-7ccf141b-3b5c-46ac-8cf6-472d8eb66446.png)

**Comment by xinsuinizhuan** [comment]
I am lossing, what your supported model list, to export the onnx? So, could support the exported the onnx model, i only want to have a test, but can't not covert.

**Comment by gaotongxiao** [comment]
@xinsuinizhuan Sorry for the confusion, it's a new section from our community but hasn't been thoroughly tested by our deployment team yet. You need to upgrade your PyTorch to 1.10.0 and ONNX to at least 1.9.0 in order to use opset 14. We'll notify users in the docs soon.

**Comment by xinsuinizhuan** [comment]
> 
> 
> @xinsuinizhuan Sorry for the confusion, it's a new section from our community but hasn't been thoroughly tested by our deployment team yet. You need to upgrade your PyTorch to 1.10.0 and ONNX to at least 1.9.0 in order to use opset 14. We'll notify users in the docs soon.

Could share the converted onnx models, I only want to test by onnxruntime?

**Comment by lyc728** [comment]
> Hi, what is your pytorch version? Can you export crnn successfully?

torch转onnx是只有'recog', 'det'没有kie吗？

**Comment by gaotongxiao** [comment]
@lyc728 Exporting KIE is not supported for now.

**Comment by gaotongxiao** [comment]
@xinsuinizhuan Sorry, I'm afraid that we don't have enough resources to accomplish your request, though we may provide them in the future.
