### ISSUE TITLE
Iteration Plan April-May 2021

### ISSUE THREAD

**Issue by innerlee** [open-mmlab/mmocr#60]
This captures the work we planned for the next month, namely, from mid-April to mid-May (5/15). We will improve the user experience including installation, documentation and demonstration. Besides, more algorithms will be supported. Details are

### Installation
- [x] Compilation-free: Move cpps to mmcv @jeffreykuang https://github.com/open-mmlab/mmcv/pull/993
- [x] Simplify installation instructions @jeffreykuang https://github.com/open-mmlab/mmocr/pull/188
- [ ] Release to pypi @jeffreykuang 

### Documentation
- [x] Chinese documentation of README @quincylin1 https://github.com/open-mmlab/mmocr/pull/77

### Demo
- [x] Documentation for demos @quincylin1 https://github.com/open-mmlab/mmocr/pull/168 https://github.com/open-mmlab/mmocr/pull/166 https://github.com/open-mmlab/mmocr/pull/151
- [x] End2end demo for text detection & recognition @cuhk-hbsun https://github.com/open-mmlab/mmocr/pull/105
- [ ] End2end demo of KIE @innerlee 
- [x] Colab @quincylin1 https://github.com/open-mmlab/mmocr/pull/147
- [ ] ~~Online demo~~ @yuexy 
- [ ] Add demo cfg @innerlee @cuhk-hbsun 

### Benchmark
- [ ] benchmarks with paddleocr, chineseocr, easyocr, chineseocr_lite
  * [ ] Algorithm coverage @jeffreykuang 
  * [ ] Feature set @jeffreykuang 

### More Algorithms
- [x] NER @HqWei https://github.com/open-mmlab/mmocr/pull/106
- [x] FCENet @Zyq-scut https://github.com/open-mmlab/mmocr/pull/133
- [x] DRRG @HolyCrap96 https://github.com/open-mmlab/mmocr/pull/189

---

### Deferred

- [ ] Online demo @yuexy 

If you got ideas on what is intersting to implement next, feel free to reply below, or request features [here](https://github.com/open-mmlab/mmocr/issues/39). Happy Research!

**Comment by manugarri** [comment]
@innerlee are you planing on making single image inference compatible with any model besides DBNET? I have been testing all of the config folder ones and its the only one that doesnt throw an exception.

**Comment by yauauau** [comment]
Yes but stop sending email to ***@***.***

**Comment by manugarri** [comment]
@yauauau  that is not how github works. I havent sent any email, just replied to the GH issue :D

**Comment by innerlee** [comment]
@manugarri Yes absolutely. The inference should be run with all configs. If you met any problem, don't hesitate to raise an issue :)

**Comment by ndcuong91** [comment]
Amazing work! I can't wait to test with end2end demo of KIE @innerlee

**Comment by manugarri** [comment]
@innerlee awesome, does that mean the project is ready to be tested with all configs for inference?

**Comment by ndcuong91** [comment]
@innerlee Hi bro, what is the status of end2end demo for KIE?

**Comment by innerlee** [comment]
@ndcuong91 Will work on it next Monday

**Comment by seekingdeep** [comment]
@innerlee @jeffreykuang
- What is the current status of the `dcn` Deformable convolution, is it fully integrated into DBNet?
 - What are the results of DBNet on CTW1500?
the main paper achieves `F-measure 83.4%`
