### ISSUE TITLE
OCR start from top left to bottom right.

### ISSUE THREAD

**Issue by sathish4ds** [open-mmlab/mmocr#601]
I have question for OCR the OCR happens from left to right instead I want to start from top left to bottom right.

**Comment by gaotongxiao** [comment]
Do you mean recognizing vertical texts? You might need to train the model from scratch and prepare your own dataset.

**Comment by sathish4ds** [comment]
not the vertical texts in the below image
![699](https://user-images.githubusercontent.com/69101781/142564970-7052bd5f-7831-498e-ad69-037887960e4a.jpg)
the output comes in this order left to right 
[{'filename': '699',
  'text': ['product: 999%',
   'serving suggestion',
   'Parve',
   'NET TW 20g(0.7',
   'verified',
   'SUGAR',
   'zeronet ETCARBS',
   'GAR',
   'natural',
   '6CALORIES',
   'Jel Dessert',
   'PEACH',
   'list',
   'Cola',
   'north',
   'PERSERVING']}]

but I need this output from left top to right bottom in this order
[{'filename': '699',
  'text', : ['product: 999%',
  'GAR', 
  'natural', 
  'PERSERVING', 
  '6CALORIES', 
  'SUGAR' 
  'zeronet ETCARBS', 
  'list', 
  'Cola', 
  'PEACH', 
  'Jel Dessert', 
  'north',
  'serving suggestion', 
  'Parve', 
  'NET TW 20g(0.7',
  'verified']}]

**Comment by gaotongxiao** [comment]
I see, you can specify `--detail` to get the bounding box coordinates of texts, in the format of [x1, y1, x2, y2...]. You will need to sort boundaries by their top-left corner points (x1, y1) and arrange them in the way you want.

**Comment by gaotongxiao** [comment]
I'm closing it as there's no update for a while.

**Comment by sathish4ds** [comment]
Thanks Tong for your help
