### ISSUE TITLE
What's the limit word count in a picture in Training Recognition Models?

### ISSUE THREAD

**Issue by bely66** [open-mmlab/mmocr#602]
I'm training a recognition model (CRNN) which can recognize multiple words (Sentences by introducing white space char).
I gathered a training data which has 200k samples ranging between (1-8 words).

My question is what would make a good range is it more than that or bigger than that?
How many epochs usually used to train such a model on this dataset size?

**Comment by gaotongxiao** [comment]
The maximum output length of CRNN depends on the width dimension of the decoder input. CRNN generally accepts input of size (32, 128) and produces 33 tokens at maximum (see https://github.com/open-mmlab/mmocr/blob/51f2d9a4c3c2ab5ae8a52fca7822660126724b21/mmocr/models/textrecog/backbones/very_deep_vgg.py#L70-L76). So your data should be fine.
I can't tell how many epochs work best for your case, but you can set it as a large number and early stop the training once the validation ACC drops. Our training logs may also be a good reference.
