### ISSUE TITLE
Need to extract key pair value

### ISSUE THREAD

**Issue by sathish4ds** [open-mmlab/mmocr#608]
Kie extract the value and what they are buy I want to have the relationship between the values 

![demo_kie](https://user-images.githubusercontent.com/69101781/142849940-26e2fea1-99d5-4398-bda8-4283886d319a.jpeg)

I Want output like 
1 Grande Meal  = 9.90
1 Sft  Tac Party PK = 10.00

like the product value with the product value

**Comment by gaotongxiao** [comment]
It can be done via [KIEOpenSet](https://mmocr.readthedocs.io/en/latest/kie_models.html#wildreceiptopenset) model. Before that please read through our [tutorial](https://mmocr.readthedocs.io/en/latest/tutorials/kie_closeset_openset.html).
