### ISSUE TITLE
KeyError: 'ori_filename'

### ISSUE THREAD

**Issue by lyc728** [open-mmlab/mmocr#619]
I  test the  kie_test_imgs.py have wrong. config (sdmgr_novisual_60e_wildreceipt)

**Comment by gaotongxiao** [comment]
I tested it on the latest version of MMOCR and everything looks fine, so I'd suggest updating MMOCR. If the issue persists, please report the bug following the error report template.

**Comment by gaotongxiao** [comment]
I'm closing this issue, but feel free to reopen it if you've caught a bug.
