### ISSUE TITLE
Number detection and recognition

### ISSUE THREAD

**Issue by Auth0rM0rgan** [open-mmlab/mmocr#635]
Hello, I wanted to ask whether the pretrained model support number detection and recognition? I tried but it couldn’t detect or recognize a number.

Thanks!

**Comment by cuhk-hbsun** [comment]
Yes, it supports number detection and recognition. Please attach one of your images here and we will figure out the problem.

**Comment by Auth0rM0rgan** [comment]
Hi @cuhk-hbsun, The numbers that I want to detect and recognize are not with the normal fonts. For example, in the following image, I want to read the number in front of bike. Which pretrained you suggest to use?
![2](https://user-images.githubusercontent.com/22752107/144203134-eea359fa-f104-4849-9a7a-e62dfbec7057.png)
Thanks!
