### ISSUE TITLE
Can we use Tesseract

### ISSUE THREAD

**Issue by sathish4ds** [open-mmlab/mmocr#637]
Hi Team,

Thanks for the excellent work I have a question can we use Tesseract ocr in place of the per-trained ocr models

Regards
Sathish

**Comment by gaotongxiao** [comment]
Thanks for asking. It's not technically impossible to develop a text recognizer wrapper for Tesseract as long as its input and output fit such a format
https://github.com/open-mmlab/mmocr/blob/d3d56182c694feafda1c1b1a84fae12c3c4dd87f/mmocr/models/textrecog/recognizer/encode_decode_recognizer.py#L121-L129

Yet it's not in our short-term plan. If you have some time and want to contribute to this part, feel free to initiate further discussion and we will help you as much as possible.
