### ISSUE TITLE
I have some custom tokens, not just a single character,each token is separated by a space in label, how to deal with these labels in code? 

### ISSUE THREAD

**Issue by yanglinxiabuaaa** [open-mmlab/mmocr#638]
annotation file is as follows :
7119.jpg ( 4 5 + 4 4 ) \times 2 \n = 8 9 \times 2 \n = 1 7 8
2113540.jpg 1 8 - 4 x = 6 \n 4 x = 1 2 \n x = 1 2 \div 4 \n x = 3
365617.jpg ( 2 5 - 6 ) \times 5 \n = 1 9 \times 5 \n = 9 5
151973.jpg \frac { 5 } { 8 } \div \frac { 1 } { 5 } = \frac { 2 5 } { 8 }

**Comment by gaotongxiao** [comment]
You may refer to https://github.com/open-mmlab/mmocr/issues/542 to deal with spaces
