### ISSUE TITLE
Error in resize?

### ISSUE THREAD

**Issue by dadada101** [open-mmlab/mmocr#639]
HI, @gaotongxiao 
https://github.com/open-mmlab/mmocr/blob/af3cb8d5d7e5b24e971d498bb41cc48012eaf7a6/mmocr/datasets/pipelines/transforms.py#L319
should be like this if min(h, w) * scale **>** self.short_size_bound:  ?

**Comment by cuhk-hbsun** [comment]
The `short_size_bound` means: the shortest edge length after resize should be larger than or equal to this bound. 
So, if the shortest edge is shorter than this bound, we need to enlarge this edge to the bound.
In conclusion, the code is correct.

**Comment by dadada101** [comment]
thanks,you mean short_size_bound is the low bound?
another confusion is :https://github.com/open-mmlab/mmocr/blob/af3cb8d5d7e5b24e971d498bb41cc48012eaf7a6/mmocr/datasets/pipelines/transforms.py#L315
here, you judge whether the image long side is larger than the long_size_bound, if it is ,you constrict it by scale1.
but after that,you resize it in https://github.com/open-mmlab/mmocr/blob/af3cb8d5d7e5b24e971d498bb41cc48012eaf7a6/mmocr/datasets/pipelines/transforms.py#L317
but after this ramdom ratio sampling ,it may be larger than long_size_bound again? is it right? should if statement be put after the ratio random sampling? @cuhk-hbsun
