### ISSUE TITLE
How to merge the "boundary_result"json and "text"json into one ?

### ISSUE THREAD

**Issue by Y-M-Y** [open-mmlab/mmocr#645]
Thank you **so much** for the open source project. I have just used this project for the last two days and have learned a lot in the process of using it.

I encountered a problem when using mmocr. In my project, I want to be able to output a json result file that contains both detection bbox and recognition text.

According to the demo in the document, I used the detection terminal command `python mmocr/utils/ocr.py 000031_crop.jpg --det PANet_IC15 --recog None --export demo/ ` and a json file containing "boundary_result" is generated.
[out_000031_boundaryresult.zip](https://github.com/open-mmlab/mmocr/files/7648696/out_000031_boundaryresult.zip)

I also used the end-to-end terminal command `python mmocr/utils/ocr.py 000031_crop.jpg --det PANet_IC15 --recog RobustScanner --export demo/` to generate a json file that only contains "text".
[out_000031_text.zip](https://github.com/open-mmlab/mmocr/files/7648699/out_000031_text.zip)

I'm wondering:
1. Do the objects in the two output json files correspond one to one? Is the order the same? If so, I can write a simple script to merge them.
2. Is there any way to output a json file containing both "boundary_result" and corresponding "text"?

Thanks again for your contribution to the mmocr!

**Comment by gaotongxiao** [comment]
Thanks! We are glad to hear that you have learned a lot from this project :) And for your questions, you just need to specify `--detail` to get the full output, which contains both boundary result and text.

**Comment by Y-M-Y** [comment]
> Thanks! We are glad to hear that you have learned a lot from this project :) And for your questions, you just need to specify `--detail` to get the full output, which contains both boundary result and text.

Thanks! It works! It really helps a lot!
