### ISSUE TITLE
question in resize

### ISSUE THREAD

**Issue by dadada101** [open-mmlab/mmocr#646]
following https://github.com/open-mmlab/mmocr/issues/639
you mean short_size_bound is the low bound?
another confusion is :https://github.com/open-mmlab/mmocr/blob/af3cb8d5d7e5b24e971d498bb41cc48012eaf7a6/mmocr/datasets/pipelines/transforms.py#L315
here, you judge whether the image long side is larger than the long_size_bound, if it is ,you constrict it by scale1.
but after that,you resize it in https://github.com/open-mmlab/mmocr/blob/af3cb8d5d7e5b24e971d498bb41cc48012eaf7a6/mmocr/datasets/pipelines/transforms.py#L317
but after this ramdom ratio sampling ,it may be larger than long_size_bound again? is it right? should if statement be put after the ratio random sampling? @cuhk-hbsun

**Comment by cuhk-hbsun** [comment]
hi @dadada101 , in the `long_short_bound`, `short_bound` is the primary concern. That is, after `keep_ratio` resize, the short size should be equal to or larger than `short_bound`. If the long edge is under `long_bound`, it will be better but don't have to.
For example, if the original size is `200 * 2000`, and we set `keep_ratio=True`, it cannot make both the long edge and short edge in the `long_short_bound`. Just make sure the short edge is larger than `short_bound` is ok.

**Comment by dadada101** [comment]
ok，but the reason why short_bound is the primary concern is for avoiding making the image too small to detect the small text?
