### ISSUE TITLE
KeyError: 'totaltext is not in the dataset registry'

### ISSUE THREAD

**Issue by AtefehBaniasadi** [open-mmlab/mmocr#647]
Hello Dear,

I faced bellow error when I try to train mm-detection with text-snake  model and total-text dataSet

**KeyError: 'totaltext is not in the dataset registry'**

Can anyone help me to address that?

Thanks in advance

**Comment by gaotongxiao** [comment]
I guess you've set your configuration like `dataset_type = 'totaltext'` which never works. To train textsnake with totaltext, you need to first convert totaltext into Icdar format (https://mmocr.readthedocs.io/en/latest/datasets/det.html#totaltext), then set your config as follows:
```python
dataset_type = 'IcdarDataset'
data_root = PATH_TO_TOTALTEXT
```

**Comment by AtefehBaniasadi** [comment]
Before anything thank you for your response

You were right I must set dataset_type with 'IcdarDataset'. I did that but Another new error has faced

** AttributeError: IcdarDataset: 'FileClient' object has no attribute 'get_local_path' **

How can I fix that?

**Comment by gaotongxiao** [comment]
Is MMCV correctly installed or needed to be upgraded? Please make sure you have followed the [installation guide](https://mmocr.readthedocs.io/en/latest/install.html) and installed all dependencies.

**Comment by AtefehBaniasadi** [comment]
Hello again,

I checked the config file again and could find what is wrong. I set the config as follows:

```
dataset_type = 'IcdarDataset'
data_root = ''/home/project/mmocr-main/mmocr/data/totaltext''
```
but when I run train.py I faced the bellow error:

AttributeError: IcdarDataset: 'FileClient' object has no attribute 'get_local_path'

**Comment by AtefehBaniasadi** [comment]
Hello again,

I checked the config file again and could find what is wrong. I set the config as follows:

```
dataset_type = 'IcdarDataset'
data_root = ''/home/project/mmocr-main/mmocr/data/totaltext''
```
but when I run train.py I faced the bellow error:

**AttributeError: IcdarDataset: 'FileClient' object has no attribute 'get_local_path'**

**Comment by AtefehBaniasadi** [comment]
Thank you for your attention,

I fixed the above error with an update of mmcv-full package to the newest version.
