### ISSUE TITLE
In multiple gpu training, how can i put the specific gpu ids

### ISSUE THREAD

**Issue by yellowjs0304** [open-mmlab/mmocr#654]
Hi, Thank you for share nice work.

I used your work. and I wanna make a training with multiple gpu.

But in your command ./dist_train.sh, there's no gpu-ids option in here. 

It looks like automatically assigned the gpus (range(0 to gpu_num) 

I wanna try 3 gpus which has 5, 6, 7 gpu ids with training.

How can i do this? Please share your tips. Thanks.

**Comment by gaotongxiao** [comment]
You can start your command with `CUDA_VISIBLE_DEVICES=5,6,7` so that only these GPUs will be exposed to the program.

**Comment by yellowjs0304** [comment]
Got it. Thank you.
