### ISSUE TITLE
Question about visualize in SATRN

### ISSUE THREAD

**Issue by yellowjs0304** [open-mmlab/mmocr#656]
HI, I used the SATRN model for recog. I trained with my custom data. And i wanna see the result, when testing.
My custom data is composed with images folder, label txt which has as below.

```
image/image001.jpg label
image/image002.jpg label2
.
.
.
```

So, I modified in my dataset config file as below.
```
test1 = dict(
    type='OCRDataset',
    img_prefix=test_img_prefix1,
    ann_file=test_ann_file1,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator='\t')),
    pipeline=None,
    test_mode=True)

test_list = [test1]
```
Here's my command.
`
CUDA_VISIBLE_DEVICES=4 python tools/test.py ./configs/textrecog/satrn/satrn_mydata.py ./work_dirs/satrn_mydata/epoch_1.pth --eval "acc" --show --show-dir ./outputs/satrn_mydata/
`

It results like this, 
![image](https://user-images.githubusercontent.com/30281608/145362483-a97aef77-7368-4d17-84d7-d017684b478a.png)

I think this is related with detection model evluation, what should i do if i wanna see the recognition model's results?

**Comment by gaotongxiao** [comment]
You can add 'img_norm_cfg" to `meta_keys` field of `Collect` in your test_pipeline.

**Comment by yellowjs0304** [comment]
Thank you for fast reply.
I can't understand exactly, are you meaning the "recog_datasets/mydata_test.py"?

In more detail,  the pipeline key in below dictionary?
```
test1 = dict(
    type='OCRDataset',
    img_prefix=test_img_prefix1,
    ann_file=test_ann_file1,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator='\t')),
    pipeline=None,
    test_mode=True)


test_list = [test1]
```

**Comment by yellowjs0304** [comment]
@gaotongxiao I'm sorry, but i can't understand.

There's img_norm_cfg in satrn_pipeline, Where i should put the img_norm_cfg?

**Comment by gaotongxiao** [comment]
Sorry for the late reply. Take our latest commit as an example (we've refactored the hierarchical structure of configs recently), you can add `img_norm_cfg` to the end of this line:
https://github.com/open-mmlab/mmocr/blob/3188e534042096e27dbd751deb83df8dedc34314/configs/_base_/recog_pipelines/satrn_pipeline.py#L41

**Comment by yellowjs0304** [comment]
Thank u for reply. @gaotongxiao 
I added the 'img_norm_cfg' below of the satrn_pipeline.py, but there's a key error
` out_file = osp.join(out_dir, img_meta['ori_filename'])
KeyError: 'ori_filename'`

So, I also added 'ori_filename' in satrn_pipeline.py, then it worked. but there's something wrong with visualize..


First, I used Korean, so there was an error in cv2.putText in korean. So i checked your visualize code, and found there's a PIL drawing function for Chinese .
I modified the "is_contain_chinese" function to always returning as True,  so I used the PIL drawing in all characters(number, english, korean ...)

this modification was okay  in inference code. But, there's an error when testing code.

![그림1](https://user-images.githubusercontent.com/30281608/145517725-6d7a9d6a-701f-44eb-b02c-4777d28583fc.jpg)

first one is the right image that i wanted, it is from inference code. second one is the wrong image, from testing code.
They all predicted well (the label is colored as black, but it is well predicted), but there's an error when loading original image for visualization. It is an black image....
could you give me some tip about this?

**Comment by yellowjs0304** [comment]
Also, This is what i modified in satrn_pipeline.py

```
img_norm_cfg = dict(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='ResizeOCR',
        height=32,
        min_width=100,
        max_width=100,
        keep_aspect_ratio=False,
        width_downsample_ratio=0.25),
    dict(type='ToTensorOCR'),
    dict(type='NormalizeOCR', **img_norm_cfg),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'filename', 'ori_shape', 'img_shape', 'text', 'valid_ratio',
            'resize_shape'
        ]),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiRotateAugOCR',
        rotate_degrees=[0, 90, 270],
        transforms=[
            dict(
                type='ResizeOCR',
                height=32,
                min_width=100,
                max_width=100,
                keep_aspect_ratio=False,
                width_downsample_ratio=0.25),
            dict(type='ToTensorOCR'),
            dict(type='NormalizeOCR', **img_norm_cfg),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=[
                    'filename', 'ori_shape', 'img_shape', 'valid_ratio',
                    'resize_shape', 'img_norm_cfg', 'ori_filename'
                ]),
        ])
]
```

Thank you for your help.

**Comment by gaotongxiao** [comment]
Could you provide more information:
- Which parts of the code are you referencing by "inference code" and "test code"? 
- Or, what were the commands resulting in the first and second pics?

**Comment by yellowjs0304** [comment]
sure, below is the information that you wanted.

Inference code mean, mmocr/utils/ocr.py file.
`python mmocr/utils/ocr.py ../raw_str_data/valid/my_data/images/image-000000081.jpg --det None --recog SATRN --output ./outputs/ --recog-config ./configs/textrecog/satrn/satrn_test.py --recog-ckpt ./work_dirs/small_dataset_test/epoch_1.pth`

Test code mean, tools/test.py file.
`CUDA_VISIBLE_DEVICES=4 python tools/test.py ./configs/textrecog/satrn/satrn_test.py ./work_dirs/small_dataset_test/epoch_1.pth --eval "acc" --show --show-dir ./outputs/satrn/`

**Comment by yellowjs0304** [comment]
Also, In Inference step, I didn't get any 'img_norm_cfg', 'ori_filename' key error yesterday.

**Comment by gaotongxiao** [comment]
Thanks for sharing the information! Inference itself does not require these keys and it works as expected. For the failure in image rendering, we find it a common problem for all text recognition models and we are working hard to locate the cause. We'll get back to you once we have some updates. You are also welcome to share more findings with us if any :)

**Comment by yellowjs0304** [comment]
I think after the image that produced by tensor2imgs must multiply 255 for visualize step, and it looks like you already did that part in [visulize file](https://github.com/open-mmlab/mmocr/blob/b04775fd78ac89e32d38ef6fbd5493dedbfd76f4/mmocr/core/visualize.py#L383), but it's really hard to debug because i don't know the whole flow of this sequence... I hope it gets resolved quickly.

**Comment by yellowjs0304** [comment]
@gaotongxiao I think this is not a good way, but I fixed it anyway.... 
I just put a line that read original file in test.py, and changed the img_show value as original image's tensor.
In my opinion  "img_show" value, it doesn't have to put the preprocessed image features.

- test.py  line number 159
```
origin_file = mmcv.imread(img_metas[0]['filename'])

h, w, _ = img_meta['img_shape']
 #img_show = img[:h, :w, :]
img_show = origin_file[:h, :w, :]
```

If you have any good way or fix this error, please let me know :)
