### ISSUE TITLE
Is there any code to display the edge strengths in an openset KIE model?

### ISSUE THREAD

**Issue by JohnReid** [open-mmlab/mmocr#658]
I'm running the openset SDMGR KIE model but I'm not seeing the connections between the keys and the values in the output.

Is there any way to generate figures such as Figure 4 in the paper?

<img width="459" alt="Screenshot 2021-12-09 at 15 14 31" src="https://user-images.githubusercontent.com/1790516/145423169-b2dbe873-c658-4445-a51d-e062c16e8ced.png">

Here is the code I am using:
```python
#!/usr/bin/env python

from pathlib import Path
from mmocr.utils.ocr import MMOCR

# Load models into memory
# config = 'configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py'
config = 'configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt_openset.py'
model = MMOCR(det='PS_CTW', recog='SAR', kie='SDMGR', kie_config=config, openset=True)

# image = Path('demo/demo_kie.jpeg')
image = Path('data/SAIL-test-documents/BT/images/16530RICC_11-000.png')
# image = Path('data/SAIL-test-documents/Tafe/images/KX2122151964-000.png')
output = Path(f'output/demo-{image.with_suffix("").name}.jpeg')

# Inference
results = model.readtext(str(image),
                         output=str(output),
                         export='export',
                         print_result=True,
                         imshow=False,
                         details=True)
print(results)
type(results)
len(results)
type(results[0])

text_results = results[0]['result']
for result in text_results:
    print(result['text'])
print(f'We have {len(text_results)} pieces of text')
```

**Comment by JohnReid** [comment]
Or figures such as this would also be great.

![3834](https://user-images.githubusercontent.com/1790516/145425380-0adb8a46-9ac0-4a98-b2d1-e1e7647c0eb5.jpeg)

**Comment by cuhk-hbsun** [comment]
![123](https://user-images.githubusercontent.com/26875266/146317487-b266e4a9-75d6-49c6-a8ef-009442f34c6e.png)

**Comment by JohnReid** [comment]
Thank you!

**Comment by xoiga123** [comment]
Did this code break?

With default kie config:
![image](https://user-images.githubusercontent.com/57395545/184312599-91507852-5491-4d5a-8593-bf6ad3afeb27.png)

With novisual_openset kie config:
![image](https://user-images.githubusercontent.com/57395545/184312933-c406d282-8009-4667-8fd8-7b557d0dc285.png)
