### ISSUE TITLE
for 646 continuing

### ISSUE THREAD

**Issue by dadada101** [open-mmlab/mmocr#668]
https://github.com/open-mmlab/mmocr/issues/646
ok，but the reason why short_bound is the primary concern is for avoiding making the image too small to detect the small text?

**Comment by cuhk-hbsun** [comment]
Yes, since the images in the dataset like icdar2015 have resolution larger than the short_bound. Of course, you can have a try to make some changes to the `resize` pipeline.

**Comment by cuhk-hbsun** [comment]
As well, in `RandomCropInstances` pipeline, the target_size is (640, 640) and we don't want to crop area outside the image.
So the shortest edge length should be equal to or larger than `short_bound`.
