### ISSUE TITLE
CRNN

### ISSUE THREAD

**Issue by lyc728** [open-mmlab/mmocr#669]
你好，关于CRNN我想问下你们做个哪些改进呢？

**Comment by cuhk-hbsun** [comment]
We just implement the original CRNN mentioned in the paper but no modification. You can make some changes like replacing the backbone.

**Comment by gaotongxiao** [comment]
We do have a CRNN variant where we add a TPS module as a preprocessor before the backbone.
https://mmocr.readthedocs.io/en/latest/textrecog_models.html#crnn-with-tps-based-stn
