### ISSUE TITLE
Build on  windows 10 error

### ISSUE THREAD

**Issue by KangolHsu** [open-mmlab/mmocr#67]
I solve some errors when build it on windows10,but i can not get through follow error:

mmocr/models/textdet/postprocess/pan.cpp(45): error C2131: 表达式的计算结果不是常数
mmocr/models/textdet/postprocess/pan.cpp(45): note: 因读取超过生命周期的变量而失败
mmocr/models/textdet/postprocess/pan.cpp(45): note: 请参见“label_num”的用法
mmocr/models/textdet/postprocess/pan.cpp(86): error C2075: “kernel_cv”: 初始化需要带括号的初始值设定项列表
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by innerlee** [comment]
We will move these parts to mmcv, and by then the building experience will be improved.
Before that, please refer to https://mmcv.readthedocs.io/en/latest/build.html?highlight=windows#build-on-windows to see if it contains useful information

**Comment by KangolHsu** [comment]
Thanks 
I solve the build error


1.pan.cpp
change “float kernel_vector[label_num][5] = {0};”
to
		int **kernel_vector;    
		kernel_vector=new int*[5];
		for(int i=0;i<5;i++)
			kernel_vector[i]=new int[label_num];


2.pse.cpp
change      "int area[label_num + 1];"
to:
		int *area;    
		area=new int[label_num+1];


3.pse.cpp
change "vector<long int> data_shape = buf.shape;"
to : "vector<long int> data_shape = {(long)buf.shape[0],(int)buf.shape[1]};"

4.pse.cpp
change "vector<long int> label_map_shape =buf_label_map.shape;"
to : "vector<long int> label_map_shape = {(long)buf_label_map.shape[0],(int)buf_label_map.shape[1]};"

**Comment by innerlee** [comment]
Thanks for your info! Would you mind making a pull request, so that your contribution would be recorded?

**Comment by yauauau** [comment]
I was just going to ask how do you do that and to receive the recording from the customers
