### ISSUE TITLE
Can onnxruntime support batch inference in deploy_test.py ?

### ISSUE THREAD

**Issue by yanglinxiabuaaa** [open-mmlab/mmocr#678]
samples_per_gpu = 1  in line 65 deploy_test.py
error as follow:
 File "/workspace/yanglinxia/mmocr/mmocr/models/textrecog/recognizer/base.py", line 66, in forward_test
   assert imgs[0].size(0) == 1, ('aug test does not support '
 AssertionError: aug test does not support inference with batch size 10

**Comment by cuhk-hbsun** [comment]
We will check it. BTW, `SAR` and `RobustScanner` are not supported exportable to ONNX. See [link](https://mmocr.readthedocs.io/en/latest/deployment.html#list-of-supported-models-exportable-to-onnx) for details.

**Comment by yanglinxiabuaaa** [comment]
my onnx_model is export from satrn_small follow the link you mentioned above

**Comment by cuhk-hbsun** [comment]
@AllentDan Please have a check.

**Comment by AllentDan** [comment]
@yanglinxiabuaaa Hi, thanks for reporting the bug. Get fixed in PR #679

**Comment by yanglinxiabuaaa** [comment]
Thank you for resolving this issue. when I tested it, Only the first batch is correct, in func simple_test of deploy_utils.py, the onnx_pred results as follows:


onnx_pred: [array([[[6.6905673e-06, 5.5716219e-03, 2.8175635e-03, ...,
         1.3657851e-08, 1.1528318e-08, 1.0327067e-07],
        [2.9538549e-08, 6.4620937e-05, 5.5341602e-06, ...,
         2.4175995e-11, 1.6648894e-11, 1.6749945e-09],
        [9.0354160e-09, 1.5449669e-09, 1.1955800e-10, ...,
         3.1967151e-13, 3.4723122e-13, 3.7744072e-11],
        ...,
        [1.2913329e-10, 2.6910531e-12, 2.1093442e-13, ...,
         2.7622936e-12, 2.4339758e-12, 7.8880860e-11],
        [3.9777996e-07, 1.4682471e-02, 2.1810094e-03, ...,
         1.3414777e-09, 1.0078124e-09, 5.2043397e-06],
        [2.3095629e-06, 1.3642127e-08, 1.2505123e-07, ...,
         8.0106798e-13, 6.8440349e-13, 1.6677536e-10]],

       [[          nan,           nan,           nan, ...,
                   nan,           nan,           nan],
        [          nan,           nan,           nan, ...,
                   nan,           nan,           nan],
        [          nan,           nan,           nan, ...,
                   nan,           nan,           nan],
        ...,
        [          nan,           nan,           nan, ...,
                   nan,           nan,           nan],
        [          nan,           nan,           nan, ...,
                   nan,           nan,           nan],
        [          nan,           nan,           nan, ...,
                   nan,           nan,           nan]],

       [[          nan,           nan,           nan, ...,
                   nan,           nan,           nan],
        [          nan,           nan,           nan, ...,
                   nan,           nan,           nan],
        [          nan,           nan,           nan, ...,
                                              

result :

**Comment by AllentDan** [comment]
Hi, have you changed any codes of mmocr, or what version of it you are using? As we've set `samples_per_gpu = 1` for testing, it is not gonna run with batch size 10. Could provide any more details please?

**Comment by yanglinxiabuaaa** [comment]
Apparently, It is correct when set samples_per_gpu =1. I changed ResizeOCR , Scale the width to 100 and the height to scale,I don't think it matters

**Comment by yanglinxiabuaaa** [comment]
@AllentDan I export onnx model with dynamic-export , dummy_input
   dummy_input = torch.randn(2, 3, 128, 100, device="cuda:0")

   with torch.no_grad():
       torch.onnx.export(
           model, dummy_input,
           output_file,
           input_names=['input'],
           output_names=['output'],
           export_params=True,
           keep_initializers_as_inputs=False,
           verbose=verbose,
           opset_version=opset_version,
           dynamic_axes=dynamic_axes)
   print(f'Successfully exported ONNX model: {output_file}')

**Comment by AllentDan** [comment]
Well, the model 'satrn' can not just use dynamic in dim-0 (or batch dim) normally as there are loops inside satrn like [here](https://github.com/open-mmlab/mmocr/blob/0a1787d6bcbec25649441a1f26e928ea7158e4c4/mmocr/models/textrecog/encoders/satrn_encoder.py#L74).

But if you still want to run it's onnx model with batch size greater than 1. You have to make sure the input tensor you use for exporting have the same batch size as  the tensors you use for onnxruntime. Besides, changing some codes aiding exporting is inevitable.

BTW, onnxruntime deployment is still experimental for mmocr and `satrn` is not in the guarantee [list](https://mmocr.readthedocs.io/en/latest/deployment.html#list-of-supported-models-exportable-to-onnx).

**Comment by Harold-lkk** [comment]
#679 can not totally fix the satrn_small onnx export with `batch_size != 1`. There are two roughly solutions:

1. export with fix batch_size and use the same batch size for inference and test.
2. replace https://github.com/open-mmlab/mmocr/blob/0a1787d6bcbec25649441a1f26e928ea7158e4c4/mmocr/models/textrecog/encoders/satrn_encoder.py#L66-L76
and
https://github.com/open-mmlab/mmocr/blob/0a1787d6bcbec25649441a1f26e928ea7158e4c4/mmocr/models/textrecog/decoders/nrtr_decoder.py#L117-L127
with fixed valid_ratios and mask (may cause not correct accuracy) for removing loop, which causes the batch problem in onnx export.

**Comment by Daisy5296** [comment]
Hi I export satrn model with fix batch_size and use the same batch size for inference and test. But I still got the batch size problem, i.e., only the first result is correct. Anyone knows why? Thanks!
