### ISSUE TITLE
0.4.0版本里，DBNet-r50的hmean有多高呢？

### ISSUE THREAD

**Issue by ahsdx** [open-mmlab/mmocr#688]
我比较了下0.4.0和0.3.0版本，发现在0.4.0版本的配置文件和0.3.0版本的配置文件有些许不同；比如0.3.0版本里dbnet_r50的
`img_norm_cfg = dict(mean=[122.67891434, 116.66876762, 104.00698793],    std=[255, 255, 255],    to_rgb=False)`，而0.4.0版本里却为`img_norm_cfg_r50dcnv2 = dict(mean=[122.67891434, 116.66876762, 104.00698793],    std=[58.395, 57.12, 57.375],    to_rgb=True)`。
**而且0.3.0版本里test_pipeline为**
![image](https://user-images.githubusercontent.com/39435512/147258798-3778b42f-ea69-4627-bfb3-a25b9e4240e7.png)
**而0.4.0版本里test_pipeline为**
![image](https://user-images.githubusercontent.com/39435512/147258867-5f1d6190-a4ed-4b2a-b2b8-ff97cb15fe49.png)
请问这样更改后，DBNet_r50的hmean是否会提升呢？

**Comment by gaotongxiao** [comment]
Yes, the hmean score was sightly higher after updating the config. You can compare the changes in our docs:
https://mmocr.readthedocs.io/en/v0.3.0/textdet_models.html#icdar2015
https://mmocr.readthedocs.io/en/latest/textdet_models.html#icdar2015

**Comment by ahsdx** [comment]
> Yes, the hmean score was sightly higher after updating the config. You can compare the changes in our docs: https://mmocr.readthedocs.io/en/v0.3.0/textdet_models.html#icdar2015 https://mmocr.readthedocs.io/en/latest/textdet_models.html#icdar2015

好的，谢谢您的解答！

**Comment by ahsdx** [comment]
> Yes, the hmean score was sightly higher after updating the config. You can compare the changes in our docs: https://mmocr.readthedocs.io/en/v0.3.0/textdet_models.html#icdar2015 https://mmocr.readthedocs.io/en/latest/textdet_models.html#icdar2015

OK, thank you for your answer! I have another question to ask you. Have you tried the configuration (test_size = (2048, 1152)) in the DB paper? The accuracy of mmocr is 3% lower than that of the paper. If I want to achieve the accuracy (87.3%) in the dbnet paper, can you give me some suggestions?

**Comment by gaotongxiao** [comment]
We have tried that but the result did not make any significant difference. Our reimplementation cannot match the acc claimed on the paper, and we were not able to identify the mismatched parts as well... That is, we are open to discussion or suggestions from our community :)

**Comment by ahsdx** [comment]
> We have tried that but the result did not make any significant difference. Our reimplementation cannot match the acc claimed on the paper, and we were not able to identify the mismatched parts as well... That is, we are open to discussion or suggestions from our community :)

Ok i got it, thank you very much for your answer
