### ISSUE TITLE
Performance of DBNet in CTW-1500？

### ISSUE THREAD

**Issue by ahsdx** [open-mmlab/mmocr#696]
Have you tried the experiment of DBNet in ctw-1500/total-text? Maybe DBNet can achieve the accuracy of paper in ctw-1500/total-text. If I want to train DBNet on curved text datasets such as ctw-1500, what changes do I need to make to dbnet?Looking forward to your reply！Thanks.

**Comment by gaotongxiao** [comment]
Not yet. Sure you can modify the config and train it on ctw1500. The quickest way is to replace the dataset config 
https://github.com/open-mmlab/mmocr/blob/a10d56cec912ba7940384d4a1cb72716969ca433/configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py#L5
with
```python
 '../../_base_/det_datasets/ctw1500.py', 
```
You might also want to check if pipeline and model match the description on the paper, depending on which variant you are trying to reproduce. You can find some general info of config [here](https://mmocr.readthedocs.io/en/latest/tutorials/config.html)

**Comment by ahsdx** [comment]
> Not yet. Sure you can modify the config and train it on ctw1500. The quickest way is to replace the dataset config
> 
> https://github.com/open-mmlab/mmocr/blob/a10d56cec912ba7940384d4a1cb72716969ca433/configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py#L5
> 
> 
> with
> ```python
>  '../../_base_/det_datasets/ctw1500.py', 
> ```
> 
> You might also want to check if pipeline and model match the description on the paper, depending on which variant you are trying to reproduce. You can find some general info of config [here](https://mmocr.readthedocs.io/en/latest/tutorials/config.html)

OK！I'll try it! Thank you very much!

**Comment by ahsdx** [comment]
> https://github.com/open-mmlab/mmocr/blob/a10d56cec912ba7940384d4a1cb72716969ca433/configs/_base_/det_pipelines/dbnet_pipeline.py#L79-L87

![image](https://user-images.githubusercontent.com/39435512/148162505-6fd79967-40c4-41d0-9065-014a57deda19.png)
I want to train ctw1500 with dbnet, but encountered some problems. What do these two img_scale mean? 

![image](https://user-images.githubusercontent.com/39435512/148163405-0c0de7a1-369e-4f5d-9404-086dd6132ca3.png)
I find some general info of config [here](https://mmocr.readthedocs.io/en/latest/tutorials/config.html). But I still don't know what the second img_scale means.

**Comment by gaotongxiao** [comment]
Thanks for pointing it out - this config is somehow confusing. As its name indicates, `Resize` resizes every input image to be the size no bigger than `img_scale`. In this case, `img_scale` in `MultiScaleFlipAug` overrides the one in `Resize` and only the first `img_scale` is actually effective. You may raise a PR to remove the second `img_scale` and prevent others from getting lost.

**Comment by ConflictPeople** [comment]
您好，请问您跑出来的性能效果是多少呀？DBNet训练CTW1500.

**Comment by ahsdx** [comment]
> 您好，请问您跑出来的性能效果是多少呀？DBNet训练CTW1500.

低得很，ResNet-50的模型只有76.1，ResNet-18的模型只有68

**Comment by ConflictPeople** [comment]
> > 你好，请问你跑出来的性能效果是多少呀？DBNetCTW1500。
> 
> 低深，ResNet-50的模型只有76.1，ResNet-18的模型只有68

是的，我之前训练也差不多是这个结果，配置文件仿照icdar2015的
