### ISSUE TITLE
训练MJ ST数据集时dataloader时快时慢

### ISSUE THREAD

**Issue by Gaoxj2020** [open-mmlab/mmocr#698]
请问你们在复现ABINet这些学术算法时训练MJ ST数据集用到的数据加载策略和现在的一致吗？你们是从HDD还是SSD上加载的数据呢？我从三个不同的平台做了如下测试：
1. SSD with 2*3090 GPUS and num workers 1 . data_time一切正常,大约在0.0x 秒
2. HDD with 4*A100 GPUS and num workers 12. data_time 时快时慢整体训练速度比1慢很多
3. HDD with 4*3090 GPUS and num workers 16. data_time 时快时慢，快的时候0.0x 秒慢的时候20几秒
所以想问一下你们，你们的平台也是在HDD上训练得吗，如果是的话是否出现dataloader 加载缓慢的问题呢？

**Comment by gaotongxiao** [comment]
We load files from ceph with SSDs. We haven't measured the performance on HDD, but a longer data_time on HDD is expected. For the third case, you should make sure your CPU and memory resources are sufficient during training.

**Comment by gaotongxiao** [comment]
Recently we received a patch from our community that might also be fixing your issue, please check it out https://github.com/open-mmlab/mmocr/pull/721
