### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by naarkhoo** [open-mmlab/mmocr#700]
I have used

`python tools/train.py configs/textrecog/seg/seg_r31_1by16_fpnocr_toy_dataset.py --work-dir seg` to use toy data to train the model.

for the test I use 

`python tools/test.py configs/textrecog/seg/seg_r31_1by16_fpnocr_toy_dataset.py seg/latest.pth --eval hmean-iou`

gives me 

```
root@Sysan:/mmocr# python tools/test.py configs/textrecog/seg/seg_r31_1by16_fpnocr_toy_dataset.py seg/latest.pth --eval hmean-iou
Use load_from_local loader
[                                                  ] 0/10, elapsed: 0s, ETA:/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:3121: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Segmentation fault (core dumped)
```

I wonder if there are other git repo that you happen know have used mmocr for their custom data ?! to me it looks a bit complicated - e.g. there are four folders under mmocr/test/ocr and each have their own format - but the manual only provide example codes for `ocr_char_ann_toy_dataset` so now I have to go and convert my own format to this.

**Comment by gaotongxiao** [comment]
I'm closing this issue since there's no update for a while.
