### ISSUE TITLE
AssertionError: MMCV==1.4.2 is used but incompatible. Please install mmcv>=1.3.8, <=1.4.0. when build dockerfile

### ISSUE THREAD

**Issue by VignetteApril** [open-mmlab/mmocr#705]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**
The following error was encountered when building docker
```shell
AssertionError: MMCV==1.4.2 is used but incompatible. Please install mmcv>=1.3.8, <=1.4.0. 
```
But the following line does not specify the version of mmcv
https://github.com/open-mmlab/mmocr/blob/a10d56cec912ba7940384d4a1cb72716969ca433/docker/Dockerfile#L16

**Bug fix**
Use the following line of code 
```dockerfile
RUN pip install mmcv-full==1.3.8 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html
```
to replace
https://github.com/open-mmlab/mmocr/blob/a10d56cec912ba7940384d4a1cb72716969ca433/docker/Dockerfile#L16

**Comment by gaotongxiao** [comment]
Hi, thanks for reporting that. But starting from 0.4.0, MMOCR has relaxed the version limit of MMCV and you should never see this assertion error as long as your MMOCR is up-to-date. Are you building the docker from scratch?

**Comment by ngaloppo** [comment]
I have a similar issue, docker image built from scratch on the main branch: 

```
AssertionError: MMCV==1.6.0 is used but incompatible. Please install mmcv>=1.3.17, <=1.5.0.
```

**Comment by gaotongxiao** [comment]
@ngaloppo It's addressed at https://github.com/open-mmlab/mmocr/pull/1192
