### ISSUE TITLE
KeyError: 'LoadImageFromFile is not in the dataset registry'

### ISSUE THREAD

**Issue by Deng-Qian** [open-mmlab/mmocr#708]
Hello, when I use DBNet training on IC15, your important [note](https://mmocr.readthedocs.io/en/latest/datasets/det.html#important-note) say that " users should use dict(type='LoadImageFromFile', color_type='color_ignore_orientation') in pipelines to change MMCV’s default loading behaviour. ",so I modify the DBNet config as follow:
`
_base_ = [
    '../../_base_/runtime_10e.py',
    '../../_base_/schedules/schedule_sgd_1200e.py',
    '../../_base_/det_models/dbnet_r50dcnv2_fpnc.py',
    '../../_base_/det_datasets/icdar2015.py',
    '../../_base_/det_pipelines/dbnet_pipeline.py'
]

train_list = {{_base_.train_list}}
test_list = {{_base_.test_list}}

train_pipeline_r50dcnv2 = {{_base_.train_pipeline_r50dcnv2}}
test_pipeline_4068_1024 = {{_base_.test_pipeline_4068_1024}}

load_from = 'checkpoints/textdet/dbnet/res50dcnv2_synthtext.pth'

data = dict(
    samples_per_gpu=8,
    workers_per_gpu=4,
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1),
    train=dict(
        **type='LoadImageFromFile',**                            #modify
        **color_type='color_ignore_orientation',**           #modify
        datasets=train_list,
        pipeline=train_pipeline_r50dcnv2),
    val=dict(
        type='UniformConcatDataset',
        datasets=test_list,
        pipeline=test_pipeline_4068_1024),
    test=dict(
        type='UniformConcatDataset',
        datasets=test_list,
        pipeline=test_pipeline_4068_1024))

evaluation = dict(interval=100, metric='hmean-iou')

`

the whole error as follows:
`2022-01-05 15:29:39,622 - mmocr - INFO - initialize DBHead with init_cfg [{'type': 'Kaiming', 'layer': 'Conv'}, {'type': 'Constant', 'layer': 'BatchNorm', 'val': 1.0, 'bias': 0.0001}]
Traceback (most recent call last):
  File "tools/train.py", line 206, in <module>
    main()
  File "tools/train.py", line 168, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/vipuser/miniconda3/envs/mmocr/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 81, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/vipuser/miniconda3/envs/mmocr/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'LoadImageFromFile is not in the dataset registry'
`

**Comment by gaotongxiao** [comment]
It's already done in the provided config
https://github.com/open-mmlab/mmocr/blob/5a8859fe6666c096b75fa44db4f6c53d81a2ed62/configs/_base_/det_pipelines/dbnet_pipeline.py#L5

And thanks for reminding me - we have refactored config structures, and the link to dbnet's config is misleading. I will update it soon.

**Comment by Deng-Qian** [comment]
> It's already done in the provided config
> 
> https://github.com/open-mmlab/mmocr/blob/5a8859fe6666c096b75fa44db4f6c53d81a2ed62/configs/_base_/det_pipelines/dbnet_pipeline.py#L5
> 
> And thanks for reminding me - we have refactored config structures, and the link to dbnet's config is misleading. I will update it soon.

ok, thank you very much!
