### ISSUE TITLE
run python mmocr/utils/ocr.py demo/demo_kie.jpeg  --det PS_CTW --recog SAR --kie SDMGR --print-result --imshow

### ISSUE THREAD

**Issue by cqray1990** [open-mmlab/mmocr#709]
utils.py:69: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
段错误 (核心已转储)

**Comment by gaotongxiao** [comment]
Are you using OpenCV 4.5.5.62? It's known to be unstable and could cause seg fault. You may roll it back to circumvent this issue (https://github.com/open-mmlab/mmocr/pull/694)

**Comment by cqray1990** [comment]
yes, opencv is OpenCV 4.5.5.62

**Comment by cqray1990** [comment]
using lower Opencv?

**Comment by cqray1990** [comment]
@gaotongxiao

**Comment by gaotongxiao** [comment]
Use `opencv-python-headless==4.5.4.60`

**Comment by cqray1990** [comment]
it's ok , and where  can i get the data of wildreceipt?

**Comment by gaotongxiao** [comment]
Please go through our [docs](https://mmocr.readthedocs.io/en/latest/datasets/kie.html).

**Comment by gaotongxiao** [comment]
I'm closing this as the question has been resolved.
