### ISSUE TITLE
这个项目支持中英文文本检测吗

### ISSUE THREAD

**Issue by xuhui1994** [open-mmlab/mmocr#712]

**Comment by cuhk-hbsun** [comment]
Yes. All the released text detection models support English detection since most of the training data is English. 
They can also detect Chinese and you can have a try.

**Comment by liuke97** [comment]
Wonder if we have codes for evaluation in open source subject?

**Comment by liuke97** [comment]
> Yes. All the released text detection models support English detection since most of the training data is English. They can also detect Chinese and you can have a try.
Wonder if we have codes for evaluation in open source subject?

**Comment by liuke97** [comment]
> Yes. All the released text detection models support English detection since most of the training data is English. They can also detect Chinese and you can have a try.

Wonder if we have codes for evaluation in open source subject?

**Comment by xuhui1994** [comment]
> Wonder if we have codes for evaluation in open source subject?

yes,can you  give a link about codes for evaluation?

**Comment by gaotongxiao** [comment]
I don't quite understand your question. If you are new to MMOCR, please take a look at our docs, especially the [getting started](https://mmocr.readthedocs.io/en/latest/getting_started.html) section and [testing](https://mmocr.readthedocs.io/en/latest/testing.html) section.
