### ISSUE TITLE
转换的tensorrt模型占的显存比pytorch的高

### ISSUE THREAD

**Issue by xuezc** [open-mmlab/mmocr#713]
检测使用了dbnet，识别使用crnn，使用pytorch推理大约占显存1500M，但是转换tensorrt后占显存7000多M，这部分有什么优化策略吗

**Comment by gaotongxiao** [comment]
@AllentDan

**Comment by gaotongxiao** [comment]
BTW, OpenMMLab has been migrating all deployment-related services to a unified repo, [MMDeploy](https://github.com/open-mmlab/mmdeploy), which are managed by our deployment team. You can raise your issue there.

**Comment by AllentDan** [comment]
> 检测使用了dbnet，识别使用crnn，使用pytorch推理大约占显存1500M，但是转换tensorrt后占显存7000多M，这部分有什么优化策略吗

What is the env and your implementation of tensorrt model in your codes? Work space can be controlled [here](https://github.com/open-mmlab/mmdeploy/blob/03ae26c91cd088806f9ab22eae4a05650404e062/configs/mmocr/text-detection/text-detection_tensorrt_dynamic-320x320-1024x1824.py#L3) in [MMDeploy](https://github.com/open-mmlab/mmdeploy)

**Comment by xuezc** [comment]
> 
pytorch: 1.8.1
TensorRT: 7.2.3.4
workspace: detect 1, recognition 2

**Comment by AllentDan** [comment]
Could you provide the code you use when testing the size of the occupied workspace?

**Comment by gaotongxiao** [comment]
I'm closing this as there's no update for a while.
