### ISSUE TITLE
Ask training details about SAR_CH

### ISSUE THREAD

**Issue by liuke97** [open-mmlab/mmocr#723]
Hello, I have read the docs about TEXT RECOGNITION MODELS, and your team give the notes below:
'For train dataset.
We did not construct distinct data groups (20 groups in [1]) to train the model group-by-group since it would render model training too complicated.
Instead, we randomly selected 2.4m patches from Syn90k, 2.4m from SynthText and 1.2m from SynthAdd, and grouped all data together. See config for details.'
I have four questions :
1.'2.4m patches from Syn90k...,' is this for Chinese ocr model or just for English model?  
2. It seems that the 'configs' link cannot be found in the folder.
3. I have read the article about MMOCR on 'zhihu',  and find the chineseocr model and its datasets on github, wonder if you can tell me some trainning details such as proportion of training and testing.
4. If  the  SAR_CH can only recognize horizontal lines?
Thank you for your reply~

**Comment by cuhk-hbsun** [comment]
1. Just for the English model.
2. The name is wrong. We will fix it. It should be `sar_r31_parallel_decoder_chinese.py`
3. We just released the Chinese model but not the training data yes.
4. Yes.
