### ISSUE TITLE
Model performance comparison: Inference Time

### ISSUE THREAD

**Issue by mmeendez8** [open-mmlab/mmocr#724]
Hi, is there any available info about inference time or fps?
I can find this in mmdetection tables, such in: 
https://github.com/open-mmlab/mmdetection/tree/master/configs/retinanet

I am trying to set up some lightweighted pipeline and I think this would really ease the task!

**Comment by gaotongxiao** [comment]
Thanks for the suggestion. We haven't been able to measure these statistics yet. But for OCR tasks, using DBNet and CRNN should be a good starting point.
