### ISSUE TITLE
文本识别支持将空格加入数据集吗

### ISSUE THREAD

**Issue by futureflsl** [open-mmlab/mmocr#725]
我看了icdar2015格式是图片路径[空格]字符串，如果我要需要识别空格，可以这么格式放吗。比如
train_image/1.jpg 1 2 3 4 5

**Comment by cuhk-hbsun** [comment]
It support `space` recognition. There are two ways now:
1. Use one special character not occuring in the dataset to replace the `space` in the gt_labels, and keep `parser["separator"]=" "` unchanged in [toy_data.py](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/toy_data.py#L18)
For example, if `^` not in your dataset, you can add it to the `dict_file` and use annotation format `train_image/1.jpg 1^2^3^4^5`. Then, you can replace `^` to space` ` back for the prediction results.
2. Change the separator between `image_file` and `gt_label` to `\t` or one special character not occuring in the gt_labels. And change `parser["separator"] = " "` to `parser["separator"] = "\t"` or something else. As well, add space ` ` to the `dict_list` in `label_convertor`.
For example, if `^` not in your dataset, you can use annotation like `train_image/1.jpg^1 2 3 4 5` and use `parser["separator"] = "^"` in [toy_data.py](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/toy_data.py#L18). And modify [line](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_models/sar.py#L2) to 
```python
type='AttnConvertor', dict_list=list('0123456789abcdefghijklmnopqrstuvwxyz '), lower=True, with_unknown=True)
```
to add space in `dict`.

**Comment by LolaWei** [comment]
thanks to your reply! actually I have already changed the seperator and change the dict chars, but still got none when predicting.here are my changes:
**train:**
train = dict(
    type='OCRDataset',
    img_prefix=train_img_prefix,
    ann_file=train_ann_file,
    loader=dict(
        #type='LmdbLoader',
         type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator='\t')),
    pipeline=None,
    test_mode=False)

**test:**
test7 = dict(
    type='OCRDataset',
    img_prefix=test_img_prefix7,
    ann_file=test_ann_file7,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator='\t')), # 注意这里的适配性,是tab键
    pipeline=None,
    test_mode=True)
