### ISSUE TITLE
能提供一个icdar2015 CRNN训练配置文件吗，官方没有提供

### ISSUE THREAD

**Issue by futureflsl** [open-mmlab/mmocr#727]
能提供一个icdar2015 CRNN训练配置文件吗，官方没有提供，自己写的也跑不起来

**Comment by cuhk-hbsun** [comment]
Do you mean just use icdar2015 data as training data? You can refer to `train3` in [ST_SA_MJ_real_train.py](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/ST_SA_MJ_real_train.py) and change [line](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/ST_SA_MJ_real_train.py#L79) to `train_list = [train3]`

**Comment by cuhk-hbsun** [comment]
But usually, we will not use only icdar2015 data as training data since it has too few images.

**Comment by futureflsl** [comment]
I got it.thinks
