### ISSUE TITLE
which model is for word detection and recognition in sentence

### ISSUE THREAD

**Issue by sayansinha2019** [open-mmlab/mmocr#733]
I cant get a model which can detect words in a sentence and recognize them out.
For eg : Input to the model -->>  Sayan Sinha    
             output--->>  SayanSinha

So, the models cant recognize space in sentences , thus can you help me how to do it.

**Comment by gaotongxiao** [comment]
All of our detection models are trained to recognize in the unit of words rather than sentences. However, you can use [this util](https://mmocr.readthedocs.io/en/latest/api.html#mmocr.utils.stitch_boxes_into_lines) to merge the results on the same line.

**Comment by sayansinha2019** [comment]
where to call this api in the code or integrate it , so as to get merged result. 
mmocr.utils.stitch_boxes_into_lines

**Comment by gaotongxiao** [comment]
You can call or use the object in `mmocr/utils/ocr.py`, please check out its guide at https://mmocr.readthedocs.io/en/latest/demo.html
