### ISSUE TITLE
about the training dataset of text reg issue

### ISSUE THREAD

**Issue by simplify23** [open-mmlab/mmocr#735]
i follow the doc to prepare text reg datasets (MJ, ST), however the provided label (alphanumeric_labels.txt （7,239,272) and label.txt (8919273) can't find about 10 pictures of both MJ and ST dataset which is downloaded from the official website. Could you please provide finished composite datasets? thanks

**Comment by simplify23** [comment]
the log is like the following:
```
prepare index 136736 with error [Errno 2] No such file or directory: 'data/mixture/SynthText/synthtext/SynthText_patch_horizontal/67/fruits_129_74_7.png'
Warning: skip broken file {'filename': '67/fruits_129_74_7.png', 'text': 'up'} with img_prefix data/mixture/SynthText/synthtext/SynthText_patch_horizontal
prepare index 3504048 with error OpenCV(4.5.4) /tmp/pip-req-build-jpmv6t9_/opencv/modules/imgcodecs/src/loadsave.cpp:814: error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'

Warning: skip broken file {'filename': './1817/2/363_actuating_904.jpg', 'text': 'actuating'} with img_prefix data/mixture/Syn90k/mnt/ramdisk/max/90kDICT32px
/share/home/ztl/anaconda3/envs/mmocr/lib/python3.7/site-packages/torchvision/transforms/functional.py:594: UserWarning: torch.lstsq is deprecated in favor of torch.linalg.lstsq and will be removed in a future PyTorch release.
torch.linalg.lstsq has reversed arguments and does not return the QR decomposition in the returned tuple (although it returns other information about the problem).
To get the qr decomposition consider using torch.linalg.qr.
The returned solution in torch.lstsq stored the residuals of the solution in the last m - n columns of the returned value whenever m > n. In torch.linalg.lstsq, the residuals in the field 'residuals' of the returned named tuple.
The unpacking of the solution, as in
X, _ = torch.lstsq(B, A).solution[:A.size(1)]
should be replaced with
X = torch.linalg.lstsq(A, B).solution (Triggered internally at  /pytorch/aten/src/ATen/LegacyTHFunctionsCPU.cpp:389.)
  res = torch.lstsq(b_imatrix, a_matrix)[0]
/share/home/ztl/anaconda3/envs/mmocr/lib/python3.7/site-packages/torchvision/transforms/functional.py:594: UserWarning: torch.lstsq is deprecated in favor of torch.linalg.lstsq and will be removed in a future PyTorch release.
torch.linalg.lstsq has reversed arguments and does not return the QR decomposition in the returned tuple (although it returns other information about the problem).
To get the qr decomposition consider using torch.linalg.qr.
The returned solution in torch.lstsq stored the residuals of the solution in the last m - n columns of the returned value whenever m > n. In torch.linalg.lstsq, the residuals in the field 'residuals' of the returned named tuple.
The unpacking of the solution, as in
X, _ = torch.lstsq(B, A).solution[:A.size(1)]
should be replaced with
X = torch.linalg.lstsq(A, B).solution (Triggered internally at  /pytorch/aten/src/ATen/LegacyTHFunctionsCPU.cpp:389.)
  res = torch.lstsq(b_matrix, a_matrix)[0]
prepare index 739919 with error 'NoneType' object has no attribute 'shape'
Warning: skip broken file {'filename': './2749/6/101_Chided_13155.jpg', 'text': 'Chided'} with img_prefix data/mixture/Syn90k/mnt/ramdisk/max/90kDICT32px
/share/home/ztl/anaconda3/envs/mmocr/lib/python3.7/site-packages/torchvision/transforms/functional.py:594: UserWarning: torch.lstsq is deprecated in favor of torch.linalg.lstsq and will be removed in a future PyTorch release.
torch.linalg.lstsq has reversed arguments and does not return the QR decomposition in the returned tuple (although it returns other information about the problem).
To get the qr decomposition consider using torch.linalg.qr.
The returned solution in torch.lstsq stored the residuals of the solution in the last m - n columns of the returned value whenever m > n. In torch.linalg.lstsq, the residuals in the field 'residuals' of the returned named tuple.

```

**Comment by gaotongxiao** [comment]
We use the origin datasets without any modification, and therefore if you find some broken files, the reason could be 1) these files are just not extracted/cropped/stored properly; 2) they have been removed from the official dataset. For MJ, you can inspect the original archive for the missing files. For ST, since our preprocessing script not only crops SynthText images but generates their gold labels, technically the generated labels should be consistent with the actual image crops. You can use this annotation to eliminate a part of errors.

**Comment by simplify23** [comment]
Could you provide the size of MJ, ST zip which is downloaded from the official website? I will check if any process has mistakes?

**Comment by simplify23** [comment]
I'm pretty sure I download the valid ST MJ zip file from the official website. Besides, I check the missing labels in MJ, 16 totally, which couldn't extract from the official zip package. In addition, I re-cropped ST but still could not find the missing label. I think the official may remove several  data, hope to get your help, thank you very much ~

The missing label in ST almost are fruits, but not all fruit dataset is 
lost. like `data/mixture/SynthText/synthtext/SynthText_patch_horizontal/67/fruits_129_44_6.png`

MJ missing label like following:
`./1881/4/225_Marbling_46673.jpg
./913/4/231_randoms_62372.jpg
./869/4/234_TRIASSIC_80582.jpg
./2489/4/221_snored_72290.jpg
./2025/2/364_SNORTERS_72304.jpg
./1817/2/363_actuating_904.jpg
./2749/6/101_Chided_13155.jpg
./2013/2/370_refract_63890.jpg
./173/2/358_BURROWING_10395.jpg
./275/6/96_hackle_34465.jpg
./2852/6/60_TOILSOME_79481.jpg
./2069/4/192_whittier_86389.jpg
./495/6/81_MIDYEAR_48332.jpg
./368/4/232_friar_30876.jpg
./2911/6/77_heretical_35885.jpg`

**Comment by gaotongxiao** [comment]
I collected these files from our copy of MJSynth and all of them are broken files. Hence, it's safe to skip these annotations.
[MJ_missing.zip](https://github.com/open-mmlab/mmocr/files/7881424/MJ_missing.zip)

For ST, please use the generated label from the script.
