### ISSUE TITLE
use new model in my project

### ISSUE THREAD

**Issue by liuke97** [open-mmlab/mmocr#738]
Hello, I met two questions:
1.I have trained a new model based on SAR_CN , and I have   'python tools/publish_model.py sar/xx(my).pth sar_r31_parallel_decoder_chineseocr_20210507.pth; and publish a model, 
I want to know how to stop 
 'load checkpoint from http path: https://download.openmmlab.com/mmocr/textrecog/sar/sar_r31_parallel_decoder_chineseocr_20210507-82194124.pth
Downloading: "https://download.openmmlab.com/mmocr/textrecog/sar/sar_r31_parallel_decoder_chineseocr_20210507-82194124.pth" to /home/lk/.cache/torch/checkpoints/sar_r31_parallel_decoder_chineseocr_20210507-82194124.pth'
In another word, I want to load my local model and dont know how to.
2.In the link( https://zhuanlan.zhihu.com/p/400578588)  you gave an example to use class 'MMOCR', and I print the result .Then I can only get '[{'filename': '0', 'text': ['SALE', 'ALLYEAR', 'SALE', 'ROUND', '7037', 'sanetakenan@nnonnew.com', '10C-HOUGHNGOWS', 'oocbcbank']}]'  and I want the detection box location also. So I want to know how to get it.
Thank you very much !

**Comment by cuhk-hbsun** [comment]
1. `tools/publish_model.py` is used to remove some metadata which is not important to make the checkpoint smaller. For self-use, it is not necessary. 
For the `Downloading xxx` message, which command do you use?
2. What's the command you use? You can use command below to have a try.
```python
import mmcv 
from mmocr.utils.ocr import MMOCR 
 
img_path = 'xxx'
det_config = 'xxx'
det_ckpt = 'xxx'
recog_config = 'xxx'
recog_ckpt = 'xxx'
ocr = MMOCR(det_config=det_config, det_ckpt=det_ckpt, recog_config=recog_config, recog_ckpt=recog_ckpt) 
results = ocr.readtext(img_path)
```

**Comment by gaotongxiao** [comment]
Please read through the docs for `mmocr/utils/ocr.py` and all your questions can be answered: https://mmocr.readthedocs.io/en/latest/demo.html
