### ISSUE TITLE
KIE model not running

### ISSUE THREAD

**Issue by sayansinha2019** [open-mmlab/mmocr#745]
oad checkpoint from http path: https://download.openmmlab.com/mmocr/textdet/psenet/psenet_r50_fpnf_600e_ctw1500_20210401-216fed50.pth
/home/sayan/Desktop/mmocr/mmocr/apis/inference.py:50: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
load checkpoint from http path: https://download.openmmlab.com/mmocr/textrecog/sar/sar_r31_parallel_decoder_academic-dba3a4a3.pth
/home/sayan/Desktop/mmocr/mmocr/apis/inference.py:50: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
load checkpoint from http path: https://download.openmmlab.com/mmocr/kie/sdmgr/sdmgr_unet16_60e_wildreceipt_20210520-7489e6de.pth
/home/sayan/anaconda3/envs/ocr/lib/python3.7/site-packages/mmdet/datasets/utils.py:69: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
/home/sayan/Desktop/mmocr/mmocr/datasets/kie_dataset.py:46: UserWarning: KIEDataset is only initialized as a downstream demo task of text detection and recognition without an annotation file.
  'without an annotation file.', UserWarning)
Traceback (most recent call last):
  File "mmocr/utils/ocr.py", line 717, in <module>
    main()
  File "mmocr/utils/ocr.py", line 713, in main
    ocr.readtext(**vars(args))
  File "mmocr/utils/ocr.py", line 429, in readtext
    self.detect_model, self.recog_model, kie_model=self.kie_model)
  File "mmocr/utils/ocr.py", line 537, in det_recog_kie_inference
    dict_file=kie_model.cfg.data.test.dict_file)
  File "/home/sayan/Desktop/mmocr/mmocr/datasets/kie_dataset.py", line 62, in __init__
    for ind, line in enumerate(list_from_file(dict_file), 1)
  File "/home/sayan/Desktop/mmocr/mmocr/utils/fileio.py", line 35, in list_from_file
    with open(filename, 'r', encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/wildreceipt/dict.txt'

**Comment by cuhk-hbsun** [comment]
For the error "FileNotFoundError: [Errno 2] No such file or directory: 'data/wildreceipt/dict.txt'"

Do you download the dataset [wildreceipt](https://download.openmmlab.com/mmocr/data/wildreceipt.tar) and put it under `data`?
