### ISSUE TITLE
Training Datasets

### ISSUE THREAD

**Issue by Auth0rM0rgan** [open-mmlab/mmocr#748]
Hello, 
I have a question about training dataset. I would like to retrain the CRNN recognition model with my own data and the other datasets which are provided in this repo. My question is it possible to use several datasets for training? if so, Do i need to merge the datasets together or do I need to do something else?

Thanks!

**Comment by cuhk-hbsun** [comment]
It is not necessary to merge multiple datasets into one. See [config](https://github.com/open-mmlab/mmocr/blob/main/configs/textrecog/sar/sar_r31_parallel_decoder_academic.py) and its [trainset](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/ST_SA_MJ_real_train.py) for an example.

**Comment by gaotongxiao** [comment]
You might also want to read tutorials on [pre-defined dataset types](https://mmocr.readthedocs.io/en/latest/tutorials/dataset_types.html) and [config file](https://mmocr.readthedocs.io/en/latest/tutorials/config.html)

**Comment by Auth0rM0rgan** [comment]
Awesome! Thanks @cuhk-hbsun, @gaotongxiao
