### ISSUE TITLE
Implementing Tesseract

### ISSUE THREAD

**Issue by AbrahamIES** [open-mmlab/mmocr#749]
**Implementing tesseract for text recognition**

**Motivation**
Tesseract has a well recognition system that can be combined well with text detectors of mmocr.
I had problems with no spaces recognized on lines pf text but was solved using mmocr detector+tesseract

I would like to integrate, can you help me?

**Comment by gaotongxiao** [comment]
Sounds great! We are glad to help. BTW, we are planning to connect to community contributors through Slack. If you feel interested, you can send an email to mmocr@openmmlab.com and I can send you the invitation link. And we can discuss the development plan there.
