### ISSUE TITLE
docker file lacks ffmpeg

### ISSUE THREAD

**Issue by Bovey0809** [open-mmlab/mmocr#75]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
The mmocr docker file can't passed "pytest" due to libgl.so.1 not found.

**Reproduction**

1. What command or script did you run?

```bash
docker build -t docker/ .
pytest
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No, I fixed it by adding  "RUN apt-get install ffmpeg" to dockerfile.

**Bug fix**
```
RUN apt-get update && apt-get install -y git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 ffmpeg\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by innerlee** [comment]
Thanks for the proposal. (Yes the `libgl.so.1` error is quite common for docker)
