### ISSUE TITLE
The order of points is not clockwise in test data 

### ISSUE THREAD

**Issue by AtefehBaniasadi** [open-mmlab/mmocr#761]
Hello mmocr team!
Excellent work on this project

I am trying to train textSnake on my own dataset, as far as I know, the order of the points in the CTW dataset is clockwise and the starting point is from the top left, but after training, I can not say these things about the results of the test data. find.

I mean that why   the first point in the test data  is not start from the top-left and is not clockwise ?
How can I fix this problem and get clockwise sorted data on test data just like train data?

Thanks in advance

**Comment by gaotongxiao** [comment]
CTW1500 should have all the points arranged clockwise for both training and test data. As per the inference results from TextSnake, the boundary points are generated from `cv2.findContours` at
https://github.com/open-mmlab/mmocr/blob/7874531db3965e9f3afb5356a312d4fdc43c2259/mmocr/models/textdet/postprocess/textsnake_postprocessor.py#L105
TBH I haven't even been concerned about the ordering of the points before, but it seems possible that the points are sorted in either clockwise or counter-clockwise order (https://stackoverflow.com/questions/45323590/do-contours-returned-by-cvfindcontours-have-a-consistent-orientation). You might need to perform an orientation check and decide whether to reverse the points.

Besides, in the latest MMOCR, we have implemented `mmocr.utils.sort_points` and can sort points in clockwise order. However, it is reported to be buggy in some cases and we haven't got time to fix it. We'd appreciate any comments or fixes if you would like to make!

**Comment by gaotongxiao** [comment]
I'm closing this issue, but feel free to reopen it if you have any followup questions.
