### ISSUE TITLE
CRNN can't recognize persian characters

### ISSUE THREAD

**Issue by azade-a** [open-mmlab/mmocr#765]
Hi. 
I trained CRNN on the Persian dataset and defined a dictionary for my dataset. I get inference using ocr.py code.
But all predicted characters are "?" symbol.
By the way, I got these evaluation results after 200 epochs:
- Epoch(val) [200][5200] 0_word_acc: 0.6888, 0_word_acc_ignore_case: 0.6888, 0_word_acc_ignore_case_symbol: 0.9931, 0_char_recall: 0.6157, 0_char_precision: 0.8526, 0_1-N.E.D: 0.9945
Please help me.
Thank you so much.

**Comment by gaotongxiao** [comment]
CRNN works on your training set.
Did you get the "?"s from the console output or from the figure illustration? Probably the default text-drawing utility doesn't support non-Latin characters. You may first check CRNN's raw outputs by specifying `--print-output` for inference. If the texts look fine, then change 
https://github.com/open-mmlab/mmocr/blob/34e3ff40e132499571f793e01e6ca794a0684f99/mmocr/core/visualize.py#L664
to
```python
text_vis_img = draw_texts_by_pil(img, texts, boxes)
```
