### ISSUE TITLE
How Create OCR for only number?

### ISSUE THREAD

**Issue by Yasin40** [open-mmlab/mmocr#766]
HI, 
I need train and create OCR model (text recognition) only for Numbers. How i can edit last layer to fit number of output to 11(0-9 and " ")?
please help and guide for this option.

**Comment by gaotongxiao** [comment]
It depends on the model architecture. Generally, it's not hard to squeeze the dictionary, but recognizing space is a bit tricky for now. You can find two ways to add space to the dictionary: https://github.com/open-mmlab/mmocr/issues/725#issuecomment-1010577093 
Take CRNN as an example. First follow the second way, change `parser['seperator']` to `\t` and modify your dataset accordingly. Then change `label_convertor` in `configs/_base_/recog_models/crnn.py` to
```python
label_convertor = dict(
    type='CTCConvertor', dict_list=list('0123456789 '), with_unknown=False)
```
And everything should work.
