### ISSUE TITLE
[Solution Needed] How to configure toy dataset for ABINet?

### ISSUE THREAD

**Issue by yue-cheng-wind** [open-mmlab/mmocr#767]
Hi:
I am new to deep learning and after reading the tutorial https://github.com/open-mmlab/mmocr/blob/main/demo/MMOCR_Tutorial.ipynb

I got interested in trying out the toy dataset on different models; however I got an exception when training on ABINet model. Below are the steps I did:

Since there is no ABINet toy dataset configuration, I made one at 
/mmocr/configs/textrecog/abinet/abinet_academic_toy_dataset.py, 
which I basically copied the 
[/mmocr/configs/textrecog/abinet/abinet_academic.py](https://github.com/open-mmlab/mmocr/blob/main/configs/textrecog/abinet/abinet_academic.py)

and replaced the original train/test data path with the toy data one:

```
_base_ = [
    '../../_base_/default_runtime.py',
    '../../_base_/recog_models/abinet.py',
    '../../_base_/schedules/schedule_adam_step_20e.py',
    '../../_base_/recog_pipelines/abinet_pipeline.py',
    # comment out the academic train/test data
    # '../../_base_/recog_datasets/ST_MJ_alphanumeric_train.py', 
    # '../../_base_/recog_datasets/academic_test.py'

  # configure toy_data for train & testing data using 
    '../../_base_/recog_datasets/toy_data.py'
]
```
The code will threw error when trying to build the dataset:

```
from mmocr.datasets import build_dataset
from mmocr.models import build_detector
from mmocr.apis import train_detector
import os.path as osp

# Build dataset
datasets = [build_dataset(cfg.data.train)]    # <--- exception occur

# more modes below
```
With the exception shown below, I can see that it's related to the ABINet pipeline configuration but I do not quite know the exact reason:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
     51     try:
---> 52         return obj_cls(**args)
     53     except Exception as e:

17 frames
[/usr/local/lib/python3.7/dist-packages/mmdet/datasets/pipelines/transforms.py](https://localhost:8080/#) in __init__(self, transforms, bbox_params, keymap, update_pad_shape, skip_img_without_anno)
   1392         self.aug = Compose([self.albu_builder(t) for t in self.transforms],
-> 1393                            bbox_params=self.bbox_params)
   1394 

[/usr/local/lib/python3.7/dist-packages/albumentations/core/composition.py](https://localhost:8080/#) in __init__(self, transforms, preprocessing_transforms, postprocessing_transforms, to_tensor, bbox_params, keypoint_params, additional_targets, p)
    119 
--> 120         self.bbox_format = bbox_params.get('format', None)
    121         self.bbox_label_fields = bbox_params.get('label_fields', [])

AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
     51     try:
---> 52         return obj_cls(**args)
     53     except Exception as e:

[/mmocr/mmocr/datasets/pipelines/transform_wrappers.py](https://localhost:8080/#) in __init__(self, transforms, p)
     59         assert 0 <= p <= 1
---> 60         self.transforms = Compose(transforms)
     61         self.p = p

[/usr/local/lib/python3.7/dist-packages/mmdet/datasets/pipelines/compose.py](https://localhost:8080/#) in __init__(self, transforms)
     22             if isinstance(transform, dict):
---> 23                 transform = build_from_cfg(transform, PIPELINES)
     24                 self.transforms.append(transform)

[/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
     54         # Normal TypeError does not print class name.
---> 55         raise type(e)(f'{obj_cls.__name__}: {e}')
     56 

AttributeError: Albu: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
     51     try:
---> 52         return obj_cls(**args)
     53     except Exception as e:

[/mmocr/mmocr/datasets/base_dataset.py](https://localhost:8080/#) in __init__(self, ann_file, loader, pipeline, img_prefix, test_mode)
     68         # processing pipeline
---> 69         self.pipeline = Compose(pipeline)
     70         # set group flag and class, no meaning

[/usr/local/lib/python3.7/dist-packages/mmdet/datasets/pipelines/compose.py](https://localhost:8080/#) in __init__(self, transforms)
     22             if isinstance(transform, dict):
---> 23                 transform = build_from_cfg(transform, PIPELINES)
     24                 self.transforms.append(transform)

[/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
     54         # Normal TypeError does not print class name.
---> 55         raise type(e)(f'{obj_cls.__name__}: {e}')
     56 

AttributeError: RandomWrapper: Albu: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
     51     try:
---> 52         return obj_cls(**args)
     53     except Exception as e:

[/mmocr/mmocr/datasets/uniform_concat_dataset.py](https://localhost:8080/#) in __init__(self, datasets, separate_eval, pipeline, force_apply, **kwargs)
     56                 new_datasets = datasets
---> 57         datasets = [build_dataset(c, kwargs) for c in new_datasets]
     58         super().__init__(datasets, separate_eval)

[/mmocr/mmocr/datasets/uniform_concat_dataset.py](https://localhost:8080/#) in <listcomp>(.0)
     56                 new_datasets = datasets
---> 57         datasets = [build_dataset(c, kwargs) for c in new_datasets]
     58         super().__init__(datasets, separate_eval)

[/usr/local/lib/python3.7/dist-packages/mmdet/datasets/builder.py](https://localhost:8080/#) in build_dataset(cfg, default_args)
     80     else:
---> 81         dataset = build_from_cfg(cfg, DATASETS, default_args)
    

[/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
     54         # Normal TypeError does not print class name.
---> 55         raise type(e)(f'{obj_cls.__name__}: {e}')
     56 

AttributeError: OCRDataset: RandomWrapper: Albu: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
[<ipython-input-157-aa0393f89790>](https://localhost:8080/#) in <module>()
      5 
      6 # Build dataset
----> 7 datasets = [build_dataset(cfg.data.train)]
      8 
      9 # # Build the detector

[/usr/local/lib/python3.7/dist-packages/mmdet/datasets/builder.py](https://localhost:8080/#) in build_dataset(cfg, default_args)
     79         dataset = _concat_dataset(cfg, default_args)
     80     else:
---> 81         dataset = build_from_cfg(cfg, DATASETS, default_args)
     82         # return "hererere"
     83 

[/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
     53     except Exception as e:
     54         # Normal TypeError does not print class name.
---> 55         raise type(e)(f'{obj_cls.__name__}: {e}')
     56 
     57 

**AttributeError: UniformConcatDataset: OCRDataset: RandomWrapper: Albu: 'NoneType' object has no attribute 'get'**

=====

I wonder why this error message will be thrown? And how I should configure the toy dataset training for ABINET? 

Thank you so much for your reply in advance.

**Comment by gaotongxiao** [comment]
You need to have `albumentations` installed for data augmentation steps.
```
pip install albumentations
```
To run ABINet on the toy dataset, some configurations are required to be changed.
In `configs/_base_/recog_models/abinet.py`:
```python
num_chars = 38
label_convertor = dict(
    ...
    with_unknown=True,
)
model = dict(
    ....
    loss=dict(
        type='ABILoss', enc_weight=1.0, dec_weight=1.0, fusion_weight=1.0, num_classes=num_chars),
)
```

**Comment by yue-cheng-wind** [comment]
> You need to have `albumentations` installed for data augmentation steps.
> 
> ```
> pip install albumentations
> ```
> 
> To run ABINet on the toy dataset, some configurations are required to be changed. In `configs/_base_/recog_models/abinet.py`:
> 
> ```python
> num_chars = 38
> label_convertor = dict(
>     ...
>     with_unknown=True,
> )
> model = dict(
>     ....
>     loss=dict(
>         type='ABILoss', enc_weight=1.0, dec_weight=1.0, fusion_weight=1.0, num_classes=num_chars),
> )
> ```

Thank you for the reply! I have installed `albumentations ` and also have modified the `abinet.py` file. However,  I still get the same error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
     51     try:
---> 52         return obj_cls(**args)
     53     except Exception as e:

17 frames
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
AttributeError: Albu: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
AttributeError: RandomWrapper: Albu: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
AttributeError: OCRDataset: RandomWrapper: Albu: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
     53     except Exception as e:
     54         # Normal TypeError does not print class name.
---> 55         raise type(e)(f'{obj_cls.__name__}: {e}')
     56 
     57 

AttributeError: UniformConcatDataset: OCRDataset: RandomWrapper: Albu: 'NoneType' object has no attribute 'get'

```

Do you have any suggestion how I could track the root causes? And also why I have to to the mofification on the `abinet.py` for toy dataset training?

Thank you so much for your help!!

**Comment by gaotongxiao** [comment]
I am also not sure about the reason as it works fine on my side. Did you make any changes to the code or the dataset config? Could you elaborate on the environment and the command you were using?

We modify  `abinet.py` to support the additional character "/" in the toy dataset only, otherwise, another error will prompt.

**Comment by gaotongxiao** [comment]
It's because the pre-installed `albumentations` on colab is too old to handle some exceptions. Upgrading it by `!pip install albumentations>=1.1.0` should solve this issue.

**Comment by yue-cheng-wind** [comment]
Unfortunately it still had the same error after I upgraded `albumentations `
https://colab.research.google.com/drive/1vmxO8w6Ci9RlFUqXCGl2WWcyJqDCmZxW?usp=sharing

If you have time, would you mind executing this notebook and see what's wrong with it? The installation of mmcor should take ~20mins.

**Comment by gaotongxiao** [comment]
Make sure you have restarted the runtime after upgrading `albumentations`. I've gone through all steps and it should work

**Comment by yue-cheng-wind** [comment]
Thanks a lot for confirming! I will try it again and get back to you tmw.
