### ISSUE TITLE
Segmentation fault occured when Im trying to run the third and last sample demo code

### ISSUE THREAD

**Issue by frank60229** [open-mmlab/mmocr#772]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
According to the tutorial, I followed the steps in https://mmocr.readthedocs.io/en/latest/demo.html
However, when I tried to run the third and fourth example, which is Text Detection + Recognition and KIE sample
something goes wrong
platform: CentOS 7
evn: python: 3.7, torch: 1.6.0+cu101, mmcv_full: 1.3.5
here are the results:

![11111111111](https://user-images.githubusercontent.com/99239158/153105256-33797e87-7d31-43e8-86e5-7b56422cd655.png)

**Reproduction**

1. What command or script did you run?

```none
python mmocr/utils/ocr.py demo/demo_text_ocr.jpg --print-result
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
>Nope

3. What dataset did you use?

**Environment**

1. Please run `python mmocr/utils/collect_env.py` to collect necessary environment information and paste it here.

fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.7.12 (default, Dec 22 2021, 17:18:34) [GCC 5.5.0]
CUDA available: True
GPU 0: GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (GCC) 7.5.0
PyTorch: 1.6.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0+cu101
OpenCV: 4.5.5
MMCV: 1.3.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMOCR: 0.4.0+

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.

```none
/Model/mmocr-main/v/lib/python3.7/site-packages/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor"
 pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it
 in the test data pipeline in your config file.'data pipeline in your config file.', UserWarning)
Segmentation fault
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by gaotongxiao** [comment]
The OpenCV 4.5.5 is the cause of seg fault, try downgrading it by running
```
pip install opencv-python-headless==4.5.4.60
```

Ref: https://github.com/open-mmlab/mmocr/issues/700

**Comment by frank60229** [comment]
> OpenCV 4.5.5 is the cause of seg fault, try downgrading it by running
> 
> ```
> pip install opencv-python-headless==4.5.4.60
> ```
> 
> Ref: #700

**Comment by frank60229** [comment]
> OpenCV 4.5.5 is the cause of seg fault, try downgrading it by running
> 
> ```
> pip install opencv-python-headless==4.5.4.60
> ```
> 
> Ref: #700


it works! However,  when I try to go through the last task, it goes wrong again, here are the results
the command  I ran:
>`python mmocr/utils/ocr.py demo/demo_kie.jpeg  --det PS_CTW --recog SAR --kie SDMGR --print-result`

the results:




> 
(v) (base) [root@server48 mmocr-main]# python mmocr/utils/ocr.py demo/demo_kie.jpeg  --det PS_CTW --recog SAR --kie SDMGR --print
Use load_from_http loader
/home/wht/Model/mmocr-main/mmocr/apis/inference.py:50: UserWarning: Class names are not saved in the checkpoint's meta data, uselasses by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
Use load_from_http loader
/home/wht/Model/mmocr-main/mmocr/apis/inference.py:50: UserWarning: Class names are not saved in the checkpoint's meta data, uselasses by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
Use load_from_http loader
/home/wht/Model/mmocr-main/v/lib/python3.7/site-packages/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is reby "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config
  'data pipeline in your config file.', UserWarning)
/home/wht/Model/mmocr-main/mmocr/datasets/kie_dataset.py:46: UserWarning: KIEDataset is only initialized as a downstream demo taext detection and recognition without an annotation file.
  'without an annotation file.', UserWarning)
/home/wht/Model/mmocr-main/mmocr/datasets/pipelines/box_utils.py:44: DeprecationWarning: `np.int` is a deprecated alias for the  `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.in may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the relea link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  indexes = (np.arange(N, dtype=np.int) + lefttop_idx) % N
/home/wht/Model/mmocr-main/mmocr/models/kie/extractors/sdmgr.py:162: UserWarning: show==False and out_file is not specified, onlt image will be returned
  warnings.warn('show==False and out_file is not specified, only '
{'filename': 'demo_kie', 'text': ['RHOVICACY', '8:27:32', '7/30/2012', 'Cashier:..Eric', '0rder-113533', '9.90', 'grande', '0.00BEAN', '9.90', 'Grande', '10-Bean', '0.00', 'Cannondate', '0.00', '1ONONIONIONS', 'SFtt.Tac.Party.Pk', '10.00', '12.SFTTACO', '0Taco-Party.Pack', '10.00', '12Crunchy', '0.00', '26_MediDrink', '43.94', '11.97', '3upreme', '11.07', '3/Pepperoni', '10.47', 'c 'Newsgroups:', 'SubTotal', '117.25', 'Tax', '11.02', 'Total', '128.27', 'Master', '128.27', 'Acct:Xxxxxxxxx8425', 'APPROVAL:052


and here is the  screenshot:
![111](https://user-images.githubusercontent.com/99239158/153134307-b07c7304-5031-4426-a3f9-6da36a3268d7.png)

**Comment by frank60229** [comment]
> OpenCV 4.5.5 is the cause of seg fault, try downgrading it by running
> 
> ```
> pip install opencv-python-headless==4.5.4.60
> ```
> 
> Ref: #700


it works! However,  when I try to go through the last task, it goes wrong again, here are the results
the command  I ran:
>`python mmocr/utils/ocr.py demo/demo_kie.jpeg  --det PS_CTW --recog SAR --kie SDMGR --print-result`

the results:




> 
(v) (base) [root@server48 mmocr-main]# python mmocr/utils/ocr.py demo/demo_kie.jpeg  --det PS_CTW --recog SAR --kie SDMGR --print
Use load_from_http loader
/home/wht/Model/mmocr-main/mmocr/apis/inference.py:50: UserWarning: Class names are not saved in the checkpoint's meta data, uselasses by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
Use load_from_http loader
/home/wht/Model/mmocr-main/mmocr/apis/inference.py:50: UserWarning: Class names are not saved in the checkpoint's meta data, uselasses by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
Use load_from_http loader
/home/wht/Model/mmocr-main/v/lib/python3.7/site-packages/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is reby "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config
  'data pipeline in your config file.', UserWarning)
/home/wht/Model/mmocr-main/mmocr/datasets/kie_dataset.py:46: UserWarning: KIEDataset is only initialized as a downstream demo taext detection and recognition without an annotation file.
  'without an annotation file.', UserWarning)
/home/wht/Model/mmocr-main/mmocr/datasets/pipelines/box_utils.py:44: DeprecationWarning: `np.int` is a deprecated alias for the  `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.in may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the relea link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  indexes = (np.arange(N, dtype=np.int) + lefttop_idx) % N
/home/wht/Model/mmocr-main/mmocr/models/kie/extractors/sdmgr.py:162: UserWarning: show==False and out_file is not specified, onlt image will be returned
  warnings.warn('show==False and out_file is not specified, only '
{'filename': 'demo_kie', 'text': ['RHOVICACY', '8:27:32', '7/30/2012', 'Cashier:..Eric', '0rder-113533', '9.90', 'grande', '0.00BEAN', '9.90', 'Grande', '10-Bean', '0.00', 'Cannondate', '0.00', '1ONONIONIONS', 'SFtt.Tac.Party.Pk', '10.00', '12.SFTTACO', '0Taco-Party.Pack', '10.00', '12Crunchy', '0.00', '26_MediDrink', '43.94', '11.97', '3upreme', '11.07', '3/Pepperoni', '10.47', 'c 'Newsgroups:', 'SubTotal', '117.25', 'Tax', '11.02', 'Total', '128.27', 'Master', '128.27', 'Acct:Xxxxxxxxx8425', 'APPROVAL:052


and here is the  screenshot:
![111](https://user-images.githubusercontent.com/99239158/153134307-b07c7304-5031-4426-a3f9-6da36a3268d7.png)

**Comment by cuhk-hbsun** [comment]
@frank60229 I didn't see any error message. What is the problem?

**Comment by frank60229** [comment]
@cuhk-hbsun  I solved in the group chat, thx
