### ISSUE TITLE
The hmean of DBnet in ICDAR15 is lower than which in paper

### ISSUE THREAD

**Issue by johnsonkee** [open-mmlab/mmocr#78]
I run the script and get the H-mean of DBnet in ICDAR15. I find my H-mean is 0.8343,  while it is 0.873 in the original paper(the model in the paper is DB-ResNet-50 (1152)).

Are the experiment settings different between them?

The script I use is "dbnet_r50dcnv2_fpnc_1200e_icdar2015", I have already downloaded the synthtext pretrained model.

**Comment by jeffreykuang** [comment]
> I run the script and get the H-mean of DBnet in ICDAR15. I find my H-mean is 0.8343, while it is 0.873 in the original paper(the model in the paper is DB-ResNet-50 (1152)).
> 
> Are the experiment settings different between them?
> 
> The script I use is "dbnet_r50dcnv2_fpnc_1200e_icdar2015", I have already downloaded the synthtext pretrained model.

We follow the same setting as the official code.  The pretrained model on synthtext is converted from that of the official code.
We are struggling to debug it.

**Comment by johnsonkee** [comment]
我查看了一下代码，发现我使用的测试方法为hmean-iou的时候，代码使用的计算iou的公式为IoU=(a&b)/(a|b - a&b)，我查看了dbnet的官方源码，发现官方源码使用的计算iou公式为IoU=(a&b)/(a|b)，请问是不是这里代码写错了呢？谢谢。下面是计算IoU的代码位置

https://github.com/open-mmlab/mmocr/blob/0bfda842c9a28f268e1cac962a5d1f09a4d24e1f/mmocr/core/evaluation/utils.py#L173

**Comment by jeffreykuang** [comment]
> 我查看了一下代码，发现我使用的测试方法为hmean-iou的时候，代码使用的计算iou的公式为IoU=(a&b)/(a|b - a&b)，我查看了dbnet的官方源码，发现官方源码使用的计算iou公式为IoU=(a&b)/(a|b)，请问是不是这里代码写错了呢？谢谢。下面是计算IoU的代码位置
> 
> https://github.com/open-mmlab/mmocr/blob/0bfda842c9a28f268e1cac962a5d1f09a4d24e1f/mmocr/core/evaluation/utils.py#L173

This is the correct way to calculate the union of two polygons.

In the official code, its union is computed as Plogyn(pD).union(Polygon(PG)).area. 
https://github.com/MhLiao/DB/blob/4e341f7c07005fe5cccac8f4042c03f0ef4424cb/concern/icdar2015_eval/detection/iou.py#L18
I think the two ways are equivalent.

**Comment by johnsonkee** [comment]
Hello, I read the code in "db_head.py", I find that loss_module is initialized, but it is not used in anywhere. Is it wrong?
