### ISSUE TITLE
details about det-model:FCE_IC15 

### ISSUE THREAD

**Issue by liuke97** [open-mmlab/mmocr#782]
My command: 
  import mmcv
  from mmocr.utils.ocr import MMOCR
  img = mmcv.imread('demo/test1.jpg')
  recog_config = '/home/lk/mmocr/configs/textrecog/sar/sar_r31_parallel_decoder_chinese.py'
  recog_ckpt = '/home/lk/mmocr/sar/98.pth'
  ocr = MMOCR(det='FCE_IC15', recog_config=recog_config, recog_ckpt=recog_ckpt)
 results = ocr.readtext(img)

My result:
[{'filename': '0', 'result': [{'box': [394, 200, 398, 200, 402, 200, 406, 201, 410, 201, 414, 201, 419, 201, 423, 200, 427, 200, 431, 201, 434, 202, 436, 205, 437, 208, 437, 212, 436, 215, 434, 217, 431, 219, 427, 219, 423, 219, 418, 218, 414, 217, 410, 217, 406, 217, 402, 217, 398, 218, 394, 218, 390, 218, 386, 217, 382, 217, 377, 216, 373, 216, 369, 217, 365, 217, 361, 217, 357, 217, 354, 215, 352, 212, 350, 209, 350, 206, 351, 203, 354, 200, 357, 199, 361, 199, 365, 199, 369, 200, 373, 200, 377, 201, 382, 200, 386, 200, 390, 200], 'box_score': 0.9978793859481812, 'text': '住宅出入口', 'text_score': 0.999996542930603}, {'box': [498, 819, 500, 819, 502, 819, 504, 819, 507, 819, 509, 818, 511, 818, 513, 818, 515, 819, 516, 516, 821, 517, 823, 517, 825, 517, 827, 517, 829, 516, 831, 516, 833, 515, 834, 513, 834, 512, 834, 509, 834, 507, 834, 504, 834, 502, 834, 500, 834, 498, 834, 496, 834, 495, 834, 492, 834, 490, 834, 488, 834, 485, 834, 484, 834, 482, 834, 481, 833, 480, 831, 480, 830, 480, 827, 480, 825, 480, 823, 480, 821, 481, 820, 482, 819, 483, 819, 485, 819, 487, 819, 490, 819, 492, 819, 494, 819, 496, 819], 'box_score': 0.9969935417175293, 'text': '9400', 'text_score': 0.9999997615814209},..

My questions: I want to know how to understand the numbers in box, I want to use the positon like the center(x,y) of  text box or four points position of box. But in fact every box has many numbers and I do not understand. 
Thank you for your answer,

**Comment by gaotongxiao** [comment]
Each pair of consecutive integers make up a point(x, y) of the text boundary. For example, your first boundary has the following points: (394, 200), (398, 200), (402, 200), ... And you can get the center of box by taking the average of these points.
