### ISSUE TITLE
建议标注每个数据集的用途

### ISSUE THREAD

**Issue by xuhui1994** [open-mmlab/mmocr#789]
每个数据集的用途都不一样，有些是关于英文的，有些是关于中文，有些是关于其他语言的，有些是混合语言，建议在每个数据集或者与训练模型后面添加语言类型，这样使得学习者更好的找到对应的数据集或者预训练模型。

**Comment by gaotongxiao** [comment]
It's a good suggestion. Now we only support English datasets but sooner multilingual datasets will be supported. By then we will mark the available language options for each dataset.
