### ISSUE TITLE
Evaluateing {dataset.ann_file} with ' AttributeError: 'ConcatDataset' object has no attribute 'ann_file'

### ISSUE THREAD

**Issue by sjtu-cz** [open-mmlab/mmocr#792]
Traceback (most recent call last):
  File "tools/train.py", line 224, in <module>
    main()
  File "tools/train.py", line 220, in main
    meta=meta)
  File "/mmocr/mmocr/apis/train.py", line 155, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/usr/local/lib/python3.6/dist-packages/mmdet/core/evaluation/eval_hooks.py", line 58, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/hooks/evaluation.py", line 362, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmdet/datasets/dataset_wrappers.py", line 124, in evaluate
    f'
Evaluateing {dataset.ann_file} with '
AttributeError: 'ConcatDataset' object has no attribute 'ann_file'

**Comment by sjtu-cz** [comment]
目前识别模块的evalute部分似乎有问题，感觉和mmdet模块的dataset存在一些不兼容的问题。

**Comment by gaotongxiao** [comment]
Could you provide all the necessary information and the config you were using following the issue template?

**Comment by sjtu-cz** [comment]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**
A clear and concise description of what the bug is.
the rec test process failed with the above err;

**Reproduction**

1. What command or script did you run?
python3 tools/test.py configs/textrecog/crnn/crnn_wxocrmt_hq.py ${HOME}/dbnet_rec_wxocrmt_hq/latest.pth --eval acc
```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmocr/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.

```none
A placeholder for traceback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by sjtu-cz** [comment]
Thanks for your error report and we appreciate it a lot.

Describe the bug
A clear and concise description of what the bug is.
the rec test process failed with the above err;

Reproduction


python3 tools/test.py configs/textrecog/crnn/crnn_wxocrmt_hq.py ${HOME}/dbnet_rec_wxocrmt_hq/latest.pth --eval acc
A placeholder for the command.
Did you make any modifications on the code or config? Did you understand what you have modified?
What dataset did you use?
Environment

Please run python mmocr/utils/collect_env.py to collect necessary environment information and paste it here.
You may add addition that may be helpful for locating the problem, such as
How you installed PyTorch [e.g., pip, conda, source]
Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)
Error traceback
If applicable, paste the error traceback here.

A placeholder for traceback.
Bug fix
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by sjtu-cz** [comment]
**Describe the bug**
the rec model (crnn) evaluate failed.

**Reproduction**

1. What command or script did you run?

```none
python3 tools/test.py configs/textrecog/crnn/crnn_wxocrmt_hq.py ${HOME}/crnn_rec_wxocrmt_hq/latest.pth --eval acc
```

**Environment**

sys.platform: linux
Python: 3.6.9 (default, Dec  8 2021, 21:08:43) [GCC 8.4.0]
CUDA available: True
GPU 0: GRID T4-8C
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0
OpenCV: 4.5.4
MMCV: 1.4.5
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMOCR: 0.4.1+5582e17


**Error traceback**


```none
A placeholder for traceback.
```

**Comment by sjtu-cz** [comment]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/20858982/155482575-c5f58e23-0ff5-4146-b40f-12645e724863.png">

**Comment by gaotongxiao** [comment]
Could you share your config, especially the dataset part? It's more likely that `ann_file` is missing from your dataset config. You can refer to some examples in `configs/_base_/recog_datasets`, such as
https://github.com/open-mmlab/mmocr/blob/3188e534042096e27dbd751deb83df8dedc34314/configs/_base_/recog_datasets/ST_MJ_train.py
for comparision.

**Comment by sjtu-cz** [comment]
I am sorry, there is an extra comma in the config, thank u~
