### ISSUE TITLE
Train ABINet on custom dataset

### ISSUE THREAD

**Issue by trongthuan205** [open-mmlab/mmocr#803]
I have trained ABiNet (https://github.com/open-mmlab/mmocr/blob/main/configs/textrecog/abinet/abinet_academic.py) with my dataset.
And I had the problem "RuntimeError: Class values must be smaller than num_classes". (as an image below)
![image](https://user-images.githubusercontent.com/43246340/155949237-7150ac94-04af-4ad4-bbea-03579ba5695a.png)

**Comment by gaotongxiao** [comment]
You can add `num_classes=num_chars` to `loss` and try training it again.
```python
    loss=dict(
        type='ABILoss', enc_weight=1.0, dec_weight=1.0, fusion_weight=1.0, num_classes=num_chars),
```

**Comment by trongthuan205** [comment]
> ```python
> loss=dict(
> ```

I still had the same problem.  Do you set num_chars= 37 ?

**Comment by gaotongxiao** [comment]
That should work if you haven't changed the dictionary size. `num_chars` should be aligned with the dictionary size and the configuration of `label_converter`. It'd be better to post your config here, especially the part you've modified.

**Comment by trongthuan205** [comment]
> That should work if you haven't changed the dictionary size. `num_chars` should be aligned with the dictionary size and the configuration of `label_converter`. It'd be better to post your config here, especially the part you've modified.

I modify dictionary in open-mmlab/mmocr/mmocr/models/textrecog/convertors/base.py. 
![image](https://user-images.githubusercontent.com/43246340/155953554-8afbf178-11a5-49be-9833-a467e966040a.png)

**Comment by gaotongxiao** [comment]
So `num_char` should be the result of `len(DICT90[0])+1`

**Comment by trongthuan205** [comment]
> So `num_char` should be the result of `len(DICT90[0])+1`

Thank you very much. I have completely fixed this problem.
