### ISSUE TITLE
Questions abount WildReceipt Dataset Annotations

### ISSUE THREAD

**Issue by Estelle-zy** [open-mmlab/mmocr#812]
I want to know what each coordinate in the box means？
is it: x1, w, h, w, h, y1, x2, y2? or else?

"annotations": [
	{"box": [550.0, 190.0, 937.0, 190.0, 937.0, 104.0, 550.0, 104.0],"text": "SAFEWAY", "label": 1},

**Comment by cuhk-hbsun** [comment]
It is `x1, y1, x2, y2, x3, y3, x4, y4`
