### ISSUE TITLE
Stuck when predicting using Pan

### ISSUE THREAD

**Issue by seekingdeep** [open-mmlab/mmocr#82]
It gets **stuck** when predicting using Pan on this image, and doesn't predict:
```
python demo/image_demo.py demo/2.jpg configs/textdet/panet/panet_r18_fpem_ffm_600e_ctw1500.py ./panet_r18_fpem_ffm_sbn_600e_ctw1500_20210219-3b3a9aa3.pth demo/output.jpg
```
![2](https://user-images.githubusercontent.com/71519088/115055980-ecf5ce00-9eea-11eb-8d7a-f12d4c8c9971.jpg)

**Comment by cuhk-hbsun** [comment]
Thanks for the feedback. We will check using the image above.

**Comment by jeffreykuang** [comment]
> It gets **stuck** when predicting using Pan on this image, and doesn't predict:
> 
> ```
> python demo/image_demo.py demo/2.jpg configs/textdet/panet/panet_r18_fpem_ffm_600e_ctw1500.py ./panet_r18_fpem_ffm_sbn_600e_ctw1500_20210219-3b3a9aa3.pth demo/output.jpg
> ```
> 
> ![2](https://user-images.githubusercontent.com/71519088/115055980-ecf5ce00-9eea-11eb-8d7a-f12d4c8c9971.jpg)

This is due to the high complexity of post processing of pan. If the text pixel number is huge, the post processing is very slow.
We are planning to speed it up.

**Comment by seekingdeep** [comment]
@jeffreykuang about 27GB is used, and **seems not to utilize the CPU**
![panet icdar](https://user-images.githubusercontent.com/71519088/115118076-3bb66d00-9faa-11eb-9c00-7d4d851abc86.png)

**Comment by seekingdeep** [comment]
This issue is still pending, but i am closing it.
