### ISSUE TITLE
自己的数据进行训练

### ISSUE THREAD

**Issue by happy20200** [open-mmlab/mmocr#831]
请问怎么将自己的数据集标签处理成icdar2015那种json格式的，目前是txt的
![image](https://user-images.githubusercontent.com/59427046/158012303-7374e7e0-7afc-4851-959c-74dc3aa7f5f9.png)

**Comment by xinke-wang** [comment]
Hi,

MMOCR provides data converters for some widely-used datasets. If you would like to train on custom datasets, you need to write a data converter to transfer the annotation to ICDAR or COCO format. You can check the official data converters as an example. 
[Detection Data Converter](https://github.com/open-mmlab/mmocr/tree/main/tools/data/textdet) 
[Recognition Data Converter](https://github.com/open-mmlab/mmocr/tree/main/tools/data/textrecog)

**Comment by Mountchicken** [comment]
@happy20200 You can also refer to #821 which the annotation files are also in `.txt` form

**Comment by laopeng111** [comment]
> Hi,
> 
> MMOCR provides data converters for some widely-used datasets. If you would like to train on custom datasets, you need to write a data converter to transfer the annotation to ICDAR or COCO format. You can check the official data converters as an example. [Detection Data Converter](https://github.com/open-mmlab/mmocr/tree/main/tools/data/textdet) [Recognition Data Converter](https://github.com/open-mmlab/mmocr/tree/main/tools/data/textrecog)

您好，我看了您提供的数据集转换器，但是屡屡尝试都不成功，请问有比较简单的方式将自己的文本检测数据集转换为mmocr需要的格式呢？以下是我的数据集中的标注文件。盼请回复，谢谢！
![捕获](https://user-images.githubusercontent.com/127070252/223010912-c6894f99-f38d-4f90-b9ae-fd900ff13258.PNG)
