### ISSUE TITLE
Error when train OCR recognition model CRNN and CRNN-TPS

### ISSUE THREAD

**Issue by ThorPham** [open-mmlab/mmocr#838]
I train model on custom dataset with vocabualary  DICT90 = tuple('aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~') . 
But error appear when like this. Sometime a get loss NA , i thing CTC loss model has some problem , can be from my data or  vocabualary. 
![Screenshot from 2022-03-15 02-46-15](https://user-images.githubusercontent.com/33828708/158249271-bc9c5dcb-91dc-452a-a7d6-50695109479b.png)

**Comment by ThorPham** [comment]
I reduce batch-size and number worker , it's work. Thank you

**Comment by ThorPham** [comment]
![Screenshot from 2022-03-15 03-21-39](https://user-images.githubusercontent.com/33828708/158254751-ab88a1b6-fa14-4e65-be96-2f655d4b665b.png)

**Comment by ThorPham** [comment]
My file config
```
_base_ = []
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=1,
    hooks=[
        dict(type='TextLoggerHook')

    ])
# yapf:enable
dist_params = dict(backend='nccl')
log_level = 'INFO'
# load_from = None
resume_from = None
workflow = [('train', 1)]
load_from = OCR/CRNN-TPS/crnn_tps_academic_dataset_20210510-d221a905.pth'
# model
label_convertor = dict(
    type='CTCConvertor', dict_type='DICT90', with_unknown=True, lower=False)

model = dict(
    type='CRNNNet',
    preprocessor=dict(
        type='TPSPreprocessor',
        num_fiducial=20,
        img_size=(32, 100),
        rectified_img_size=(32, 100),
        num_img_channel=1),
    backbone=dict(type='VeryDeepVgg', leaky_relu=False, input_channels=1),
    encoder=None,
    decoder=dict(type='CRNNDecoder', in_channels=512, rnn_flag=True),
    loss=dict(type='CTCLoss'),
    label_convertor=label_convertor,
    pretrained=None)

train_cfg = None
test_cfg = None

# optimizer
optimizer = dict(type='Adadelta', lr=1.0)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[])
total_epochs = 20

# data
img_norm_cfg = dict(mean=[0.5], std=[0.5])

train_pipeline = [
    dict(type='LoadImageFromFile',color_type='grayscale'),
    #  dict(type='MyAuggemt',p=0.5),
    dict(
        type='ResizeOCR',
        height=32,
        min_width=100,
        max_width=100,
        keep_aspect_ratio=True),
    dict(type='ToTensorOCR'),
    dict(type='NormalizeOCR', **img_norm_cfg),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'filename', 'ori_shape', 'resize_shape', 'text', 'valid_ratio'
        ]),
]
test_pipeline = [
    dict(type='LoadImageFromFile', color_type='grayscale'),
    dict(
        type='ResizeOCR',
        height=32,
        min_width=32,
        max_width=100,
        keep_aspect_ratio=False),
    dict(type='ToTensorOCR'),
    dict(type='NormalizeOCR', **img_norm_cfg),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=['filename', 'ori_shape', 'resize_shape', 'valid_ratio']),
]
dataset_type = 'OCRDataset'


train_prefix = 'data_ocr/mixture/'
train_img_prefix = train_prefix + 'ocr_train_paper/'
train_ann_file = train_prefix + 'ocr_train_paper/train.txt'
train = dict(
    type=dataset_type,
    img_prefix=train_img_prefix,
    ann_file=train_ann_file,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=False)
test_prefix = 'data_ocr/mixture/'
test_img_prefix = test_prefix + 'ocr_train_paper/'
test_ann_file = test_prefix + 'ocr_train_paper/test.txt'
test = dict(
    type=dataset_type,
    img_prefix=test_img_prefix,
    ann_file=test_ann_file,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=True)

val_prefix = 'data_ocr/mixture/'
val_img_prefix = val_prefix + 'ocr_train_paper/'
val_ann_file = val_prefix + 'ocr_train_paper/val.txt'
val = dict(
    type=dataset_type,
    img_prefix=val_img_prefix,
    ann_file=val_ann_file,
    loader=dict(
        type='HardDiskLoader',
        repeat=1,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=True)    
data = dict(
    samples_per_gpu=64,
    workers_per_gpu=1,
    val_dataloader=dict(samples_per_gpu=8),
    test_dataloader=dict(samples_per_gpu=4),
    train=dict(
        type='UniformConcatDataset',
        datasets=[train],
        pipeline=train_pipeline),
    val=dict(
        type='UniformConcatDataset',
        datasets=[test,val],
        pipeline=test_pipeline),
    test=dict(
        type='UniformConcatDataset',
        datasets=[val],
        pipeline=test_pipeline))


evaluation = dict(interval=1, metric='acc')

cudnn_benchmark = True



```

**Comment by Mountchicken** [comment]
Hi Thor⚡
I Never tried adding a TPS block in CRNN. TPS block may just work fine with an attention decoder, like ASTER. So you can remove the TPS block and train a pure CRNN on your custom dataset. If the loss keeps being NAN, it may be a problem with your data or vocabulary. Otherwise, it may be a problem with the TPS block, and we will look into it.

**Comment by Mountchicken** [comment]
Hi Thor⚡ again
After checking your vocabulary, I think CTC may just work terribly with such complicate characters. E.g.  `AÀẢÃÁẠĂẰẲẴẮẶÂẦẨẪẤẬ`. They are so similar to each other and the differences between them are on the top of `A`, which have abundant 2D information. However, CTC only takes 1D input and it's hard for it to perceive 2D information.  I strongly suggest you use an attention decoder here. `SAR` model may be suitable.

**Comment by gaotongxiao** [comment]
It seems like you're loading from our pretrained model, which in fact has a different architecture from yours due to the different dictionary you were using. `CRNNDecoder` has a `num_classes` property which is updated to be the length of the dictionary during initialization:
https://github.com/open-mmlab/mmocr/blob/7571763376c5c1b21cdd95461440f7db7dcf295d/mmocr/models/textrecog/recognizer/encode_decode_recognizer.py#L52

So it's not surprising to encounter such a weird bug. You might try training one from scratch and get back to us if the error persists.

**Comment by ThorPham** [comment]
@Mountchicken Thank you for you support. I train both CRNN and  CRNN-TPS same problem. I also train SAR and satrn the result is good. But i want to train CRNN to compare result  with other method. My vocabuary is normal alphabet A,B,C with mark (Á, À, Â, Ă, Ậ) it's no problem with other method

**Comment by ThorPham** [comment]
@gaotongxiao i remove pretrain model and after 1 epoch  error persists. I attach file config.
![Screenshot from 2022-03-15 10-28-37](https://user-images.githubusercontent.com/33828708/158300363-1f81e4d3-b756-4485-9360-86c05c53b2c5.png)
[config.txt](https://github.com/open-mmlab/mmocr/files/8249908/config.txt)

**Comment by gaotongxiao** [comment]
You might consider dumping down all tensors passed to CTCLoss and analyzing them after the error prompts. Some of the usual reasons are that the target index/length is out of the range. Another probably helpful way to analyze the error is to use CPU to compute ctc loss, which can present you with more information when encountering erroneous instances.

**Comment by cuhk-hbsun** [comment]
@ThorPham You can replace `loss=dict(type='CTCLoss')` to `loss=dict(type='CTCLoss', flatten=False, zero_infinity=True)`, and have a try. It may be because the `loss` is `Infinity` or `NaA`.

**Comment by gaotongxiao** [comment]
Hi @ThorPham , has this bug been solved?

**Comment by ThorPham** [comment]
@[gaotongxiao] Sorry for rely later. i just check my data and see some image error . Thank for you support.

**Comment by RundongCao** [comment]
KeyError: 'TPSPreprocessor is not in the mmocr::model registry.
