### ISSUE TITLE
What's the difference between the 'load_from' and 'resume_from' options in training

### ISSUE THREAD

**Issue by yue-cheng-wind** [open-mmlab/mmocr#839]
Hi:
Just a naive question as title, which I see in
https://mmocr.readthedocs.io/en/stable/training.html

that '--load-from' is str and '--resume-from' is bool, but could you elaborate more the differences between the two?

Thank you!

**Comment by gaotongxiao** [comment]
A checkpoint file contains not only the weights of the model but metadata about the training state, e.g., the current iteration # and the learning rate. `--load-from` only loads the weights from the checkpoint and starts training from the very first iteration, whereas `--resume-from` loads additional metadata to resume exactly from the stage where the checkpoint was saved.

**Comment by yue-cheng-wind** [comment]
Hi Tong:
Thank you so much for your response! Then in that case, should '--resume-from' also be the path of the checkpoint file? That I just confirmed it here https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/checkpoint.py, but the documentation said it's bool?

**Comment by gaotongxiao** [comment]
Right, `--resume-from` accepts a string, sorry for the mistake

**Comment by gaotongxiao** [comment]
@xinke-wang Pls fix the docs and supplement some details to these two parameters :)

**Comment by yue-cheng-wind** [comment]
Thanks again for the clarification! I will close this issue then.
