### ISSUE TITLE
The documentation of the config files is poor 

### ISSUE THREAD

**Issue by EMRAN-SALEH-CORSEARCH** [open-mmlab/mmocr#843]
I like this OCR framework. Great job!

I have one note: 

The config files details and the options of them are really poor. 
In many situations we get confused or we do not know how to do or change things or enable a feature. We need to google it and check in the issues here. 
I think it is really improtant to improve this feature . At lease in the commants in the same config file.

**Comment by gaotongxiao** [comment]
Thanks for your suggestion! I agree with you. While the config files are powerful, the options are not quite transparent and could confuse users. We will discuss the way to improve this experience, like, writing a more thorough tutorial to customize the config and adding more comments to each term of the config file could be a good start. We might also provide an interactive tool for config customization in the future.

BTW, have you skimmed through [our tutorial about the config](https://mmocr.readthedocs.io/en/latest/tutorials/config.html)? We'd appreciate that if you could leave any suggestions on it. :)

**Comment by cvarun94** [comment]
> Thanks for your suggestion! I agree with you. While the config files are powerful, the options are not quite transparent and could confuse users. We will discuss the way to improve this experience, like, writing a more thorough tutorial to customize the config and adding more comments to each term of the config file could be a good start. We might also provide an interactive tool for config customization in the future.
> 
> BTW, have you skimmed through [our tutorial about the config](https://mmocr.readthedocs.io/en/latest/tutorials/config.html)? We'd appreciate that if you could leave any suggestions on it. :)

Hey @gaotongxiao 
thanks for this awesome mmocr.. I've been exploring mmocr for a few days and it is really interesting.
I am currently trying to train ABINet on my own custom data for recognition task but finding it really hard to edit the config for it. I saw many threads in github and tried them also but unable to correctly make the changes to the config. 

I have gone through the tutorial of config which you've linked, but it does not clearly explain what needs to be changed in the config of a model when you want to train it on custom data. 

Would be really helpful if you could provide related resources, tips or tutorials for the same.

Thanks

**Comment by gaotongxiao** [comment]
Sure, we will provide a walkthrough to clearly explain the steps to modify the config. Before they are ready, you can ask for specific solutions via issues. @cvarun94
