### ISSUE TITLE
A complete text line is splited into several pieces

### ISSUE THREAD

**Issue by GivanTsai** [open-mmlab/mmocr#846]
When I use DBNet algorithm to do the text detection, due to the existance of space, a complete line was split into several pieces, how can I merge them back to a text box, and I want to recognize the space character at the same time.

**Comment by Mountchicken** [comment]
Hi GivanTsai!
Do you mean that your DBNet can only detect words, not a complete sentence, and your want to merge those separated boxes into a  large box?

**Comment by GivanTsai** [comment]
> 

Yes. If the space betweem two characeters is somehow large, the box was broken due to the space, I need the complete box and recognize the space.

**Comment by GivanTsai** [comment]
> You might want to check [this](https://mmocr.readthedocs.io/en/latest/api.html#mmocr.utils.stitch_boxes_into_lines) out?

Thanks.
