### ISSUE TITLE
Is there any pretrained model of mmocr?

### ISSUE THREAD

**Issue by GivanTsai** [open-mmlab/mmocr#856]
Is there any pretrained model of mmocr?

**Comment by xinke-wang** [comment]
Hi @GivanTsai ,

MMOCR provides pre-trained models for [text detection](https://mmocr.readthedocs.io/en/latest/textdet_models.html), [recognition](https://mmocr.readthedocs.io/en/latest/textrecog_models.html), [key information extraction](https://mmocr.readthedocs.io/en/latest/kie_models.html), and [named entity recognition](https://mmocr.readthedocs.io/en/latest/ner_models.html).

You can check the list of checkpoints [here](https://mmocr.readthedocs.io/en/latest/modelzoo.html).
