### ISSUE TITLE
UniformConcatDataset set different sample ratio

### ISSUE THREAD

**Issue by aiboys** [open-mmlab/mmocr#860]
When I concat many datasets by <'UniforConcatDataset'> class, how can I set their sample ratios to balance these datasets. I have not found such feat.
Looking forward to your reply, so thx.

**Comment by xinke-wang** [comment]
This can be achieved by specifying a `repeat` number. For example, set `repeat=1` for dataset A, and `repeat=5` for dataset B, then you got a 1:5 concat dataset.

https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/ST_SA_MJ_real_train.py#L31
