### ISSUE TITLE
Permission denied: '/mmocr/mmocr/core/font.TTF'

### ISSUE THREAD

**Issue by formerlya** [open-mmlab/mmocr#868]
When I run recog-demo liked that python mmocr/utils/ocr.py %INPUT_FOLDER_PATH% --det None --recog CRNN_TPS --batch-mode --single-batch-size 10 --output %OUPUT_FOLDER_PATH%,permissionError happened.

Matplotlib created a temporary config/cache directory at /tmp/matplotlib-wz8itdit because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
load checkpoint from local path: /gdata1/huyc/hzx/weights/sar_r31_parallel_decoder_chineseocr_20210507-b4be8214.pth
/mmocr/mmocr/apis/utils.py:53: UserWarning: Remove "MultiRotateAugOCR" to support batch inference since samples_per_gpu > 1.
  warnings.warn(warning_msg)
/mmocr/mmocr/apis/utils.py:53: UserWarning: Remove "MultiRotateAugOCR" to support batch inference since samples_per_gpu > 1.
  warnings.warn(warning_msg)
Downloading https://download.openmmlab.com/mmocr/data/font.TTF ...(because of the safe question，I can't download it 
 directly from the web)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/shutil.py", line 788, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/tmp/tmpt7zujgkl' -> '/mmocr/mmocr/core/font.TTF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mmocr/utils/ocr.py", line 718, in <module>
    main()
  File "mmocr/utils/ocr.py", line 714, in main
    ocr.readtext(**vars(args))
  File "mmocr/utils/ocr.py", line 438, in readtext
    pp_result = self.single_pp(result, model)
  File "mmocr/utils/ocr.py", line 479, in single_pp
    res_img = model.show_result(arr, res, out_file=output)
  File "/mmocr/mmocr/models/textrecog/recognizer/base.py", line 218, in show_result
    img = imshow_text_label(
  File "/mmocr/mmocr/core/visualize.py", line 357, in imshow_text_label
    pred_img = draw_texts_by_pil(img, [pred_label], None)
  File "/mmocr/mmocr/core/visualize.py", line 608, in draw_texts_by_pil
    shutil.move(local_filename, font_path)
  File "/opt/conda/lib/python3.8/shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "/opt/conda/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/mmocr/mmocr/core/font.TTF'
I have no name!@8f2c5473204a:/ghome/mmocr-main$ Permission denied: '/mmocr/mmocr/core/font.TTF'
``

**Comment by formerlya** [comment]
Then I download the front.TTF,and put it at /ghome/mmocr-main/mmocr/core.
But nothing happened.
So,anybody know where are the files or configs about the local folder location rather than http links?
I need to find the file and modify the path.
Thanks!!

**Comment by Mountchicken** [comment]
Hi @formerlya 
Have you tried by adding permission like this ` sudo chmode -R 777 /ghome/mmocr-main/mmocr/core.font.TTF`

**Comment by formerlya** [comment]
> Hi @formerlya Have you tried by adding permission like this ` sudo chmod -R 777 /ghome/mmocr-main/mmocr/core.font.TTF`

非常感谢你的回复！我试了一下但还报相同的错。可以跑检测、检测加识别的demo，但这个bug不知道咋办了，谢谢你。

**Comment by Mountchicken** [comment]
sorry, I gave the wrong command. It should be `sudo chmod -R 777 {Path to your current folder}/mmocr/core/font.TTF`.

**Comment by formerlya** [comment]
> sorry, I gave the wrong command. It should be `sudo chmod -R 777 {path to your current folder}/mmocr/core/font.TTF`. Modiffy `{path to your current folder}`

Thank you so much! But still the same error.( Ĭ ^ Ĭ )

**Comment by Mountchicken** [comment]
Can you give your full command, I will try on my computer.

**Comment by formerlya** [comment]
> Please give your full command and I will try it on my computer.

python mmocr/utils/ocr.py /gdata1/huyc/hzx/crop_data_part --det None --recog SAR_CN --batch-mode --single-batch-size 10 --output /gdata1/huyc/hzx/results

**Comment by gaotongxiao** [comment]
Seems the script doesn't have the write permission to `mmocr/` folder. You can recursively relax its permission by running
```bash
sudo chmod -R 777 {path to your current folder}/mmocr
```
Read through the guide for more details: https://www.guru99.com/file-permissions.html

**Comment by formerlya** [comment]
> Seems the script doesn't have the write permission to `mmocr/` folder. You can recursively relax its permission by running
> 
> ```shell
> sudo chmod -R 777 {path to your current folder}/mmocr
> ```
> 
> Read through the guide for more details: https://www.guru99.com/file-permissions.html

Thank you very much for your answer, I will study this link well, but the above command still doesn't solve my problem.( Ĭ ^ Ĭ )
![360截图20220323153532425](https://user-images.githubusercontent.com/88373367/159647293-151dad5c-0c51-49af-a19e-f570b662bf2b.jpg)

**Comment by xinke-wang** [comment]
The path '/mmocr/mmocr/core/font.TTF' is an absolute path to root. I guess it should be changed to the current mmocr path, like '/ghome/huyc/hzx/mmocr/core/font.TTF'.

**Comment by formerlya** [comment]
> 

Thanks for the note! I changed it to local but it still didn't work.
![111](https://user-images.githubusercontent.com/88373367/159655582-fcc26751-35b5-4418-a63e-201271031f4e.jpg)

**Comment by formerlya** [comment]
When I use the detection demo command and replace it with recognition, the following happens
![222](https://user-images.githubusercontent.com/88373367/159657375-8ad20c87-9b4b-4965-91e2-31bd2696432c.jpg)

**Comment by xinke-wang** [comment]
It seems the `__file__`  refers to an incorrect path. I am not sure why this happened. But you may like to try a temporary ugly solution for now. Specifically, comment [Line#602](https://github.com/open-mmlab/mmocr/blob/main/mmocr/core/visualize.py#L602) in `visualize.py`, and force the `dirname` to your font path.

```python
# dirname, _ = os.path.split(os.path.abspath(__file__))
dirname = '/ghome/huyc/hzx/mmocr-main/mmocr/core'
```

Looking for any ideas about this issue from @gaotongxiao and @Mountchicken

**Comment by Mountchicken** [comment]
comment [Line#602](https://github.com/open-mmlab/mmocr/blob/main/mmocr/core/visualize.py#L603) in visualize.py
```python
font_path = os.path.join(dirname, 'font.TTF')
...
shutil.move(local_filename, font_path)
```
The `move` operation will try to rename the font file and may cause permission error. How about modify the code in this way 
 ```python
font_path = dirname
```

**Comment by gaotongxiao** [comment]
There are at least two MMOCR copies on your machine/container, one at `/mmocr/` and another one at `/ghome/huyc/hzx/mmocr-main`. I guess you're running our docker image, mounting `mmocr/` in your host to `/mmocr/` in your container. And you've cloned another `mmocr` to `/ghome/huyc/hzx/mmocr-main`, which is the directory that you are working on.

First, since the pre-installed `mmocr` package in this container is pointing to `/mmocr/`, I'd suggest you remove your clone at `/ghome/huyc/hzx/mmocr-main` and change your working directory to `/mmocr` to avoid any confusion.

As for the permission issue, you might not give enough permission to `mmocr/` directory on your host machine. Try `sudo chmod -R 777 PATH_TO_MMOCR` on your **host machine** and see if you can modify the files in `/mmocr/` in your container.

**Comment by formerlya** [comment]
> It seems there are at least two MMOCR copies on your machine/container, one at `/mmocr/` and another one at `/ghome/huyc/hzx/mmocr-main`. I guess you're running our docker image, mounting `mmocr/` in your host to `/mmocr/` in your container. And you've cloned another `mmocr` to `/ghome/huyc/hzx/mmocr-main`, which is the directory that you are working on.
> 
> First, since the pre-installed `mmocr` package in this container is pointing to `/mmocr/`, I'd suggest you remove your clone at `/ghome/huyc/hzx/mmocr-main` and change your working directory to `/mmocr` to avoid any confusion.
> 
> As for the permission issue, you might not give enough permission to `mmocr/` directory on your host machine. Try `sudo chmod -R 777 PATH_TO_MMOCR` on your **host machine** and see if you can modify the files in `/mmocr/` in your container.

Thanks for the insight, I looked it up and indeed this is the problem.Thanks!

**Comment by formerlya** [comment]
> It seems the `__file__` refers to an incorrect path. I am not sure why this happened. But you may like to try a temporary ugly solution for now. Specifically, comment [Line#602](https://github.com/open-mmlab/mmocr/blob/main/mmocr/core/visualize.py#L602) in `visualize.py`, and force the `dirname` to your font path.
> 
> ```python
> # dirname, _ = os.path.split(os.path.abspath(__file__))
> dirname = '/ghome/huyc/hzx/mmocr-main/mmocr/core'
> ```
> 
> Looking for any ideas about this issue from @gaotongxiao and @Mountchicken

Thanks, I have modified the command line in the file.

**Comment by gaotongxiao** [comment]
Glad to know it helps. I'm closing this issue.
