### ISSUE TITLE
test configs/_base_/det_datasets/icdar2015.py on my own data

### ISSUE THREAD

**Issue by happy20200** [open-mmlab/mmocr#874]
test configs/_base_/det_datasets/icdar2015.py on my own data
![1648096704(1)](https://user-images.githubusercontent.com/59427046/159843351-069a776a-5ebb-47f6-a7dc-2f70d35596d9.png)
how could i fix it? any help will be delightful

**Comment by gaotongxiao** [comment]
Hi, please describe the context following our issue template.
