### ISSUE TITLE
synthtext，coco-textv2, unrealtext预训练中dbtarget生成出错

### ISSUE THREAD

**Issue by aiboys** [open-mmlab/mmocr#875]
Hi,
  [在用dbnet加载上述三种数据集预训练的时候发现在dbtarget生成会报错：[padded_polygon = np.array(padded_polygon[0])](https://github.com/open-mmlab/mmocr/blob/main/mmocr/datasets/pipelines/textdet_targets/dbnet_targets.py#L150), 似乎是因为pyclipper根据distance map生成[padding](https://github.com/open-mmlab/mmocr/blob/main/mmocr/datasets/pipelines/textdet_targets/dbnet_targets.py#L148) 时候传入的polygon有负数或者polygon出现交叉而导致bug，想知道遇到这种情况怎么处理（目前排除了负数坐标以及交叉多边形但还是会报错，，不知道为啥）

**Comment by gaotongxiao** [comment]
Not sure as well, you may print every polygon before running pyclipper to capture the troublemaker. Please also keep us updated if you have any progress on it :)

**Comment by aiboys** [comment]
thx for your reply, I have fixed it already.
I referenced mmocr resource code to re-implement DB-Net, but there were some mistakes in my code by my own fault.

**Comment by gaotongxiao** [comment]
I see, glad to know that!
