### ISSUE TITLE
How to show total parameter model ?

### ISSUE THREAD

**Issue by ThorPham** [open-mmlab/mmocr#885]
Can you show me how to print number parameter each model ?

**Comment by Mountchicken** [comment]
An ugly way to do this is add codes right after the model is [defined](https://github.com/open-mmlab/mmocr/blob/main/tools/train.py#L191) in `tools/train.py` at `line 190`
```python
#model = build_detector(
#        cfg.model,
#        train_cfg=cfg.get('train_cfg'),
#       test_cfg=cfg.get('test_cfg'))
total_params = sum(p.numel() for p in model.parameters())
print(f'{total_params:,} total parameters.')
total_trainable_params = sum(p.numel() for p in model.parameters()
                             if p.requires_grad)
print(f'{total_trainable_params:,} training parameters.')
#model.init_weights()
```
@gaotongxiao Looking for a better way❤

**Comment by gaotongxiao** [comment]
Seems we can't find a more elegant solution than it.

**Comment by ThorPham** [comment]
@gaotongxiao Mountchicken Thank you for support
