### ISSUE TITLE
Why I used SAR_CN, but the recognition result is still in English？

### ISSUE THREAD

**Issue by formerlya** [open-mmlab/mmocr#889]
python mmocr/utils/ocr.py {my_image_path} --det TextSnake --recog SAR_CN --output demo/result.jpg
The dictionary and the corresponding weight have been downloaded, why is it still recognized as English?
I just want to test the result of Chinese character recognition.
![1234](https://user-images.githubusercontent.com/88373367/160366182-a5e3509f-b6c3-4dd2-8a6c-0c9827af53b9.jpg)
Whether there any further modification?

**Comment by xinke-wang** [comment]
You may try some other images. Currently, the Chinese recognition is not fully supported, hence the performance might be not convincing enough for the text instances that are not clear.

**Comment by gaotongxiao** [comment]
We've been working hard on providing better Chinese recognition models. Stay tuned!
