### ISSUE TITLE
ModuleNotFoundError: No module named 'mmocr'

### ISSUE THREAD

**Issue by liuwenhaha** [open-mmlab/mmocr#906]
when I run 'python mmocr/utils/ocr.py demo/demo_text_ocr.jpg --print-result --imshow'
I got this:
Traceback (most recent call last):
  File "mmocr/utils/ocr.py", line 16, in <module>
    from mmocr.apis import init_detector
ModuleNotFoundError: No module named 'mmocr'
////////////////
what can I do?

**Comment by gaotongxiao** [comment]
Hi, have you correctly installed MMOCR following the instruction: https://mmocr.readthedocs.io/en/latest/install.html#step-by-step-installation-instructions

**Comment by liuwenhaha** [comment]
> Hi, have you correctly installed MMOCR following the instruction: https://mmocr.readthedocs.io/en/latest/install.html#step-by-step-installation-instructions

...sorry,i forgot one cmd 'pip install -v -e . '
...so stupid i am

**Comment by esraa-abdelmaksoud** [comment]
Unfortunately, I'm facing the same problem though I used pip freeze to make sure that the packages were installed. I have already used an older version in the past and it was working properly.

Error: ```ModuleNotFoundError: No module named 'mmocr'```

I followed the installation details here:
https://mmocr.readthedocs.io/en/dev-1.x/get_started/install.html#best-practices

The versions installed:
```
mmcv==2.0.0
mmcv-full==1.7.1
mmdet==3.0.0
mmengine==0.7.3
mmocr==1.0.0
```

**Comment by gaotongxiao** [comment]
mmcv and mmcv-full cannot coexist in the same environment. I think there was something wrong with your upgrading process.

The best starting point is to create a new virtual environment and re-install the packages from scratch. As said in https://mmocr.readthedocs.io/en/dev-1.x/migration/overview.html

**Comment by esraa-abdelmaksoud** [comment]
I found that the problem is with VS code. Though the virtual environment is activated in the terminal, the packages were being installed in a venv virtual environment, not the currently activated conda environment. Activating the environment and installing the packages in Ubuntu Terminal solved the problem. Thanks.

**Comment by pixml27** [comment]
Hi! I want use mmocr library in kaggle notebooks without internet access
So i can't install it as says in instrutctions (through the mim, so i do this things):
```
!pip wheel --wheel-dir=wheelocr2/ -r mmocr/mmocr-git/requirements.txt
!pip install --no-index --find-links wheelocr2 -v -e mmocr/mmocr-git
```
The same things i do for mmdet,mmvc and mmengine
After all, i have this strange behavior:
<img width="902" alt="Снимок экрана 2023-06-17 в 13 01 30" src="https://github.com/open-mmlab/mmocr/assets/38530905/55165cdc-0ca1-4987-9c04-5d93883c087e">

Can anybody help me with it?
