### ISSUE TITLE
请问本项目支持AP值计算吗？

### ISSUE THREAD

**Issue by zhonguoliuzhe** [open-mmlab/mmocr#907]
我想计算IC15数据集不同尺寸目标的的AP值，看到这里说[tools/test.py/line51](https://github.com/open-mmlab/mmocr/blob/0546134771e27be47d42d17befeb0559d89673a0/tools/test.py#L51)
可以向eval中传递bbox和seg两个评估指标，于是我执行了以下命令
./tools/dist_test.sh ./configs/textdet/maskrcnn/mask_rcnn_r50_fpn_160e_icdar2015.py ./checkpoints/maskrcnn-epoch_180.pth 1 --eval bbox seg
但是测试完后没有输出结果，想知道本项目支持AP计算吗，是否需要自己实现这部分功能？

**Comment by xinke-wang** [comment]
Hi,

Please check this [doc](https://mmocr.readthedocs.io/en/latest/testing.html), MMOCR currently supports `hmean-ic13` and `hmean-iou` for detection evaluation, which are implemented in [here](https://github.com/open-mmlab/mmocr/tree/main/mmocr/core/evaluation). If you would like to compute AP metric, you may need to implement it by yourself or use the `pycocotools`.

I think the help string in `test.py` Line51 was not updated, sorry for the confusion. @gaotongxiao Can you check this?

**Comment by xinke-wang** [comment]
Fixed in PR #908
