### ISSUE TITLE
为啥没有icdar2017_test.json呢

### ISSUE THREAD

**Issue by ocrhei** [open-mmlab/mmocr#910]
大多数关于icdar2017的论文都是用7200张train.image和1800张val.image拿来训练的，9000张test.img是来测试的，而您代码的意思是用val数据集来测试，这和大多数论文都不符合呀，能否提供test图片的json文件呢

**Comment by xinke-wang** [comment]
Hi,

The test set annotation is not publicly available. You have to download the test images from the competition website and upload the predictions to the official evaluation server to get evaluation results.
