### ISSUE TITLE
SDMG-R模型支持中文吗

### ISSUE THREAD

**Issue by ga546** [open-mmlab/mmocr#911]

**Comment by gaotongxiao** [comment]
Yes - but the released model is trained in English. You can use a Chinese dictionary and a custom dataset to train SDMG-R in Chinese.

**Comment by gaotongxiao** [comment]
It depends, but WildReceipt contains ~1200 train instances. You can take it as a reference.

**Comment by ga546** [comment]
@gaotongxiao thanks!
