### ISSUE TITLE
convetsyntext中的顺时针或逆时针sort_points并非是最优的方案

### ISSUE THREAD

**Issue by 6098669** [open-mmlab/mmocr#913]
特别是对于极度弯曲文本，可能上边界在sortpoint的时候会直接跳到下边界导致轮廓描述不准，我试了一下滚球法比sortpoint好点，但是速度太慢，请问有没有更好的方法能从边界点中准确绘制轮廓

**Comment by Mountchicken** [comment]
Hi @6098669 
I'm not quite familiar with this problem, can you tell me where this function is?  I'll take a close look。

**Comment by 6098669** [comment]
我用的是https://github.com/bellockk/alphashape.git中的函数，不过速度太慢，不知有没有更好的方法了

**Comment by gaotongxiao** [comment]
Hi, thanks for the feedback! We'll keep looking for a better way to deal with this case.
Also, if we could discuss this issue in English, we may be able to receive more ideas :)
