### ISSUE TITLE
Text detection model test failed

### ISSUE THREAD

**Issue by wangjiale1998** [open-mmlab/mmocr#915]
I used test.py to test on my own dataset, the format of the dataset is generated in the style of icdar2015, and the test indicator uses hmean-iou, but it always gets stuck. details as follows.
 python tools/test.py configs/textdet/psenet/psenet_r50_fpnf_5e_fr.py workdir/textdet/psenet/latest.pth --eval hmean-iou
D:\ProgramData\Anaconda3\envs\mmocr\lib\site-packages\mmdet\datasets\pipelines\formating.py:7: UserWarning: DeprecationWarning: mmdet.datasets.pipelines.formating will be deprecated, please replace it with mmdet.datasets.pipelines.formatting.
  warnings.warn('DeprecationWarning: mmdet.datasets.pipelines.formating will be '
d:\ocr\mmocr-main\mmocr\utils\setup_env.py:33: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting OMP_NUM_THREADS environment variable for each process '
d:\ocr\mmocr-main\mmocr\utils\setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
loading annotations into memory...
Done (t=0.20s)
creating index...
index created!
load checkpoint from local path: workdir/textdet/psenet/latest.pth
[                                                  ] 0/100, elapsed: 0s, ETA:D:\ProgramData\Anaconda3\envs\mmocr\lib\site-packages\mmdet\datasets\pipelines\formating.py:7: UserWarning: DeprecationWarning: mmdet.datasets.pipelines.formating will be deprecated, please replace it with mmdet.datasets.pipelines.formatt
ing.
  warnings.warn('DeprecationWarning: mmdet.datasets.pipelines.formating will be '
D:\ProgramData\Anaconda3\envs\mmocr\lib\site-packages\mmdet\datasets\pipelines\formating.py:7: UserWarning: DeprecationWarning: mmdet.datasets.pipelines.formating will be deprecated, please replace it with mmdet.datasets.pipelines.formatting.
  warnings.warn('DeprecationWarning: mmdet.datasets.pipelines.formating will be '
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100/100, 1.2 task/s, elapsed: 83s, ETA:     0s
Evaluateing D:/ocr_data/test/instances_test.json with 100 images now

Evaluating hmean-iou...

Hope to get your help！

**Comment by xinke-wang** [comment]
Have you encountered the same issue when evaluating any datasets that MMOCR officially supported?

**Comment by wangjiale1998** [comment]
> Have you encountered the same issue when evaluating any datasets that MMOCR officially supported?

No, I can run fine on icdar2015 dataset

**Comment by gaotongxiao** [comment]
Possibly your dataset contains a large number of polygons in each image, which significantly damps the evaluation.
https://github.com/open-mmlab/mmocr/blob/d1d2c1f4693258635eb470cc24ffd81f85a28ddc/mmocr/core/evaluation/hmean.py#L120

**Comment by wangjiale1998** [comment]
> Possibly your dataset contains a large number of polygons in each image, which significantly damps the evaluation.
> 
> https://github.com/open-mmlab/mmocr/blob/d1d2c1f4693258635eb470cc24ffd81f85a28ddc/mmocr/core/evaluation/hmean.py#L120

Thanks for your answer, that should be the reason

**Comment by gaotongxiao** [comment]
Great, I'm closing it now.
