### ISSUE TITLE
How to train a model with multiple gpus without  distribution training

### ISSUE THREAD

**Issue by simplify23** [open-mmlab/mmocr#919]
Because of the need to set a larger batchsize, I hope to run parallel training on 8 gpus, without using distributed training. How can i change my code?

**Comment by Mountchicken** [comment]
Hi @simplify23 
You can refer to the document on distributed training in MMOCR: [https://mmocr.readthedocs.io/en/latest/training.html#training-on-multiple-gpus](https://mmocr.readthedocs.io/en/latest/training.html#training-on-multiple-gpus)

**Comment by simplify23** [comment]
> Hi @simplify23 You can refer to the document on distributed training in MMOCR: https://mmocr.readthedocs.io/en/latest/training.html#training-on-multiple-gpus

i know that. But i want to train my model with 8 gpus on parallel training, not distributed training. As i know in document, it is not support with more than one gpu on parallel training, how can i change?

**Comment by xinke-wang** [comment]
What do you mean parallel training? The distributed training in MMOCR supports training models with multiple GPUs on a single machine. You may be confusing with multiple machine training here.

**Comment by simplify23** [comment]
i just have one machine with 8 gpus. if i use distributed training in mmocr, i can only set 128 batchszie because i just have 10GB memory for each gpus. I hope i can set 512 or more higher batchsize for training, which can 
accomplish without using distributed training.

**Comment by gaotongxiao** [comment]
This issue has nothing to do with distributed/parallel training. In distributed training, the actual batch size is the number of your GPUs times `samples_per_gpu`. You might have misinterpreted `samples_per_gpu` as the batch size itself.

Also, parallel training is not as efficient as distributed training, and therefore all OpenMMLab repositories only support mulit-gpu training in DDP mode.

**Comment by simplify23** [comment]
i think higher batch size can improve my model accuracy.  As i know each GPU can only process samples_per_gpu datasets, example 128 in DDP training.  Because the limitation of my GPUs, i hope to process 512+ batch size for imporve my model accuracy. In this reason, i think the best method is change a train script for parallel traing with mulit-gpu. Can i change for that?

**Comment by gaotongxiao** [comment]
As for the backward gradients, parallel training and distributed training both computes the average gradients over the actual batch size. Switching the mode would make no difference to the result at all. In both modes, training on 4 GPUs with 128 samples per GPU is equivalent to training on 1 GPU with batch size of 512.

If you want even more than that - for example, 512 samples per actual GPU, then you might want gradient acculmulation. Set up the following in config:
```python
optimizer_config = dict(type='GradientCumulativeOptimizerHook', cumulative_iters=4)
```
It accumulates the gradients for 4 iterations before each parameter update.

**Comment by simplify23** [comment]
that's a great idea, thanks for your advice!
