### ISSUE TITLE
Question about TPS preprocessor

### ISSUE THREAD

**Issue by yue-cheng-wind** [open-mmlab/mmocr#925]
Hi:
I have images with curved text and I noticed that there is a TPS preprocessor ready for use:
https://github.com/open-mmlab/mmocr/blob/main/mmocr/models/textrecog/preprocessor/tps_preprocessor.py

And I also checked the example configuration file here:
https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_models/crnn_tps.py

My questions are:
1. Is it like that for all the recognition models, we can add a TPS preprocessor like this:
https://github.com/open-mmlab/mmocr/blob/a3834ab24e47f951138e1a8a6ca396e36eea6e2e/configs/_base_/recog_models/crnn_tps.py#L7-L12

2. When using my own image to do the curved text recognition task, what modifications I should do? Do I just override the **img_size**  and **rectified_img_size** ?

```
        num_fiducial (int): Number of fiducial points of TPS-STN.
        img_size (tuple(int, int)): Size :math:`(H, W)` of the input image.
        rectified_img_size (tuple(int, int)): Size :math:`(H_r, W_r)` of
            the rectified image.
        num_img_channel (int): Number of channels of the input image.
```

Thanks a lot for the response in advance!

**Comment by Mountchicken** [comment]
Hi @yue-cheng-wind 
You are right, but there are a few things you need to be aware of.
- keep `img_size` the same with `heigth, min_width, max_width` in pipeline (both train_pipeline and text_pipeline). E.g. if your `img_size` is (64, 256) in preprocessor, then the `height, min_width, max_width`  in train_pipeline should be 64, 256, 256, respectively
- The `rectified_img_size` should  remain unchanged as it relates to the input of the subsequent network. 
- So you can set a larger `img_size`, which according to the paper ASTER can effectively improve the rectification effect, and keep `rectified_img_size` unchanged.

**Comment by yue-cheng-wind** [comment]
Hi @Mountchicken:
Thank you so much for the detailed explanation! Just to clarify, `img_size ` does not need to be the input size of the image, but just the size that we would like the input size to be resized to?

**Comment by Mountchicken** [comment]
> Hi @Mountchicken: Thank you so much for the detailed explanation! Just to clarify, `img_size ` does not need to be the input size of the image, but just the size that we would like the input size to be resized to?

Yes.

**Comment by yue-cheng-wind** [comment]
Thanks a lot for your help! I will close this issue.
