### ISSUE TITLE
Where is FCENet's Pretrained Model (ImageNet)?

### ISSUE THREAD

**Issue by qqqqq127** [open-mmlab/mmocr#932]

**Comment by xinke-wang** [comment]
Hi, the default config of FCENet uses the torchvision `ResNet-50` that was pre-trained on the ImageNet for initialization, which will be automatically downloaded from the torchvision website while training started.

https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/det_models/fcenet_r50_fpn.py#L10
