### ISSUE TITLE
cannot export onnx model

### ISSUE THREAD

**Issue by SpaceView** [open-mmlab/mmocr#936]
Platform:  Window10 + open-mmlab for mmocr (latest version)
python 3.8.13

I'm following the below link installing mmocr,  and I can run the detection successfully,
https://mmocr.readthedocs.io/en/latest/deployment.html#example

When I'm trying to export models to onnx, i got the following errors, for the detection model, i got the detection.onnx, for the second error, the program got stuck permanently and seems deadlocked.

===>>>Problem for detection model<<<=========================================================
(open-mmlab) PS E:\wOCR\mmocr> python  tools/deployment/pytorch2onnx.py --verify --output-file detector.onnx  configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py   E:/dataset/mmocr/detection/dbnet_r18_fpnc_sbn_1200e_icdar2015_20210329-ba3ab597.pth  --dynamic-export det  demo/R1920x1080.png
D:\anaconda3\envs\open-mmlab\lib\site-packages\mmdet\datasets\pipelines\formating.py:7: UserWarning: DeprecationWarning: mmdet.datasets.pipelines.formating will be deprecated, please replace it with mmdet.datasets.pipelines.formatting.
  warnings.warn('DeprecationWarning: mmdet.datasets.pipelines.formating will be '
tools/deployment/pytorch2onnx.py:336: UserWarning: DeprecationWarning: This tool will be deprecated in future. Welcome to use the unified model deployment toolbox MMDeploy: https://github.com/open-mmlab/mmdeploy
  warnings.warn(msg)
load checkpoint from local path: E:/dataset/mmocr/detection/dbnet_r18_fpnc_sbn_1200e_icdar2015_20210329-ba3ab597.pth
D:\anaconda3\envs\open-mmlab\lib\site-packages\mmdet\datasets\utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
D:\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\onnx\symbolic.py:481: UserWarning: DeprecationWarning: This function will be deprecated in future. Welcome to use the unified model deployment toolbox 
MMDeploy: https://github.com/open-mmlab/mmdeploy
  warnings.warn(msg)
Successfully exported ONNX model: detector.onnx
D:\anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\functional.py:3679: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
  warnings.warn(
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 368, in <module>
    main()
  File "tools/deployment/pytorch2onnx.py", line 354, in main
    pytorch2onnx(
  File "tools/deployment/pytorch2onnx.py", line 236, in pytorch2onnx
    onnx_out = onnx_model.simple_test(
  File "e:\wocr\mmocr\mmocr\core\deployment\deploy_utils.py", line 95, in simple_test
    onnx_pred = inference_with_session(self.sess, self.io_binding, 'input',
  File "e:\wocr\mmocr\mmocr\core\deployment\deploy_utils.py", line 23, in inference_with_session
    io_binding.bind_input(
  File "D:\anaconda3\envs\open-mmlab\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 441, in bind_input
    self._iobinding.bind_input(name,
RuntimeError: Error when binding input: There's no data transfer registered for copying tensors from Device:[DeviceType:1 MemoryType:0 DeviceId:0] to Device:[DeviceType:0 MemoryType:0 DeviceId:0]  

===>>>Problem for recog model<<<=========================================================
(open-mmlab) PS E:\wOCR\mmocr> python  tools/deployment/pytorch2onnx.py --opset 14 --verify --output-file recognizer.onnx  configs/textrecog/satrn/satrn_small.py         E:/dataset/mmocr/recognition/satrn_small_20211009-2cf13355.pth   recog  demo/r200x50.png
D:\anaconda3\envs\open-mmlab\lib\site-packages\mmdet\datasets\pipelines\formating.py:7: UserWarning: DeprecationWarning: mmdet.datasets.pipelines.formating will be deprecated, please replace it with mmdet.datasets.pipelines.formatting.
  warnings.warn('DeprecationWarning: mmdet.datasets.pipelines.formating will be '
tools/deployment/pytorch2onnx.py:336: UserWarning: DeprecationWarning: This tool will be deprecated in future. Welcome to use the unified model deployment toolbox MMDeploy: https://github.com/open-mmlab/mmdeploy
  warnings.warn(msg)
load checkpoint from local path: E:/dataset/mmocr/recognition/satrn_small_20211009-2cf13355.pth
D:\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\onnx\symbolic.py:481: UserWarning: DeprecationWarning: This function will be deprecated in future. Welcome to use the unified model deployment toolbox 
MMDeploy: https://github.com/open-mmlab/mmdeploy
  warnings.warn(msg)
e:\wocr\mmocr\mmocr\models\textrecog\encoders\satrn_encoder.py:76: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  valid_width = min(w, math.ceil(w * valid_ratio))
e:\wocr\mmocr\mmocr\models\textrecog\encoders\satrn_encoder.py:76: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  valid_width = min(w, math.ceil(w * valid_ratio))
e:\wocr\mmocr\mmocr\models\textrecog\decoders\nrtr_decoder.py:126: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  valid_width = min(T, math.ceil(T * valid_ratio))
e:\wocr\mmocr\mmocr\models\textrecog\decoders\nrtr_decoder.py:126: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  valid_width = min(T, math.ceil(T * valid_ratio))
D:\anaconda3\envs\open-mmlab\lib\site-packages\torch\onnx\symbolic_helper.py:716: UserWarning: allowzero=0 by default. In order to honor zero value in shape use allowzero=1
  warnings.warn("allowzero=0 by default. In order to honor zero value in shape use allowzero=1")
D:\anaconda3\envs\open-mmlab\lib\site-packages\torch\onnx\symbolic_helper.py:325: UserWarning: Type cannot be inferred, which might cause exported graph to produce incorrect results.
  warnings.warn("Type cannot be inferred, which might cause exported graph to produce incorrect results.")

=============>Question<==================
(1) How can I fix this?
(2) what is the meaning of the 2 images at the end of these code, why resolution 1920x1020 and 200x50 ?

**Comment by gaotongxiao** [comment]
Hi, all deployment-related issues, please reraise them to [MMDeploy](https://github.com/open-mmlab/mmdeploy), where we have a professional team responsible for these questions. MMDeploy provides a full deployment workflow for MMOCR and many other OpenMMLab projects, and these legacy deployment scripts you were using are deprecated and will be removed soon. Sorry for causing the confusion!
