### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by young-xz** [open-mmlab/mmocr#938]
When i execute
python mmocr/utils/ocr.py demo/demo_kie.jpeg  --det PS_CTW --recog SAR --kie SDMGR --print-result --imshow
in Linux
it throw some error about print ，but i modify them,until i met blow error
File "mmocr/utils/ocr.py", line 831
    str(output_path / f'out_{x}.png') for x in args.filenames
                                   ^
SyntaxError: invalid syntax
I can't resolve it

**Comment by Mountchicken** [comment]
Hi @young-xz 
- You have to check if the correct python environment is activated.
- When I try to execute your command, I get a different error: `No such file or directory: 'data/wildreceipt/dict.txt'`.

**Comment by gaotongxiao** [comment]
Everything is fine from my side, but it looks like you've changed the file somewhere else, so it would be great if you could double-check what you have modified, or post them here

**Comment by young-xz** [comment]
![QQ图片20220417092225](https://user-images.githubusercontent.com/62629010/163696303-4bf7326b-d995-465b-b230-c434f15c520f.png)
I have modified it and it is same as original content

**Comment by gaotongxiao** [comment]
Are you using python 2.x? We support python 3.x only.

**Comment by young-xz** [comment]
sorry,i'm using 2.x,but when i'm using,it throw 
FileNotFoundError: [Errno 2] No such file or directory: 'data/wildreceipt/dict.txt'

**Comment by gaotongxiao** [comment]
In this case, please download wildreceipt (https://mmocr.readthedocs.io/en/latest/datasets/kie.html#wildreceipt) and extract it to data/

**Comment by young-xz** [comment]
thank you.I have dealed with it.
