### ISSUE TITLE
mmdet problem

### ISSUE THREAD

**Issue by Zhaohaojie4598** [open-mmlab/mmocr#942]
When I'm ready to use the pre training model for reasoning，I received some feedback asfollow，
mmdet.datasets.pipelines.formating will be deprecated, please replace it with mmdet.datasets.pipelines.formatting.
  warnings.warn('DeprecationWarning: mmdet.datasets.pipelines.formating will be '
Traceback (most recent call last):File "C:/Users/Administrator/mmocr/mmocr/utils/ocr.py", line 863, in <module>
    main()
  File "C:/Users/Administrator/mmocr/mmocr/utils/ocr.py", line 857, in main
    args = parse_args()
  File "C:/Users/Administrator/mmocr/mmocr/utils/ocr.py", line 165, in parse_args
    Path.cwd()))) and (args.det_config != ''
  File "D:\ProgramData\Anaconda3\envs\zhao\lib\genericpath.py", line 100, in samefile
    s1 = os.stat(f1)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\Administrator\\mmocr\\mmocr\\utils\\configs/'
maybe my environment was wrong? what should I do?

**Comment by gaotongxiao** [comment]
You might have installed MMOCR by `pip install mmocr`. But for now, the configs are packed together with our source code (https://github.com/open-mmlab/mmocr/tree/main/configs) instead of the pypi package. And that's why we always suggest users to install MMOCR in develop mode (https://mmocr.readthedocs.io/en/latest/install.html#step-by-step-installation-instructions).

In this case, the fastest way is to uninstall your MMOCR and reinstall it from the source code. Another solution would be cloning the config directory from this repo and specify the path to config when you run `ocr.py`.

**Comment by Zhaohaojie4598** [comment]
No，I installed MMOCR by following the steps，but I'll try to add this configs to the file. Hope it helps.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月17日(星期天) 晚上8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmocr] mmdet problem (Issue #942)





 
You might have installed MMOCR by pip install mmocr. But for now, the configs are packed together with our source code (https://github.com/open-mmlab/mmocr/tree/main/configs) instead of the pypi package. And that's why we always suggest users to install MMOCR in develop mode (https://mmocr.readthedocs.io/en/latest/install.html#step-by-step-installation-instructions).
 
In this case, the fastest way is to uninstall your MMOCR and reinstall it from the source code. Another solution would be cloning the config directory from this repo and specify the path to config when you run ocr.py.

**Comment by Zhaohaojie4598** [comment]
> You might have installed MMOCR by `pip install mmocr`. But for now, the configs are packed together with our source code (https://github.com/open-mmlab/mmocr/tree/main/configs) instead of the pypi package. And that's why we always suggest users to install MMOCR in develop mode (https://mmocr.readthedocs.io/en/latest/install.html#step-by-step-installation-instructions).
> 
> In this case, the fastest way is to uninstall your MMOCR and reinstall it from the source code. Another solution would be cloning the config directory from this repo and specify the path to config when you run `ocr.py`. You can switch the default config directory with `--config_dir`

I add this file to the designated file and then I run ocr.py, with the similar result.
 UserWarning: DeprecationWarning: mmdet.datasets.pipelines.formating will be deprecated, please replace it with mmdet.datasets.pipelines.formatting.
  warnings.warn('DeprecationWarning: mmdet.datasets.pipelines.formating will be '
usage: ocr.py [-h] [--output OUTPUT] [--det DET] [--det-config DET_CONFIG]
              [--det-ckpt DET_CKPT] [--recog RECOG]
              [--recog-config RECOG_CONFIG] [--recog-ckpt RECOG_CKPT]
              [--kie KIE] [--kie-config KIE_CONFIG] [--kie-ckpt KIE_CKPT]
              [--config-dir CONFIG_DIR] [--batch-mode]
              [--recog-batch-size RECOG_BATCH_SIZE]
              [--det-batch-size DET_BATCH_SIZE]
              [--single-batch-size SINGLE_BATCH_SIZE] [--device DEVICE]
              [--export EXPORT] [--export-format EXPORT_FORMAT] [--details]
              [--imshow] [--print-result] [--merge]
              [--merge-xdist MERGE_XDIST]
              img
ocr.py: error: unrecognized arguments: --work-dir seg

**Comment by gaotongxiao** [comment]
It's `--config-dir` instead of `--work-dir`. Read the docs for full details: https://mmocr.readthedocs.io/en/latest/demo.html#api-arguments

**Comment by Zhaohaojie4598** [comment]
> It's `--config-dir` instead of `--work-dir`. Read the docs for full details: https://mmocr.readthedocs.io/en/latest/demo.html#api-arguments

I am sorry，I read this but I still don‘t know how to set config_dir.

**Comment by Mountchicken** [comment]
Hi @Zhaohaojie4598 
- You have passed in a parameter `work_dir` that does not exist in ocr.py. The correct parameter should be `python ocr.py  YOUR_IMAGE_PATH --config-dir PATH_TO_ALL_THE_CONFIG_FILES` 
- `PATH_TO_ALL_THE_CONFIG_FILES` is the path where you store the [configs](https://github.com/open-mmlab/mmocr/tree/main/configs) file.

**Comment by gaotongxiao** [comment]
I'm closing this issue as there have been no updates for weeks.
