### ISSUE TITLE
why did it not supply lmab files for crnn rec , official code just covert label to lmdb,wi want to convert my data to lmdb with images and label,and how to change dataset loader ?

### ISSUE THREAD

**Issue by cqray1990** [open-mmlab/mmocr#952]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

why did it not supply lmab files for crnn rec , official code just covert label to lmdb,wi want to convert my data to lmdb with images and label,and how to change dataset loader ?

**Comment by xinke-wang** [comment]
Hi, 
1. Currently, MMOCR only supports lmdb format labels, loading images from lmdb is not implemented at this time.
2. We provide a [toydata config](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/toy_data.py#L28) in `configs/_base_/recog_datasets/toy_data.py` as a tutorial to demonstrate the usage of lmdb data loader. Specifically, you only need to modify the `type` in the `loader` to `LmdbLoader`.

**Comment by gaotongxiao** [comment]
BTW, loading images from lmdb could be a nice feature. Adding a new transform as [`LoadImageFromFile`](https://github.com/open-mmlab/mmdetection/blob/c546b5044098b71d59a139036a87c5c97bcab4e2/mmdet/datasets/pipelines/loading.py#L18) and put a single image into `results['img']` would be enough. We could discuss more if you are interested in implementing one.

**Comment by Mountchicken** [comment]
> Loading images from lmdb could be a nice feature. Adding a new transform as [`LoadImageFromFile`](https://github.com/open-mmlab/mmdetection/blob/c546b5044098b71d59a139036a87c5c97bcab4e2/mmdet/datasets/pipelines/loading.py#L18) and put a single image into `results['img']` would be enough. We could discuss more if you are interested in implementing one.

- Supporting datasets in `lmdb` format, both images and labels,  can do great benefits, as academics are basically using the `lmdb` dataset in scene text recognition.

**Comment by cqray1990** [comment]
> Hi,
> 
> 1. Currently, MMOCR only supports lmdb format labels, loading images from lmdb is not implemented at this time.
> 2. We provide a [toydata config](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/toy_data.py#L28) in `configs/_base_/recog_datasets/toy_data.py` as a tutorial to demonstrate the usage of lmdb data loader. Specifically, you only need to modify the `type` in the `loader` to `LmdbLoader`.

can add cutomer dataset loader,what if i have large images, it is not convinient to load train data?

**Comment by cqray1990** [comment]
> > Hi,
> > 
> > 1. Currently, MMOCR only supports lmdb format labels, loading images from lmdb is not implemented at this time.
> > 2. We provide a [toydata config](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/toy_data.py#L28) in `configs/_base_/recog_datasets/toy_data.py` as a tutorial to demonstrate the usage of lmdb data loader. Specifically, you only need to modify the `type` in the `loader` to `LmdbLoader`.
> 
> can add cutomer dataset loader,what if i have large images, it is not convinient to load train data?

i read the source code and i find it maybe can't add cutomer dataset loader
