### ISSUE TITLE
open cv

### ISSUE THREAD

**Issue by Zhaohaojie4598** [open-mmlab/mmocr#953]
When I run this command,I get the feedback as follows:
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1274: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'.
Before asking this question. I tried to pip install opencv-contrib-python and opencv-python==4.5.5.62. But it gives me the same error.What should I do for this question?

**Comment by gaotongxiao** [comment]
Try 
```
pip uninstall opencv-python-headless
```
and rerun the command?

**Comment by Zhaohaojie4598** [comment]
I found it is not compatible for mmcor, then I checked this and it allows opencv-python <=4.5.4.60. So I installed this edition and solved this bug.&nbsp;I still thank you from the bottom of my heart for your answer.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 晚上10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmocr] open cv (Issue #953)





 
Try
 pip uninstall opencv-python-headless  
and rerun the command?
