### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by Zhaohaojie4598** [open-mmlab/mmocr#956]
When I run this command :python tools/train.py configs/textrecog/seg/seg_r31_1by16_fpnocr_toy_dataset.py --work-dir seg, I got the error No such file or directory: 'tests/data/ocr_char_ann_toy_dataset//instances_train.txt' .
 But in fact ,I can find this direction file in "C:\Users\Administrator\mmocr\tests\data\ocr_char_ann_toy_dataset\instances_train.txt" . Maybe it is a Directional question？ But I don't know how to change . Or what I should do?

**Comment by xinke-wang** [comment]
Hi, please check if you run the command at the MMOCR root directory.

**Comment by Zhaohaojie4598** [comment]
yes, work_dir is mmocr/tools.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 晚上11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmocr] train problem (Issue #956)





 
Hi, please check if you run the command at the MMOCR root directory.

**Comment by Xiangrui-Li** [comment]
i think @xinke-wang 's answer is great, u need to check it first, and then u need to check all the configs is right, for example, the configs file's import path etc.. That is a easy and normal problem.  Check it carefully no careless.

**Comment by gaotongxiao** [comment]
I'm closing this issue as there have been no updates for weeks.
