### ISSUE TITLE
Aster reproduction

### ISSUE THREAD

**Issue by GHuiXin** [open-mmlab/mmocr#963]
**Describe the feature**

**Motivation**

Ex1. There is a recent paper 《ASTER: An Attentional Scene Text Recognizer with Flexible Rectification》, which is a very classic paper. its ideas  are  useful guidelines  for character recognition, so to do code reproduction.

**Related resources**
  - https://github.com/ayumiymk/aster.pytorch

**Additional context**
  - the code reproduction of ASTER has finished.

**Comment by gaotongxiao** [comment]
Thanks for the update! Could you make a new PR for your implementation?

**Comment by GHuiXin** [comment]
yet,  I'll resubmit it according to the documents which you gave me.

**Comment by GHuiXin** [comment]
> Thanks for the update! Could you make a new PR for your implementation?

I'll resubmit it according to the documents you gave me
