### ISSUE TITLE
How to train datasets labeled by PPOCRLabel?

### ISSUE THREAD

**Issue by dsp6414** [open-mmlab/mmocr#968]
what is data standard format of mmocr det and recog datasets.

**Comment by xinke-wang** [comment]
Hi, we introduce the dataset type implemented in MMOCR [here](https://mmocr.readthedocs.io/en/latest/tutorials/dataset_types.html).

For detection, MMOCR uses COCO-like format annotations, a sample annotation file can be found in [`tests/data/toy_dataset/instances_test.json`](https://github.com/open-mmlab/mmocr/blob/main/tests/data/toy_dataset/instances_test.json)
```json
{"file_name": "test/img_10.jpg", "height": 720, "width": 1280, 
"annotations": [{"iscrowd": 1, "category_id": 1, "bbox": [260.0, 138.0, 24.0, 20.0], 
"segmentation": [[261, 138, 284, 140, 279, 158, 260, 158]]}
```

For recognition, MMOCR provides two options:

1. A simple txt format annotation, a sample annotation file can be found in [`tests/data/ocr_toy_dataset/label.tx`](https://github.com/open-mmlab/mmocr/blob/main/tests/data/ocr_toy_dataset/label.txt)
```text
1223731.jpg GRAND
1223733.jpg HOTEL
1223732.jpg HOTEL
```
2. A jsonl format annotation:
```text
{'filename': '1223731.jpg', 'text': 'GRAND'}
```
It should be noted that if your dataset contains `space blanks`, you have to use the jsonl format annotations and follow the steps [here](https://mmocr.readthedocs.io/en/latest/tutorials/blank_recog.html) to set `parser` and `DICT`. Also, we provide [scripts](https://mmocr.readthedocs.io/en/latest/tutorials/blank_recog.html) to convert txt annotations to lmdb.


For most public datasets, MMOCR provides both [detection](https://github.com/open-mmlab/mmocr/tree/main/tools/data/textdet) and [recognition](https://github.com/open-mmlab/mmocr/tree/main/tools/data/textrecog) data converters. **If you would like to convert a dataset labeled by PPOCRLabel, you can write a data converter by yourself, and you are welcome to raise a pull request to submit your converter scripts**.

In addition, welcome to use [Labelbee](https://github.com/open-mmlab/labelbee-client) developed by OpenMMLAB for label annotations.

**Comment by dsp6414** [comment]
does mmocr support labels with space. such as: "Yunshan HOTEL"
hotel023.jpg Yunshan HOTEL

**Comment by dsp6414** [comment]
My training imgs are line segmentation's img,the label is line label.

**Comment by xinke-wang** [comment]
Reply to the email comments which do not show on GitHub website:

**Q:** does mmocr support labels with space. such as: "Yunshan HOTEL" hotel023.jpg Yunshan HOTEL

**A:** Yes, MMOCR does support labels with spaces, which I have emphasized in the initial reply, please refer to this [doc](https://mmocr.readthedocs.io/en/latest/tutorials/blank_recog.html).

Q: My training imgs are line segmentation's img,the label is line label.

**A:** What do you mean line label? Could you paste a sample annotation of text instances here?
