### ISSUE TITLE
Help needed regarding Text recognition.

### ISSUE THREAD

**Issue by KKhushhalR2405** [open-mmlab/mmocr#97]
Can someone help me on how to perform Text Recognition?
I am using (for example) the following image.
![test1](https://user-images.githubusercontent.com/58569950/115270542-0781ae80-a15a-11eb-8aa6-9f0f30ee1be6.jpg)

And getting this result.
![test](https://user-images.githubusercontent.com/58569950/115270588-15373400-a15a-11eb-954a-730e27c28df0.jpg)

How can I get the desired output. Any kind of help would be appreciated. Thanks

**Comment by cuhk-hbsun** [comment]
1. The input of text recognition is just a box image containing one text string like `demo/demo_text_recog.jpg`.
2. The image you provide need an end-to-end pipeline (text detection + text recognition).
3. And We will give the end-to-end demo script as soon as possible.

**Comment by yauauau** [comment]
How do you receive all of this to watch it like how do you send the link

**Comment by yauauau** [comment]
`[https://github.com/open-mmlab/mmocr/issues/97#issue-861498653](ok) `

**Comment by cuhk-hbsun** [comment]
The code has been updated, please pull the latest code and run
```bash
python demo/ocr_image_demo.py <image_above>.jpg output.jpg
```

**Comment by cuhk-hbsun** [comment]
fix #97
