### ISSUE TITLE
I can not find runner config item in config file, how can i find it?

### ISSUE THREAD

**Issue by dsp6414** [open-mmlab/mmocr#985]
Does mmocr not need to configure runner?

**Comment by gaotongxiao** [comment]
Hi, the runner field has been added in #980 , and you should be able to find it in all the base configs under `configs/_base_/schedules`

**Comment by dsp6414** [comment]
i use print(cfg.pretty_text)
but i can not find runner config item.

**Comment by gaotongxiao** [comment]
Have you updated your mmocr to the latest commit? Run `git pull origin main` in mmocr directory to get the changes.
