### ISSUE TITLE
demo 推理

### ISSUE THREAD

**Issue by Jialiang123** [open-mmlab/mmocr#986]
您好，我在官方给的代码进行批量推理图片的时候，如果图片数量过多就会出现OOM的情况，为什么咱们没办法推理一张存一张，或者按照一个batch存一次，这一块有优化吗，谢谢。
![image](https://user-images.githubusercontent.com/37236583/165747110-4601919c-29e0-483f-b243-df3c717f892a.png)

**Comment by Jialiang123** [comment]
> Hi, The `batch-mode` is set to `False` by default. Please check if the OOM is caused by an image that has high resolution.
> 
> https://github.com/open-mmlab/mmocr/blob/64f02ba1a21683a511418738b1611ca2ac0d9237/mmocr/utils/ocr.py#L103-L106
> 
> 
> Or if you have turned on the `batch-mode`, you may try a smaller `batch-size`
> https://github.com/open-mmlab/mmocr/blob/64f02ba1a21683a511418738b1611ca2ac0d9237/mmocr/utils/ocr.py#L107-L116

Thank you for your help,I have tired to turn on the batch-mode and to try a smaller batch-size,but there is still an OOM error.
I have 2000  images to inferecce.
![image](https://user-images.githubusercontent.com/37236583/165871534-76300a27-5c5b-42bd-af46-23d928b04f6e.png)
![image](https://user-images.githubusercontent.com/37236583/165871545-b8eb7584-b37d-4333-bcc5-4f0019aa9b72.png)

**Comment by xinke-wang** [comment]
Hi, sorry for the late reply.

Thank you for reporting this issue. We will fix this soon.

**Comment by xinke-wang** [comment]
Hi, sorry for the late reply. Since I noticed you close the issue, have you solved the problem?

**Comment by Jialiang123** [comment]
> 

Thanks a lot for your reply,I wrote a for loop to solve this problem for now.

**Comment by xinke-wang** [comment]
Ok then, I will reopen this issue for a record. Thank you for reporting the issue. We will fix it soon.
