### ISSUE TITLE
在ubuntu环境里按照文档提示操作拉取docker镜像时出错

### ISSUE THREAD

**Issue by tangjinou** [open-mmlab/mmocr#987]
报错如下：
Reading package lists...
W: GPG error: https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.

操作如下：
docker build -t mmocr docker/

**Comment by Mountchicken** [comment]
Hotfix now. #988

**Comment by gaotongxiao** [comment]
I'm closing this issue since it should have been fixed now.
