### ISSUE TITLE
Production Deployment

### ISSUE THREAD

**Issue by seekingdeep** [open-mmlab/mmocr#99]
Hi there,
Production Deployment means optimizing the models for inferencing-only environments.
The goal is to allow ordinary users without coding knowledge to detect and recognize documents on CPU-only and ARM-based devices such as Raspberry Pi.

Therefore, quantization and exporting the models into TensorRT and ONNX is important.
Few examples:
https://github.com/Media-Smart/volksdep
https://github.com/Media-Smart/vedastr
https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy

**Comment by innerlee** [comment]
Thanks for the suggestion. Deployment is an important topic for mm-series. Hold on and follow our iteration plans 😄
