### ISSUE TITLE
About the average acc for text_recog task?

### ISSUE THREAD

**Issue by simplify23** [open-mmlab/mmocr#993]
I'm working on a text recognition task and want to test it with an academic dataset. Only the six common baseline datasets for the first metric are required. Like this,
`0_word_acc_ignore_case_symbol: 0.9327, 1_word_acc_ignore_case_symbol: 0.8887, 2_word_acc_ignore_case_symbol: 0.9084, 3_word_acc_ignore_case_symbol: 0.7862, 4_word_acc_ignore_case_symbol: 0.8047, 5_word_acc_ignore_case_symbol: 0.8229`

To see the results quickly, I want to average the six baseline results for each epoch and save the average results. How to achieve my goals with minimal code changes.
like above example:
`Avg:0.88XX`

**Comment by gaotongxiao** [comment]
It's already supported in #981, please check out the use case there. https://github.com/open-mmlab/mmocr/pull/989 might also interest you, after it's merged you can customize the set of evaluation metrics and simply the output.

**Comment by simplify23** [comment]
This is really awesome. Can I update the code to support this function?

**Comment by simplify23** [comment]
I got the average result, thank you very much for your help
